### ISSUE TITLE
update contact us form to submit github issue

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#1001]
We should probably also stop asking for people's emails (or at least make it optional + warn them).

**Comment by MrinallU** [comment]
@thecodingwizard If Jeffery is busy with other issues can I give this a shot?

**Comment by jeffreymeng** [comment]
Actually I am currently working on this. Just waiting for https://github.com/cpinitiative/usaco-guide/tree/problems-refactor to be done, because the JSON files for problems will make it easier.

**Comment by MrinallU** [comment]
Alright.
