### ISSUE TITLE
Problem Suggestion: Add "Matrix Block Sum" to Silver - More on Prefix Sums

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1006]
*Gaurav B* (UID WkRvlFzYilY9qq7ZqUr8Bv5N6pS2) suggested adding the problem [Matrix Block Sum](https://leetcode.com/problems/matrix-block-sum/) to the module [Silver - More on Prefix Sums](https://usaco.guide/silver/prefix-sums-2#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=919).

**Difficulty**: Normal
**Tags**: 2D Prefix Sums
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by andrewwangva** [comment]
I'll add this one as easy later today.
