### ISSUE TITLE
Problem Suggestion: Add "NOI '05 P2 - Maintaining a Sequence" to Advanced - Treaps

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1007]
*Aaeria* (UID wXnq5KSs9ZZklOb0yFaESkqpc0z2) suggested adding the problem [NOI '05 P2 - Maintaining a Sequence](https://dmoj.ca/problem/noi05p2) to the module [Advanced - Treaps](https://usaco.guide/adv/treaps#problem-https://szkopul.edu.pl/problemset/problem/b0BM0al2crQBt6zovEtJfOc6/site/?key=statement).

**Difficulty**: Easy
**Tags**: 
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by bqi343** [comment]
also

https://cses.fi/problemset/task/2072 -> cut & paste
https://cses.fi/problemset/task/2073 -> reverse
https://cses.fi/problemset/task/2074 -> reverse, sum

**Comment by bqi343** [comment]
oops I don't rlly want to do this, can I assign to someone else? :)

**Comment by nchn27** [comment]
I'm not good with the problem list syntax... is anyone more capable of putting the current bullet-pointed problems + the ones benq listed above into a problem list

**Comment by thecodingwizard** [comment]
@jeffreymeng would you recommend adding it manually right now or waiting for editor UI?

**Comment by jeffreymeng** [comment]
well I don't know if the editor UI will make it that much better
you'd still have to type in the same stuff, the only difference is you'd put it into a slightly nicer looking form

**Comment by thecodingwizard** [comment]
it would also help generate IDs (and ideally check for duplicates, etc etc). At a minimum we should either document the list syntax or build out the form faster :P
