### ISSUE TITLE
Improve URLs

### ISSUE THREAD

**Issue by jeffreymeng** [cpinitiative/usaco-guide#1011]
The URLs for modules are not very descriptive. This may or may not be bad for SEO, but it definitely makes it harder to figure out what a link is when somebody sends you one, especially in places where there are no link previews, such as email or zoom chat.

It might be better to just slugify the module name (the old URLs should still redirect though).

Examples of questionable URLs:
https://usaco.guide/general/factors-choosing?lang=cpp
https://usaco.guide/general/generic?lang=cpp
https://usaco.guide/silver/ff?lang=cpp
https://usaco.guide/gold/sp?lang=cpp
https://usaco.guide/plat/2DRQ?lang=cpp

**Comment by mizlan** [comment]
Competitive programming habits have crept into production...

**Comment by SansPapyrus683** [comment]
i warned yall
