### ISSUE TITLE
Problem Suggestion: Add "USACO February 2021 Bronze - Comfortable Cows" to Bronze - Simulation

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1017]
*Karthik Perugupalli* (UID DegJAsENkXWpbVOccEgc01UW1o83) suggested adding the problem [USACO February 2021 Bronze - Comfortable Cows](http://usaco.org/index.php?page=viewproblem2&cpid=1108) to the module [Bronze - Simulation](https://usaco.guide/bronze/simulation#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=917).

**Difficulty**: Normal
**Tags**: 
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by caoash** [comment]
Seems interesting, will add.
