### ISSUE TITLE
Problem Suggestion: Add "Google Kickstart 2021 Round A Checksum" to Gold - Minimum Spanning Trees

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1018]
*Divyansh Garg* (UID 0km7uxhOi3RoeGaCZHsBwdfRxGf2) suggested adding the problem [Google Kickstart 2021 Round A Checksum](https://codingcompetitions.withgoogle.com/kickstart/round/0000000000436140/000000000068c2c3) to the module [Gold - Minimum Spanning Trees](https://usaco.guide/gold/mst#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=531).

**Difficulty**: Normal
**Tags**: Spanning Trees
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by caoash** [comment]
Will add.
