### ISSUE TITLE
Change link for Balkan OI 2012 Shortest Paths

### ISSUE THREAD

**Issue by dolphingarlic** [cpinitiative/usaco-guide#1024]
The link leads to a Korean website right now. It would be nice to be able to view and submit to the problem in English

**Comment by dolphingarlic** [comment]
@frodakcin do you think it's possible to generate test data and put the problem on that CF gym?

**Comment by HarryWangATX** [comment]
working on it

**Comment by HarryWangATX** [comment]
are you able to get is testcases or gen new ones?

**Comment by dolphingarlic** [comment]
Test cases don't seem to be available online, unfortunately

**Comment by HarryWangATX** [comment]
Okay, Ill gen the graph. Do you want both dense and sparse graphs?

**Comment by dolphingarlic** [comment]
I think both, since M can get up to O(N^2)

**Comment by HarryWangATX** [comment]
> I think both, since M can get up to O(N^2)

okay, ill get started. sry was prepping for usaco

**Comment by HarryWangATX** [comment]
hmmmm my graph gen is bugged. maybe someone else can take over this.

**Comment by bqi343** [comment]
If the site that's currently linked is the only place where test data is available, then let's just leave it as is.
