### ISSUE TITLE
Code Submission - Don't Select C++ By Default

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#1027]
from @maggie-j-liu:

> the language selection starts out as c++ so people might forget to change the language - it would be better to not select any initially and make it a required field (so they can't submit until they pick one)

**Comment by thecodingwizard** [comment]
It currently defaults as whatever language the user is currently using. Do we want to change this?

**Comment by maggie-j-liu** [comment]
Oops, I didn't realize that. It would be less convenient for people to pick the language every time, but it would probably decrease the number of submissions that have the wrong language?

**Comment by thecodingwizard** [comment]
fixed in 310afd60
