### ISSUE TITLE
custom comparator focus problem?

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#1028]
https://usaco.guide/silver/sorting-custom?lang=cpp

Do we want a focus problem for the more complicated custom sort examples (that can't be done with just the builtin sort functions)?

**Comment by jessechoe10** [comment]
What do you think about making Out of Sorts as this?

**Comment by bqi343** [comment]
You can do that w/ builtin sort.

**Comment by jessechoe10** [comment]
> You can do that w/ builtin sort.

How about Rental Service?

**Comment by bqi343** [comment]
same ... I'm pretty sure you can do all of the problems in the modules w/ builtin sort

**Comment by thecodingwizard** [comment]
are there any that makes more sense to do w/ builtin sort (for like the average person who can't keep track of `pair<pair<ii, ii>, pair<ii, ii>>`)?

**Comment by jessechoe10** [comment]
> are there any that makes more sense to do w/ builtin sort (for like the average person who can't keep track of `pair<pair<ii, ii>, pair<ii, ii>>`)?

Meetings, but that's like way too hard for a focus problem :)

**Comment by bqi343** [comment]
er, sorting pairs of ints works for that too ...

**Comment by jessechoe10** [comment]
Are there any problems where you sort by `first, but sort by `second` if the `first` are equal cuz idt u can sort pairs of ints for those, right?

**Comment by jessechoe10** [comment]
How about Mountain View. My solution uses a non-builtin sort: https://usaco.guide/problems/usaco-mountain-view/solution.

**Comment by Aryansh-S** [comment]
> are there any that makes more sense to do w/ builtin sort (for like the average person who can't keep track of `pair<pair<ii, ii>, pair<ii, ii>>`)?

Uhh hello fortunately `std::array` and such tuple-like constructs exist, after which builtin sort is lexicographical. 

> Are there any problems where you sort by `first`, but sort by `second` if the `first` are equal cuz idt u can sort pairs of ints for those, right?

This is the definition of builtin sort for pairs...

> How about Mountain View. My solution uses a non-builtin sort: https://usaco.guide/problems/usaco-mountain-view/solution.

For the same reason as above, builtin sort suffices.

**Comment by jessechoe10** [comment]
> You can always default to `std::array` and such tuple-like constructs and sort them lexicographically using builtin sort, but sometimes it will be more convenient to use custom comparators.

Nobody does this tho :).

**Comment by Aryansh-S** [comment]
In practice, a significant number of people do actually (it's usually faster this way -- who wants to waste time writing a comparator when the standard works well?)

**Comment by jessechoe10** [comment]
> waste time writing a comparator

It actually isn't really a waste of time if you define a lambda :smile:

**Comment by thecodingwizard** [comment]
closing since there don't seem to be any ideas. feel free to reopen if you have a better problem in mind :P
