### ISSUE TITLE
header link issues (?)

### ISSUE THREAD

**Issue by dongliu0426** [cpinitiative/usaco-guide#1030]
![Screen Shot 2021-03-25 at 1 24 10 PM](https://user-images.githubusercontent.com/59348162/112538729-69264700-8d6d-11eb-843c-a4c4b9a1a24d.png)

from https://usaco.guide/silver/prefix-sums-2?lang=java#max-subarray-sum

**Comment by dongliu0426** [comment]
is it supposed to go outside the spoiler @thecodingwizard ?

**Comment by thecodingwizard** [comment]
honestly I'm not sure. I don't really want to fix this though :P

header links are even worse on mobile. The link doesn't even show up

**Comment by thecodingwizard** [comment]
I'll close this issue unless anybody has proposed fixes (feel free to reopen)
