### ISSUE TITLE
Problem Suggestion: Add "USACO December 2017 Silver Problem 1 My Cow Ate My Homework" to Silver - Introduction to Prefix Sums

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1032]
*Angela Zhang* (UID fFx2kImi2YW80isJEzvCToLl4PN2) suggested adding the problem [USACO December 2017 Silver Problem 1 My Cow Ate My Homework](http://www.usaco.org/index.php?page=viewproblem2&cpid=762 ) to the module [Silver - Introduction to Prefix Sums](https://usaco.guide/silver/prefix-sums#problem-https://leetcode.com/problems/find-pivot-index).

**Difficulty**: Easy
**Tags**: Prefix Sums
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by jessechoe10** [comment]
You should make a PR for this. I don't think this should be an issue...

**Comment by HarryWangATX** [comment]
hmmm this was in the module like two weeks ago

**Comment by HarryWangATX** [comment]
@bqi343  did u move anything out? i remeber it being there

**Comment by bqi343** [comment]
It was too boring, I removed it ;)

(you don't even need to keep a suffix, sum array, just a running counter ...)

**Comment by HarryWangATX** [comment]
LOL i'll close
