### ISSUE TITLE
Problem Suggestion: Add "USACO 2021 January Contest, Silver Problem 2. No Time to Paint" to Silver - Introduction to Prefix Sums

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1034]
*Angela Zhang* (UID fFx2kImi2YW80isJEzvCToLl4PN2) suggested adding the problem [USACO 2021 January Contest, Silver Problem 2. No Time to Paint](http://www.usaco.org/index.php?page=viewproblem2&cpid=1087) to the module [Silver - Introduction to Prefix Sums](https://usaco.guide/silver/prefix-sums#problem-https://leetcode.com/problems/find-pivot-index).

**Difficulty**: Normal
**Tags**: Prefix Sums
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by jessechoe10** [comment]
Same for this.

**Comment by jessechoe10** [comment]
Also, Benq said we shouldn't add.
