### ISSUE TITLE
Problem Suggestion: Add "USACO US Open 2016 Bronze - Bull in a China Shop" to Bronze - Simulation

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1042]
*Trisha Sabadra* (UID M2JoLeXI1NMPU8haWLweUOMGAGr2) suggested adding the problem [USACO US Open 2016 Bronze - Bull in a China Shop](http://www.usaco.org/index.php?page=viewproblem2&cpid=640) to the module [Bronze - Simulation](https://usaco.guide/bronze/simulation#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=917).

**Difficulty**: Very Hard
**Tags**: Simulation
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by dongliu0426** [comment]
i think this should be marked as Insane

**Comment by bqi343** [comment]
It's already in https://usaco.guide/bronze/intro-complete?lang=cpp. Unless we want to move it?
