### ISSUE TITLE
Problem Suggestion: Add "Connecting Cities With Minimum Cost" to Gold - Minimum Spanning Trees

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1043]
*aarush yadav* (UID vaD5tRcoz7Wxn35v8GytmdBORdf2) suggested adding the problem [Connecting Cities With Minimum Cost](https://leetcode.com/problems/connecting-cities-with-minimum-cost/) to the module [Gold - Minimum Spanning Trees](https://usaco.guide/gold/mst#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=531).

**Difficulty**: Easy
**Tags**: MST, DSU
**Additional Notes**:
This is a problem from LeetCode. 

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by HarryWangATX** [comment]
its a premium questeion lol
