### ISSUE TITLE
Problem Suggestion: Add "Buckets" to Bronze - Simulation

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1044]
*Ryan Ding* (UID 504XFEqniQTJjPZe5PeSrTwLjnG3) suggested adding the problem [Buckets](http://www.usaco.org/index.php?page=viewproblem2&cpid=939) to the module [Bronze - Simulation](https://usaco.guide/bronze/simulation#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=665).

**Difficulty**: Normal
**Tags**: 
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by caoash** [comment]
I wouldn't say this is simulation, seems more like ad-hoc to me.
