### ISSUE TITLE
Misc problem migration todos

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#1048]
- [x] document changes / how to add problems & stuff
- [x] improve editor experience (ie. don't just crash the moment problem JSON is malformatted) (see also #1051)
- [x] auto-generate problem suggestion stuff
- [x] Add tooltips to sources (see benq's comment below)

**Comment by bqi343** [comment]
<img width="773" alt="Screen Shot 2021-03-29 at 12 55 52 PM" src="https://user-images.githubusercontent.com/21228024/112872248-24145480-908e-11eb-8f47-d14d32a7f621.png">

why are most sources no longer underlined?

**Comment by thecodingwizard** [comment]
Source issue should be fixed in 82ee3d7cc654a77dc60f775cb7f505b129d456a2
