### ISSUE TITLE
Platinum Module Migration

### ISSUE THREAD

**Issue by Aryansh-S** [cpinitiative/usaco-guide#1049]
A significant number of modules in the plat division as of right now belong to earlier divisions. Below is a comprehensive list to help you:

- "Sweep Line" should be in Silver
- "Small-To-Large Merging" should be in Gold 
- "Dynamic Programming on Bitmasks" should be in Gold
- "Dynamic Programming on Ranges" should be in Gold
- "Intro to Bitwise Operators" might be better suited for Silver or Gold (I could see problem statements at those levels possibly referencing these operations -- even though they will most likely be defined in that case -- and the exposition can make certain solutions at those levels easier to code. I've even seen these used in editorials at those levels. In any case, prior experience can only help.)
- "(Optional) Bitsets" might be better suited for Silver or Gold (The reasons are similar to those mentioned above.)

From what I understand, your main argument against this right now is that plat would have too few modules. However, since the divisions for USACO are incremental in the first place (e.g., for plat, you should also be comfortable with everything from bronze to gold), this really shouldn't be a problem. Besides, the vast majority of users for the guide are beginners, so it would only behoove them to see these sections added to their proper divisions. 

I'll conclude with some things @thecodingwizard told me to mention here: 

- Division D should include all topics in the interval [easiest topic that can show up in D but not D-1, hardest topic that can show up in D] (obviously as topologically sorted as possible, so that all prerequisites for a given topic show up before that topic if possible)
- To respond to the apparently common argument that "modules should go in the division the topic most appears in, not can appear in":
a) what's the point of this if "This guide...makes no guarantees about the topics in future USACO contests."
b) this is subjective (multiple solutions exist for problems, and demonstrative a particular problem is of a particular technique is up to the judgment of the individual. for instance, one might argue that even if a technique does show up often in plat, it's so normalized that it's almost never the main idea, whereas if it shows up in a lower division, it does show up as the main idea)
c) again, is this really all that beneficial if most users are in lower divisions looking for as holistic a review as possible?

**Comment by antiquicksort** [comment]
Sweepline problems in plat are different from sweepline problems in silver. There could be technically hundreds of topics that can be covered within a given a division (ex: HLD was in gold). Keeping the emphasis on a certain division is probably most pragmatic to users, but module separation might be a good idea. (ex: gold bitmask dp and plat bitmask dp)

Putting small-to-large for example in gold might be a little overwhelming, important to emphasize it rarely occurs and is not typically required to promo

**Comment by bqi343** [comment]
Actually, maybe moving the DP modules you mentioned to Gold might be reasonable, considering that there has been more than one Gold DP on Ranges problem, and because using a bitmask as a state for partial credit was mentioned [here](http://www.usaco.org/current/data/sol_prob2_gold_feb21.html).

Though moving Sweep Line (in its current state) to Silver seems like a bad idea ...

> "Intro to Bitwise Operators" might be better suited for Silver or Gold (I could see problem statements at those levels possibly referencing these operations -- even though they will most likely be defined in that case -- and the exposition can make certain solutions at those levels easier to code. I've even seen these used in editorials at those levels. In any case, prior experience can only help.)

> "(Optional) Bitsets" might be better suited for Silver or Gold (The reasons are similar to those mentioned above.)

Which Silver analysis mentions bitwise operators? Which Silver or Gold analysis references bitsets? I don't see how knowing bitsets is useful for Gold (aside from fakesolving compatibility)

> "Small-To-Large Merging" should be in Gold

Similarly, what Gold editorial references small-to-large merging (aside from favorite colors, where you don't actually need to use it?)

**Comment by Aryansh-S** [comment]
> Moving the DP modules you mentioned to Gold might be reasonable, considering that there has been more than one Gold DP on Ranges problem, and because using a bitmask as a state for partial credit was mentioned here.

Yes, glad to know you're on board with this. We should go through with it then. 

> Though moving Sweep Line (in its current state) to Silver seems like a bad idea ...
> Sweepline problems in plat are different from sweepline problems in silver. 
Here's my compromise: We can write an easier sweep line module for Silver (for instance, duplicate the current plat module, remove the inappropriate problems, and add some easier ones). I'd like to emphasize that this is actually necessary, since there are a significant number of times sweep line has occurred in the past, and I can easily see it occurring in the future, especially during Open contests.

> There could be technically hundreds of topics that can be covered within a given a division (ex: HLD was in gold). 

I wouldn't say "HLD was in gold" because the editorial was simply overkill. The problem could easily have been done using another method covered in the guide (e.g., euler tours). That editorial is an outlier for being particularly unsuitable. 

> Keeping the emphasis on a certain division is probably most pragmatic to users, but module separation might be a good idea. (ex: gold bitmask dp and plat bitmask dp)

Since most users are looking for an end-to-end list of what has occurred in the past, I'd still say we go through with at least a few of these changes. 

> Which Silver analysis mentions bitwise operators? 

I'd like to emphasize here that I used "might be" for a reason -- this suggestion wasn't as important as the others. For further reason, @darren-yao 's book seems to include them under Silver as well. Granted, there are a few editorials I can think of which use them in their analyses, such as http://www.usaco.org/current/data/sol_leftout_silver_open19.html. Of course, this analysis could be just as easily written without making use of these operators, but just a thought. 

> Which Silver or Gold analysis references bitsets? I don't see how knowing bitsets is useful for Gold (aside from being an unintended solution to compatibility)

Probably none, which is why I used "might be." We don't have to go through with this one to be honest. 

> Similarly, what Gold editorial references small-to-large merging (aside from favorite colors, where you don't actually need to use it?)

Can't think of any off the top of my head other than fcolor. However, at the Gold level, it should suffice to just have "Sets and other containers with logarithmic insertion should be merged from small to large." We don't necessarily have to include a proof or any of the advanced applications like Arpa's trick or DSU merging. 

> I don't see why you dismiss this as having no point. We're only saying that modules go in the division the topic most appeared in the past, not that they will continue to appear frequently in the future.

Right, but again, "only saying" something without justification doesn't really prove anything. I don't see why you need to limit the scope of each division to only the most frequently occurring topics when most users want to see as comprehensive a categorization as possible based on past occurrence. You literally already indicate the frequency of each topic using the frequency measure thing right below each title.

**Comment by bqi343** [comment]
> significant number of times sweep line has occurred in the past

Really? Some of the problems in sorting w/ custom comparators qualify as sweep line (sort points by x, then iterate in order), but I don't see a point in distinguishing them from the other sorting problems.

> We can write an easier sweep line module for Silver (for instance, duplicate the current plat module, remove the inappropriate problems, and add some easier ones)

If there was a Silver sweep line module, I think starting from scratch would be more reasonable than building on the current platinum module (though in my opinion, "Cow Steeplechase II" qualifies as inappropriate for Silver ...)

> However, at the Gold level, it should suffice to just have "Sets and other containers with logarithmic insertion should be merged from small to large."

>  We don't necessarily have to include a proof or any of the advanced applications like Arpa's trick or DSU merging, which also solves the below concern.

So what about all of the practice problems in the Small to Large module? Leave them in Platinum? 

The proof is quite simple. And I don't think "Arpa's trick" / "DSU merging" qualify as advanced. They're pretty standard applications - I'm not sure why you would introduce small to large merging without including these.

> You literally already indicate the frequency of each topic using the frequency measure thing right below each title.

> Also, we can easily emphasize something rarely occurs by using the frequency feature already available rather than omitting it entirely (also see the below).

> I don't see why you need to limit the scope of each division to only the most frequently occurring topics when most users want to see as comprehensive a categorization as possible based on past occurrence. You literally already indicate the frequency of each topic using the frequency measure thing right below each title.

>  I think it means you're saying we should omit rarely occurring modules from their divisions and put them in the divisions for which they most frequently occur. 

I think that it's quite reasonable to move a module to a higher division if it has frequency <= 1 in the lower division and a much higher frequency in the higher division. Personally, I don't think the guide needs to be as comprehensive a categorization as possible.

**Comment by antiquicksort** [comment]
Agree with Ben - no need to move things around too much. It might be good to add a "other topics" module for each division to just inform users of potential topics they should look out for. ex bitmask dp in gold.

**Comment by Aryansh-S** [comment]
We should still definitely move the following: 

- "Dynamic Programming on Bitmasks" should be in Gold
- "Dynamic Programming on Ranges" should be in Gold

**Comment by thecodingwizard** [comment]
I don't know how much I like moving modules into Gold solely because they appeared once or twice in the past. The reason being that people shouldn't expect topics listed under a particular division to be exhaustive (for example, DP Bitmasks / DP Ranges appeared in Gold when it was listed under Platinum).

Furthermore, people generally complete the Guide in order (skipping Optional modules). I think it would make more sense for a Gold contestant to do DP Bitmasks / DP Ranges last, after finishing all the other modules, rather than doing six DP modules in a row before even learning about DSU or shortest path algorithms (in other words, ignoring what type of problems have appeared in what divisions, I think it makes more sense to learn about DP Bitmasks and DP Ranges last, after completing the rest of Gold).

I think it suffices to just list out the exceptions somewhere (for example, we specify that "DP on Bitmasks / Ranges (listed under Platinum) have appeared in recent Gold contests" on the Gold syllabus page).

Specifically with regards to DP on Bitmasks / DP on Ranges, I'm sort of fine either way, but if we do move them into Gold then the DP section in Gold would have six modules while the DP section in Platinum would have 1 module, which is really odd. Also, we already specify that DP Bitmasks / Ranges have appeared in Gold before on the syllabus page, so I don't think we _have_ move the modules.

I am thinking of adding a "mixed problemset" module to the end of each division where we can dump extra practice problems. Perhaps we can also add a "conclusion" module to the end of each division that lists general advice for passing that division, as well as a list of topics that are categorized in higher divisions but have appeared previously (or we suspect may appear / may be helpful) in the current division.

**Comment by Aryansh-S** [comment]
> rather than doing six DP modules in a row before even learning about DSU or shortest path algorithms (in other words, ignoring what type of problems have appeared in what divisions, I think it makes more sense to learn about DP Bitmasks and DP Ranges last, after completing the rest of Gold).

Who said we'd need to have them listed in a row? As long as they're topologically sorted, we can still keep the advanced concepts at the end. 

> I think it suffices to just list out the exceptions somewhere (for example, we specify that "DP on Bitmasks / Ranges (listed under Platinum) have appeared in recent Gold contests" on the Gold syllabus page).

Yes, except for the particular case of the dp, I think we should actually move the modules

> DP section in Platinum would have 1 module, which is really odd.

It's incremental, so why's it odd lol

> I am thinking of adding a "mixed problemset" module to the end of each division where we can dump extra practice problems. Perhaps we can also add a "conclusion" (or "introduction") module to the end (or beginning) of each division that lists general advice for passing that division, as well as a list of topics that are categorized in higher divisions but have appeared previously (or we suspect may appear / may be helpful) in the current division.

I agree

**Comment by Aryansh-S** [comment]
Bump, so for now, I think it's best that we at least start with the following: 

- Moving "Dynamic Programming on Bitmasks" and "Dynamic Programming on Ranges" from Plat to Gold
- A "mixed problemset" module to the end of each division where we can dump extra practice problems. Perhaps we can also add a "conclusion" (or "introduction") module to the end (or beginning) of each division that lists general advice for passing that division, as well as a list of topics that are categorized in higher divisions but have appeared previously (or we suspect may appear / may be helpful) in the current division / "other topics" module for each division to just inform users of potential topics they should look out for. ex bitmask dp in gold.

Is anyone willing to make the necessary PRs for these? @thecodingwizard 

We can discuss this more later based on how things pan out with the "mixed problemset" module idea.

**Comment by thecodingwizard** [comment]
> Moving "Dynamic Programming on Bitmasks" and "Dynamic Programming on Ranges" from Plat to Gold

If we do this we should also consider moving the last DP module in Plat to the Misc Topics section

**Comment by Aryansh-S** [comment]
I'll make the pull requests and if we're agreed then we can go ahead and merge them.
