### ISSUE TITLE
Problem Suggestion: Add "CF-  Educational Codeforces Round 93 (Rated for Div. 2)-C-Good Subarrays" to Silver - Introduction to Prefix Sums

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1050]
*Rishab Purkayastha* (UID 7zN0WRjIUjRAQzgA1kuru29WGCk1) suggested adding the problem [CF-  Educational Codeforces Round 93 (Rated for Div. 2)-C-Good Subarrays](https://codeforces.com/contest/1398/problem/C) to the module [Silver - Introduction to Prefix Sums](https://usaco.guide/silver/prefix-sums#problemlist-cum).

**Difficulty**: Normal
**Tags**: Prefix Sums,Maths
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by andrewwangva** [comment]
Yea looks good I'll add.
