### ISSUE TITLE
Edit Live Update Function Issue

### ISSUE THREAD

**Issue by Qw3rTy827** [cpinitiative/usaco-guide#1051]
Hi all, 

During my attempt to test and push a new editorial in the RURQ section. I have discovered that the Edit Live Update function does not work anymore (at least on my side shown in the video below). Is this a problem only on my side? I have tested multiple other sections other than RURQ and the same issue appears for me. 

Best Regards, 
Andrew C

https://user-images.githubusercontent.com/38941398/112861097-10e1a300-90e7-11eb-92e6-e49fcc944baa.mp4

**Comment by Aryansh-S** [comment]
I can reproduce this with 100% frequency, and it occurs for every module.

**Comment by thecodingwizard** [comment]
@jeffreymeng

**Comment by thecodingwizard** [comment]
You can use the liveupdate here for now: https://usaco-guide-7sxilljfc-cpinitiative.vercel.app/

**Comment by jeffreymeng** [comment]
should be fixed in 2ac3e5dd314748f6242d8c655576609a3c6c9923
