### ISSUE TITLE
Problem Suggestion: Add "USACO February 2021 Silver - Year of the Cow" to Silver - Greedy Algorithms with Sorting

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1052]
*Dennis Miczek* (UID 3W4qF6BfFnhqRPU6sqZ0G9OEXFw2) suggested adding the problem [USACO February 2021 Silver - Year of the Cow](http://www.usaco.org/index.php?page=viewproblem2&cpid=1111) to the module [Silver - Greedy Algorithms with Sorting](https://usaco.guide/silver/greedy-sorting#problemlist-other).

**Difficulty**: Easy
**Tags**: Greedy, Sorting
**Additional Notes**:
https://pastebin.com/dVqSdE8k - easy to read solution

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by jessechoe10** [comment]
I think the difficulty should be **Normal** instead of **Easy**.

**Comment by andrewwangva** [comment]
I don't feel like this is a good greedy problem given it doesn't exemplify when to really decide if greedy works.
