### ISSUE TITLE
Qs

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#1054]
rip
<img width="280" alt="Screen Shot 2021-03-29 at 12 58 26 PM" src="https://user-images.githubusercontent.com/21228024/112872534-7ce3ed00-908e-11eb-81e3-aee88846d32e.png">

**Comment by thecodingwizard** [comment]
https://github.com/rsms/inter/issues/360

I think it's their issue

**Comment by thecodingwizard** [comment]
should be fixed now
