### ISSUE TITLE
Inconsistent use of : vs - in Section Headers

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#1056]
Compare:

<img width="251" alt="Screen Shot 2021-03-29 at 1 07 04 PM" src="https://user-images.githubusercontent.com/21228024/112873482-aea98380-908f-11eb-851f-da9271f5c920.png">

<img width="246" alt="Screen Shot 2021-03-29 at 1 06 59 PM" src="https://user-images.githubusercontent.com/21228024/112873485-aea98380-908f-11eb-8fa3-a7e7848a2fc9.png">

Personally I've been using `-`

**Comment by thecodingwizard** [comment]
let's just go with `-` then?
