### ISSUE TITLE
Make the Contributing Module a Section

### ISSUE THREAD

**Issue by jeffreymeng** [cpinitiative/usaco-guide#1057]
Right now, we have a [module on contributing](https://usaco.guide/general/contributing/) and some [content docs](https://github.com/cpinitiative/usaco-guide/blob/master/docs/Content%20Documentation.md).

Would it be better if we made a new group of modules for Contributing and eliminated most of the content docs files?
(the benefits are that it looks nicer, can be edited with the editor, can contain MDX, and will be more accessible)

The section would tentatively contain:
- Getting Started (ways to contribute, dev server & editor)
- Editing Modules (how modules work, how to edit them, some basic and common components, philosophy of modules and when to create a new module)
- Adding Solutions (basically [this section](http://localhost:8000/general/contributing/#adding-a-solution))
- Working with MDX (exhaustive list of all of the different components, some internals on how MDX works?)
- Front End Development (working with the js code for the website)

**Comment by thecodingwizard** [comment]
@bqi343

**Comment by bqi343** [comment]
sure

**Comment by dongliu0426** [comment]
nice idea

**Comment by darren-yao** [comment]
sure, why not
