### ISSUE TITLE
Remove Tree Problems from Silver

### ISSUE THREAD

**Issue by jessechoe10** [cpinitiative/usaco-guide#1059]
We should remove **Tree Diameter**, **Tree Distances I**, and **Tree Distances II** to `DP on Trees - Introduction (Gold)`.

**Comment by Aryansh-S** [comment]
Why? They're just (fairly standard) applications of DFS that can be instructive.

**Comment by jessechoe10** [comment]
Since they use DP...

**Comment by Aryansh-S** [comment]
Uh you can calculate the diameter of a tree with 2 DFS processes, after which tree distances I is basically trivial. I agree tree distances ii should move up to gold :).

**Comment by jessechoe10** [comment]
Oh tru.
