### ISSUE TITLE
Activity chart not showing column on reload

### ISSUE THREAD

**Issue by maggie-j-liu** [cpinitiative/usaco-guide#1063]
The rightmost column doesn't show if you reload the page, but it shows after navigating to another page and back.
![image](https://user-images.githubusercontent.com/63619830/112940561-2a342080-90e2-11eb-943d-f37e46d5ad74.png)

**Comment by thecodingwizard** [comment]
https://github.com/cpinitiative/usaco-guide/blob/473d22489969986a0574b17594baafb2127440d3/src/components/Dashboard/Activity.tsx#L70 (thanks @ dolphingarlic)

**Comment by dolphingarlic** [comment]
@thecodingwizard is https://www.joshwcomeau.com/react/the-perils-of-rehydration/ relevant to this bug?

**Comment by thecodingwizard** [comment]
Yes, that is the bug (to my understanding). The solution is as described in the blog too -- add an effect to check when the component is mounted (or even better, once firebase data is loaded).
