### ISSUE TITLE
IOI solutions have usacoid instead of year

### ISSUE THREAD

**Issue by maggie-j-liu** [cpinitiative/usaco-guide#1066]
https://github.com/cpinitiative/usaco-guide/blob/c87011e439904af7c50e9c64c9138faaca928786/src/models/problem.ts#L401-L404

https://github.com/cpinitiative/usaco-guide/blob/c87011e439904af7c50e9c64c9138faaca928786/src/models/problem.ts#L416-L419

should be `year: i`

**Comment by thecodingwizard** [comment]
oops, this is really annoying to fix. That code is no longer used anymore so we have to manually change this in the problem JSON files. @jeffreymeng can you do this?
