### ISSUE TITLE
Problem Suggestion: Add "Ehab and the Expected XOR Problem" to Silver - Introduction to Prefix Sums

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1075]
*Somya Mehta* (UID 1DthbWdgtuZGMn0VF1AwE13jSZZ2) suggested adding the problem [Ehab and the Expected XOR Problem](https://codeforces.com/contest/1174/problem/D) to the module [Silver - Introduction to Prefix Sums](https://usaco.guide/silver/prefix-sums#problemlist-cum).

**Difficulty**: Normal
**Tags**: Prefix Sums
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by andrewwangva** [comment]
I'll add to mixed problemset maybe since module has good amt of quality ones.
