### ISSUE TITLE
Problem Suggestion: Add "USACO 2021 January Contest, Silver - Dance Mooves" to Silver - (Optional) Introduction to Functional Graphs

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1084]
*Ukuma Sympa* (UID TIf7RckuciYVd928FQ43h5oloOm2) suggested adding the problem [USACO 2021 January Contest, Silver - Dance Mooves](http://www.usaco.org/index.php?page=viewproblem2&cpid=1086) to the module [Silver - (Optional) Introduction to Functional Graphs](https://usaco.guide/silver/func-graphs#problemlist-probs).

**Difficulty**: Normal
**Tags**: 
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by bqi343** [comment]
cycle doesn't rlly count ^_^
