### ISSUE TITLE
Problem Suggestion: Add "CSES Elevator Rides" to Platinum - Dynamic Programming on Bitmasks

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1085]
*Abhishek Singh* (UID bAe6gjaliyapKcr8grWhF23AQj33) suggested adding the problem [CSES Elevator Rides](https://cses.fi/problemset/task/1653) to the module [Platinum - Dynamic Programming on Bitmasks](https://usaco.guide/plat/dp-bitmasks#problemlist-general).

**Difficulty**: Normal
**Tags**: DP, Bitmask, Classical
**Additional Notes**:
refer to CPH( pg. 103-104) Elevator Rides example in DP using Bitmasks Section

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by dongliu0426** [comment]
it's already there
