### ISSUE TITLE
Problem Suggestion: Add "CSES Projects" to Gold - Knapsack DP

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1086]
*Abhishek Singh* (UID bAe6gjaliyapKcr8grWhF23AQj33) suggested adding the problem [CSES Projects](https://cses.fi/problemset/task/1140/) to the module [Gold - Knapsack DP](https://usaco.guide/gold/knapsack#problemlist-knapsack).

**Difficulty**: Easy
**Tags**: Classical Weighted Job Scheduling, DP, Binary Search
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by dongliu0426** [comment]
idt this is knapsack.
