### ISSUE TITLE
"You have encountered an error" on the USACO Monthlies page

### ISSUE THREAD

**Issue by huynhtrankhanh** [cpinitiative/usaco-guide#1089]
[This issue was reported by Malachi_Noel3#9962 on the unofficial USACO Discord server.](https://discord.com/channels/516125324711297024/516125325219069954/827572299930533909)

Screenshot:
![Screenshot from 2021-04-02 22 59 12](https://user-images.githubusercontent.com/61727983/113432152-10a71780-9407-11eb-9a60-d8683280f8f3.png)

**Comment by thecodingwizard** [comment]
will be fixed soon, sorry about that D:

**Comment by thecodingwizard** [comment]
should be fixed now
