### ISSUE TITLE
Problem Suggestion: Add "Square Pasture" to General - Expected Knowledge

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1091]
*Ethan Liang* (UID QofM50M3AMUbrMeGjpGPHj3n3ri1) suggested adding the problem [Square Pasture](http://www.usaco.org/index.php?page=viewproblem2&cpid=663) to the module [General - Expected Knowledge](https://usaco.guide/general/expected#problemlist-general).

**Difficulty**: Easy
**Tags**: 
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by bqi343** [comment]
for a moment I thought it was [this](http://www.usaco.org/index.php?page=viewproblem2&cpid=1067) square pasture ^_^

**Comment by maggie-j-liu** [comment]
This problem is already in Rectangle Geometry (which doesn't have that many problems)...
