### ISSUE TITLE
misc email suggestions

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#1092]
https://usaco.guide/plat/dp-bitmasks/#bitmask-over-primes

Please complete section: Bitmask over Primes.
what mean b in binary representation? {0b0111,0b101,0b110}, please explain it.

Prefix Sum resource suggestion

add https://codeforces.com/blog/entry/88474

**Comment by bqi343** [comment]
0b just means that the number is binary lol

also that resource is in Russian :/
