### ISSUE TITLE
Problem Suggestion: Add "Silver Fox vs Monster" to Silver - Two Pointers

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1093]
*Joshua Liu* (UID Ih4VpIMmAmfa2eyZyscK4pkeNLy2) suggested adding the problem [Silver Fox vs Monster](https://atcoder.jp/contests/abc153/tasks/abc153_f) to the module [Silver - Two Pointers](https://usaco.guide/silver/2P#problemlist-ad).

**Difficulty**: Normal
**Tags**: Two Pointers, Prefix Sums
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by andrewwangva** [comment]
Don't think this is a great two p problem. Imo it's closer to greedy and its kinda a repeated concept.
