### ISSUE TITLE
Problem submitting code in group

### ISSUE THREAD

**Issue by coderinblack08** [cpinitiative/usaco-guide#1098]
Whenever I try to submit code for a HW problem in my USACO group (CPI intermediate class), it doesn't save and I get this error

![image](https://user-images.githubusercontent.com/41022901/113496628-76031300-94b0-11eb-8918-cca3dc7a3917.png)

**Comment by thecodingwizard** [comment]
@jeffreymeng

**Comment by coderinblack08** [comment]
IDK why something is undefined in my user document.
