### ISSUE TITLE
Problem Suggestion: Add "subarray squares" to Platinum - Divide & Conquer - DP

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1099]
*Ray Tang* (UID jjkJgktEM3brQnXtcoJaqtkjnYg1) suggested adding the problem [subarray squares](https://cses.fi/problemset/task/2086) to the module [Platinum - Divide & Conquer - DP](https://usaco.guide/plat/DC-DP#problemlist-dnc_general).

**Difficulty**: Easy
**Tags**: 
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by nchn27** [comment]
good to add to the section's problem list (there's currently no easy problems) or to a mixed problemset
