### ISSUE TITLE
Problem Suggestion: Add "Codeforces Beta Round #13 E.Holes" to Platinum - Square Root Decomposition

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1105]
*Ahmet Ala* (UID NojEbJTvdyQYvN5mqvHo5k6qYE03) suggested adding the problem [Codeforces Beta Round #13 E.Holes](https://codeforces.com/problemset/problem/13/E) to the module [Platinum - Square Root Decomposition](https://usaco.guide/plat/sqrt#problemlist-fst).

**Difficulty**: Easy
**Tags**: Square Root Decomposition, Data Structures
**Additional Notes**:
It is a pure sqrt problem. I highly suggest you to add this to problem suggestions.

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by nchn27** [comment]
good to add to either the problem list or a mixed problemset
