### ISSUE TITLE
Auto-Generate Author Names

### ISSUE THREAD

**Issue by Aryansh-S** [cpinitiative/usaco-guide#1106]
I recommend finding a way to auto-generate names (the authors at the top of the module) and ranking them by contribution amount for each module. 

I'm not sure how exactly this could work, but I'm sure there's a way. This will increase flexibility of contributions.

**Comment by SansPapyrus683** [comment]
How would that even work? I guess the code would have to link to GitHub, see which authors contributed which characters, then rank them and put them at the top.

Seems like too much work for too little reward.

**Comment by Aryansh-S** [comment]
I don't see how the reward would be "too little" because it allows people to contribute freely without having to worry about being recognized for their work. This might in turn make it easier to contribute and encourage more people to contribute. The more the contribution to an open source project like this, the better. Additionally, it would also be extensible, a script that could run with file modification commit.

**Comment by SansPapyrus683** [comment]
If they want to be recognized for their work, couldn't they just type their name in with the rest of the authors?

**Comment by Aryansh-S** [comment]
They could indeed, but this streamlines the process and formally orders the credits by contribution amount.

**Comment by MrinallU** [comment]
@Aryansh-S More commits that are directed to the module does not necessarily mean that they put in more work. For example  if BenQ wrote the whole module in one commit and another person wrote a single solution with five commits the order of contribution would not add up. You must also consider other cases such as the links to Darren Yao's book, he may have added the link in one commit but the chapter of the book may help more than the explanation in the guide.  Also, it does seem like too much work for such something as small as the ordering of names.

**Comment by Aryansh-S** [comment]
I never said to factor in the number of commits but rather the number of lines of contribution to the mdx file. If someone writes most of the module in one commit, they'll be credited first. In terms of external sources, they're credited on a per source basis (meaning that if someone authors an external source, they're credited next to where that source is referenced), so I believe author ordering would be best done by lines of contribution to the module itself.

**Comment by MrinallU** [comment]
What about the quality of the contribution, would I don't think it would be right to have one solution that contains many lines to outrank someone that made the entire solution. Plus what about the illustrations and animations made by the contributors (ex https://usaco.guide/plat/bin-jump?lang=cpp). Basically what I'm saying is that the number of lines/characters contributed to the file cannot accurately rank the quality of the contribution. And to be honest contributing to the guide should not be treated as some kind of competition, people should contribute because they want to help the community or gain more experience in open source, not because of their ranking.

**Comment by MrinallU** [comment]
Besides I doubt many of the contributors would care about the order of their names on the site, I'm sure they are happy just by having their name inside the site so they can gain the recognition.

**Comment by MrinallU** [comment]
But I guess if the contributors really want it, then it wouldn't hurt to implement this.

**Comment by Aryansh-S** [comment]
You're absolutely right in the fact that contributions shouldn't be treated as competition and that the ordering of the names doesn't even entirely matter, but I just thought it might be useful to come up with a uniform, automated way to generate the ordering, especially since some contributors who do contribute significantly to certain modules may simply append themselves at the end of the list (I'm not sure how much of a problem this is for USACO Guide, but this is something contentious in the world of general research and academia). You do bring up great points about how the quality of the contribution matters, but I think that, as a general trend, contributions are always kept as concise as possible. If the concision of contributions is maximized, then the length of the contribution should be roughly proportional to its quality or relevance to the module as a whole.

**Comment by MrinallU** [comment]
I'll close this for now.

**Comment by thecodingwizard** [comment]
> especially since some contributors who do contribute significantly to certain modules may simply append themselves at the end of the list

I think we should specify more clearly when/how people should add themselves to the authors list (though to be fair this hasn't been a huge issue so far). I think automating this process is too hard though :P
