### ISSUE TITLE
Problem Suggestion: Add "IOI 2009 Mecho" to Gold - Breadth First Search (BFS)

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1120]
*ignacio cantarella* (UID u5tnOwwl9vRItES9RAuv7i6CTwu2) suggested adding the problem [IOI 2009 Mecho](https://oj.uz/problem/view/IOI09_mecho) to the module [Gold - Breadth First Search (BFS)](https://usaco.guide/gold/bfs#problemlist-general).

**Difficulty**: Normal
**Tags**: BFS, Binary Search
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by maggie-j-liu** [comment]
done in #1334
