### ISSUE TITLE
Problem Suggestion: Add "COCI 2020/21 Contest #5: Sjeckanje" to Platinum - More Applications of Segment Tree

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1121]
*Suneet Mahajan (ScarletS)* (UID vPbPRGNVC9RWaOpTshd1rTY5rLy1) suggested adding the problem [COCI 2020/21 Contest #5: Sjeckanje](https://hsin.hr/coci/contest5_tasks.pdf) to the module [Platinum - More Applications of Segment Tree](https://usaco.guide/plat/seg-ext#problemlist-comb).

**Difficulty**: Normal
**Tags**: Data Structures
**Additional Notes**:
Just another problem that fits into this section pretty well :D
My solution: https://github.com/SMiles02/CompetitiveProgramming/blob/master/OIs/COCI/2020-21/sjeckanje.cpp

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by dolphingarlic** [comment]
Good problem, but I think it should be hard instead of normal
