### ISSUE TITLE
Problem Suggestion: Add "USACO January 2016 Platinum - Fort Moo" to Silver - Introduction to Prefix Sums

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1122]
*Rayfish5* (UID M6y0nf7NEpbM1BhgQ8ZvYXylFg12) suggested adding the problem [USACO January 2016 Platinum - Fort Moo](http://www.usaco.org/index.php?page=viewproblem2&cpid=600) to the module [Silver - Introduction to Prefix Sums](https://usaco.guide/silver/prefix-sums#problemlist-cum).

**Difficulty**: Hard
**Tags**: Prefix Sums, Sliding Window
**Additional Notes**:
Solution very similar to first solution in USACO Silver Just Green Enough.

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by SansPapyrus683** [comment]
I feel like a difficulty of normal would be better.

**Comment by andrewwangva** [comment]
> I feel like a difficulty of normal would be better.

Definitely Hard given the gold module places it as Normal.

**Comment by andrewwangva** [comment]
Also sorry Jeffrey I haven't been adding the problems - Ill add them all in one big batch over the weekend.

**Comment by SansPapyrus683** [comment]
I mean, it's just a sort of 2D Kadane's combined with prefix sums, so it isn't really *that* hard. But of course, that's just my opinion.
