### ISSUE TITLE
Problem Suggestion: Add "Bear and Bad Powers of 42" to Advanced - Segment Tree Beats

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1125]
*Michael Yu* (UID EycPEYQB54WHpv7HVSKhcclQAwE2) suggested adding the problem [Bear and Bad Powers of 42](https://codeforces.com/contest/679/problem/E) to the module [Advanced - Segment Tree Beats](https://usaco.guide/adv/segtree-beats#problemlist-segTreeBeats).

**Difficulty**: Hard
**Tags**: SegTreeBeats
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by SansPapyrus683** [comment]
![image](https://user-images.githubusercontent.com/55369003/113783843-3c691c80-96e9-11eb-9a1f-adfa12b893b8.png)

Also, maybe make the section marked as incomplete or something.
