### ISSUE TITLE
Problem Suggestion: Add "USACO January 2016 Silver - Build Gates" to Silver - Flood Fill

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1127]
*Rayfish5* (UID M6y0nf7NEpbM1BhgQ8ZvYXylFg12) suggested adding the problem [USACO January 2016 Silver - Build Gates](http://www.usaco.org/index.php?page=viewproblem2&cpid=596) to the module [Silver - Flood Fill](https://usaco.guide/silver/ff#problemlist-general).

**Difficulty**: Easy
**Tags**: Flood Fill
**Additional Notes**:
Already in module, but it should have an Easy difficulty.

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by HarryWangATX** [comment]
i think normal is fine.
