### ISSUE TITLE
Problem Suggestion: Add "I Curse Myself" to Advanced - Fracturing Search

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#1128]
*luca dantas* (UID O5kCsFhdUfXLPWqOgBviDbvCEpB3) suggested adding the problem [I Curse Myself](https://codeforces.com/gym/102253/problem/I) to the module [Advanced - Fracturing Search](https://usaco.guide/adv/fracture#problemlist-general).

**Difficulty**: Normal
**Tags**: 
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by bqi343** [comment]
almost identical to roboherd (though with some preprocessing and an easier solution intended), don't think it's necessary to add
