### ISSUE TITLE
Code Submission Area

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#1133]
https://github.com/cpinitiative/usaco-guide/blob/master/src/components/SubmitProbemSolutionModal.tsx

Why so tiny?

<img width="586" alt="Screen Shot 2021-04-06 at 8 54 23 PM" src="https://user-images.githubusercontent.com/21228024/113795476-017fdc80-971b-11eb-9d9b-5e5ba973d63f.png">

**Comment by maggie-j-liu** [comment]
![image](https://user-images.githubusercontent.com/63619830/113795866-b78afc80-9702-11eb-8a3b-eed14eed0a3d.png)
the submit button's styles are also not showing

**Comment by HarryWangATX** [comment]
also doesnt let me type on mobile sized window

**Comment by HarryWangATX** [comment]
the white text box also looks rly bad with dark mode
