### ISSUE TITLE
Remove "(Optional)" from the Gold LIS and DP on Trees

### ISSUE THREAD

**Issue by Aryansh-S** [cpinitiative/usaco-guide#1147]
https://usaco.guide/gold/lis?lang=cpp
https://usaco.guide/gold/all-roots?lang=cpp

You should lower the frequency instead. I think "(Optional)" discourages people from ever reading these modules, and I don't think that's a good approach. The above concepts could be used as or in the main ideas of harder gold problems. 

"(Optional)" should be reserved for concepts that strictly aren't required and have notable alternatives, such as the following, where I do believe "(Optional)" is warranted:
https://usaco.guide/gold/unordered?lang=cpp (easily replaced by coordinate compression)
https://usaco.guide/gold/faster-hashmap?lang=cpp (easily replaced by Fenwick trees in the case of ordered statistics and again by coordinate compression for hashes, and not even an option outside of the GCC distribution of C++)

**Comment by SansPapyrus683** [comment]
> not even an option outside of the GCC distribution of C++

Most (if not all) OJs use GCC, so this shouldn't be a problem.

**Comment by Aryansh-S** [comment]
True, but in any case, the "(Optional)" still makes sense because it's C++-specific.

**Comment by Aryansh-S** [comment]
@bqi343 @thecodingwizard 
would appreciate some feedback on this issue to potentially make a pr

**Comment by thecodingwizard** [comment]
I'm fine with these changes if @bqi343 is fine with them too

**Comment by bqi343** [comment]
sure

**Comment by Aryansh-S** [comment]
Will make a PR for these changes later today; thanks

**Comment by Aryansh-S** [comment]
Made the necessary PRs through the issues above; closing
