### ISSUE TITLE
Live Editor - Clicking on Hyperlink Shifts Page

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#1365]
<img width="1440" alt="Screen Shot 2021-04-18 at 10 56 01 PM" src="https://user-images.githubusercontent.com/21228024/115175633-54ea1700-a099-11eb-8880-872d74165ccd.png">

 - URL icons on left hand side of rendered content partially hidden
 - white space at bottom after clicking on URL icon
 - language selection is partially hidden

**Comment by thecodingwizard** [comment]
in Editor v2 (#1398) somehow the second and third issues got fixed. Not sure if the first issue is worth fixing (is there a use case for when you would actually click the URL icon in the editor?)

**Comment by bqi343** [comment]
yea it's fine
