### ISSUE TITLE
editor bug

### ISSUE THREAD

**Issue by dongliu0426** [cpinitiative/usaco-guide#1402]
when i try to edit a solution page with https://usaco.guide/editor, it shows:

```
An error occurred while generating the problem solution info. This typically indicates an error in the problems JSON file:
SyntaxError: Unexpected token : in JSON at position 3

This error has also been logged to the console.
```

**Comment by maggie-j-liu** [comment]
> editing an internal solution in editor will also try to load a problems.json file, which will return a 404 and throw an error for invalid json

@thecodingwizard said 
> Should be fixed in new editor I think

**Comment by dongliu0426** [comment]
ig i'll close this
