### ISSUE TITLE
No English Version of JOI 2016 - Matryoshka available 

### ISSUE THREAD

**Issue by Qw3rTy827** [cpinitiative/usaco-guide#1426]
I was working on the LIS module in Gold recently. After I click on the link for this problem, I can only find a download PDF version describing the problem in Japanese. Can anyone add the English version of the problem. 

The link in the module directs me to: https://atcoder.jp/contests/joisc2016/tasks/joisc2016_a  (Japanese only).

**Comment by maggie-j-liu** [comment]
Duplicate of #1348...

**Comment by SansPapyrus683** [comment]
yeah it's a duplicate
