### ISSUE TITLE
Running Code Snippets Inline

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#1456]
Like https://marketplace.visualstudio.com/items?itemName=statiolake.vscode-markdown-run-snippet?

Alternatively, add a button that opens the code snippet in https://ide.usaco.guide/ when pushed?

**Comment by thecodingwizard** [comment]
that would be super cool (and wouldn't even be that hard to implement)

**Comment by maggie-j-liu** [comment]
If this isn't possible, maybe a button to copy all the code so it would be easier to paste and run?
