### ISSUE TITLE
URL language param changes?

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#1472]
Should the language be added automatically, or only when an anchor tag is clicked?

Seems a bit annoying to have to remove the lang param every time I try to share a module URL.

**Comment by maggie-j-liu** [comment]
Maybe we could add a button to copy the module url without the lang param and the actual url could be used for sharing with the language?

**Comment by bqi343** [comment]
@thecodingwizard Do you usually want to share w/ the language when you click on an anchor tag that appears for all languages? Current behavior seems fine to me.

**Comment by thecodingwizard** [comment]
> @thecodingwizard Do you usually want to share w/ the language when you click on an anchor tag that appears in all languages? Current behavior seems fine to me.

Ideally maybe the `lang=` query param is only appended if you click on an anchor tag that does not appear in all three languages?

Alternatively, just don't ever append the `lang=` query param, and show a warning message if a user opens a link with an anchor tag that doesn't exist on their particular language?

---

When people share links they're always looking to share information about a particular *topic*, not a particular *language*, right? so other than the case where an anchor tag doesn't exist for a specific language, is it reasonable to say that the user does not want to share URL's with `lang=`?

**Comment by bqi343** [comment]
> so other than the case where an anchor tag doesn't exist for a specific language, is it reasonable to say that the user does not want to share URL's with lang=?

Yes, though the anchor tag not existing is quite a frequent occurrence.

**Comment by maggie-j-liu** [comment]
hmm i think the current behavior is okay, but feel free to reopen if you have a different opinion
