### ISSUE TITLE
Division Table Updates

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#1502]
https://usaco.guide/general/usaco-monthlies

- [ ] permalinks should open the corresponding division table (ex. https://usaco.guide/general/usaco-monthlies#problem-usaco-789)
- [ ] problems that appear in the division table but not in any module should still appear in dashboard active problems

**Comment by bqi343** [comment]
will work on this after camp ...

**Comment by thecodingwizard** [comment]
also we should ask Dr. Dean to share anonymized solve statistics with us :eyes:

is "percentage solved amongst promoters" more important or is "percentage solved amongst contestants" more important?

**Comment by bqi343** [comment]
sure

def the latter
