### ISSUE TITLE
Zookeepers' Gathering

### ISSUE THREAD

**Issue by dongliu0426** [cpinitiative/usaco-guide#1539]
https://usaco.guide/adv/CntMin#problem-mbit-ZookeepersGathering

might be cf error but the link results in a blank page :/

![Screen Shot 2021-05-16 at 10 44 30 PM](https://user-images.githubusercontent.com/59348162/118437899-498a0b80-b698-11eb-8ccc-df34f37e7f59.png)

**Comment by bqi343** [comment]
there's an attached PDF

**Comment by SansPapyrus683** [comment]
how should we point this out in the website?

**Comment by thecodingwizard** [comment]
Just add a note under the problems header?
