### ISSUE TITLE
Consider Firebase Alternatives

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#1595]
Our firebase system is sort of messed up right now -- every time the user doc changes (which is very often), the user re-downloads the whole doc with no delta optimization, which is bad if the user doc is large. We should consider moving some stuff / everything out of firebase and into a custom database...

**Comment by mizlan** [comment]
Firebase supports GraphQL, which we can use to limit requests to only the information needed.

**Comment by mizlan** [comment]
Nevermind, it's not a true solution

**Comment by MrinallU** [comment]
Consider using sequelize along with Mysql.

**Comment by thecodingwizard** [comment]
Hm okay being realistic this probably will not get done anytime soon :(
