### ISSUE TITLE
UI: problem search results not clickable

### ISSUE THREAD

**Issue by mizlan** [cpinitiative/usaco-guide#1646]
Small inconvenience that probably has gone unnoticed by common users of the webapp: when I perform a search on https://usaco.guide/problems/, the search results come in boxes, of which neither the box itself nor the title of the box are clickable. This was particularly confusing for me since I didn't realize there was anything clickable in the box for a while, since the links have gone so far as to be greyed out.

I'm thinking that the they should both link to the problem, but feel free to bring up other ideas.

**Comment by SansPapyrus683** [comment]
I take it you mean the problem on USACO Guide- there's already a "View Problem Statement" hyperlink.
And yeah, this would definitely help.

**Comment by maggie-j-liu** [comment]
Some problems appear on the guide multiple times; so I think mizlan means the problem statement? He said that he didn't realize that the link was clickable since it was grayed out. If we link the box/title to the problem statement, then we can remove the "View Problem Statement" link.

**Comment by mizlan** [comment]
It was more that I kept trying to click the box and/or title to no avail, I would like those to be clickable as well.

**Comment by maggie-j-liu** [comment]
Do you think it would make more sense to link the box/title to the problem statement itself, or to one of the occurrences in the guide?
