### ISSUE TITLE
Conventions for Problem Sources & Tags

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#1731]
- [x] make sure existing sources / tags follow conventions (ex. #1730, https://github.com/cpinitiative/usaco-guide/pull/1657#issuecomment-860261282)
 - [x] note conventions for sources / tags somewhere

**Comment by thecodingwizard** [comment]
@cpinitiative/content-managers do we note these conventions anywhere?

**Comment by SansPapyrus683** [comment]
is this still a problem?

**Comment by bqi343** [comment]
Some concrete conventions:

 1. Use the existing sources in https://github.com/cpinitiative/usaco-guide/blob/20d696c1306947a054c41b1d3554f9a6a5515064/src/models/problem.ts#L6 when possible.
 2. Leave the list of tags blank as opposed to adding "Ad Hoc" as a tag.
 3. Use existing tags when possible, capitalize new tags in the same way as previous tags.
 4. Split tags into separate strings (e.g., `['Meet in the Middle', 'DP']` rather than `['Meet in the Middle, DP']`). Seems to have been violated a lot recently (https://usaco.guide/problems/).

> "adding solution" maybe

Probably https://usaco.guide/general/modules?lang=cpp#practice-problems would be more suitable, since "Adding Solution" doesn't include adding problems.
