### ISSUE TITLE
# Users Online

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#174]
Like USACO Training :o
<img width="211" alt="Screen Shot 2020-08-18 at 7 03 01 PM" src="https://user-images.githubusercontent.com/21228024/90573858-7bac2280-e185-11ea-9da6-034d5b14d4fb.png">

**Comment by dolphingarlic** [comment]
I think I'd like to try to implement this. Where would this count go? Maybe on the homepage?

**Comment by thecodingwizard** [comment]
Sure, or the dashboard or both. Firebase has this: https://firebase.google.com/docs/auth/web/auth-state-persistence but it seems inaccurate... Maybe there's a better way of doing it
