### ISSUE TITLE
[Enhancement] Adding "Notes" feature to problem statements

### ISSUE THREAD

**Issue by joshualiu555** [cpinitiative/usaco-guide#1798]
For the current problem statements, you can click the 3 vertical dots to see official editorials, user solutions, and permalink. 

There could also be another feature that allows the user to create a little note. 

One reason someone might want this is if they skipped a problem but planned to return to it later. If they don't want to forget their current solution, they can sketch down their thought process for next time. 

This probably aren't too many uses for this, and someone could do it manually, but having the feature in the website itself would make things a little more convenient.

**Comment by bqi343** [comment]
You could add your notes under "View User Solutions." Though then the problem would be spoiled if you caught a glimpse of someone else's solution.

**Comment by MrinallU** [comment]
I'll do this.

**Comment by SansPapyrus683** [comment]
it's been like 8 months

**Comment by MrinallU** [comment]
https://github.com/cpinitiative/usaco-guide/pull/2093 this has been here for a while, but we decided to ditch this since submitting a private user solution is the exact same thing as having problem notes

**Comment by MrinallU** [comment]
I can finish this if you like.

**Comment by SansPapyrus683** [comment]
not needed, you can close this @ your own discretion

**Comment by MrinallU** [comment]
Many users already make use of private user submissions to keep problem notes, as such, this feature is not needed.
