### ISSUE TITLE
Add internal solution link to focus problems

### ISSUE THREAD

**Issue by maggie-j-liu** [cpinitiative/usaco-guide#1870]
add a link here:
![image](https://user-images.githubusercontent.com/63619830/124327269-a6ecf580-db3c-11eb-9a26-2f87102e320b.png)

this is mostly for video solutions; we want to keep the module's original solution but also link to the new internal solution

**Comment by SansPapyrus683** [comment]
what would we call it
"sol w/ video" or something

**Comment by maggie-j-liu** [comment]
@thecodingwizard ?

**Comment by thecodingwizard** [comment]
just "Internal Solution" is fine?
