### ISSUE TITLE
Fix Planets Queries II Explanation (And Code?)

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#1939]
https://usaco.guide/problems/cses-1160-planets-queries-ii/solution

https://forum.usaco.guide/t/need-help-in-cses-planets-queries-ii/1662/2

**Comment by SansPapyrus683** [comment]
lmao michael went afk on this so i'll put this on my todo list

**Comment by SansPapyrus683** [comment]
actually nvm it's a platinum topic this is beyond my pay grade lol

**Comment by dutinmeow** [comment]
I will address this issue

**Comment by SansPapyrus683** [comment]
you'd better

**Comment by dutinmeow** [comment]
https://github.com/cpinitiative/usaco-guide/pull/2366

**Comment by SansPapyrus683** [comment]
close when the pr gets merged

**Comment by SansPapyrus683** [comment]
i'll take a crack at this problem
