### ISSUE TITLE
Verify modules and internal solutions

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#1945]
- [x] verify that all modules in `ordering.ts` exist
   - apparently the build stalls when they don't ...
 - [x] verify that all problems that claim to have internal solutions actually do #1945

**Comment by SansPapyrus683** [comment]
how would a problem w/ a "fake" internal solution exist

**Comment by bqi343** [comment]
> how would a problem w/ a "fake" internal solution exist

if someone adds an internal solution but changed the `solutionMetadata` for the wrong problem. not sure whether this has happened though since we haven't set up a method of detecting this afaik
