### ISSUE TITLE
Add Settings Popup

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#197]
Add a settings modal popup that has three options:

1. Language (C++/Java/Python)
2. Hide tags & solutions (checkbox, yes/no)
3. Dark mode (checkbox, yes/no)

In the module layout, replace the three options in the sidebar with a singular "settings" button that opens the modal popup

For the navbar, replace the "Login/Logout" button with a vertical three-dots dropdown menu with the following options:

- Settings, which opens the modal
- Login/Logout, which works as described

**Comment by MrinallU** [comment]
Is this still going on?

**Comment by thecodingwizard** [comment]
Yep. @koxuan is working on this!
