### ISSUE TITLE
Fix internal solution to Cow At Large

### ISSUE THREAD

**Issue by dongliu0426** [cpinitiative/usaco-guide#1990]
https://usaco.guide/problems/usaco-790-cow-at-large/solution

https://forum.usaco.guide/t/usaco-2018-january-contest-gold-cow-at-large/1731

Current solution runs in `O(N * LEAVES)` so it's `O(N^2)` when there are `N - 1` leaves.

**Comment by Aadit-Ambadkar** [comment]
But it gets AC

**Comment by SansPapyrus683** [comment]
you can actually fakesolve some problems on usaco i think

**Comment by RedBlueBird** [comment]
Alright I will work on this

**Comment by RedBlueBird** [comment]
> Alright I will work on this

Woah ok, this is already fixed, the issue was just not closed
