### ISSUE TITLE
Add more topics (not a priority)

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#2]
* Min Deque
 * Meet in Middle
 * Ternary Search
 * Boruvka

**Comment by dolphingarlic** [comment]
Some more potential topics:
- Virtual trees (this might fall under stacks)
- CDQ D&C (and other weird Chinese tricks: https://oi-wiki.org/)
- Weird graphs where you can do NP-hard problems in polynomial time(?) e.g. series-parallel graphs (not sure how relevant these are for cp, but I think they're cool and I've seen a few problems that use them)

**Comment by bqi343** [comment]
> CDQ D&C

already mentioned here: https://usaco.guide/plat/2DRQ?lang=py#idea-3-use-divide--conquer-with-a-1d-bit
