### ISSUE TITLE
Fix Fence Painting focus problem solution

### ISSUE THREAD

**Issue by dongliu0426** [cpinitiative/usaco-guide#2004]
https://usaco.guide/bronze/rect-geo/#fast-solution

C++ code doesn't compile

**Comment by SansPapyrus683** [comment]
which one now?

**Comment by maggie-j-liu** [comment]
i think `union` is a keyword?

**Comment by SansPapyrus683** [comment]
what standard yall compiling with

**Comment by bqi343** [comment]
It should work on `ide.usaco.guide` (GCC 9.2.0 with `-std=c++17`)

**Comment by dongliu0426** [comment]
Hmm it doesn't work on my machine (it's GCC 11.1.0 with -std=c++17)

**Comment by SansPapyrus683** [comment]
uh dong check my pr
