### ISSUE TITLE
Extension Displayed Twice in Editor File Search

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#2055]
See last image.

<img width="509" alt="Screen Shot 2021-08-06 at 9 27 14 AM" src="https://user-images.githubusercontent.com/21228024/128522140-b28fcdb6-e5d0-4398-8cd2-da499a5c3f64.png">

<img width="507" alt="Screen Shot 2021-08-06 at 10 06 44 AM" src="https://user-images.githubusercontent.com/21228024/128522692-e3b7617d-2f44-4345-af1e-c3e138a1c5f4.png">

<img width="510" alt="Screen Shot 2021-08-06 at 9 27 24 AM" src="https://user-images.githubusercontent.com/21228024/128522138-88d44d6e-a1f7-4abc-aa03-684815714dd7.png">

**Comment by SansPapyrus683** [comment]
what might be the cause of the bug? idk how the search engine works

**Comment by bqi343** [comment]
Can't reproduce this issue anymore (though I'm still not sure why `md` is highlighted).

<img width="500" alt="Screen Shot 2022-06-18 at 2 55 34 PM" src="https://user-images.githubusercontent.com/21228024/174452546-8b7cead8-56f0-4730-9133-32eb1b1abb07.png">
