### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by caoash** [cpinitiative/usaco-guide#206]
![image](https://user-images.githubusercontent.com/45920019/91234304-912aca80-e6f8-11ea-8be9-0abf40dfc4ad.png)

To be honest, not a huge fan of this. Maybe just me...

**Comment by thecodingwizard** [comment]
I'll close for now, feel free to reopen if anyone has ideas...

**Comment by MrinallU** [comment]
@thecodingwizard I have an idea, can I work on this in my free time?
