### ISSUE TITLE
que: Should we include the free ebook link provided on CSES site 

### ISSUE THREAD

**Issue by dr-raul-aguirre** [cpinitiative/usaco-guide#2095]
In the input and output section(General Category), a link for springer is included for the `cses book`. Should we alternatively include the free ebook link? https://cses.fi/book/book.pdf. Thank you.

**Comment by dongliu0426** [comment]
Which link are you talking about @dr-raul-aguirre ? https://usaco.guide/general/input-output?lang=cpp#resource-https%3A%2F%2Flink.springer.com%2Fbook%2F10.1007%2F978-3-319-72547-5 This one?

**Comment by dr-raul-aguirre** [comment]
yes.

**Comment by dongliu0426** [comment]
The link points to GCP (Guide to Competitive Programming), which isn't the same as CPH (https://cses.fi/book/book.pdf).

**Comment by dr-raul-aguirre** [comment]
It is not exactly same, but I would say it is a close cousin 😄 almost similar index and same author. What do you say?

**Comment by dongliu0426** [comment]
yea but CPH doesn't have the example C++ solution for CSES Weird Algorithm.

**Comment by dr-raul-aguirre** [comment]
yeah, that is true. My thinking was as CPH is free and easily accessible, people who maybe can't/don't want to buy can go for this alternative.

**Comment by bqi343** [comment]
CPH is included within the guide many times (ex. [here](https://usaco.guide/general/resources-cp?lang=cpp#within-this-guide))

**Comment by dr-raul-aguirre** [comment]
my bad, I didn't saw that.
