### ISSUE TITLE
Quiz Answer Choices Aren't Saved

### ISSUE THREAD

**Issue by nathangong** [cpinitiative/usaco-guide#2155]
Currently, if you've finished a few questions but go back, the previous answer choices aren't saved and thus you have to re-enter all your answers before moving to the question you were on previously. Is this intended?

**Comment by bqi343** [comment]
+1, it shouldn't be necessary to answer a question before proceeding to the next.

**Comment by bqi343** [comment]
Another thing - when a wrong answer is selected, only the explanation for that one should be shown, and the user should be free to select another option.

**Comment by topshenyi-web** [comment]
See #2739 :D
