### ISSUE TITLE
Home Page Theme

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [cpinitiative/usaco-guide#2226]
Home page theme is not consistent. It flops between light and dark, making it painful for the eyes. Toning down the light and making it consistent with the theme selected in settings would be benefitial.

**Comment by SansPapyrus683** [comment]
actually yeah why not just make everything dark theme

**Comment by Aadit-Ambadkar** [comment]
Is anyone gonna do this?

**Comment by shaymor** [comment]
permission to work on this?

**Comment by SansPapyrus683** [comment]
ye sure, but i see you alr have an issue open @shaymor

**Comment by Aadit-Ambadkar** [comment]
How is this coming along? (I can't webdev sorry)

**Comment by SansPapyrus683** [comment]
so either make everything white or everything black?

**Comment by omkarbajaj073** [comment]
I tried making everything black, which works well on the dark theme, but on the light theme, it doesn't flow with the rest of the site. I'll try making separate styles.

**Comment by ryanchou-dev** [comment]
hmm, ok, ill assign you for now \ lmk if you're unable to work on it
