### ISSUE TITLE
Typo in Range for Long Long

### ISSUE THREAD

**Issue by shubhanshu02** [cpinitiative/usaco-guide#2289]
## Description 

There's a typo in the table for the range of `long long`. Since a `long long` variable uses 8-bit memory and can be both positive or negative, its range must be from - 2^63 to 2^63 - 1. 

Actual Present: `$-2^{64}$ to $2^{64}-1$ `
Expected: `$-2^{63}$ to $2^{63}-1$ `

Line Number:  40
File Link: https://github.com/cpinitiative/usaco-guide/blob/master/content/1_General/Data_Types.mdx

**Comment by bqi343** [comment]
Good catch. Should be 8 *bytes*, not bits, though.

**Comment by shubhanshu02** [comment]
Oops, right 😅. Thanks for correcting.
