### ISSUE TITLE
Clean up Language-Specific Section

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#2300]
Everything from "Debugging (Language-Specific)" downwards is sort of a mess

**Comment by SansPapyrus683** [comment]
ok if the test case is too big for you to even compare the output
if you know which answer is wrong then you probably can't debug the test case even if you do know which query or whatever went wrong

**Comment by bqi343** [comment]
Ideally, your generator should generate small tests.

**Comment by SansPapyrus683** [comment]
oh i see yeah that makes sense

**Comment by SansPapyrus683** [comment]
<img width="278" alt="image" src="https://user-images.githubusercontent.com/55369003/143793889-02382c38-62ec-4951-8380-b20a13f48c23.png">
so are you talking about this entire section?

**Comment by SansPapyrus683** [comment]
so how should i fix these? tbh some seem a bit unnecessary

**Comment by bqi343** [comment]
idk

**Comment by SansPapyrus683** [comment]
ok maybe we should discuss this next meeting actually

**Comment by SansPapyrus683** [comment]
done
