### ISSUE TITLE
another english translation needed

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#2301]
https://usaco.guide/gold/mst?lang=cpp#problem-joi-15-inheritance
bruh

**Comment by SansPapyrus683** [comment]
even worse, there doesn't seem to be a submission page

**Comment by bqi343** [comment]
Doesn't it link to the submission page?

(Though I'm all in favor of removing all problems without English statements from the guide ...)

**Comment by SansPapyrus683** [comment]
> Doesn't it link to the submission page?

![image](https://user-images.githubusercontent.com/55369003/140246312-b2a323a7-0869-4dfd-b183-c3c0f0095b1c.png)
well tell me where i submit lol

**Comment by bqi343** [comment]
I see it when I'm signed in.

**Comment by SansPapyrus683** [comment]
oh alr
also the actual statement requires some digging
the link links to a page full of japanese which then contains the pdf of the problem

**Comment by SansPapyrus683** [comment]
https://gist.github.com/SansPapyrus683/a17f37a4a938e13000e281e4843b73bc
ok i got the translation up and running

**Comment by SansPapyrus683** [comment]
i'll add this with a solution after nathan answers my question in the forum *cough cough wink wink*
