### ISSUE TITLE
Make Modules Consistent With Each Other & Across Languages

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#2349]
Referring to the bronze and silver set modules

https://github.com/cpinitiative/usaco-guide/pull/2317#issuecomment-974746436

**Comment by SansPapyrus683** [comment]
is this just the module in general or just jesse's quiz

**Comment by bqi343** [comment]
in general

**Comment by SansPapyrus683** [comment]
ok will do after io module

**Comment by ryanchou-dev** [comment]
> ok will do after io module EDIT: lmao @ryanchou-dev wanna take a stab at this?

yeah sure, ill have to start on saturday though :(
