### ISSUE TITLE
Feature Request: "Read Later"/"Do Later" status for modules & problems

### ISSUE THREAD

**Issue by megargayu** [cpinitiative/usaco-guide#2350]
I really like being able to see the status of each section I'm working on. However, I would really like to see a "Read Later" status for modules and "Do Later" for problems, or something similar to this. It would also be nice to add this to the front page, with the "Active Problems" and the "Active Modules" sections.

**Comment by bqi343** [comment]
You can already mark a module or problem as "Skipped" and it will be added to the front page.
