### ISSUE TITLE
missing sol

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#2359]
https://usaco.guide/gold/all-roots#problem-apio-10-patrol
yeah, click on the external solution link
![image](https://user-images.githubusercontent.com/55369003/143158124-45cd420f-1c9b-4929-b7ac-a726edf49436.png)
bruh

**Comment by TruaShamu** [comment]
There's a copy of the pdf from the [wayback machine.](https://web.archive.org/web/20210310031148/http://apio-olympiad.org/2010/solutions.pdf)

I can make a pr and change the link if that would help?

**Comment by SansPapyrus683** [comment]
imo linking to wayback machine is a bit sus
maybe host the pdf on usaco guide itself? do we have the server space?

**Comment by TruaShamu** [comment]
i actually have no idea where the files are hosted on the server though, sorry 😭
maybe ask on discord?

**Comment by thecodingwizard** [comment]
you can put it here: https://github.com/cpinitiative/usaco-guide/tree/master/static 

`static/A.pdf` can be accessed at `usaco.guide/A.pdf`

**Comment by SansPapyrus683** [comment]
lmao can someone else do that

**Comment by thecodingwizard** [comment]
bump @cpinitiative/content-managers :D

**Comment by HarryWangATX** [comment]
ill do it
