### ISSUE TITLE
Hints editing is broken in groups

### ISSUE THREAD

**Issue by maggie-j-liu** [cpinitiative/usaco-guide#2377]
thanks to evan for reporting this bug!

> I dunno whether this is the right place to ask, but I think I've just found a bug on Groups
so if I have more than 1 hint on a problem
and I press the Edit button for the second hint:
![image](https://user-images.githubusercontent.com/63619830/144687583-69ff5857-11e2-4774-a672-07e06c543ca2.png)
and then I edit the second hint:
![image](https://user-images.githubusercontent.com/63619830/144687595-92057d74-3413-4485-b0c9-187db06780bb.png)
and then press the Save button
this is what I see:
![image](https://user-images.githubusercontent.com/63619830/144687611-cd969471-3180-4fe6-8f5e-e5dce23c65f8.png)
it seems that Group saved my changes to the first hint, even though I edited the second hint 

this is what i think the problem is
> oh the problem is with the ids 
they're all the same
![image](https://user-images.githubusercontent.com/63619830/144687641-a3b6126e-faa2-4283-afab-2e8a91bcc654.png)
because the modal is not unmounted/remounted when opened or closed
and the id is never reset

**Comment by SansPapyrus683** [comment]
every day, we get more web dev bugs
and they are never fixed

**Comment by caoash** [comment]
@webdev
