### ISSUE TITLE
Note Preferred Style for Links Within the Guide

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#2380]
https://github.com/cpinitiative/usaco-guide/pull/2270#pullrequestreview-823299428

Maybe in https://usaco.guide/general/adding-solution

**Comment by SansPapyrus683** [comment]
under general?

**Comment by bqi343** [comment]
hm it's not a code convention though

**Comment by SansPapyrus683** [comment]
don't really see any other place for it tho
