### ISSUE TITLE
stress testing cmd app

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#2401]
ok so i was looking @ the debugging module
and most of it works only in bash, and python isn't supported it all
so i was thinking
what if we made an entire encapsulated cmd app that just took the program along with the input + output files, and outputted all the results and then put it on github?

**Comment by ryanchou-dev** [comment]
yeah cool, i could help with it, probably sometime in the next two weeks though

**Comment by bqi343** [comment]
>  python isn't supported it all

Isn't it easy enough to modify the script to support Python (or Java)?

```
# Usage: 'sh stress.sh'
gen="./gen"
prog1="python3 py_sol.py" # or java java_sol, etc
prog2="./cpp_sol"

for((i = 1; ; ++i)); do
    echo $i
    $gen $i > int # gen takes in tc as a command line argument
    $prog1 < int > out1
    $prog2 < int > out2
    diff -b out1 out2 || break
done
```

**Comment by SansPapyrus683** [comment]
i mean i feel like it'd still be nice to have one command to rule them all, yknow?

**Comment by bqi343** [comment]
what do you mean by that?

**Comment by SansPapyrus683** [comment]
no? not really?

**Comment by bqi343** [comment]
so what's this for, if it's not for debugging in a USACO contest?

**Comment by SansPapyrus683** [comment]
just stress testing in general?

**Comment by SansPapyrus683** [comment]
something like [this](https://cfstress.com/) but in the cmd

**Comment by ryanchou-dev** [comment]
> something like [this](https://cfstress.com/) but in the cmd

it looks like the creator has to manually add the problems (probably get data & stuff from the problem?)

**Comment by ryanchou-dev** [comment]
unless you want something like you give the problem's format for input and it just brute forces like a lot of them?

**Comment by SansPapyrus683** [comment]
https://github.com/SansPapyrus683/AAARGH
