### ISSUE TITLE
Attach sponsorship prospectus on homepage of USACO Guide and CPI

### ISSUE THREAD

**Issue by shaymor** [cpinitiative/usaco-guide#2421]
Add link to the sponsorship prospectus on homepage of USACO Guide and CPI

**Comment by SansPapyrus683** [comment]
lmao what

**Comment by shaymor** [comment]
Add link to the sponsorship prospectus on homepage of USACO Guide and CPI

**Comment by shaymor** [comment]
[PR #2423](https://github.com/cpinitiative/usaco-guide/pull/2423)
