### ISSUE TITLE
Contact Form Submission - Groups

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2430]
Someone submitted the contact form!

**Module**: USACO Groups
**Topic**: Other
**Message**: 
I requested access to groups a little bit ago. Do you guys know when we'll be able to access them? Our club wants to start learning during winter break, and this would be really helpful.

Thanks for your help!

**Comment by SansPapyrus683** [comment]
think michael said they'd be out in a couple of days?
