### ISSUE TITLE
Gold BFS Problem Difficulties

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [cpinitiative/usaco-guide#2435]
The Problem Difficulties for the Gold BFS Section are pretty old, and need to be updated. For example, Piggyback should be considered an easy problem, as it is a straightforward bfs implementation. 

Also we need to add more hard to very hard level problems to the BFS section (and split it up the way the DSU Module does)

**Comment by SansPapyrus683** [comment]
lol can you do that then

**Comment by Aadit-Ambadkar** [comment]
Yeah this is more so a reminder for me to do it cause i'm lazy

**Comment by SansPapyrus683** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/55369003/164569244-a8526128-7c03-4cf5-9cb6-4e5e09d68647.png">
it's been 4 months...

**Comment by Aadit-Ambadkar** [comment]
holy cow

I completely forgot to do this. Thanks @SansPapyrus683!

**Comment by SansPapyrus683** [comment]
bruh I already did it
