### ISSUE TITLE
Contact Form Submission - Euler Tour Technique Typo

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2443]
Someone submitted the contact form!

**Module**: Gold - Euler Tour Technique
**Topic**: Other
**Message**: 
In the solution of USACO Gold 2019 February - Cow Land (https://usaco.guide/problems/usaco-921-cow-land/solution), in the implementation part, line 16, 17, 18 of the code:
```
	par[v][0] = p;
	for(int i = 1; i < 22; i++)
		par[v][i] = par[par[v][i-1]][i-1];
```
I think there is probably an out of bound error when p = -1 and i = 0, because then par[v][i] = par[-1][i-1].

**Comment by bqi343** [comment]
The loop doesn't start at `i=0`, but yeah this solution goes out of bounds

**Comment by xyzyzl** [comment]
it AC'd for me :eyes:

**Comment by bqi343** [comment]
Regardless of whether it AC'd, could you fix it?

**Comment by xyzyzl** [comment]
yep i'll fix it un segundo
