### ISSUE TITLE
Cat & Mice Bug

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#2450]
https://usaco.guide/gold/dp-bitmasks#problem-kattis-catandmice

In the problem statement:

> Your answer should be correct within a relative or absolute error of 10−3.

should actually be just "absolute." should make a note about this somewhere, at least until Kattis fixes this

**Comment by SansPapyrus683** [comment]
i mean does it matter that much? is there a solution that WAs if it was using the abs. error but not for the relative one?

**Comment by bqi343** [comment]
It certainly is (try removing `fixed << setprecision(16)`).
