### ISSUE TITLE
Broken Link (CF EDU)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2455]
Someone submitted the contact form!

**Module**: Silver - Binary Search
**Topic**: Typo / Broken Link
**Message**: 
https://codeforces.com/edu/course/2/lesson/6/1/practice leads to a "course not found" message

**Comment by bqi343** [comment]
It works for me. Could someone who is seeing this error see if it goes away after enrolling in the course?

**Comment by SansPapyrus683** [comment]
yeah i tried it on an alt
if you enroll in the course it goes away

**Comment by bqi343** [comment]
Thanks for checking. Do you think a note should be added to the module, or should we just close this?

**Comment by SansPapyrus683** [comment]
note should be added yeah

**Comment by SansPapyrus683** [comment]
so many modules have these edu links, i think a note for every one of them would be redundant

**Comment by SansPapyrus683** [comment]
bump

**Comment by bqi343** [comment]
Could add a tooltip for CF EDU that tells you to enroll in the course.

**Comment by SansPapyrus683** [comment]
how do i add tooltips to resources

**Comment by bqi343** [comment]
https://github.com/cpinitiative/usaco-guide/blob/5de3b4b1bb7fe7053a37d20406dcc502b93a4d46/src/models/problem.ts#L61 <- could add "CF EDU" here.
