### ISSUE TITLE
Add "Ligatures" to Vectorization Module

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#2477]
https://open.kattis.com/problems/ligatures

https://github.com/Kodsport/swedish-coding-cup-finals-2021/blob/main/ligatures/submissions/accepted/sl_simd.cpp

**Comment by Alexis-Tao88** [comment]
Hello! I would love to be of assistance. Is there a specific format you'd like for me to follow?

**Comment by bqi343** [comment]
you can follow the same format as other problems that have been added
