### ISSUE TITLE
Automatic Formatter Pre-Commit Hook?

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#2486]
Related to #2292, it would be great if there was some way to automatically detect (and fix?) some of the most egregious violations of the [conventions](https://usaco.guide/general/adding-solution?lang=cpp#general) (at the very least, spaces vs tabs).

**Comment by SansPapyrus683** [comment]
should this be an additional feature of the maggie-bot?

**Comment by SansPapyrus683** [comment]
so any possible resolution for this?
