### ISSUE TITLE
Automatically Add Blank Line after Code Blocks

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#250]
@thecodingwizard 

I frequently find myself adding `<br />` after code blocks.

<img width="441" alt="Screen Shot 2020-09-13 at 12 52 02 PM" src="https://user-images.githubusercontent.com/21228024/93023859-f834f400-f5bf-11ea-94aa-dd359310287b.png">

**Comment by thecodingwizard** [comment]
@bqi343 can you provide me an example? there should already be some margin after a code block...

**Comment by thecodingwizard** [comment]
Hopefully closed by db823848612f10e0b3c3c64bab4e3b800bd65efb and f4e7614593e74bf2406414741653ff7721892de4 ...

**Comment by bqi343** [comment]
Cool
