### ISSUE TITLE
User Data Backups

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#2541]
#2536 #2503 #534 #3035 #3036 #3117

We should auto-backup user data once a day, keep the last 7 unique backups or something, and then allow users to download their backed-up data through user settings (at least until we identify why people's progress is being lost).

Relevant Files:
 - https://github.com/cpinitiative/usaco-guide/blob/master/src/components/Settings/UserData.tsx
 - https://github.com/cpinitiative/usaco-guide/blob/master/src/context/UserDataContext/UserDataContext.tsx

---

after #534 is closed by #3241, this is probably less urgent...

**Comment by bqi343** [comment]
@thecodingwizard I assume that due to #3241 we don't need this anymore?

**Comment by thecodingwizard** [comment]
Probably!
