### ISSUE TITLE
Code issue for CF - Power Products solution

### ISSUE THREAD

**Issue by wolfsudo** [cpinitiative/usaco-guide#2560]
**Module**: Gold-Divisibility
**Topic**: Small issues in the suggested code
**Message**: I was practicing this topic and according to some bugs in my code , I went to check the suggested code for this problem and i saw 2 little issues in code that causes wrong answer for that solution.

- `int size` for variable n of the main codeforces problem , because of .size() method for vectors , string and ... ,  makes compile error
- in the line 43 `vector<pi> inverse(size);` should be change to `vector<pi> inverse(number_of_primes);` to get the code works correct.

**Comment by SansPapyrus683** [comment]
don't think 1 is an issue, maybe your compiler's just acting up

**Comment by SansPapyrus683** [comment]
wait just a second it is an issue what

**Comment by wolfsudo** [comment]
Actually i mean issue to avoid getting the meaning wrong for the word problem , because problem also means as a question so it may causes someone misunderstanding.Thanks.
