### ISSUE TITLE
[Feature request] Turn the image background-color to gray when in dark mode

### ISSUE THREAD

**Issue by ChungZH** [cpinitiative/usaco-guide#2563]
USACO Guide:
![image](https://user-images.githubusercontent.com/42088872/153404079-ab9cc671-ec4e-4c59-acbd-4e3836df6e9a.png)

A good [example](https://cp-algorithms.com/data_structures/treap.html):
![image](https://user-images.githubusercontent.com/42088872/153404423-5600f7aa-817f-4aa2-9ee8-7b038595c6a2.png)

**Comment by ChungZH** [comment]
@bqi343 @thecodingwizard

**Comment by SansPapyrus683** [comment]
probably best not to ping admins

**Comment by ChungZH** [comment]
> probably best not to ping admins

i'm sorry... 😥😥😥
