### ISSUE TITLE
Discord Link (Expired)

### ISSUE THREAD

**Issue by YashDiscordNo** [cpinitiative/usaco-guide#2568]
It appears that the discord link is expired.

![Screenshot 2022-02-12 9 12 31 AM](https://user-images.githubusercontent.com/79669582/153721066-4ced7c25-e602-4a28-9e2f-c14ea2af0283.png)
(Where I got the link from)

![Screenshot 2022-02-12 9 13 25 AM](https://user-images.githubusercontent.com/79669582/153721100-0b33306a-00f7-4c63-8c4c-58b6549617c1.png)

**Comment by SansPapyrus683** [comment]
bruh didn't i literally fix this

**Comment by RmdanJr** [comment]
@SansPapyrus683 
It seems like discord link has expired again, please fix it.

**Comment by SansPapyrus683** [comment]
alright it seems there's a deeper problem
