### ISSUE TITLE
bit operations resource?

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#257]
do we have a module / resources on bit operations?

**Comment by bqi343** [comment]
https://cses.fi/book/book.pdf#page=106

**Comment by thecodingwizard** [comment]
err okay should we make a module for bit operations or stick it into an existing module?

Existing modules w/ bitmasks that I could find:

- bronze complete search with recursion
- plat dp on bitmasks

(oops I didn't look very hard)

**Comment by bqi343** [comment]
Could stick "Bit Operations" + "Representing sets" in Bronze? Neither of them will be very useful in any division aside from Plat though ...

**Comment by thecodingwizard** [comment]
Maybe like, silver/gold? (might be useful for some subtasks? idk)

I think Bronze shouldn't need bitmasks right?

**Comment by bqi343** [comment]
Complete Rec mentions it in a solution though (maybe shouldn't though :P)

**Comment by thecodingwizard** [comment]
We can just link to the module? I just don't think bronze ppl should be learning bitmasks LOL

**Comment by frodakcin** [comment]
I think we should have a silver/bit_operations module. In general, it's good to know.

Maybe something simple like implementing addition using bitwise operators as an example/for practice.

Also reminds me that sos dp is a thing... would that be plat or advanced?

**Comment by thecodingwizard** [comment]
I think this was closed by frodakcin at some point :heart:
