### ISSUE TITLE
Paths on Grids

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#258]
Some broken formatting. Also, we should be consistent about how we format 2D arrays.

**Comment by caoash** [comment]
what way do you prefer to format them

**Comment by bqi343** [comment]
$\texttt{dp}[x][y]$

**Comment by caoash** [comment]
hmm okay, @anyone which looks best? we should pick and stay consistent, personally I like the second
![image](https://user-images.githubusercontent.com/45920019/93842212-b3fac100-fc5b-11ea-90e8-3664900efdc4.png)

**Comment by thecodingwizard** [comment]
I'm fine with anything (including inconsistent formatting as long as it's one of the three above LOL)

**Comment by frodakcin** [comment]
https://github.com/cpinitiative/usaco-guide/pull/424 Is this correct?
