### ISSUE TITLE
Traffic Lights Solution

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#2583]
https://forum.usaco.guide/t/cses-traffic-lights-time-complexity-of-2nd-solution/2655

https://usaco.guide/problems/cses-1163-traffic-lights/solution#solution-2---going-backwards

Fix time complexity and add the linked list solution.

**Comment by SansPapyrus683** [comment]
> add the linked list solution

What's this?

**Comment by SansPapyrus683** [comment]
i'll just add a note like "hey linked lists also exist for a hard linear solution but it doesn't matter"

**Comment by bqi343** [comment]
it's not harder than the current solutions

**Comment by SansPapyrus683** [comment]
still seems pretty similar to the sorted set solution though?

**Comment by bqi343** [comment]
yes. but the complexity is better.

**Comment by SansPapyrus683** [comment]
fair enough, i'll try implementing it
