### ISSUE TITLE
[Outdated link]A starred resource requires University of Michigan account.

### ISSUE THREAD

**Issue by notwatermango** [cpinitiative/usaco-guide#2624]
Found here: https://usaco.guide/general/lambda-funcs?lang=cpp
Resources: Using C++ Lambdas (starred)

Problem: As the title says

This link
http://www.umich.edu/~eecs381/handouts/Lambda.pdf
Redirects to
https://weblogin.umich.edu/?cosign-websites.umich.edu&https://websites.umich.edu/~eecs381/handouts/Lambda.pdf

Found workaround:
Use wayback machine.

I can't find guidelines regarding opening an issue, hope this format doesn't annoy you guys. 😉

**Comment by SansPapyrus683** [comment]
<img width="767" alt="image" src="https://user-images.githubusercontent.com/55369003/158003454-7d518581-b6b9-42d8-bafd-16bb6575f667.png">
it works just fine for me?

**Comment by notwatermango** [comment]
![image](https://user-images.githubusercontent.com/67574872/158004492-a5fef305-1e29-4b6c-ab25-10041d5a6ef8.png)

Tried using Google DNS, incognito, still redirects me here

**Comment by SansPapyrus683** [comment]
hm
i'm on edge, have you tried that?

**Comment by notwatermango** [comment]
connection timed out :/ I'll try again later

**Comment by notwatermango** [comment]
It's working now, 😮  no idea what happened. I guess it's safe to close this issue now.

Cheers
