### ISSUE TITLE
Use Discussions Instead of Issues for Contact Form Submissions

### ISSUE THREAD

**Issue by maggie-j-liu** [cpinitiative/usaco-guide#2650]
We can probably put submissions of type `Suggestion` and `Other` in discussions, `Typo` and `Website Bug` in issues, and `Request` and `Unclear Explanation` initially in issues (but we can convert them to a discussion if necessary)

**Comment by SansPapyrus683** [comment]
wha'ts the difference

**Comment by maggie-j-liu** [comment]
I guess it's to sort of clean out issues (there's a lot :eyes:)

**Comment by SansPapyrus683** [comment]
i mean most of those issues are legitimate tho

**Comment by maggie-j-liu** [comment]
i think at least problem suggestions should go there right? since we're not going to immediately accept all of them... we can always open up an issue if we're going to implement something

**Comment by SansPapyrus683** [comment]
tru

**Comment by bqi343** [comment]
@MrinallU @maggie-j-liu so what happened?

**Comment by bqi343** [comment]
The current setup seems fine to me. problem suggestions go in PRs atm
