### ISSUE TITLE
Queue Composite should be in Modular Arithmetic

### ISSUE THREAD

**Issue by rayfish5** [cpinitiative/usaco-guide#2705]
I feel like [Queue Composite](https://usaco.guide/gold/sliding-window#problem-ys-QueueComposite) isn't really a sliding window problem. I do think that it is a nice application of modular arithmetic and would be good in that module.

Here's the solution I think is the easiest: The composition of many linear functions is itself a linear function. 
If we let m and n be integers such that mx + n = f1( f2( f3( ... fn(x) ... ))), then it suffices to quickly update m and n. When f(x) = ax + b is added, then the composition is a(mx + n) + b = amx + an + b, and we can update m and n accordingly.
When f(x) = ax + b is removed, then we want to find m' and n' such that m'(ax + b) + n' = mx + n. Rearranging gives m' = ma^-1 and n' = n - bm', so we can use FLT to calculate a^-1.

Here's my code:
```c++
#include <bits/stdc++.h>

using namespace std;
typedef long long ll;

const ll MOD = 998244353;

ll pow(ll b, ll e) {
  if (e == 0) return 1;
  if (e % 2 == 1) return pow(b, e-1) * b % MOD;
  ll val = pow(b, e/2);
  return val * val % MOD;
}
ll inv(ll x) {
  return pow(x, MOD-2);
}
int main() {
  cin.tie(0)->sync_with_stdio(0);
  // freopen(".in","r",stdin);
  // freopen(".out","w",stdout);
  int q; cin >> q;
  queue<ll> coef, con;
  ll m = 1, n = 0;
  for (int i = 0; i < q; i++) {
    int com; cin >> com;
    if (com == 0) {
      ll a, b; cin >> a >> b;
      coef.push(a); con.push(b);
      ll new_m = a * m % MOD;
      ll new_n = (a * n + b) % MOD;
      m = new_m; n = new_n;
    } else if (com == 1) {
      ll a = coef.front(); coef.pop();
      ll b = con.front(); con.pop();
      ll inv_a = inv(a);
      ll new_m = inv_a * m % MOD;
      ll new_n = (n - b * new_m) % MOD;
      m = new_m; n = (new_n >= 0 ? new_n : new_n + MOD);
    } else {
      ll x; cin >> x;
      cout << ((m * x + n) % MOD) << "\n";
    }
  }
}
```

**Comment by SansPapyrus683** [comment]
@bqi343? you wrote the module (and presumably added the problems)

**Comment by bqi343** [comment]
Sure. I had a different solution in mind though (which easily generalizes to non-prime moduli)

**Comment by SansPapyrus683** [comment]
how bout putting it in both modules? would that work?

**Comment by bqi343** [comment]
sure
