### ISSUE TITLE
binary jumping benq link broken

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#2770]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/55369003/168454787-9494ac79-13b6-4a2a-a03a-9b662e6031a6.png">
https://github.com/bqi343/USACO/blob/master/Implementations/content/graphs%20(12)/Trees%20(10)/LCAjump.h

bruh

**Comment by bqi343** [comment]
can replace with the current version:

https://github.com/bqi343/USACO/blob/master/Implementations/content/graphs%20(12)/Trees%20(10)/LCAjump%20(10.2).h

or just remove that from the module and link to something more readable (maybe https://github.com/kth-competitive-programming/kactl/blob/main/content/graph/BinaryLifting.h? idk if it is actually more readable)

**Comment by SansPapyrus683** [comment]
what if i coded up something myself?

**Comment by bqi343** [comment]
feel free to
