### ISSUE TITLE
unclear explanation for silver load balancing

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#2793]
https://usaco.guide/problems/usaco-619-load-balancing/solution
<img width="742" alt="image" src="https://user-images.githubusercontent.com/55369003/169673726-3105ff4d-49af-4b17-9c9c-369a7a14eaa2.png">
this really needs elaboration

**Comment by Aadit-Ambadkar** [comment]
I'll do this later today.

**Comment by Aadit-Ambadkar** [comment]
Okay what this solution makes no sense. I don't even see a reason for us to have this soluton.

**Comment by bqi343** [comment]
It looks like @SansPapyrus683 already cleaned up the code in #2794 but didn't change the explanation, so presumably, he thought the explanation was okay?

**Comment by SansPapyrus683** [comment]
no, i had no clue what was happening
i just cleaned up the code and threw in the towel

**Comment by Aadit-Ambadkar** [comment]
> no, i had no clue what was happening i just cleaned up the code and threw in the towel

lmao. then should @bqi343 be listed as an assignee?

**Comment by SansPapyrus683** [comment]
bro stop pinging benq
why not you try doing it?

**Comment by Aadit-Ambadkar** [comment]
I have no clue what the hell is going on with that solution.
