### ISSUE TITLE
Groups: back button after creating a new group has weird behavior

### ISSUE THREAD

**Issue by maggie-j-liu** [cpinitiative/usaco-guide#2831]
After creating a new group, you'd expect the "back" button to behave like a cancel button:

![image](https://user-images.githubusercontent.com/63619830/173161121-54e6313d-2d7d-487b-9ac0-0a3a7a514766.png)

Since the group was created before that page comes up, and it's actually just the edit page, the back button doesn't cancel the creation of the group or delete the group. We could make a different modal for creating groups, or just remove the button.

Also there are 2 save buttons...

**Comment by MrinallU** [comment]
This seems pretty easy so I'll do it

**Comment by cirex-web** [comment]
Did you start this yet? If not, could I do it? @MrinallU

**Comment by MrinallU** [comment]
> Did you start this yet? If not, could I do it? @MrinallU 

I'm almost done with it.

**Comment by MrinallU** [comment]
@cirex-web Can you do #2817 instead?

**Comment by cirex-web** [comment]
@MrinallU hmm I'll think about it

**Comment by MrinallU** [comment]
Resolved by #2868
