### ISSUE TITLE
Groups: minor issues

### ISSUE THREAD

**Issue by maggie-j-liu** [cpinitiative/usaco-guide#2833]
- [ ] reloading a group's page shows a 404 not found before loading the group
- [ ] after joining a group, then hitting the back button to go back to the list of groups, the new group doesn't show up in the list until you reload

**Comment by omkarbajaj073** [comment]
Another minor issue I noticed is that when posting an assignment, it is allowed to set a due date in the past before the assignment is posted. Like if I create an assignment, I am allowed to set its due date to June 10th.
