### ISSUE TITLE
Bug - Registering for New Account on usaco.org

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2854]
Someone submitted the contact form!

**URL**: https://usaco.guide/
**Module**: None
**Topic**: Other
**Message**: 
I’m trying to register a new account but didn’t received anything after submitting request.

**Comment by SansPapyrus683** [comment]
uh could we have some more info?

**Comment by h190330190** [comment]
When we try to register a new account or click on forgot password and submit our details, we don't receive any link in our g-mail account

**Comment by thecodingwizard** [comment]
If this is in reference to http://usaco.org/ (which is different from the USACO Guide), see this section on the USACO website:

> We have been made aware that gmail has recently stopped accepting some emails from the USACO server -- e.g., for new accounts and password resets. If this issue is affecting you, please try adding usaco@usaco.org to your gmail contacts list. If you are still having issues, please notify the contest director, Brian Dean (bcdean@clemson.edu). If you have recently received an email from the USACO server such as a password reset email or an account creation email, consider starring it, so that gmail will hopefully treat USACO emails with better priority.

If it's an issue related to the USACO Guide, please reopen this issue!

**Comment by bqi343** [comment]
Forgot to mention that in the meantime, you can use https://ide.usaco.guide/ to submit! We should probably say this somewhere more visible since this seems to be pretty common nowadays (maybe on https://usaco.guide/dashboard or the forum?). Reopening until we do this.

**Comment by lite-27** [comment]
i didnt recieve any mail after trying to register

**Comment by bqi343** [comment]
Addressed by #3266 (this is the most we can do)

**Comment by Artning331** [comment]
how can i **delate the account** and **register it again** cause i' ve wrote the wrong information
