### ISSUE TITLE
No Email Upon Account Creation

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2876]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: None
**Topic**: Other
**Message**: 
I have created my account but I didnot get any email regarding setting the password.

**Comment by SansPapyrus683** [comment]
wha
why are so many submissions about this these days

**Comment by bqi343** [comment]
I assume this is a duplicate of #2854, feel free to reopen if not.
