### ISSUE TITLE
Contact Form Submission - Suggestion (Lazy Prop)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2887]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cses-2166-prefix-sum-queries/solution#solution-1---segment-tree
**Module**: Range Update Range Query
**Topic**: Suggestion
**Message**: 
Why would someone ever use prefix sums plus lazy propagation on a segment tree when it’s just a direct application of a normal segment tree on the original array?

**Comment by SansPapyrus683** [comment]
> normal segment tree

what's your definition of that? from what i remember a normal implementation could only handle point update range query

**Comment by bqi343** [comment]
Solution 1 in that link is a "normal segment tree." That being said, it's not clear how much simpler it is than solution 2, so I don't see a problem with cindlugin both solutions.
