### ISSUE TITLE
Contact Form Submission - Unclear Explanation (POI 2017 - Containers)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2892]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/poi-2017containers/solution
**Module**: None
**Topic**: Unclear Explanation
**Message**: 
The solution uses the variable k as approximately sqrt(N), and q is the number of queries (aka cranes). However, in the problem statement k represents the number of queries. This could be very confusing if someone tries looking at the implementation in the solution.

**Comment by bqi343** [comment]
@dolphingarlic
