### ISSUE TITLE
Contact Form Submission - Unclear Explanation (CSES - Sum of Divisors)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2893]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cses-1082-sum-of-divisors/solution
**Module**: https://usaco.guide/problems/cses-1082-sum-of-divisors/solution
**Topic**: Unclear Explanation
**Message**: 
This is a very good question and it requires the concept of fermets little theorem also and at the same moment most of the people who are using usaco are beginers so you should explain code by simple template as compared to complex template code that has been writtem

**Comment by SansPapyrus683** [comment]
yeah...we know...
