### ISSUE TITLE
Button / Slider to Give Feedback for Each Module?

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#292]
Ex. Clarity 1-5, Difficulty 1-5? Or make "Contact Us" more visible? Or like at the bottom of [this page](https://reactjs.org/docs/hooks-effect.html).

NEED MORE FEEDBACK

**Comment by thecodingwizard** [comment]
![image](https://user-images.githubusercontent.com/7865976/95003291-b847a800-0592-11eb-9342-8079114705b1.png)

**Comment by thecodingwizard** [comment]
(partially) implemented on 1d992ed2fea0976dfb2738c9aeb5d96a4eac4dda

**Comment by bqi343** [comment]
Cool, should include email as well :)

**Comment by thecodingwizard** [comment]
Added in 9d3fad098938b5146a1602bc41ce94366a3d25a5

**Comment by bqi343** [comment]
Also keep track of URL where form was submitted (like contact us form)

**Comment by thecodingwizard** [comment]
ok I think that is implemented in 1e7f8cb7d232f17df2345151df59d3858a8e9c6e

**Comment by bqi343** [comment]
seems fine
