### ISSUE TITLE
Adding Hacking Section to Bronze Sorting & Sets

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [cpinitiative/usaco-guide#2925]
I think it's important to discuss hacking and the issues with sorting and sets with most of the languages. Specifically, unordered sets and unordered maps (for c++ and python, these can be hacked; see https://codeforces.com/blog/entry/62393 and https://codeforces.com/blog/entry/101817) and Arrays.sort for Java. It is possible that testcases can be designed to break these in some of the problems, and during CF competitions they are likely targets for hacking.

**Comment by bqi343** [comment]
C++ and Java are already included in https://usaco.guide/gold/unordered-map?lang=cpp and https://usaco.guide/bronze/intro-sorting?lang=java.

**Comment by SansPapyrus683** [comment]
i mean does hacking really matter that much

**Comment by Aryansh-S** [comment]
Hacking's not an issue for USACO (coaches wouldn't explicitly design test cases to break default hash functions, etc.), and the notice in Ben's links seems sufficient for CF.

**Comment by bqi343** [comment]
Just read through the blog about Python and added the corresponding hacks to CSES: https://cses.fi/problemset/hack/1621/result/21648. Once the CSES tests get updated we should add something like this to the module since the Python solutions currently in the module will be broken:

```
<Warning>

The problem above contains tests designed specifically to make Python `set`s and `dict`s with `int`s as keys run slowly. See [this CF post](https://codeforces.com/blog/entry/101817) for more information. To fix this, we can use `str`s as keys instead.

</Warning>
```
