### ISSUE TITLE
Contact Form Submission - Unclear Explanation (intro-cp)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2926]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/intro-cp?lang=cpp
**Module**: General - Introduction to Competitive Programming
**Topic**: Unclear Explanation
**Message**: 
i think the instruction is unclear in this section , specifically on the "Basketnball Problem" , assuming that we are complete beginner in CP or maybe coding and wanting to start from zero using CP as a start in this web , the problem will make us confused as the problem required some prior knowledge from C++ , ofc its a different thing when we just need to find the "trick" or algorithm to solve the problem without implementing it ( since we have zero knowledge ) , i know that some people who got here already know something on their language choice ,but i think its better to avoid confusion as much as possible and make it more beginner friendly as things like this could , albeit rarely, make people get discouraged especially  for complete beginners that just want a fresh start. Please dont be mistaken that im saying that this is bad , maybe there was a motive or something but i think its too early yet to give things like these to people who have just started.

 On other note , i absolutely love this website and its future development , so i just wish to give this argument to improve the user experience in learning CP.

**Comment by bqi343** [comment]
> don't we assume some prior programming knowledge alr?

Yeah, but that's mentioned later. Perhaps it's worth adding a note like:

> If you have prior programming experience we encourage you to register a Kattis account and submit a solution. If not, feel free to skip ahead to the solution.

Side note: Should use something like the following for the Java solution, no need to introduce `Kattio` here.

```java
import java.util.Scanner;

public class basketballoneonone {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String s = sc.next();
        System.out.println(s.charAt(s.length()-2));
    }
}
```

**Comment by HarryWangATX** [comment]
I can go add the note.

> Side note: Should use something like the following for the Java solution, no need to introduce Kattio here.

sure, since you cant even use the kattio template in contest anymore why not.
