### ISSUE TITLE
Package.json issue

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [cpinitiative/usaco-guide#2929]
Minor issue but in package.json, nathan's email is visible.

**Comment by bqi343** [comment]
@thecodingwizard Is this a problem?

**Comment by thecodingwizard** [comment]
oops uhhhhhhh I don't think it's an issue but it can probably be removed :P

**Comment by Aadit-Ambadkar** [comment]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/58674441/185502089-26596378-b9f9-45e1-a525-a750b8e5fe54.png">
> but it can probably be removed :P

hmm yes
