### ISSUE TITLE
Add proper code editor to /liveupdate

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#293]
I think Monaco would work quite well; they have reasonable markdown/mdx support.

https://microsoft.github.io/monaco-editor/

**Comment by thecodingwizard** [comment]
Assigned, thanks @TanayB11!

Try to lazy-load if possible.

**Comment by thecodingwizard** [comment]
Also, copy-pasting Bronze intro DS has some scrolling issues...

**Comment by thecodingwizard** [comment]
Fixed in #331

**Comment by bqi343** [comment]
Add settings (language, hide, etc)?

**Comment by thecodingwizard** [comment]
See #319
