### ISSUE TITLE
unimplemented reason

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#2941]
so whenever a solution is unimplemented there's a red error box & whatever
i feel like there should be a wontfix thing
kinda like instead of showing "lol we didn't do this please help"
something like "we tried to do this & failed miserably"

**Comment by bqi343** [comment]
```
<IncompleteSection>

text here

 </IncompleteSection>
```

**Comment by SansPapyrus683** [comment]
cool
