### ISSUE TITLE
improve user count accuracy

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#296]
- Update Firebase last seen every 30 seconds or something
- Optimize listening to database to reduce bandwidth usage
- (maybe) Run a firebase function to remove users who aren't seen for too long

**Comment by MasonWang025** [comment]
How is user count implemented currently? IIRC there isn't any built-in way to do this.

**Comment by thecodingwizard** [comment]
We use firebase auth persistence

**Comment by thecodingwizard** [comment]
closing unless somebody has a better idea as to how to do this :/
