### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by chezbgone** [cpinitiative/usaco-guide#2968]
The link on [this page](https://github.com/cpinitiative/usaco-guide/blob/4f7dacbea3fca0274fd5ab2dbc4b7273f00e3acc/content/1_General/Contributing.mdx) leads to an expired invite.

**Comment by robinaerts** [comment]
Created pull request with correct discord link [#2973](https://github.com/cpinitiative/usaco-guide/pull/2973)
