### ISSUE TITLE
problem solutions page URL (https://usaco.guide/problem-solutions/) should include problem ID

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#2971]
- [ ] add problem ID to the end of the URL so that you can link to the solutions page for a specific problem. 
- [x] this page also should link to the contact form rather than asking users to email us. (done in #3289)

**Comment by HarryWangATX** [comment]
not seeing a page for the link in the title??

**Comment by bqi343** [comment]
you'll only see a page if you click "View User Solutions" for some problem

**Comment by thecodingwizard** [comment]
I think this issue is fixed now? ie. user solutions URL looks something like https://usaco.guide/problems/ys-montmort/user-solutions
