### ISSUE TITLE
Wrong link in 'adding_solution' to 'Working with mdx' (twice)

### ISSUE THREAD

**Issue by robinaerts** [cpinitiative/usaco-guide#2974]
The urls to [Working_MDX](/cpinitiative/usaco-guide/blob/c8c2626fc40e8c1cf0fbc5688a851b8cbd791739/content/1_General/Working_MDX.mdx) In the file [Adding_Solution](/cpinitiative/usaco-guide/blob/c8c2626fc40e8c1cf0fbc5688a851b8cbd791739/content/1_General/Adding_Solution.mdx) don't work.

**Comment by bqi343** [comment]
They do. Try going to https://usaco.guide/general/adding-solution?lang=cpp and clicking on the first link.
