### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Editorial (The Fair Nut and Rectangles)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2987]
Someone submitted the contact form!

**URL**: https://usaco.guide/plat/convex-hull-trick?lang=cpp
**Module**: Platinum - Convex Hull Trick
**Topic**: Request - Missing Section or Editorial
**Message**: 
Could you guys make an explanation of the solution to The Fair Nut and Rectangles? The Codeforces link is a bit confusing, so an explanation in the USACO Guide would be very helpful.

**Comment by SansPapyrus683** [comment]
moved to #4165
