### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Editorial (POI Sums)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2992]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/gold-conclusion/?lang=cpp#problem-poi-sums
**Module**: Gold - Additional Practice for USACO Gold
**Topic**: Request - Missing Section or Editorial
**Message**: 
Could you guys add a solution to the problem 'Sums'?

Thanks!

**Comment by bqi343** [comment]
https://codeforces.com/blog/entry/18193?#comment-230790

**Comment by SansPapyrus683** [comment]
moved to #4165

**Comment by danielzsh** [comment]
this is done btw (idk if we should still update here?)

**Comment by SansPapyrus683** [comment]
it's alr closed

**Comment by danielzsh** [comment]
yeah but it was closed as completed before the actual editorial was published since it was moved to the larger issue
