### ISSUE TITLE
Authors You Can Trust Styling

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [cpinitiative/usaco-guide#3007]
It would make more sense to style the "Authors You Can Trust" like the "Created by the CP Initiative" section (using cards). The grid currently looks jank and out of place given the way everything else is styled.

**Comment by zhao-stanley** [comment]
Should be fixed with [this commit](https://github.com/cpinitiative/usaco-guide/commit/7a8e0f4b566881135cf7e70b5e9fed37046b6f4c)
