### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Editorial (BCCs and 2CCs)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3053]
Someone submitted the contact form!

**URL**: https://usaco.guide/adv/BCC-2CC
**Module**: Advanced - BCCs and 2CCs
**Topic**: Request - Missing Section or Editorial
**Message**: 
Could someone please put an implementation of Biconnected Components here? Right it now it just says (implementation)

**Comment by SansPapyrus683** [comment]
think mihnea fixed this actuallly
