### ISSUE TITLE
Add section for Constructive Algorithms 

### ISSUE THREAD

**Issue by Awadesh365** [cpinitiative/usaco-guide#3057]
Cf Article- https://codeforces.com/blog/entry/80317 

e.g. https://assets.hkoi.org/training2019/cast.pdf
    https://codeforces.com/problemset/problem/1405/B

**Comment by bqi343** [comment]
The tips in the articles aren't specific to constructive problems; solving small cases and finding patterns is always a reasonable thing to try ...

**Comment by Awadesh365** [comment]
got it.
