### ISSUE TITLE
Bug - Registering for New Account on USACO Training Pages

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3087]
Someone submitted the contact form!

**URL**: https://usaco.guide/
**Module**: None
**Topic**: Website Bug
**Message**: 
I can't sign up in USACO training gate. Every time I try to register, I don't get an email with the password. I've tried different emails, and My friends also tried, and we have the same problem.

**Comment by bqi343** [comment]
Probably the same as https://github.com/cpinitiative/usaco-guide/issues/2854#issuecomment-1162802123?

**Comment by bqi343** [comment]
Addressed by #3266 (this is the most we can do)
