### ISSUE TITLE
Two Pointers

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#309]
+ Harder Problems

**Comment by dolphingarlic** [comment]
What difficulty should we aim for? Would [CEOI 10 Tower](https://oj.uz/problem/view/CEOI10_tower) and [Baltic OI 09 Rect](https://cses.fi/108/list/) be fine or are they too hard for silver? (Tower is DP and Rect is geometry)

**Comment by bqi343** [comment]
That first task seems fine. (but how is it DP?) Should probably avoid putting any geometry (unless it's really basic ...)
