### ISSUE TITLE
working w/ mdx weirdness

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#3091]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/55369003/193114081-a7f904bf-6523-4d41-8507-8898460d753c.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/55369003/193114115-651654c1-6817-483d-a5bb-c007a7cbf58b.png">
but it's really just a demo of how to use the incomplete section thing

**Comment by bqi343** [comment]
This behavior seems fine to me; the warning sign can be considered part of the demo.

**Comment by SansPapyrus683** [comment]
fair
