### ISSUE TITLE
undefined displayName causes submitToProblem function to error

### ISSUE THREAD

**Issue by maggie-j-liu** [cpinitiative/usaco-guide#3122]
the submitToProblem function will error if displayName is undefined; we should handle that case (and other places it might be causing a problem)

**Comment by Fury-101** [comment]
what situation does this occur in / what error should it give the user?

**Comment by maggie-j-liu** [comment]
when [`displayName`](https://github.com/cpinitiative/usaco-guide/blob/master/src/functions/src/groups/submitToProblem.ts#L78) is undefined; no error. just save an empty string instead of undefined. the reason is because it saves the user's displayName to firestore, but it can't save `undefined` so it will error internally & not calculate the user's score
