### ISSUE TITLE
Gold LIS - Trapezoid Explanation

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#313]
@dolphingarlic ?

**Comment by dolphingarlic** [comment]
Sure

**Comment by bqi343** [comment]
@dolphingarlic 

Trapezoids is here:

https://usaco.guide/plat/range-sweep#problems

(w/o a linked sol)

**Comment by dolphingarlic** [comment]
Should I just link the official editorial? http://boi2011.ro/resurse/tasks/trapezoid-sol.pdf

**Comment by bqi343** [comment]
sure

**Comment by dolphingarlic** [comment]
Closed with https://github.com/cpinitiative/usaco-guide/commit/256ef725e37c3e9a504657db1e6823de3b5f91c3
