### ISSUE TITLE
Adding a section about exponentiation by squaring or binary exponentiation

### ISSUE THREAD

**Issue by brebenelmihnea** [cpinitiative/usaco-guide#3165]
I haven't seen a topic about binary exponentiation.
https://cp-algorithms.com/algebra/binary-exp.html

**Comment by bqi343** [comment]
https://usaco.guide/gold/modular?lang=cpp#modular-exponentiation

**Comment by brebenelmihnea** [comment]
Oh, my bad, I haven't seen this. Thanks !
