### ISSUE TITLE
vjudge.usaco.guide expired SSL certificate

### ISSUE THREAD

**Issue by crissem** [cpinitiative/usaco-guide#3171]
Attempting to submit a solution via "Submit" on ide.usaco.guide will infinitely hang 100% of the time and spit the following error into the console:

"vjudge.usaco.guide/submit:1
Failed to load resource: net::ERR_CERT_DATE_INVALID"

Going to https://vjudge.usaco.guide/ in-browser will be blocked by Chrome/Firefox (presumably others), saying its SSL certificate is expired. Chrome explicitly says "its security certificate expired in the last day."

("Run code"/"Run samples" still work fine, since they make requests to some AWS link instead of vjudge)

**Comment by thecodingwizard** [comment]
fixed (for the next month)
