### ISSUE TITLE
Add Blog for SEO

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#318]
If I google "usaco" then "usaco-guide.netlify.app" appears on the third page of results but "usaco.guide" doesn't seem to appear at all ...

**Comment by thecodingwizard** [comment]
Can potentially make a blog about "how to get better at USACO" to improve SEO (?)

**Comment by MasonWang025** [comment]
Not exactly sure of the situation, but maybe try adding a redirect from usaco-guide.netlify.app to usaco.guide?

`https://usaco-guide.netlify.app/* https://usaco.guide/:splat 301!`

If possible to redirect from Netlify, that'll help SEO for sure. It may take a while for crawlers to discover the redirect.

**Comment by thecodingwizard** [comment]
nice okay, I added that :)

**Comment by thecodingwizard** [comment]
Unless someone wants to implement a blog, I'm thinking of just using novela's blog theme and setting up a reverse proxy with cloudflare or something (https://blog.cloudflare.com/subdomains-vs-subdirectories-improved-seo-part-2/) :P

**Comment by thecodingwizard** [comment]
never mind I'll just implement this real quick ig

**Comment by thecodingwizard** [comment]
actually it might be better to just implement a nice FAQ page rather than an entire blog system

**Comment by thecodingwizard** [comment]
gonna close this in favor of #362
