### ISSUE TITLE
Issues with String Hashing Module

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3195]
https://usaco.guide/gold/string-hashing?lang=cpp

1. The first two resources say that the probability of the hashes of two different length-$n$ strings colliding is $\approx \frac{1}{MOD}$. Actually, Schwartz-Zippel only upper bounds this probability by $\frac{n}{MOD}$, and for certain prime moduli you can construct test cases that achieve this probability (see https://codeforces.com/blog/entry/60442). There are also other inaccuracies (e.g., $p$ needing to be prime in the cp-algo link)

2. > Since the test data for this particular problem is very strong, 

    Actually, the test data doesn't need to be "very strong" to fail solutions with a single modulus around $10^9+7$. All you need to do is construct a haystack with many different permutations of the needle, and then the solution will probably fail by the birthday paradox.

3. Why use a single base with two different moduli? Using two different bases with a single small modulus (or even better, just one base modulo a large modulus) have better theoretical guarantees ( $n^2/MOD^2$ and $n/MOD$, respectively), according to the blog above.

4. ~~Why is one solution labeled "one hash" and the other "two hashes?" They both use two hashes.~~ Also, it's probably worth noting that they have the same collision guarantees.

**Comment by SansPapyrus683** [comment]
so what should we do to address this? remove the resources and make our own? add a disclaimer?

**Comment by bqi343** [comment]
Another thing - as long as int128 is supported, there isn't really any reason to use double hashing with two small moduli instead of just using a single large modulus. Maybe should rewrite https://usaco.guide/gold/string-hashing?lang=cpp#solution---searching-for-strings to use the latter approach.
