### ISSUE TITLE
misleading problem statement

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#3213]
so this problem: [boi mobile](https://oj.uz/problem/view/BOI12_mobile)

the thing it asks for is a bit weirdly worded
> the maximal distance of a point on the highway to the nearest base transceiver station.

it's pretty easy to misinterpret this, so i suggest adding a small note, maybe something like:
> The problem BOI - Mobile is asking to output the farthest distance to the nearest station out of _all_ the points on the highway.

**Comment by bqi343** [comment]
what could it be misinterpreted as?

**Comment by SansPapyrus683** [comment]
it's just the "a" in the initial statement that could confuse some people
you can close this at your own discretion, idc too much

**Comment by bqi343** [comment]
the wording is weird but it's understandable
