### ISSUE TITLE
Profanity in user submissions?

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#3222]
so i was browsing the user solutions for [this](https://usaco.guide/silver/greedy-sorting/#problem-usaco-1158) problem
<img width="461" alt="image" src="https://user-images.githubusercontent.com/55369003/204071037-17d704dd-7bdb-42ae-8364-c6c262d144f2.png">
should we take any steps to implement some rudimentary filter, or just "let the viewer beware"

**Comment by bqi343** [comment]
A filter seems reasonable. Though it's worth noting that you will occasionally encounter this when browsing public submissions on any site.

**Comment by SansPapyrus683** [comment]
i mean we don't have to put too much effort into it, maybe just a regex replace will work

**Comment by bqi343** [comment]
this should be extended to usernames (e.g., see https://usaco.guide/problems/cf-1478C/user-solutions)
