### ISSUE TITLE
"Edit This Page" Doesn't Work

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3244]
For example, clicking "Edit This Page" from https://usaco.guide/problems/usaco-714-why-did-the-cow-cross-the-road/solution sends me to the editor, but does *not* open the corresponding file.

Not sure if this is related:

<img width="926" alt="Screen Shot 2022-12-18 at 9 59 04 PM" src="https://user-images.githubusercontent.com/21228024/208339031-01b73929-7a5f-42a0-a00b-1994f677b0fc.png">

**Comment by HarryWangATX** [comment]
for me, it doesn't open the file anymore. it just opens the last opened file i had on the editor.

**Comment by bqi343** [comment]
@thecodingwizard do you know how to fix this? it seems that `get(filesListAtom)` is returning `null` at https://github.com/cpinitiative/usaco-guide/blob/master/src/atoms/editor.ts#L68
