### ISSUE TITLE
Add dark mode support for module status dropdowns

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#325]
Scrollbar shows up on right only in dark mode.

<img width="326" alt="Screen Shot 2020-10-21 at 12 46 38 PM" src="https://user-images.githubusercontent.com/21228024/96751736-8fe5e900-139b-11eb-9dd7-3361a5a9dd7e.png">

**Comment by bqi343** [comment]
Also, color scheme is messed up when you click on problems tab.

**Comment by bqi343** [comment]
+ live update text is white

**Comment by thecodingwizard** [comment]
I think all of the aforementioned issues are either fixed or about to be fixed!

**Comment by thecodingwizard** [comment]
The scrollbar thing isn't really an issue, and the other two were fixed, so I'll close this :)

**Comment by bqi343** [comment]
> Small thing: in dark mode, the Module and problem progress dropdowns are not dark. It doesn't matter much, but just UI wise it would look better dark :)

> I think that using a custom scrollbar for light mode as well would look good UI-wise.

**Comment by thecodingwizard** [comment]
err I'm fine with the first (dark dropdowns); I think the second is a non-issue since browser default scrollbar works well enough...
