### ISSUE TITLE
"Not Attempted" tag doesn't work in Problems search bar

### ISSUE THREAD

**Issue by megargayu** [cpinitiative/usaco-guide#3264]
Whenever I try to view problems that I haven't tried before (using the "Not Attempted" tag), it doesn't filter anything out - however, other tags like "Solved" do work under the same category.

This can be shown using the problem "Mootube" as an example, which I have solved:
![image](https://user-images.githubusercontent.com/56703197/206612265-307af08b-2c72-4a0f-ab0e-a47eff4fcee1.png)

However, when searching for "Mootube" using the "Not Attempted" tag, it still shows up with the silver version of the problem, even though it shouldn't:
![image](https://user-images.githubusercontent.com/56703197/206612406-2aa28d27-2ddc-4b47-b90c-df7fd12bb2e4.png)

**Comment by bqi343** [comment]
Seems like "Ignored" also doesn't work as intended.
