### ISSUE TITLE
Contact Form Submission - Suggestion (Filter Problems by Source)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3272]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/shortest-paths?lang=cpp
**Module**: Any module with "Problems" Section.
**Topic**: Suggestion
**Message**: 
Two suggestions for the "Problems" sections on tutorial pages:

1. Add a filter that allows users to filter the problems by website and/or difficulty (i.e. filter problems from USACO)

2. Create some mechanic allowing users to store notes for each problem (maybe add another column next to "STATUS" or smthn.

**Comment by bqi343** [comment]
1.  Filtering by source sounds useful to add. You can already filter by difficulty.
2. You can already store notes using via "View User Solutions."
