### ISSUE TITLE
Confusion Regarding Ad Hoc Module

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3276]
https://usaco.guide/bronze/ad-hoc?lang=cpp

> - Trying to complete search an ad hoc problem could end up wasting a lot of your time in contest.

Depends on the constraints? Sometimes you can complete search for partial credit (see http://www.usaco.org/index.php?page=viewproblem2&cpid=1088) and/or use the output of a complete search solution to gain more insight about the problem.

> Try to mess around with formulas or draw a visual depiction of the problem (maybe some sort of [graph](https://usaco.guide/bronze/intro-graphs))

If it's a graph problem, then it's no longer ad hoc, is it?

> Each ad hoc problem is different; no specific or general techniques exist to solve them.

Don't the tips in this module comprise a set of (*very*) general techniques to solve them?

**Comment by SansPapyrus683** [comment]
what do you suggest we replace these suggestions with?
