### ISSUE TITLE
Time Complexity Module

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3283]
1. I think we should formally define big O notation at the end of the module (or highly encourage people to check out a certain resource) so that people know how to answer questions [like these](https://forum.usaco.guide/t/a-question-on-time-complexity/3789) after completing the module (that is, the total runtime of two $O(N^2)$ loops could be said to be $O(N^2)$, $O(2N^2)$, $O(100N^2)$, $O(N^N)$, etc)

2. Looking at #540 again, it seems confusing to include this considering that we never define P and NP in the module. I think we should remove it, or quickly define them in the optional block before the link to the video.

3. "Big O notation" is used inconsistently throughout the module ("big-O notation", "Big O Notation").

**Comment by HarryWangATX** [comment]
i think P and NP section can go at the bottom of the module
