### ISSUE TITLE
Not Promoting Despite Doing all the Problems

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3286]
From #2949 (and https://www.youtube.com/watch?v=MUmOdDUucXQ):

> people might say "I went through the USACO Guide, did all the problems, and still can't promote."

I'm curious as to whether anyone (particularly those using the USACO Guide who participated in the most recent USACO contest) has any suggestions about what the USACO Guide could add to help with such situations. My opinion is that nothing in #2949 really helps with this, but feel free to disagree.

-----

Alternatively, you can just wait for an easier USACO contest ...

**Comment by IDON-TEXIST** [comment]
A potential solution might be to make the how to practice module more in-depth. One thing I think it absolutely should link to is [this cf blog](https://codeforces.com/blog/entry/98621).

And maybe (somehow) it could be more specific in terms of how to go through massive archives like the USACO and CF problemsets. I’m not experienced enough to know what such an explanation would entail, if it is possible.

**Comment by bqi343** [comment]
> One thing I think it absolutely should link to is [this cf blog](https://codeforces.com/blog/entry/98621).

Sounds reasonable, feel free to open a PR for this.

> And maybe (somehow) it could be more specific in terms of how to go through massive archives like the USACO and CF problemsets.

Just do problems around your level (by rating or solve rate)?

**Comment by thecodingwizard** [comment]
I'm somewhat inclined to agree with @SansPapyrus683 here:

> people might be too lazy to go & find problems themselves
on cf, the problemset is just one giant hodgepodge of problems, all the way from bronze to plat
you can filter by tag/rating, but knowing the tags of a problem can go a long way in helping you solve it
> curating a list of problems might encourage people to do them more than just "look at cf lmao"
again, i'm not agreeing with them, just trying to think of their possible reasons

Mostly, while I think filtering by rating on CF + going down the list works fine, I believe most people failing to promote are too lazy to take that step. I think activation energy to go through a list of problems on the Guide is substantially lower, even if all the Guide does is list the same exact problems that you can find on CF by sorting by rating.

With that being said, I could be wrong & hopefully actual contestants can weigh in here (maybe we should send out a survey or something?)

**Comment by SansPapyrus683** [comment]
what's this issue still open for again

**Comment by bqi343** [comment]
no particular reason
