### ISSUE TITLE
Split solutions by division

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3316]
Have a separate folder for each division's solutions so that the appropriate codeowners get notified when a solution is modified. If a problem is in multiple divisions, the corresponding solution can go in the folder corresponding to any of those divisions.

**Comment by mjh316** [comment]
Sounds doable, where should the folders be located? Should we create /content/#_Division/solutions folders, since they already have some owners in the CODEOWNERS file?

**Comment by HarryWangATX** [comment]
I think solution/division/ is better and then u can just add the path to the codeowner file. but that's gonna take a long time cuz there's a lot of solution files.

**Comment by mjh316** [comment]
> I think solution/division/ is better and then u can just add the path to the codeowner file. but that's gonna take a long time cuz there's a lot of solution files.

Sounds good. Also, it should just be the USACO solution files, right? They already have metadata based on the problem division - this shouldn't take more than a few minutes to do.

**Comment by bqi343** [comment]
all of the solutions, depending on the division of the module they appear in

**Comment by HarryWangATX** [comment]
maybe someone can write a script scraping the problem.json files in each content/division and then move it into folders.

**Comment by mjh316** [comment]
That's pretty much what I was thinking of doing - I think it's better than trying to find a corresponding division for each problem.

**Comment by HarryWangATX** [comment]
can u do dis for us then 😁😁

**Comment by bqi343** [comment]
If you build the site locally, you can go to`http://localhost:8000/___graphql` to get a mapping from modules to problems:

<img width="1329" alt="Screen Shot 2023-01-08 at 8 56 55 PM" src="https://user-images.githubusercontent.com/21228024/211230510-27fcf24d-817c-4efd-b3e2-7083916b765c.png">

**Comment by mjh316** [comment]
Alright, I moved some 500 files with a few scripts. Below, I've listed the roughly 20 files that do not show up under any division (when I search on https://usaco.guide/problems/). There's an APIO_taskauthor_problem_image.png and an "AC Knapsack 2.txt" that I have no idea what to do with.

Here are the aforementioned solutions that don't show up under any division (some seem to be tagged):
cf-1593A.mdx
ioi-10-traffic.mdx
cf-1566B.mdx
cf-1557B.mdx
lc-FindPivotIndex.mdx
sapo-18-stadium.mdx
cses-1631.mdx
cf-1560B.mdx
cco-EscapeRoom.mdx
cf-1702E.mdx
cf-20C.mdx
poi-14-hotels.mdx
cses-2220.mdx
ks-CandiesTestSet1.mdx
ccc-PhenomenalReviews.mdx
lc-MatrixBlockSum.mdx
poi-17-sabotage.mdx

**Comment by HarryWangATX** [comment]
some of the solutions had images, so that's the png files, you need to regroup them in a folder with the unique id. the ones without solutions might be problems that were previously used in the guide and then after a refactor got removed. maybe we should just add these to extraproblems.json if not already.

**Comment by mjh316** [comment]
Yeah, all but one of the images were already in a folder with the unique id - I just found the last one. All the aforementioned problems are already in extraProblems.json - should I just leave them in the solutions folder as is, then? Finally, the last file that I don't know what to do with is (this)[https://github.com/cpinitiative/usaco-guide/blob/master/solutions/AC%20Knapsack%202.txt].

**Comment by HarryWangATX** [comment]
I think this was an old solution to the DP Atcoder contest linked in gold. But now the editorial is linked to Neo's website, so I think this is safe to be deleted. Can you check by building locally?

**Comment by mjh316** [comment]
Yup, it is linked to the website - gotcha.

> idk how the solution files are rendered, but do u have to switch some paths for it to find where the new unique ids are placed?

Sorry, I'm not sure what this means - the solutions seem to be showing up fine, any pages I should specifically check on the local build?

**Comment by bqi343** [comment]
For now, you can leave the files you don't know what to do with in `solutions/`.
