### ISSUE TITLE
Add Codeowners for Platinum / Advanced

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3317]
Would be a good idea if we ever decide to revise these sections ...

https://github.com/cpinitiative/usaco-guide/blob/master/CODEOWNERS

(we don't get many PRs for these so it shouldn't be much of a time commitment)

**Comment by SansPapyrus683** [comment]
maybe dustin & dong?

**Comment by bqi343** [comment]
@dutinmeow @dongliu0426 ?

**Comment by dutinmeow** [comment]
works for me

**Comment by dongliu0426** [comment]
yep that works
