### ISSUE TITLE
Time Complexity Out of Place

### ISSUE THREAD

**Issue by saa938** [cpinitiative/usaco-guide#3327]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/83087832/210918487-9c81b837-6006-411d-b774-8d37c8372786.png">

In https://github.com/cpinitiative/usaco-guide/blob/master/solutions/usaco-785.mdx, it says the time complexity is O(N), but one of the lines reads "ordsort = sorted(order)", so the time complexity should be changed to nlogn. Correct me if I'm wrong.

**Comment by bqi343** [comment]
Feel free to open a PR.

**Comment by saa938** [comment]
Alright I opened a PR.

**Comment by saa938** [comment]
Thank you.
