### ISSUE TITLE
complete search w/ recursion solutions don't use recursion

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#3361]
https://usaco.guide/bronze/complete-rec

https://usaco.guide/bronze/complete-rec#problem-ccc-Twenty-four
https://usaco.guide/bronze/complete-rec#problem-usaco-965

these problems' internal solutions don't have recursion in the internal solution  
now i'm thinking either
1. just make it so they use recursion
2. delete this module entirely? idt complete search but with recursion warrants an entirely new module, i'm feeling we just make it another section of the prev raw complete search module

**Comment by HarryWangATX** [comment]
is permutations, subsets, etc required for bronze?

**Comment by bqi343** [comment]
[Livestock lineup](https://usaco.guide/bronze/complete-rec#problem-usaco-965) has iterating over all permutations as the intended solution. Idk about subsets.

> just make it so they use recursion

sure. As Java doesn't have built-in `next_permutation()` probably the cleanest way to do these problems in Java would be to use recursion.

**Comment by IDON-TEXIST** [comment]
An iterating through subsets problem appeared last weekend, for the record
