### ISSUE TITLE
Contact Form Submission - Suggestion (Dijkstra Visualizer)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3367]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/shortest-paths?lang=cpp
**Module**: Gold - Shortest Paths with Non-Negative Edge Weights
**Topic**: Suggestion
**Message**: 
I made a step by step visualization of dijkstra with relevant information at each step. Perhaps it would be a useful resource? link: https://alexyd88.github.io/Dijkstra-Visualizer/

**Comment by HarryWangATX** [comment]
is there any way that u can move the visualizer to be side by side?

**Comment by alexyd88** [comment]
> is there any way that u can move the visualizer to be side by side?

Side by side to what? Like distance to node is side by side edges in priority queue? Should be possible though.

**Comment by bqi343** [comment]
I think it would look better if everything including and below "Nodes" was to the right of the screen. Anyway, feel free to open a PR to add this.
