### ISSUE TITLE
Contact Form Submission - Other (Problem Solution - Load Balancing (ID: usaco-617))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3378]
Someone submitted the contact form!

**URL**: https://usaco.guide/problem-solutions/
**Module**: Problem Solution - Load Balancing (ID: usaco-617)
**Topic**: Other
**Message**: 
Jet Xavier's code has a problem in line 28. Because the variable i and the variable i in line 21 overlap.

**Comment by bqi343** [comment]
it still compiles
