### ISSUE TITLE
Contact Form Submission - Suggestion (Hints)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3392]
Someone submitted the contact form!

**URL**: https://usaco.guide/
**Module**: None
**Topic**: Suggestion
**Message**: 
Please add hints to more problem solutions. I really like the hints in Codeforces editorials and I find them really helpful for learning the intuition behind the solutions, so I think it would be nice to have them in problem solutions.

**Comment by yiminghuang47** [comment]
Btw I'm willing to help add hints

**Comment by SansPapyrus683** [comment]
then make some prs & get going ig

**Comment by SansPapyrus683** [comment]
i feel like this is in the same vein of "add more solutions," so i'm gonna close this
