### ISSUE TITLE
User problem data getting erased

### ISSUE THREAD

**Issue by waynewei07** [cpinitiative/usaco-guide#3396]
Hi, I'm the user that submitted the issue #3389.
I saw bqi343's comment on my issue.
<img width="428" alt="image" src="https://user-images.githubusercontent.com/89534097/216260750-5d59f888-6224-43fe-b7e0-df6e9ea278b6.png">
Does this imply that the same problem had happened before?
If so, can you guys give me the link of the previous issue or maybe tell me how the issue got solved?
Thank you.

**Comment by bqi343** [comment]
This was supposed to have been resolved by #3241. Unfortunately, I'm not aware of a way to recover the lost data.

**Comment by thecodingwizard** [comment]
@waynewei07 Could you help answer a few questions that might pinpoint the issue?

- Are you signing in with Google / Github (and if so, which one)?
- How long ago did you create your account (or do you not have an online account)?
- Did you switch devices at any point?
- When did this issue happen?
- Do you remember what you were doing before you lost all your data? Did you just sign out / sign in / etc?
- Is all your data lost (including module progress, streak, etc) or just your problem data?

**Comment by waynewei07** [comment]
@thecodingwizard 

- I'm signing in with google
- I forgot the exact date. But according to the activity chart, I registered on 2022/04/04.

<img width="774" alt="Screen Shot 2023-02-03 at 10 21 02 AM" src="https://user-images.githubusercontent.com/89534097/216497046-19099df3-04b7-4c46-a196-aef1e8fa3313.png">

- I logged in on multiple devices, but mainly on the same computer.
- It happened on 1/28.
- I was doing a problem in the guide, when I finished the problem and wanted to mark the problem as "solved", it didn't let me. So I refreshed the page, and all the problems suddenly got reset. I don't think I got signed out, because after the issue happened I managed to sign out and sign in again, but nothing changed.
- Fortunately only my problems' status had been changed. All other records such as module progress and streak remained normal.

**Comment by thecodingwizard** [comment]
oh yikes, this is a different issue than the one I fixed. Thanks for reporting this. In the future you can back up your data at https://usaco.guide/settings#user-data until we figure this issue out...

**Comment by waynewei07** [comment]
Got it, thank you for responding!

**Comment by waynewei07** [comment]
@thecodingwizard 
A moment ago I tried to export then import my data to see if it works, but it didn't. 
But I checked the code in the file and saw all my problems' progress which was lost!
https://ideone.com/fo2w1B
I tried to import this file into a new usaco guide account but it did nothing.
Hope this helps you with the problem!

**Comment by bqi343** [comment]
Looks like `userProgressOnProblems` was reset but `userProgressOnProblemsActivity` was not.

**Comment by bqi343** [comment]
It seems that #3396 and #3425 are the same except that problem activity was preserved in #3396 but not in #3425.

Looking at https://github.com/cpinitiative/usaco-guide/blob/master/src/context/UserDataContext/properties/userProgressOnProblems.ts, it seems that `setDoc` could potentially overwrite the value associated with `this.activityStorageKey`, while `updateDoc` could potentially overwrite the value associated with `this.progressStorageKey`. I'm not familiar enough with the code to know whether these are the only places where these values could be overwritten though. @thecodingwizard thoughts?

**Comment by thecodingwizard** [comment]
That makes sense. Thanks for gathering all this info! I think the linked PR should address these issues (hopefully).
