### ISSUE TITLE
Contact Form Submission - Typo / Broken Link (General - Expected Knowledge)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3398]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/expected-knowledge?lang=cpp#introductory-usaco-bronze-problems
**Module**: General - Expected Knowledge
**Topic**: Typo / Broken Link
**Message**: 
The "Introductory USACO Bronze Problems" section has non-USACO problems. Maybe this section should be renamed.

**Comment by SansPapyrus683** [comment]
i think what it means is those are bronze level
