### ISSUE TITLE
Change Navbar Design

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#341]
Our current navbar can get quite cluttered:
![image](https://user-images.githubusercontent.com/7865976/97096909-ea937500-1627-11eb-9e2d-6b70c59f7ff5.png)

We might want to change some stuff (specifically changing the search bar to become a button that then opens into a full-width search?)

**Comment by MrinallU** [comment]
@thecodingwizard I can do this.

**Comment by MrinallU** [comment]
@thecodingwizard So other than changing the search bar what else would you need to me to get done?

**Comment by thecodingwizard** [comment]
Stuff here: https://github.com/cpinitiative/usaco-guide/labels/website (especially the Blog :P)

And also feel free to help with content issues as well.

Thanks! :)

**Comment by MrinallU** [comment]
@thecodingwizard Essentially what I had in mind was a component like the problem search, with a route in the navbar containing the new search component.

**Comment by MrinallU** [comment]
@thecodingwizard Can you assign me to this so I don't forget?

**Comment by MrinallU** [comment]
@thecodingwizard Just making sure a full width search just means a page like the problems search but with the modules

**Comment by thecodingwizard** [comment]
no... I was thinking of a search icon button that would expand to become full width when clicked (or something similar). Or, alternatively, when clicking the search icon a full-page popup for search appears; that is probably fine too. I just want the ability for users to search without having to leave their page.

**Comment by MrinallU** [comment]
Ohhhh, I got you!

**Comment by Hanaffi** [comment]
@thecodingwizard 
Something like this: https://www.youtube.com/watch?v=2yfLpNALc1g ?

**Comment by thecodingwizard** [comment]
actually, why don't we just make the search bar into a search button, and then when they click the search button a modal pops up? something like https://tailwindcss.com/

Would this be better?

**Comment by Hanaffi** [comment]
@thecodingwizard Yeah, Thats even better.
I can finish it quickly.
May you assign it to me?

**Comment by thecodingwizard** [comment]
alright, it's assigned :)

**Comment by MrinallU** [comment]
@thecodingwizard I'm almost done with this but it's fine if hanaffi wants to try.

**Comment by thecodingwizard** [comment]
I don't want to overload you since you're already working on numerous other issues, so if it's alright with you I think it's best if Hanaffi takes this one

**Comment by MrinallU** [comment]
@thecodingwizard That's true the BenQ repo  browsing is kinda hard so I think he can take care of the easier ui issues way faster than me.

**Comment by Hanaffi** [comment]
@thecodingwizard Can you tell me where is that home page located?
Im just not very prof with React&Gatsby so I cant find it :(

**Comment by thecodingwizard** [comment]
The navigation bar code is here: https://github.com/cpinitiative/usaco-guide/blob/master/src/components/TopNavigationBar/TopNavigationBar.tsx

(Feel free to refactor, it seems quite messy oops XD)

**Comment by Hanaffi** [comment]
@thecodingwizard Wow ,
Aside from the issue , Can you tell me how to approach complex stuff in react?
I feel so beginner looking at your codebase , LOL.
I built moviesapp and to-do list :(

**Comment by MrinallU** [comment]
@Hanaffi Try not to get overwhelmed, it seems big at first, but once you really take the time to read it most of the code becomes pretty trivial.

**Comment by MrinallU** [comment]
@Hanaffi What exactly are you having trouble understanding

**Comment by Hanaffi** [comment]
@MrinallU 
Well, I cant actually find the code needed to be edited in that file :(

**Comment by MrinallU** [comment]
ohhh

**Comment by Hanaffi** [comment]
Oh, just found it

**Comment by MrinallU** [comment]
@Hanaffi https://github.com/cpinitiative/usaco-guide/blob/master/src/components/TopNavigationBar/TopNavigationBar.tsx

**Comment by Hanaffi** [comment]
@MrinallU I cant understand the classes names.
Is that a framework or what?

**Comment by MrinallU** [comment]
ummm no

**Comment by MrinallU** [comment]
If you don't understand the basic ideas you should check the React documentation: https://reactjs.org/docs/getting-started.html

**Comment by Hanaffi** [comment]
@thecodingwizard May I use material UI?

**Comment by thecodingwizard** [comment]
err probably not; that would add a large dependency to our project + we are using tailwind css already

**Comment by Hanaffi** [comment]
@thecodingwizard  Can you tell me some hint on how to implement this popup using tailwind??

**Comment by HarryWangATX** [comment]
@Hanaffi https://tailwindui.com/components/application-ui/overlays/modals tailwind ui components has some good examples of their usage.

**Comment by Hanaffi** [comment]
@HarryWangATX Thanks.

Can someone tell me how to fix this issue?
I mean , the search results goes out of the modal !
![Untitled](https://user-images.githubusercontent.com/35642947/103644406-fd4af400-4f5e-11eb-9a5d-bfb197813fe1.png)

**Comment by bqi343** [comment]
looks like this is done?
