### ISSUE TITLE
Prevent Line Breaks Between Equations and Punctuation

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3418]
Example:

<img width="888" alt="Screen Shot 2023-02-09 at 8 13 27 PM" src="https://user-images.githubusercontent.com/21228024/217975347-554455a3-2e86-43c9-b4f5-93b2332bd3ab.png">

**Comment by bqi343** [comment]
Seems like this is an open issue: https://github.com/KaTeX/KaTeX/issues/1233

**Comment by thecodingwizard** [comment]
We can probably just wait for https://github.com/KaTeX/KaTeX/pull/3133 to be merged...

**Comment by SansPapyrus683** [comment]
if this is wontfix then we can just close this right?
