### ISSUE TITLE
Standardize colors/components

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#342]
Especially since we have dark mode support, it's getting very messy & difficult to stay consistent with colors & components; for example, buttons/modals/dropdowns/text inputs all need both light mode and dark mode support. We should probably refactor common components like buttons, etc. into their own components...

Alternatively, instead of using tailwind color palette so aggressively, we can define custom css variables for different colors; for example, "background color" or "foreground text color" and then change the variable value based on the dark mode setting.

**Comment by MrinallU** [comment]
Also the dropdown for changing section status needs dark mode support as well.
![Capture](https://user-images.githubusercontent.com/61529929/97111367-bdd96f00-16b4-11eb-9826-a3ea9fe3615c.JPG)

**Comment by thecodingwizard** [comment]
~~too lazy won't fix~~
