### ISSUE TITLE
ccc '24's internal sol doesn't use recursion

### ISSUE THREAD

**Issue by 876pol** [cpinitiative/usaco-guide#3422]
[this problem](https://usaco.guide/bronze/complete-rec#problem-ccc-Twenty-four), even though it's in the complete search w/ rec module,,,, doesn't have an internal solution that uses recursion

**Comment by 876pol** [comment]
i made this internal solution originally -- i don't really know why i put it in the complete search with recursion module.
writing a complicated recursive function for an array of 4 numbers doesn't really make sense, so can i just move this to the normal complete search section?

**Comment by bqi343** [comment]
I assume Java users would use recursion in place of `next_permutation`

**Comment by 876pol** [comment]
oh right java
ill submit a pr changing it to recursion in the near future

**Comment by SansPapyrus683** [comment]
when's "the near future" for you pol

**Comment by 876pol** [comment]
sorry, i've been mostly prepping for my country's (canada) cs olympiad, which is tomorrow. ill submit the pr by friday.
