### ISSUE TITLE
All problem statuses disappeared

### ISSUE THREAD

**Issue by Yash-Singh1** [cpinitiative/usaco-guide#3425]
I've been using USACO Guide for quite a while now and I had several problems marked as complete in the problem tracker, but today the site started refreshing randomly and then the site went into light mode for a second, then all the problems marked as complete became marked as "not started" for every division. The modules' and resources' progress did not change though.

**Comment by bqi343** [comment]
Same as #3396?

**Comment by bqi343** [comment]
@Yash-Singh1 Could you also answer the questions in https://github.com/cpinitiative/usaco-guide/issues/3396#issuecomment-1414102550?

**Comment by Yash-Singh1** [comment]
- Are you signing in with Google / Github (and if so, which one)?

I sign in with Google, but I have both accounts linked

- How long ago did you create your account (or do you not have an online account)?

I am not sure

- Did you switch devices at any point?

I use the Guide on several devices

- When did this issue happen?

Early today morning

- Do you remember what you were doing before you lost all your data? Did you just sign out / sign in / etc?

The page was reloading so I closed it and reopened it then the problem data got erased.

- Is all your data lost (including module progress, streak, etc) or just your problem data?

No, it's just my problem data, I still have my streak, module progress, resource progress, etc.

**Comment by bqi343** [comment]
@Yash-Singh1 some followups:

> I use the Guide on several devices

Were you using the Guide on several devices just before the disappearance?

> The page was reloading so I closed it and reopened it 

What were you doing before the page was reloading?

> No, it's just my problem data, I still have my streak, module progress, resource progress, etc.

Is your problem activity still present? (check https://usaco.guide/dashboard)

**Comment by Yash-Singh1** [comment]
> Were you using the Guide on several devices just before the disappearance?

No, the last time I used it on another device was yesterday.

> What were you doing before the page was reloading?

I was solving a problem, and came back to the Guide page to mark it as complete.

> Is your problem activity still present? (check [usaco.guide/dashboard](usaco.guide/dashboard))

No, it's no longer there.

**Comment by bqi343** [comment]
> I was solving a problem, and came back to the Guide page to mark it as complete.

Did the page start reloading after you attempted to mark the problem as complete?

**Comment by Yash-Singh1** [comment]
> Did the page start reloading after you attempted to mark the problem as complete?

I don't think so, I came back to mark the problem as complete, when I noticed the page wasn't interactive, and I saw that it was reloading.

**Comment by marcliang** [comment]
I'm not sure if I should open a new issue for this, but something similiar happened to me. I used a different device on the weekend, and when I logged back in on monday, my progress was gone for ~2 days, then on the third day my progress came back...? During the 3 days I was using the same device only.

My activity status was also gone, but that didn't sync back; it says in the last 3 days I completed 19 modules, but I have 12 modules completed currently (because it synced back).

Questions from https://github.com/cpinitiative/usaco-guide/issues/3396#issuecomment-1414102550:

> Are you signing in with Google / Github (and if so, which one)?

Github

> How long ago did you create your account (or do you not have an online account)?

1-2 weeks ago

> Did you switch devices at any point near the erasure?

Yes, logged in on a different device 1-2 days before

> When did this issue happen?

Few days ago

> Do you remember what you were doing before you lost all your data? Did you just sign out / sign in / etc?

The first time I used the initial computer after using a different device, it was all gone

> Is all your data lost (including module progress, streak, problem activity, etc) or just your problem data?

Everything

**Comment by bqi343** [comment]
> The first time I used the initial computer after using a different device, it was all gone

Did everything disappear on both devices?

> Okay, another update: I just went on the website again after a few hours and now all my progress is gone again. 

Could you try exporting your user data (https://usaco.guide/settings#user-data) and checking whether everything is indeed gone?

**Comment by marcliang** [comment]
> Did everything disappear on both devices? Huh, when I tried looking up your user ID I saw that you've completed 12 modules and two problems (is that correct?). Just to confirm...

You're right, it only disappeared on this computer.

> If you go to https://usaco.guide/general/ do you see that all the modules you previously marked as complete are now unmarked?

On this computer yes, logging out & in again didn't change anything.

> Could you try exporting your user data (https://usaco.guide/settings#user-data) and checking whether everything is indeed gone?

[This](https://pastebin.com/9UipD9s7) is how it looks like from the computer where the progress disappeared again.

**Comment by bqi343** [comment]
Maybe it's a browser- or device-specific issue. What browser are you using, and do you encounter the same problem when using a different one? Do you see any errors in the developer console when you log in?

**Comment by thecodingwizard** [comment]
I'm closing this issue since it seems like we haven't seen many complaints for this recently, so hopefully this issue has been resolved?

We should still show a message if firebase fails to connect. That is tracked in #3573.

**Please reopen this issue if you experience data loss!!**
