### ISSUE TITLE
Integrate liveupdate page

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#343]
Instead of an "Edit on Github" link, we should change it to "Edit This Page," and then link to the liveupdate page and autofill the contents of that page w/ the source code for that particular module (might be doable w/ github API or something?). Then, there should be an "open PR" button or something that links to the github edit page where they can copy-paste their changes and open a PR.

(even better, we should be able to programmatically create a PR so people don't have to login to github...)

**Comment by caoash** [comment]
seems useful, however i think liveupdate is very laggy on some larger modules

**Comment by thecodingwizard** [comment]
I added a debounce, it should be a lot better now? Which module causes the lag? (maybe there should be an option to change the debounce...?)

**Comment by caoash** [comment]
uhh this was prior to adding that, and I don't remember specifically, I just remember it used to lag

**Comment by thecodingwizard** [comment]
oh LOL yeah it lagged a lot before. It should be a lot better now... my hope is using liveupdate will be just as good / better than local editing so that it's easier for people to contribute :P

**Comment by caoash** [comment]
yes i agree

**Comment by bqi343** [comment]
no "open PR" button but #521 seems good enough
