### ISSUE TITLE
Contact Form Submission - Suggestion (Gold - Longest Increasing Subsequence)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3434]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/lis?lang=cpp
**Module**: Gold - Longest Increasing Subsequence
**Topic**: Suggestion
**Message**: 
The baltic IO example problem for the module Gold->DP->Longest Increasing Subsequence links to the contest itself, is that intentional?

**Comment by bqi343** [comment]
yes, if you link to the problem itself you can't view the statement
