### ISSUE TITLE
Contact Form Submission - Website Bug (General - Data Types)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3439]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/data-types?lang=java
**Module**: General - Data Types
**Topic**: Website Bug
**Message**: 
Table causes webpage able to be resized in width on mobile

**Comment by bqi343** [comment]
https://stackoverflow.com/questions/41076390/is-there-a-way-to-overflow-a-markdown-table-using-html seems related. idk what the best way to fix this is though. @thecodingwizard ?
