### ISSUE TITLE
Add pageview counter per user

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#344]
We should track how many page views each user has. We can use this to then selectively prompt users to sign in / give feedback / etc.

The pageview counter can be added as a property in UserDataContext.

**Comment by MrinallU** [comment]
Hmm so overtime we would have to reset the page views on firebase, or the algorithm for feedback would have to account for large amounts of page views, for example, the user might keep viewing pages for years and thus all of the pages they have seen would be in the hundreds or even thousands. I think it's a good idea  as it definitely brings the guide to the next level in terms of interacting with the user.

**Comment by MrinallU** [comment]
@thecodingwizard So would that meant if we had a componentDidMount function for each of the module components, we could get the firebase data and increment the number of views for that particular page by one. (But there are quite a few module pages in the guide so adding them all to firebase would be a bit tedious)

**Comment by thecodingwizard** [comment]
We can probably implement this in the layout component similar to how `updateStreakEffect` is implemented. We don't really need to reset views...

**Comment by thecodingwizard** [comment]
Assigned to @koxuan , thanks! :)

**Comment by MrinallU** [comment]
@thecodingwizard I think you forgot to assign him.

**Comment by thecodingwizard** [comment]
For some reason I can't add him; Github won't let me. I'm not sure why oops
