### ISSUE TITLE
Misleading Binary Search Quiz Question

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3446]
https://usaco.guide/silver/binary-search?lang=cpp#quiz

<img width="883" alt="Screen Shot 2023-02-18 at 6 54 33 PM" src="https://user-images.githubusercontent.com/21228024/219904771-888fe8f3-fcc5-4da9-9105-5b0158b9b2d7.png">

Depending on the implementation, it could be $\Omega(\log n)$ in the best case. Probably best to include a code snippet as part of the question.

**Comment by Aadit-Ambadkar** [comment]
Out of curiosity, why is best-case even considered here?
