### ISSUE TITLE
Style sign in / user count info on dashboard page

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#345]
![image](https://user-images.githubusercontent.com/7865976/97122019-e75bc000-16df-11eb-96a3-e73e27c2c6ce.png)

We should style this so it doesn't look like a debug message...

Note that when you're not signed in, it prompts you to:

![image](https://user-images.githubusercontent.com/7865976/97122033-fa6e9000-16df-11eb-952d-3aeb09c672b1.png)

We should ideally prompt users to sign in if they aren't signed in.

**Comment by TanayB11** [comment]
I'll work on this

**Comment by bqi343** [comment]
Can we remove the user count for now?

**Comment by thecodingwizard** [comment]
sure (cdc4cd57e5ada38407cc7e34bb5e0367185f3cd8)

**Comment by MrinallU** [comment]
![Capture](https://user-images.githubusercontent.com/61529929/99814472-06027a80-2b17-11eb-8c94-140093d176e8.JPG)
@thecodingwizard How's this? All I need to do is remove the email at the top which is trivial but other than it's just a matter of your feedback!

**Comment by MrinallU** [comment]
@thecodingwizard I just placed the Display name as on the welcome dashboard to make it look a bit cleaner.

**Comment by thecodingwizard** [comment]
Hmm, how would we show the sign in prompt if they aren't signed in though?

**Comment by MrinallU** [comment]
hmm...

**Comment by MrinallU** [comment]
If they are not signed in then keep the message at the top and if they are not then remove it?

**Comment by thecodingwizard** [comment]
I don't think that looks much better than what we have now.

**Comment by MrinallU** [comment]
@thecodingwizard The name on the banner or the message on the top?

**Comment by MrinallU** [comment]
![Capture](https://user-images.githubusercontent.com/61529929/99836332-ed548d80-2b33-11eb-836a-ae4a7d9e2cac.JPG)
@thecodingwizard How about this?

**Comment by MrinallU** [comment]
@thecodingwizard Can you show me where the original sign in now message was so I can see how you put in the link to signin?

**Comment by thecodingwizard** [comment]
idk, I don't like it very much because that doesn't really belong there (it doesn't have anything to do with the CTA).

@MrinallU just look at the source code? it's in the same file I think?

**Comment by MrinallU** [comment]
@thecodingwizard What do you have in mind then?

**Comment by thecodingwizard** [comment]
idk lol, if I knew I would just implement it :P

**Comment by MrinallU** [comment]
@thecodingwizard So just to be clear you don't want the user's name showing on the Welcome Back screen correct?

**Comment by thecodingwizard** [comment]
I don't see the point? So yes, let's not show their name unless other people like it.

**Comment by MrinallU** [comment]
Ok then

**Comment by MrinallU** [comment]
@thecodingwizard I guess come back to it later?

**Comment by MrinallU** [comment]
@thecodingwizard How did you get the tiny box to appear to let everybody know about usaco forum? It could be applied to alert people to sign in.

**Comment by MrinallU** [comment]
![Capture](https://user-images.githubusercontent.com/61529929/99837718-0b22f200-2b36-11eb-9d20-0d61e6c6d5a5.JPG)
I mean this thing

**Comment by thecodingwizard** [comment]
it's in markdownlayout somewhere...

It looks ugly though and will probably be removed at some point :P

**Comment by MrinallU** [comment]
Oof

**Comment by MrinallU** [comment]
@thecodingwizard I'm in chem right now, and should really start paying attention, so I'll carry on the discussion after I brainstorm a little.

**Comment by thecodingwizard** [comment]
No clue how to do this (I tried https://github.com/cpinitiative/usaco-guide/tree/alt-signin-dashboard but didn't really work that well), and looks like you're busy with other issues, so I'll just close this for now.

**Comment by MrinallU** [comment]
@thecodingwizard So what if we had a quick notification that popped up for a few seconds indicating that the user has signed with some email.

**Comment by MrinallU** [comment]
@thecodingwizard I was considering something like a redux toast.

**Comment by MrinallU** [comment]
@thecodingwizard If you  don't know what that is here is a quick example: https://www.geeksforgeeks.org/reactjs-toast-notification/

**Comment by thecodingwizard** [comment]
I think that might be a bit annoying...

**Comment by MrinallU** [comment]
@thecodingwizard I mean it leaves in like five seconds plus we can style it to make it look better.

**Comment by MrinallU** [comment]
idk though just a suggestion, in my opinion the message on the top messes up the nice vibe of the dashboard so we can entertain the possibility of removing the message all together...

**Comment by MrinallU** [comment]
A better styled example, we can make it so the message only appears in the top and bottom corner. https://codesandbox.io/s/rl0xpx7k64
