### ISSUE TITLE
is pruning necessary

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#3468]
[this part](https://usaco.guide/bronze/complete-rec?lang=cpp#pruning)

gonna be honest idt any usaco or even cf problems require this  
it's just this one niche cses problem  
or i might just be very shortsighted

also all there is to this section is just "yeah lmao we can't explain it, just look here"

**Comment by bqi343** [comment]
It shows up on USACO training and some really old IOI iirc. we can remove it
