### ISSUE TITLE
Complete Search with Recursion - Java Code

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#348]
https://usaco.guide/bronze/complete-rec

> Please leave out FastIO in those code blocks to enhance readability. You could do smt like:
> static class FastIO {
>     // see ____ (link)
> }
> // actual code....

**Comment by thecodingwizard** [comment]
meh, I think it's fine as is :P but I'm down to change it too if we want

**Comment by thecodingwizard** [comment]
closing unless someone feels strongly one way or another
