### ISSUE TITLE
Contact Form Submission - Unclear Explanation (Bronze - Introduction to Sets & Maps)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3498]
Someone submitted the contact form!

**URL**: https://usaco.guide/bronze/intro-sets?lang=java
**Module**: Bronze - Introduction to Sets & Maps
**Topic**: Unclear Explanation
**Message**: 
"While you are free to change the values in a map when iterating over it (as demonstrated above), it is generally a bad idea to insert or remove elements of a map while iterating over it."

This only applies to the C++ code; the other languages don't provide examples of changing the values while iterating over the map.

**Comment by SansPapyrus683** [comment]
```py
In [1]: x = {'a': 1, 'b': 2}

In [2]: for k in x:
   ...:     x[k] = 1234
   ...:

In [3]: x
Out[3]: {'a': 1234, 'b': 1234}
```what do they mean by this?

**Comment by bqi343** [comment]
the code snippet corresponding to the quoted text only appears when the language is set to C++

**Comment by SansPapyrus683** [comment]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/55369003/223780659-1e6e2b46-a871-499d-82ea-a6bc083a3be9.png">
really?

**Comment by SansPapyrus683** [comment]
ah, that's what you meant
