### ISSUE TITLE
DFS - Python Code

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#350]
> It would be nice if you guys placed a traditional graph representation for your java implementation so everyone could get an idea of how we code the more common approach rather than just using chinese edge representation.

**Comment by frodakcin** [comment]
The problem is, I couldn't get a standard arraylist/list to ac in the cses system.

**Comment by thecodingwizard** [comment]
it's fine if it doesn't AC -- I think it's better to use standard arraylist and just be like "make sure you get 9/10 test cases, the last one is expected to TLE" or something

**Comment by frodakcin** [comment]
holy shit u replied fast, but ok sg

**Comment by frodakcin** [comment]
https://github.com/cpinitiative/usaco-guide/pull/388
Thanks Andrew!

**Comment by bqi343** [comment]
+ Python Code
