### ISSUE TITLE
Contact Form Submission - Minor Mistake (Silver - Introduction to Prefix Sums)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3514]
Someone submitted the contact form!

**URL**: http://localhost:8000/silver/prefix-sums?lang=cpp
**Module**: Silver - Introduction to Prefix Sums
**Topic**: Minor Mistake
**Message**: 
Under 1D prefix sums: $n$ should be $N$

**Comment by SansPapyrus683** [comment]
localhost 🤔

**Comment by bqi343** [comment]
yeah it's just me
