### ISSUE TITLE
Link to JoinCPI

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#352]
Link to https://joincpi.org/ 

> I think it should go in the FAQ next to where we have the "Is this open source?" part. There's an empty space there that we could fill with a relevant question and link

**Comment by thecodingwizard** [comment]
Added in bae53a15412a3af8d0ef2d5fccb38c70cf939fcc

![image](https://user-images.githubusercontent.com/7865976/97465810-a93ce700-18ff-11eb-856e-fd4941746f04.png)

Not too sure what to put oops
