### ISSUE TITLE
Atcoder ModInt

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3524]
is used in `/gold/combo` but not in `/gold/modular`. it should probably be used in both

**Comment by SansPapyrus683** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/55369003/223776374-c975416f-5f89-44bf-afe8-544172eeb389.png">
you mean we should replace this section with atcoder's?

**Comment by SansPapyrus683** [comment]
is there a link to the source code? the link i have rn only points to the docs
