### ISSUE TITLE
general problem issues

### ISSUE THREAD

**Issue by ryanchou-dev** [cpinitiative/usaco-guide#3540]
(by kevin sheng)

this is gonna be a big issue, imma gradually put down the list of problems that i feel need hints or those that are missing languages, contact me on discord if you feel a problem needs/doesn't need hints

# a whole-a** internal solution is missing
* [x] [photoshoot](https://usaco.guide/bronze/intro-greedy#problem-usaco-1227)

# hints

* [x] [sleepy cow herding](https://usaco.guide/problems/usaco-915-sleepy-cow-herding/solution) (wait why is this marked as easy)
* [x] [sleepy cow sorting](https://usaco.guide/problems/usaco-892-sleepy-cow-sorting/solution)
* [x] [milking order](https://usaco.guide/problems/usaco-832-milking-order/solution)
* [x] [taming the herd](https://usaco.guide/problems/usaco-809-taming-the-herd/solution)
* [x] [modern art](https://usaco.guide/problems/usaco-737-modern-art/solution)
* [x] [hoofball](https://usaco.guide/problems/usaco-808-hoofball/solution)
* [x] [spaced out](https://usaco.guide/problems/usaco-1088-spaced-out/solution)
* [x] [even more odd photos](https://usaco.guide/problems/usaco-1084-even-more-odd-photos/solution)
* [x] [race](https://usaco.guide/problems/usaco-989-race/solution)
* [x] [grass planting](https://usaco.guide/problems/usaco-894-grass-planting/solution)
* [x] [the great revegetation](https://usaco.guide/problems/usaco-916-the-great-revegetation/solution)
* [x] [milk factory](https://usaco.guide/problems/usaco-940-milk-factory/solution)
* [x] [swapity swap](https://usaco.guide/problems/usaco-1013-swapity-swap/solution)
* [x] [cow evolution](https://usaco.guide/problems/usaco-941-cow-evolution/solution)
# c++ missing

# java missing
* [x] [milking order](https://usaco.guide/problems/usaco-832-milking-order/solution)
* [x] [out of place](https://usaco.guide/problems/usaco-785-out-of-place/solution)

# python missing

**Comment by bqi343** [comment]
> wait why is this marked as easy

chatgpt can do it (mostly)

```py
with open('herding.in', 'r') as f:
    positions = list(map(int, f.readline().split()))
positions.sort()
 
# Minimum moves
if positions[1] - positions[0] == 1 and positions[2] - positions[1] == 1:
    min_moves = 0
elif positions[1] - positions[0] <= 2 or positions[2] - positions[1] <= 2:
    min_moves = 1
else:
    min_moves = 2
 
# Maximum moves
max_moves = max(positions[1] - positions[0], positions[2] - positions[1]) - 1
if max_moves == 1 and (positions[1] - positions[0] == 2 or positions[2] - positions[1] == 2):
    max_moves = 2
elif max_moves == 2 and positions[1] - positions[0] == 3 and positions[2] - positions[1] == 3:
    max_moves = 2
 
with open('herding.out', 'w') as f:
    f.write(str(min_moves) + '\n' + str(max_moves) + '\n')
```
