### ISSUE TITLE
add a module problem to bronze graphs module

### ISSUE THREAD

**Issue by ryanchou-dev** [cpinitiative/usaco-guide#3541]
rn [this](https://usaco.guide/bronze/intro-graphs) just like

> yeah these are what graphs are

> you're on your own bye

![Image](https://user-images.githubusercontent.com/55369003/217664091-154a68d4-ef53-4f1d-98e0-2a8586bef5ee.png)
also is this still relevant?

yea walking home from 2021 dec can be cheesed using dfs

**Comment by SansPapyrus683** [comment]
> yea walking home from 2021 dec can be cheesed using dfs

meant more like "dfs should be required in bronze tbh"

**Comment by ryanchou-dev** [comment]
actually?
