### ISSUE TITLE
Move BFS to Silver

### ISSUE THREAD

**Issue by ryanchou-dev** [cpinitiative/usaco-guide#3544]
Move BFS to Silver...

**Comment by bqi343** [comment]
why? is there a silver problem that specifically requires BFS?

**Comment by ryanchou-dev** [comment]
I was discussing with envy, and we thought that BFS and DFS were quite similar anyway and that it would make sense to learn them both together.

Plus, most people got partial on last contests' p3 with BFS / helps with thought process on silver problems?

What do you think?

**Comment by ryanchou-dev** [comment]
> you can also get partial without BFS, so I don't see how this is relevant
oops what i meant was that a lot of ppl got more partials than others because they implemented BFS (14/20 iirc), but yeah makes sense

> sure, but (almost) all of the problems in the BFS module are from Gold, so it doesn't make sense to move it to Silver. I think the current setup is fine (linking to BFS as an alternative to DFS for finding connected components)

alright, sounds good.
what do you think about adding an extra note about it in the "Additional Practice for Silver" module?

**Comment by bqi343** [comment]
> what do you think about adding an extra note about it in the "Additional Practice for Silver" module?

what sort of extra note?

another option (if you prefer) would be to move everything above "0/1 BFS" in the BFS module to the DFS module, and then rename the DFS module to something like "Connected Components"

**Comment by ryanchou-dev** [comment]
something like -- "if you have time, we highly recommend you check out the bfs module or smtg"

> another option (if you prefer) would be to move everything above "0/1 BFS" in the BFS module to the DFS module, and then rename the DFS module to something like "Connected Components." Then rename the current BFS module to "Unweighted Shortest Paths."

im good with that :>

will try and get it done tonight
