### ISSUE TITLE
add website testing framework?

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#355]
I'm not sure if it's worth the time though...

https://firebase.google.com/docs/emulator-suite

**Comment by MrinallU** [comment]
@thecodingwizard I have some experience in testing, which framework and what kinds of tests did you have in mind?

**Comment by thecodingwizard** [comment]
honestly I'm not sure, maybe e2e tests to make sure every page renders okay?

testing user context api would be nice but it's probably not worth the effort

**Comment by MrinallU** [comment]
Any specific framework you had in mind?

**Comment by thecodingwizard** [comment]
no, I'm fine with anything (though cypress was nice last time I used it iirc)

https://github.com/shlomif/testing-static-sites might be useful (?)

**Comment by MrinallU** [comment]
Alright this may take some time but seems pretty straight forward, I'll create the framework, make some basic tests and create a PR/ask what specific features should be tested.

**Comment by MrinallU** [comment]
![Capture](https://user-images.githubusercontent.com/61529929/98760469-56ecd300-23a1-11eb-8267-5b91c79190ef.JPG)

Cypress has been implemented :)

**Comment by MrinallU** [comment]
@thecodingwizard Should I PR?

**Comment by thecodingwizard** [comment]
Draft PR? (What tests did you add?)

**Comment by thecodingwizard** [comment]
Maybe some basic tests would be:
-user auth
-module progress
???

Some of these might be better as unit tests honestly

**Comment by MrinallU** [comment]
Alright I'll do user auth first.

**Comment by thecodingwizard** [comment]
Ok. Firebase auth testing might be a bit nontrivial so if you can't get that working no worries

**Comment by MrinallU** [comment]
Hmm, I see that now, but I'll give it my best shot!

**Comment by MrinallU** [comment]
Can I get the firebase config from the firebase console?

**Comment by thecodingwizard** [comment]
The config is in firebasecontext.tsx

**Comment by MrinallU** [comment]
Oops, didn't see that.

**Comment by MrinallU** [comment]
Can you send me the JSON file that you get from generating a new private key in firebase? I need it to write the tests for firebase I will add it to gitignore so it stays private.

**Comment by thecodingwizard** [comment]
Oops sorry, I don't think it is safe to distribute private keys for firebase (I'm not an expert on security oops). I think you should be able to write tests without those private keys? What specifically do you need them for? If you want I can add a delete user account function or something.

**Comment by MrinallU** [comment]
![Capture](https://user-images.githubusercontent.com/61529929/98865734-d8903f80-2439-11eb-9e5c-ebed7dbe0ce6.JPG)
I need it for using the tools for the testing that are provided in the above repository screenshot, I believe the url to the repo is in the screenshot so you can read through it see if there are any other ideas for using the tools. If you know of any good alternatives I'm open to anything!

**Comment by thecodingwizard** [comment]
hm... I don't know much about testing oops. If that is really the only option, then you can set up a new firebase project just for testing purposes?

Also, it might be easier just to write some unit tests for UserDataContext? not sure...

**Comment by MrinallU** [comment]
It is a bit tricky but I'll try experimenting a bit and I'll let you know.

**Comment by MrinallU** [comment]
Ok so I completed the auth testing by making my own sample firebase project and everything seems to be working fine.

**Comment by MrinallU** [comment]
@thecodingwizard Should I PR?

**Comment by thecodingwizard** [comment]
sure, submit a draft PR maybe?

for user auth, when logging in for the first time, it should prompt to upload local progress to the server. we might want to test this functionality...

**Comment by MrinallU** [comment]
@thecodingwizard Hmm what file is this in, and if applicable what function is this stored in? Also would this be better as a end to end or a unit test?

**Comment by MrinallU** [comment]
@thecodingwizard Also can you explain to me what the user context api does, no docs really explain it lol, it's pretty hard to write tests for an a complex api without knowing what exactly it does.

**Comment by thecodingwizard** [comment]
it's in `context/UserDataContext/UserDataContext.tsx`. I'm not sure if e2e or unit test is better; e2e is probably easier but unit test is probably more ideal.

User Data Context handles all user data. It should probably be replaced by mobx https://mobx.js.org/README.html at some point.

If it's too hard to get testing set up, then don't worry about it -- much of the code should be refactored anyway.

**Comment by MrinallU** [comment]
@thecodingwizard Got it, so I'll PR all of the more stable tests I created.

**Comment by thecodingwizard** [comment]
Oh this is neat: https://firebase.google.com/docs/emulator-suite

**Comment by MrinallU** [comment]
I'll take a look

**Comment by MrinallU** [comment]
![Capture1](https://user-images.githubusercontent.com/61529929/99601078-b2841580-29cc-11eb-9a33-520dfe16a9f4.JPG)
Like add me as an editor or something, if you can't for security purposes I understand.

**Comment by thecodingwizard** [comment]
firebase emulator requires you to be an editor? I thought it didn't need that.

Also since more people are using the guide now, I'm not really comfortable granting additional people access to the database, sorry about that :(

**Comment by thecodingwizard** [comment]
honestly I don't think it's worth implementing testing at the moment -- extra dev time would probably be better spent migrating UserDataContext into mobx or something, so I'll just close this issue for now.

**Comment by MrinallU** [comment]
Yeah that's true lol, testing sucks 😋
