### ISSUE TITLE
Graph Traversal Issues

### ISSUE THREAD

**Issue by ryanchou-dev** [cpinitiative/usaco-guide#3550]
https://github.com/cpinitiative/usaco-guide/pull/3549#issuecomment-1478767519

Todo:

- [x] Fix incomplete sections
- [x] Clean up code/organize

**Comment by SansPapyrus683** [comment]
when do you plan to do these

**Comment by ryanchou-dev** [comment]
after USACO -- if that's alright (?)

**Comment by bqi343** [comment]
More issues:
 - [ ] There isn't a DFS C++ Solution for building roads.
 - [ ] The DFS / BFS example code doesn't compile on its own. I think we should just remove these parts since you can see implementations of DFS / BFS in the solutions to building roads anyways.

**Comment by SansPapyrus683** [comment]
> The DFS / BFS example code doesn't compile on its own.

i was thinking we give some dummy input
the current gif, we can translate that into the input or something

**Comment by ryanchou-dev** [comment]
okay, remove it or edit the gif to reflect some dummy input in the program?

**Comment by SansPapyrus683** [comment]
i'm thinking 2 but benq probably has other ideas

**Comment by bqi343** [comment]
> the current gif, we can translate that into the input or something

ok
