### ISSUE TITLE
Contact Form Submission - Minor Mistake (Platinum : Tree : Binary Jumping : CF : MST for each edge)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3552]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cf-mst-for-each-edge/solution
**Module**: Platinum : Tree : Binary Jumping : CF : MST for each edge
**Topic**: Minor Mistake
**Message**: 
lca(u,v) instead of lcm(u,v) in the analysis

**Comment by SansPapyrus683** [comment]
@envyaims

**Comment by envyaims** [comment]
oopsies lol
