### ISSUE TITLE
Contact Form Submission - Minor Mistake (Convex Hull Trick)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3574]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: Convex Hull Trick
**Topic**: Minor Mistake
**Message**: 
internal solution for cf - Bear and Bowling 4 says that O(n) time complexity can be achieved because pre[r] is non-decreasing, but pre[r] is not non-decreasing becuase a[r] can be negative.

**Comment by SansPapyrus683** [comment]
@dustin-miao this is yours
