### ISSUE TITLE
Link http://ide.thecodingwizard.me/ 

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#358]

**Comment by thecodingwizard** [comment]
Lol where xD

**Comment by bqi343** [comment]
probably just under https://usaco.guide/general/running-code#running-code-online if you think that's okay?

**Comment by thecodingwizard** [comment]
ok I updated java; what about python needs to be updated? (I just changed the vercel link to the domain name)

**Comment by bqi343** [comment]
The input code changed

https://usaco.guide/general/io#standard-io
