### ISSUE TITLE
benq USACO repo code browser

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#360]
We should have a page on the USACO Guide that searches benq's repo: https://github.com/bqi343/USACO and offers the following functionality:

- search
- prettify
- undo certain macros (lol this might be a bit hard idk)

**Comment by MrinallU** [comment]
How would one go about doing this, as in how would we connect the repo to the site?

**Comment by thecodingwizard** [comment]
Github should have an API (or we can just copy the repo's content)

**Comment by MrinallU** [comment]
I'm willing to work on this.

**Comment by thecodingwizard** [comment]
Sure, go for it! http://ekzlib.herokuapp.com/home Might be helpful

**Comment by MrinallU** [comment]
Right, so I'll probably try fetching the data from the repository first.

**Comment by dliu426** [comment]
I think you should considering using [Git Submodules](https://github.blog/2016-02-01-working-with-submodules/) to link his repo to here. Then you could just query the files.

**Comment by thecodingwizard** [comment]
Or Gatsby GitHub plugin

**Comment by MrinallU** [comment]
Thanks for the suggestions guys!

**Comment by MrinallU** [comment]
@dliu426 I'll probably use your suggestion, thanks for bringing it to my attention!

**Comment by MrinallU** [comment]
@thecodingwizard So I finished getting all the files from Benjamin's repo! Now I need some help in regards to the UI aspect, is there any kind of sample react component I can see for putting in the content of the repo, also how would I get the syntax highlighting in the site for displaying the code?

**Comment by thecodingwizard** [comment]
For syntax highlighting, you probably want to use a variant of CodeBlock, which can be found in `components/markdown/CodeBlock/CodeBlock.tsx`. Honestly syntax highlighting can be added easily later on; I wouldn't worry about it too much for now. Simply using a `<pre>` tag should suffice.

I'm not sure what you mean by "putting in the content of the repo"?

**Comment by thecodingwizard** [comment]
Also I just realized that we'll have to somehow parse the description from the top of each file and then store everything in algolia so we can search it... I may have underestimated the complexity of this oops :P

(Also I can't find any C++ code prettifier??)

**Comment by MrinallU** [comment]
@thecodingwizard If we take it one step at a time, I can focus on creating the page in the site for storing all the code (similar to the problems section of the site). After that I'm positive we can figure something out for searching :)

**Comment by MrinallU** [comment]
@thecodingwizard Also, I don't quite understand what "undoing certain macros" really means.

**Comment by thecodingwizard** [comment]
Ben uses a lot of OP macros like trav(x, v). Undoing that would become for (auto &x : v)

(They're c++ macros)

**Comment by MrinallU** [comment]
@thecodingwizard Is it fine if we just manually place BenQ's repo directly into the project?

**Comment by thecodingwizard** [comment]
preferably not...

**Comment by thecodingwizard** [comment]
eventually this would be hooked up to Github API I hope. For development purposes I guess it's okay to just copy paste the repo?

**Comment by MrinallU** [comment]
Alright

**Comment by dongliu0426** [comment]
FYI, the the endpoint for the content of benq's repo is https://api.github.com/repos/bqi343/usaco/git/trees/master (if you need it)

**Comment by MrinallU** [comment]
@thecodingwizard I was stuck on this for a while but the liveupdate code gave me a good idea of what to do now.

**Comment by thecodingwizard** [comment]
I'll close this for now since it seems like there's more important issues to work on (like problem search :eyes:)
