### ISSUE TITLE
USACO FAQ Page

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#362]
We're looking to make a nice FAQ page in order to help with SEO.

- Put FAQ content here: https://github.com/cpinitiative/usaco-guide/blob/feature/faq-page/src/faq.mdx
- Can use content from here: https://darren-yao.gitbook.io/darren-s-blog/usaco-faq (Thanks Darren!)
- Try to structure the content in a way that helps SEO

Also we need a nice photo for the FAQ page

**Comment by Hanaffi** [comment]
Assign it to me pls

**Comment by thecodingwizard** [comment]
@Hanaffi Check out https://github.com/cpinitiative/usaco-guide/tree/feature/faq-page too

**Comment by Hanaffi** [comment]
@thecodingwizard  
I just have exams next week (Mid term) so I might have a delay for a week.

**Comment by HarryWangATX** [comment]
I can do it if needed

**Comment by thecodingwizard** [comment]
Thanks! See this branch for a starting point: https://github.com/cpinitiative/usaco-guide/tree/feature/faq-page

**Comment by HarryWangATX** [comment]
Alright, lemme finish correcting the hack case explanation first and I'll get started

**Comment by HarryWangATX** [comment]
@thecodingwizard do you want a new usaco faq page or add new ones to the existing one there?

**Comment by thecodingwizard** [comment]
just add new ones to the existing one I guess?

**Comment by HarryWangATX** [comment]
k

**Comment by HarryWangATX** [comment]
Hmm, Darren's blog seems to be down.

**Comment by HarryWangATX** [comment]
nvm just noticed that the existing one is from darren

**Comment by HarryWangATX** [comment]
close?
