### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Advanced - Lagrangian Relaxation)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3623]
Someone submitted the contact form!

**URL**: https://usaco.guide/adv/lagrange?lang=cpp
**Module**: Advanced - Lagrangian Relaxation
**Topic**: Request - Missing Section or Solution
**Message**: 
please add https://oj.uz/problem/view/BOI21_prison

**Comment by SansPapyrus683** [comment]
bro this is just a problem suggestion, i'll add it to the discussion thread
