### ISSUE TITLE
Contact Form Submission - Unclear Explanation (Bronze - Simulation)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3627]
Someone submitted the contact form!

**URL**: https://usaco.guide/bronze/simulation?lang=cpp
**Module**: Bronze - Simulation
**Topic**: Unclear Explanation
**Message**: 
hello, iam having trouble submiting a problem solution. i dont know where to submit it and how. i use normal c++ (stdcin, stdcout) and iam having trouble with it. and thank you for your service, didint know where to start cp without you.

**Comment by bqi343** [comment]
submitting a solution to which problem?

**Comment by SansPapyrus683** [comment]
it's been a week & op hasn't clarified, i think it's safe to close this
