### ISSUE TITLE
Contact Form Submission - Other (Problem Solution - Grass Planting (ID: usaco-894))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3637]
Someone submitted the contact form!

**URL**: https://usaco.guide/problem-solutions/
**Module**: Problem Solution - Grass Planting (ID: usaco-894)
**Topic**: Other
**Message**: 
I don't think the solution given works for this case 
9
1 2
1 3
1 4
1 5
6 2
6 3
6 4
6 5

**Comment by bqi343** [comment]
this test case does not satisfy the constraints described in the statement
