### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Problem Solution - Grass Planting (ID: usaco-894))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3638]
Someone submitted the contact form!

**URL**: https://usaco.guide/problem-solutions/
**Module**: Problem Solution - Grass Planting (ID: usaco-894)
**Topic**: Request - Missing Section or Solution
**Message**: 
the internal solution doesn't work for this case 
5
1 2
1 3
4 2
4 3

**Comment by bqi343** [comment]
same as #3637
