### ISSUE TITLE
Contact Form Submission - Suggestion (whether a problem has hints)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3650]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: None
**Topic**: Suggestion
**Message**: 
Minor suggestion: for a problem that has hints, maybe we could put them under a link separate from the internal sol? That way users can tell whether a problem has hints or not easily (for me, I try to keep myself from consulting the sol but am relatively open to hints, so separating those two would be nice)

**Comment by bqi343** [comment]
I think the easiest way to deal with this would just be to add a spoiler block around the solution whenever you add hints.

**Comment by SansPapyrus683** [comment]
we're already doing that

**Comment by bqi343** [comment]
maybe add a field to the frontmatter for each solution that says whether the solution contains a hint. then if the solution contains a hint, display "Internal Sol + Hints" instead of just "Internal Sol"

**Comment by bqi343** [comment]
actually, the easiest way to do this would be to add a `hint` field to `solutionMetadata` in `.problems.json`. What I mentioned in the previous comment would be better for internal solutions that appear in multiple modules though.
