### ISSUE TITLE
Vectorization

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#367]
https://codeforces.com/blog/entry/84257?#comment-718314

Should create a new module rather than combining w/ lambdas.

(Also, which pragmas actually make a difference lol)

**Comment by HarryWangATX** [comment]
> (Also, which pragmas actually make a difference lol)

https://codeforces.com/blog/entry/66279

**Comment by thecodingwizard** [comment]
https://usaco.guide/adv/vectorization?lang=cpp looks like this was done at some point?
