### ISSUE TITLE
Contact Form Submission - Suggestion (Silver Graph Traversal)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3671]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: Silver Graph Traversal
**Topic**: Suggestion
**Message**: 
This problem is rlly good for this module imo
https://codeforces.com/contest/1833/problem/E

**Comment by SansPapyrus683** [comment]
there's enough problems here...
