### ISSUE TITLE
Contact Form Submission - Suggestion (Bronze - Complete Search with Recursion)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3683]
Someone submitted the contact form!

**URL**: https://usaco.guide/bronze/complete-rec?lang=cpp
**Module**: Bronze - Complete Search with Recursion
**Topic**: Suggestion
**Message**: 
On line 14, you can make the n as n - 1 here: "	for (int mask = 0; mask < (1 << n); mask++) {" to "	for (int mask = 0; mask < (1 << n-1); mask++) {", this eliminates repeated cases.

**Comment by SansPapyrus683** [comment]
what
doesn't that just eliminate half the cases

**Comment by bqi343** [comment]
The suggestion seems correct - the current code counts each case twice.

**Comment by SansPapyrus683** [comment]
ok yeah now i see what it means
but this is bronze, and i don't think it's really necessary to explain the repeated cases and the optimization stuff
as long as it works...

**Comment by bqi343** [comment]
yeah it's fine
