### ISSUE TITLE
Contact Form Submission - Minor Mistake

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3694]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cses-2138-reachable-nodes/solution
**Module**: None
**Topic**: Minor Mistake
**Message**: 
Shouldn't the time complexity be O(N * M), not O(N + M) due to the |= operation for each edge? The bitset reduces the constant factor which should let it pass.

**Comment by SansPapyrus683** [comment]
@envyaims your problem

**Comment by envyaims** [comment]
yeah, he's right. it's NM/32
