### ISSUE TITLE
Contact Form Submission - Minor Mistake (Gold - Shortest Paths with Unweighted Edges)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3710]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/unweighted-shortest-paths?lang=cpp#extension---01-bfs
**Module**: Gold - Shortest Paths with Unweighted Edges
**Topic**: Minor Mistake
**Message**: 
in the last sentence of the second paragraph of http://www.usaco.org/index.php?page=viewproblem2&cpid=790 farms should be farmers

**Comment by bqi343** [comment]
this is an issue with USACO, not the USACO Guide
