### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Gold - Combinatorics)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3723]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/combo?lang=cpp
**Module**: Gold - Combinatorics
**Topic**: Request - Missing Section or Solution
**Message**: 
How can i get silver and gold courses ?

**Comment by SansPapyrus683** [comment]
what

**Comment by bqi343** [comment]
CPI offers Bronze and Silver classes: https://joincpi.org/classes

idk when they'll be offered again though

**Comment by SansPapyrus683** [comment]
prob next school year(?)
