### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Problem Solution - Strivore (ID: ac-strivore))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3727]
Someone submitted the contact form!

**URL**: https://usaco.guide/problem-solutions/
**Module**: Problem Solution - Strivore (ID: ac-strivore)
**Topic**: Request - Missing Section or Solution
**Message**: 
Missing solution for Strivore question.

**Comment by SansPapyrus683** [comment]
https://img.atcoder.jp/abc171/editorial.pdf
