### ISSUE TITLE
Solution for Bitwise Module (Silver)

### ISSUE THREAD

**Issue by ChuangSheep** [cpinitiative/usaco-guide#3729]
ok so uh, since this is now in silver, we should be trying to get solutions for this module done, since we only have one rn :<

- [x] [Powered Addition](https://codeforces.com/contest/1338/problem/A)
- [x] #3730
- [x] #3757
- [x] [Field Day](http://www.usaco.org/index.php?page=viewproblem2&cpid=1327)
- [x] [Sheikh (Easy version)](https://codeforces.com/problemset/problem/1732/C1)
- [x] [Prime Multiples](https://cses.fi/problemset/task/2185)
- [x] [AND, OR, and square sum](https://codeforces.com/contest/1368/problem/D)
- [x] [Ehab and another another xor problem](https://codeforces.com/contest/1088/problem/D)
- ~~[Lights Off](http://www.usaco.org/index.php?page=viewproblem2&cpid=1282)~~

**Comment by SansPapyrus683** [comment]
there is no way lights off should be in silver what

**Comment by envyaims** [comment]
> there is no way lights off should be in silver what
> 
> <img alt="image" width="158" src="https://user-images.githubusercontent.com/55369003/244544992-e40a8f6d-3536-4906-b2c6-abdbf47dc8de.png">
> yeah

im fine with you moving it to additional gold
i selected problems before i asked for it to be moved to silver lol

**Comment by SansPapyrus683** [comment]
<img width="343" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/55369003/69763e94-c510-42e7-8f56-ecbd5c693d61">

how is this easy 😭, should be normal at least

**Comment by envyaims** [comment]
> <img alt="image" width="343" src="https://user-images.githubusercontent.com/55369003/244906271-69763e94-c510-42e7-8f56-ecbd5c693d61.png">
> how is this easy 😭, should be normal at least

it's still relatively easier than the normal problems
this is my whole solution using very basic recursion

```c++
int test(int a, int b){
	if(a == b) return 0;
	if(a > b){
		// if a is even, then divide 2 rn
		// else add 1 to make it even and then divide by 2 lol
		int odd = a % 2;
		return 1 + odd + test((a + odd)/2,b);
	}
	else{
		int odd = b % 2;
		// divide b by 2 to meet a, or go straight to a
		return min(b - a, 1 + odd + test(a, b/2));
	}
}

void solve() {
    int a,b; cin>>a>>b;
    cout<<test(a,b)<<"\n";
}
```

**Comment by SansPapyrus683** [comment]
short solution != easy

**Comment by envyaims** [comment]
> short solution != easy

im aware, but this is still easier than all the normal problems i put up

**Comment by ryanchou-dev** [comment]
OH YEAH WE DID THAT

**Comment by envyaims** [comment]
W

**Comment by SansPapyrus683** [comment]
i remember this was in silver then we moved it to gold lol
back in the day...when guide classes weren't even a thing
