### ISSUE TITLE
Contact Form Submission - Suggestion (Advanced - Sum over Subsets DP)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3733]
Someone submitted the contact form!

**URL**: https://usaco.guide/adv/dp-sos?lang=cpp
**Module**: Advanced - Sum over Subsets DP
**Topic**: Suggestion
**Message**: 
I would suggest adding this CF blog as a resource: https://codeforces.com/blog/entry/105247
I struggled a bit with the current resources but this blog helped me get it instantly by viewing it as a multi-dimensional prefix sum.

**Comment by SansPapyrus683** [comment]
@Keys9873
