### ISSUE TITLE
Contact Form Submission - Website Bug (Negative Cow Photo Timer)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3734]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard
**Module**: None
**Topic**: Website Bug
**Message**: 
I think that the timer for the cow photos is broken - it said to come back in -11 hours to unlock Day 2's photo. My current streak is about 4-5 days, including today. Thank you!

**Comment by bqi343** [comment]
Did you switch time zones at any point? If the issue has persisted, could you export and send your user data (using https://usaco.guide/settings#user-data)?

**Comment by bqi343** [comment]
Emailed the OP asking for more details.
