### ISSUE TITLE
Contact Form Submission - Other (General - (Optional) C++ - Lambda Expressions)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3744]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/lambda-funcs?lang=cpp
**Module**: General - (Optional) C++ - Lambda Expressions
**Topic**: Other
**Message**: 
Introduction: Using C++ Lambdas https://websites.umich.edu/errors/500.html

This link is not working; it's showing 500: The web server has encountered an error. This resource is star-marked, so please resolve this issue.

**Comment by bqi343** [comment]
It works for me.
