### ISSUE TITLE
TripTastic appears in "More on Prefix Sums" module before Binary Search is taught

### ISSUE THREAD

**Issue by DenialRiver1434** [cpinitiative/usaco-guide#3749]
The problem is quite good, but there is no feasible solution without doing a binary search.

Move it to the binary search module instead as an easy/medium problem and it should be fine (please do not remove it as I [just typed up a solution](https://github.com/cpinitiative/usaco-guide/pull/3750) for it :D )

**Comment by SansPapyrus683** [comment]
did you move it to the binsearch mod?

**Comment by DenialRiver1434** [comment]
I'll add that to my PR
