### ISSUE TITLE
Contact Form Submission - Suggestion (Graph Traversal (Silver))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3751]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard
**Module**: Graph Traversal (Silver)
**Topic**: Suggestion
**Message**: 
I am currently solving the Graph Traversal problemset. By now, I've encountered 2 problems that should be solved with cycle finding, but that is not explained in the section. It would be nice if you could add a short section explaining how to detect cycles using DFS.

**Comment by bqi343** [comment]
> By now, I've encountered 2 problems that should be solved with cycle finding

which ones?

**Comment by ViktorMaksimoski** [comment]
Sorry for the late response.
The problems are:
Rank - DMOJ
Redistributing Gifts - Silver
Even if I am wrong, it would be nice to add a section for cycles.

**Comment by bqi343** [comment]
Sure, they involve cycles, but I don't think you need to know about cycles beforehand to solve either of these problems (just compute the all-pairs reachability matrix)
