### ISSUE TITLE
Contact Form Submission - Website Bug (General - How to Debug)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3752]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/debugging-checklist?lang=cpp
**Module**: General - How to Debug
**Topic**: Website Bug
**Message**: 
USACO IDE not working for promotion counting.
Says I output 21846
1429449537
5462
when i output 1
1
1 
for the sample test case.

**Comment by bqi343** [comment]
Please include your code.

**Comment by bqi343** [comment]
reopen if you have more details. but probably it's undefined behavior
