### ISSUE TITLE
DMOJ Contests have Inconsistent Labels

### ISSUE THREAD

**Issue by dustin-miao** [cpinitiative/usaco-guide#3756]
Certain links are inconsistent as to whether they're labelled "DMOJ" or the name of the contest they're originally from. For example, see the the [merging subtrees module](https://usaco.guide/editor/?filepath=content/6_Advanced/Comb_Sub.mdx) or [IOI Phidias](https://usaco.guide/problems/dmoj-phidias/solution). Most contests are labelled with the name of the competition, so I assume that's the correct way. 

Not sure if this is also true for other OJs. 

Tagging #3755

**Comment by SansPapyrus683** [comment]
be the change you want to see in the world
