### ISSUE TITLE
Contact Form Submission - Other (Usaco Guide usage)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3783]
Someone submitted the contact form!

**URL**: https://usaco.guide/
**Module**: Usaco Guide usage
**Topic**: Other
**Message**: 
Hi, I am Khan. I am from Kazakhstan ex Competitive programmer(https://codeforces.com/profile/verstand). A year ago we founded Competitive Programming Federation in Kazakhstan. Our current goals are to create a good ecosystem for competitive programming in small regions in our country. And we wanted to create guides for studying. We think that USACO. guide matches our needs and we wanted to translate it into Kazakh language and use it on our website: https://cpfed.kz/en/.  We would like to ask if it is okay or if not, can you provide any alternative solutions to use your guide in the Kazakh language?  We are open to any type of cooperation.

Regards,
Khan

**Comment by bqi343** [comment]
There is some discussion about this at https://github.com/cpinitiative/usaco-guide/discussions/2788, but I don't think anything has been done.

**Comment by bqi343** [comment]
> We would like to ask if it is okay or if not,

Yes, see https://github.com/cpinitiative/usaco-guide/issues/2775#issuecomment-1132523831
