### ISSUE TITLE
Contact Form Submission - Website Bug (USACO Guide groups)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3789]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems
**Module**: USACO Guide groups
**Topic**: Website Bug
**Message**: 
Group assignment problems shown as complete when individual problems are selected, but those same problems are shown as incomplete when the overall assignment is opened.

**Comment by bqi343** [comment]
Can you provide screenshots?

**Comment by SansPapyrus683** [comment]
not enough info
