### ISSUE TITLE
Contact Form Submission - Other (General - How to Practice)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3793]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/practicing?lang=cpp
**Module**: General - How to Practice
**Topic**: Other
**Message**: 
Dear USACO Guide,

I'm new to competitive programming. This guide looks fantastic, but I think I'm missing something that would be obvious to an experienced programmer: how can you tell when you've solved a problem?

If your programme fails to provide an output, then it's wrong. But if it always provides an output, how can you tell if it's correct? Is the USACO Guide IDE an online judge, into which you can enter programmes and receive a response, like 'passed all test cases' or 'failed a test case' or 'time limit exceeded'? Or is the only way to check your programme by comparing your outputs to those of a correct (official or user) solution?

Thank you and apologies if my query has an obvious answer!

**Comment by bqi343** [comment]
I've answered that question here (this will be merged into the main Guide soon):

https://usaco-guide-pgqgmljrd-cpinitiative.vercel.app/general/usaco-faq?lang=cpp#q-how-are-usaco-contests-scored

Please let us know if you have any additional questions.

**Comment by Daniel16384** [comment]
Thank you for replying but I don't think I was clear enough. I understand how programs are scored during an actual contest, but when practising in between contests, when working through the USACO Guide, in particular attempting the starred problems, how do you 'submit' your program for testing its correctness? The problem might be from years ago, so the contest it originally appeared in is over.

Does the USACO Guide have online judge capability, or should we be looking elsewhere for an online judge when practicing in between contests?

**Comment by bqi343** [comment]
> Does the USACO Guide have online judge capability,

No. You should log into the contest website, then look for the submit solution button (for USACO problems, this is at the bottom of the problem page).
