### ISSUE TITLE
Contact Form Submission - Suggestion (Silver - Custom Comparators and Coordinate Compression)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3803]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/sorting-custom?lang=cpp
**Module**: Silver - Custom Comparators and Coordinate Compression
**Topic**: Suggestion
**Message**: 
https://codeforces.com/contest/1846/problem/C

**Comment by envyaims** [comment]
no coordinate compression, just sorting with very obvious greedy. can't see this being in silver
