### ISSUE TITLE
Contact Form Submission - Suggestion (Bronze - Simulation)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3807]
Someone submitted the contact form!

**URL**: https://usaco.guide/bronze/simulation?lang=cpp
**Module**: Bronze - Simulation
**Topic**: Suggestion
**Message**: 
Add Hoof, Paper, Scissor, USACO 2017 January Contest, Bronze, Problem 2 to the module "Bronze - Simulation". It's a good simulation problem.

**Comment by envyaims** [comment]
not really simulation, more like complete search

**Comment by SansPapyrus683** [comment]
^, and there's enough complete search problems so
