### ISSUE TITLE
Contact Form Submission - Suggestion (General - Running Code Locally)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3810]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/running-code-locally?lang=cpp
**Module**: General - Running Code Locally
**Topic**: Suggestion
**Message**: 
Atom has since been deprecated, so maybe replace it with VSCode? Also maybe mention Neovim in addition to Vim

**Comment by bqi343** [comment]
VSCode is already mentioned

**Comment by SansPapyrus683** [comment]
<img width="102" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/55369003/a4950a4d-45e4-40e3-a887-35f8459f6e55">

yeah i feel like we can close this now
