### ISSUE TITLE
Contact Form Submission - Minor Mistake (Dynamic Programming)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3813]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/noi-knapsack/solution
**Module**: Dynamic Programming
**Topic**: Minor Mistake
**Message**: 
In given solution https://usaco.guide/problems/noi-knapsack/solution, it doesn't account for inner while loop for each sum or am i missing something?

**Comment by SansPapyrus683** [comment]
it runs in time lmao  
if my sol should tle though, i'm not sure how to fix it  
it's been ages since i touched this problem

**Comment by bqi343** [comment]
the solution is fine, I don't understand the message
