### ISSUE TITLE
Contact Form Submission - Other (Silver - Custom Comparators and Coordinate Compression)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3814]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/sorting-custom?lang=cpp
**Module**: Silver - Custom Comparators and Coordinate Compression
**Topic**: Other
**Message**: 
sssssssssssssssss

**Comment by SansPapyrus683** [comment]
lmao
