### ISSUE TITLE
Contact Form Submission - Other (Problem Solution - Censoring (ID: usaco-526))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3819]
Someone submitted the contact form!

**URL**: https://usaco.guide/problem-solutions/
**Module**: Problem Solution - Censoring (ID: usaco-526)
**Topic**: Other
**Message**: 
The solutions that use a while loop with contains() are incorrect, and do not work for 6 out of 15 test cases.

**Comment by SansPapyrus683** [comment]
is it wa or tle

**Comment by SansPapyrus683** [comment]
ccan't reproduce
