### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Problem Solution - Handshake (ID: ac-handshake))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3824]
Someone submitted the contact form!

**URL**: https://usaco.guide/problem-solutions/
**Module**: Problem Solution - Handshake (ID: ac-handshake)
**Topic**: Request - Missing Section or Solution
**Message**: 
Please write a solution for handshake in Binary search.

**Comment by bqi343** [comment]
moved to #3832
