### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Problem Solution - Irrigation (ID: cf-1181D))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3829]
Someone submitted the contact form!

**URL**: https://usaco.guide/problem-solutions/
**Module**: Problem Solution - Irrigation (ID: cf-1181D)
**Topic**: Request - Missing Section or Solution
**Message**: 
Please add an editorial for Irrigation in Gold. The CF solution is confusing and has no implementation. Furthermore, it doesn't show the approach needed to solve the problem.

**Comment by SansPapyrus683** [comment]
it's joeever

**Comment by SansPapyrus683** [comment]
wait...how is this purs

**Comment by SansPapyrus683** [comment]
oh nvm
