### ISSUE TITLE
Contact Form Submission - Unclear Explanation (Problem Solution - The Lazy Cow (ID: usaco-416))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3835]
Someone submitted the contact form!

**URL**: https://usaco.guide/problem-solutions/
**Module**: Problem Solution - The Lazy Cow (ID: usaco-416)
**Topic**: Unclear Explanation
**Message**: 
The Internal solution with prefix sum approach gives wrong answer for a user input
3 1
1 1 1
1 9 9
1 9 9
correct output: 29 but it gives 36

**Comment by bqi343** [comment]
Which internal solution (and what language)? Both of the C++ internal solutions output 36 for me.

**Comment by bqi343** [comment]
Looks like both of the internal sols output 36. @SansPapyrus683

**Comment by SansPapyrus683** [comment]
💀 💀 💀

**Comment by SansPapyrus683** [comment]
yeah idk what's going on with the sol, i just translated/formatted it (i think?)

**Comment by bqi343** [comment]
The problem is likely because the internal sol allows non-integer initial locations.
