### ISSUE TITLE
Completion Dates for Modules / Problems

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#385]
Like USACO Training?
<img width="521" alt="Screen Shot 2020-11-08 at 8 34 46 PM" src="https://user-images.githubusercontent.com/21228024/98491139-e491bc80-2201-11eb-8563-c823e3f612ef.png">

**Comment by bqi343** [comment]
> a calendar of some sort to help us track our daily USACO practice ?

**Comment by thecodingwizard** [comment]
github contribution style maybe? or stopstalk-ish?

**Comment by bqi343** [comment]
Can we take this off the backlog? Would definitely be useful for retaining users.

**Comment by thecodingwizard** [comment]
does this mean I actually have to think about how to implement it D:

**Comment by thecodingwizard** [comment]
@bqi343 what counts as an "activity" (the things that count towards the colored blocks)? Just completing modules / completing problems, or does "practicing" a module count as well?

**Comment by bqi343** [comment]
Oops I didn't mean to self-assign.

Completing modules / completing problems would make sense.

**Comment by thecodingwizard** [comment]
ok so:

- module progress changing to "Practicing" or "Complete" = +1
- problem progress changed to "Complete" = +1

Also, separately:

- each pageview = +1

Does this work?

**Comment by bqi343** [comment]
Sure. Why pageviews though? (Do you mean +1 if visited on a certain day?)

**Comment by MrinallU** [comment]
@thecodingwizard I'm kind of confused, how does this pertain to module dates?

**Comment by thecodingwizard** [comment]
idk, pageviews seems nice (and also rewards dumb people like me who can't always solve one problem a day D:)

also it's fairly easy to implement I think

**Comment by thecodingwizard** [comment]
> @thecodingwizard I'm kind of confused, how does this pertain to module dates?

when designing dates we should also design it in a way that allows github contribution style visualization...

**Comment by MrinallU** [comment]
@thecodingwizard Ohh ok, your right it doesn't seem too hard to implement.

**Comment by thecodingwizard** [comment]
https://github.com/frappe/charts charts :heart:

**Comment by MrinallU** [comment]
Yo thats cool

**Comment by MrinallU** [comment]
@thecodingwizard Using the charts we can make a whole page for user stats

**Comment by thecodingwizard** [comment]
okay I have an idea for how to implement module / problem activity:

- Make a giant list of user "activities"
- Every time the user changes module status or problem status, append to user activities list
  - Include type of activity, timestamp, activity payload (module/problem ID + what the new status is)
- When making the chart, somehow make a list of timestamps that count (for example, if the user sets status to practicing and then back to not started, that shouldn't count)

Assuming the user doesn't randomly toggle problem / module status too frequently, this should be okay...

**Comment by MrinallU** [comment]
@thecodingwizard And one would store the list in firebase?

**Comment by thecodingwizard** [comment]
yes

**Comment by MrinallU** [comment]
@thecodingwizard Makes sense, if you want me to do it and refer back to you for guidance or if you want to do it yourself I'm fine either way.

**Comment by thecodingwizard** [comment]
I'll just do it myself since it seems a bit complicated.

Also, I realized that a singular list of activities doesn't work very well with our current setup, so I'm thinking of just splitting it into two lists; one for problems, one for modules.

We should really figure out a good backend database soon oops

**Comment by MrinallU** [comment]
@thecodingwizard I have experience with MySQL so let me know if you need help to refactor to a SQL style database.

**Comment by thecodingwizard** [comment]
I'll close this for now since Dashboard -> Activity sort of does this. If someone has an idea for where to put module/progress completion elsewhere feel free to reopen
