### ISSUE TITLE
Copying Problem URLs to Clipboard

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#386]
When accessed from the dashboard, you get smth like the following:

https://usaco.guide/bronze/complete-rec/#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=857 

There should be a way to obtain such a link from the module directly.

**Comment by MrinallU** [comment]
@thecodingwizard How do you guys store the completion status of the problems, as someone could probably add a new row to the table and store the current date using the same storage process as the problem status.

**Comment by thecodingwizard** [comment]
It's stored as a key-value pair where key = problem ID and value = problem status; it's certainly possible to store the current date too but I'm not sure how DB migrations will work, and I'm also not sure how to add a date into the UI. (Also adding a date is for issue #385, not this issue)

**Comment by MrinallU** [comment]
@thecodingwizard Oops, I typed in the wrong issue lol.

**Comment by Hanaffi** [comment]
@thecodingwizard  Can you assign it to me?

**Comment by thecodingwizard** [comment]
@Hanaffi finish your other issue first (FAQ Page)! ;)

**Comment by bqi343** [comment]
What would this look like? (Double click on a row of the table to display or copy a URL to clipboard?)

**Comment by thecodingwizard** [comment]
maybe hover? (like what the heading tags are right now). On mobile, perhaps add another column at the very end? not sure

**Comment by MrinallU** [comment]
@thecodingwizard Where in the dashboard would this be as there is only a place for the modules?

**Comment by bqi343** [comment]
A bit confused, what does this have to do with modifying the dashboard?

**Comment by MrinallU** [comment]
I'm kinda confused here, I thought you guys said the problem links should be displayed from the dashboard.

**Comment by bqi343** [comment]
> There should be a way to obtain such a link from the module directly.

**Comment by MrinallU** [comment]
@thecodingwizard This I can work on this if you want me to.

**Comment by MrinallU** [comment]
So did you want a hover effect or another row on the table which displays the problems?

**Comment by thecodingwizard** [comment]
hover effect on desktop, another row on mobile?

**Comment by MrinallU** [comment]
So like how would the hober work here, like just a simple message that they can  view and how would they be able to copy  paste the hover message as it disappears after they take their mouse away from the problem.

**Comment by thecodingwizard** [comment]
When you hover over a header you can see a link:

![image](https://user-images.githubusercontent.com/7865976/102524328-b2b81500-404d-11eb-8e30-d32079bcca8c.png)

Something like that?

**Comment by MrinallU** [comment]
Is this a page in the guide?

**Comment by thecodingwizard** [comment]
yes (?)

**Comment by MrinallU** [comment]
So basically you want to have that header function but for the problems, plus the ability to copy and paste that link correct?

**Comment by thecodingwizard** [comment]
wait like the icon _is_ the link... you click the icon and your URL changes, and then you copy paste the URL to share it (just like how the current header works)

**Comment by MrinallU** [comment]
@thecodingwizard dumb question but can you give me the link to the page where you got that header screenshot?

**Comment by thecodingwizard** [comment]
any module page!! just hover over a header.

**Comment by MrinallU** [comment]
@thecodingwizard Well I'm it seems me two hours ago lacked brain cells.

**Comment by MrinallU** [comment]
@thecodingwizard So in the problem table in which row would the user hover over, as hovering over  the problem name in the table gives the link of the problem in the official usaco website.

**Comment by bqi343** [comment]
Anywhere in the row corresponding to that problem.

**Comment by MrinallU** [comment]
@bqi343 When clicking on that icon do you want  it to automatically copy to clipboard?

**Comment by bqi343** [comment]
Sure if you know how to do that. It's fine as is though.

**Comment by MrinallU** [comment]
@bqi343 If I have some free time I'll do that.

**Comment by thecodingwizard** [comment]
If you do this also make sure to add a brief "Copied" indicator somewhere!

**Comment by MrinallU** [comment]
@thecodingwizard planning on using this.

**Comment by MrinallU** [comment]
https://www.npmjs.com/package/react-copy-to-clipboard

**Comment by MrinallU** [comment]
So the copy and pasting feature works, as when clicking on that icon the specific problem automatically copies to the clipboard. Now, how would we notify the user when they copied the URL to the clipboard?

**Comment by bqi343** [comment]
<img width="361" alt="Screen Shot 2020-12-24 at 10 38 06 AM" src="https://user-images.githubusercontent.com/21228024/103097093-228d4900-45d4-11eb-82f1-7cb667a337b8.png">

Ex. The tooltip here becomes `Sample Input Copied to Clipboard` when the icon clicked.
