### ISSUE TITLE
Contact Form Submission - Website Bug (Gold - Minimum Spanning Trees)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3865]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/mst?lang=cpp
**Module**: Gold - Minimum Spanning Trees
**Topic**: Website Bug
**Message**: 
Kickstart problems are not available from the official website

**Comment by bqi343** [comment]
should link somewhere else (maybe https://codeforces.com/blog/entry/113809) or remove these

**Comment by SansPapyrus683** [comment]
well the kickstart link now links to some contest archive site: https://zibada.guru/gcj/ks2021a/problems/#D
is this issue still relevant

**Comment by bqi343** [comment]
The links need to be fixed for all kickstart problems, not just this one.
