### ISSUE TITLE
Contact Form Submission - Suggestion (Problem Solution - Fixed-Length Paths I (ID: cses-2080))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3867]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cses-2080/user-solutions
**Module**: Problem Solution - Fixed-Length Paths I (ID: cses-2080)
**Topic**: Suggestion
**Message**: 
You can add a tag with small to large for this and Fixed-Length Paths II as well

**Comment by SansPapyrus683** [comment]
@envyaims yes or no

**Comment by envyaims** [comment]
sure
