### ISSUE TITLE
Contact Form Submission - Website Bug (General - USACO Monthlies)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3870]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/usaco-monthlies?lang=cpp
**Module**: General - USACO Monthlies
**Topic**: Website Bug
**Message**: 
404 page after clicking "View User Solutions" on some recent problems (such as https://usaco.guide/problems/usaco-1278/user-solutions)
it seems to only happen on untagged problems

**Comment by bqi343** [comment]
After #3837 it looks like user solutions pages are not being created for problems on the USACO monthlies page that do not appear in `/content/extraProblems.json`. Such problems also are not appearing on the problems page: https://usaco.guide/problems/

**Comment by thecodingwizard** [comment]
Oops, I forgot about that. For the user solutions page, we can probably modify gatsby-node.ts to read https://github.com/cpinitiative/usaco-guide/blob/5a753e1f87ecbad0959314d7965ba04edf732ffd/src/components/markdown/ProblemsList/DivisionList/div_to_probs.json and create a user solution page for that usaco problem if we have not created that page already.

For search, we’ll probably have to modify one of the algolia related files…

**Comment by Vinceyou1** [comment]
I can work on adding the user solutions pages for the missing problems

**Comment by SansPapyrus683** [comment]
is this fixed?

**Comment by bqi343** [comment]
The problems page hasn't.

**Comment by MatheusHenriqueSS** [comment]
To ensure these problems are indexed by Algolia, they must be added to the `extraProblems.json` file. However, it seems that these changes don't take effect locally. Is there a way to test them before pushing?

**Comment by Vinceyou1** [comment]
I don’t think there’s any way to make a test deployment locally, but you can open a pr and it’ll create a test deployment without pushing to production

**Comment by thecodingwizard** [comment]
I think this will be fixed by #4086
