### ISSUE TITLE
USACO January 2018 Silver - Lifeguards

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#389]
https://usaco.guide/solutions/usaco-786

> What are the variables res, iz, and der for?

@Farrius

**Comment by bqi343** [comment]
closed by 57f2042

**Comment by Farrius** [comment]
I am sorry, I have to check my email more often.  If you are curious
(probably you know it already) der = derecha = right, iz = izquierda =
left, res = respuesta = response.

Missatge de Benjamin Qi <notifications@github.com> del dia dj., 12 de nov.
2020 a les 18:03:
