### ISSUE TITLE
Contact Form Submission - Suggestion (Advanced - Interactive and Communication Problems)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3892]
Someone submitted the contact form!

**URL**: https://usaco.guide/adv/interactive?lang=cpp
**Module**: Advanced - Interactive and Communication Problems
**Topic**: Suggestion
**Message**: 
Suggest to add IOI 2022 practice session "Magic Cards" in Communication problems
https://www.acmicpc.net/problem/25434

my solution:
http://boj.kr/ea5fd766af5d4c7285e79a339c339e70

**Comment by SansPapyrus683** [comment]
can you just submit a problem suggestion instead

**Comment by envyaims** [comment]
does anyone look at this module
