### ISSUE TITLE
Contact Form Submission - Minor Mistake (Silver - Introduction to Prefix Sums)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3901]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/prefix-sums?lang=cpp
**Module**: Silver - Introduction to Prefix Sums
**Topic**: Minor Mistake
**Message**: 
The User Solutions to the Old Bronze problem, Haybale Stacking, links to a 404 error broken link (https://usaco.guide/problems/usaco-104/user-solutions)

**Comment by SansPapyrus683** [comment]
@Vinceyou1 ayo?

**Comment by Vinceyou1** [comment]
oops, again

**Comment by Vinceyou1** [comment]
It seems like old USACO problems are not included in div_to_probs, so I accidentally skipped this page creation assuming it'd be in the other data file. Going forward, it might be helpful to do dynamic page routing of the user solutions page just to avoid any of these missed problems.
