### ISSUE TITLE
Bronze - Mark and Intro to Sorting, Intro to Sets & Maps as optional?

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3919]
The constraints for all the Bronze problems in these modules are so low that you can solve them without knowledge of sorting or sets and maps.

**Comment by SansPapyrus683** [comment]
i mean it's still good to know
and given how hard bronze problems are these days...

**Comment by envyaims** [comment]
maybe keep sets? D;

**Comment by SansPapyrus683** [comment]
so are we marking these optional?

**Comment by SansPapyrus683** [comment]
bump

**Comment by bqi343** [comment]
sure
