### ISSUE TITLE
Contact Form Submission - Other (General - Input & Output)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3922]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/input-output?lang=java
**Module**: General - Input & Output
**Topic**: Other
**Message**: 
Hi I am new to USACO and would like to get some clarification concerning what materials/references are allowed in USACO competition. Is there any reference link given during the competition? If yes can you share with me the link of Java standard library that we can refer to during competition? Or are we allowed to use a java textbook to check the syntax? Also, are we allowed to see the test question cases during the contest?

**Comment by SansPapyrus683** [comment]
rules are [here](http://usaco.org/index.php?page=instructions)

you can only view the sample case the problem gives in-contest
