### ISSUE TITLE
Contact Form Submission - Other (ACPC Sponsership)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3928]
Someone submitted the contact form!

**URL**: https://usaco.guide/
**Module**: ACPC Sponsership
**Topic**: Other
**Message**: 
Hello Usaco team, 
I hope this email finds you well.

My name is Ziad Monem, I'm currently a coach at ECPC (Egyptian Collegiate Programming Contest). I've coached four teams, helping them learn new algorithmic stuff and enhance their problem solving skills and thinking abilities.

We were facing an issue and we thought you might help us.

Fortunately, one of the four teams was able to make it and qualify to ACPC(Arab & Africa Collegiate Programming Contest). Quite simply, it is the oldest, largest, and most prestigious programming contest in the middle east and it qualifies to the ICPC (International Collegiate Programming Contest).

Despite my team's great performance in ECPC and our current nomination for qualification to ACPC, we find ourselves facing only one unfortunate obstacle. The cost of the sponsorship required for participation is beyond our means, making it impossible for us to proceed without external assistance. With great humility, we kindly seek your support in overcoming this financial burden and realizing their dream of competing in ACPC. Your generosity will make a significant difference in our journey, and we sincerely hope you can help us in this endeavor.

Sorry for the inconveniences.

Please let me hear from you soon (even if you can't help us we'll still be thankful).
Thank you in advance.

**Comment by Evang264** [comment]
Thanks for your request. We apologize for your difficult situation, but unfortunately, we cannot sponsor this.
I suggest asking for help on Codeforces, where similar past fundraisers have been conducted.
Good luck!
