### ISSUE TITLE
Contact Form Submission - Other (Problem Solution - Static Range Queries (ID: cfgym-102951D))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3930]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cfgym-102951D/user-solutions
**Module**: Problem Solution - Static Range Queries (ID: cfgym-102951D)
**Topic**: Other
**Message**: 
Could you also please explain on why we can't update the prefix array directly with adjusted effect. So for example my original <l,r,v> was [1,10,4] and my compressed <l,r> came as [1,5] by some chance then effectively I should be adding 9 throughout the new l,r. So shouldn't [1,10,4] translate to [1,5,9] in the compressed array ?

Code that I wrote:
https://ideone.com/0oNeQU

**Comment by SansPapyrus683** [comment]
i feel like this would go better on https://forum.usaco.guide/
