### ISSUE TITLE
Contact Form Submission - Website Bug (Bronze - Complete Search with Recursion)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3940]
Someone submitted the contact form!

**URL**: https://usaco.guide/bronze/complete-rec?lang=cpp#lexicographical-order
**Module**: Bronze - Complete Search with Recursion
**Topic**: Website Bug
**Message**: 
Air Cownditioning II (USACO 1276) gives "Error: Could not identify problem ID." when trying to open in the IDE.

**Comment by bqi343** [comment]
@thecodingwizard I added the most recent USACO problems to `vjudge-usaco`, can you restart it?

**Comment by thecodingwizard** [comment]
Done, thanks!
