### ISSUE TITLE
USACO Bronze 2019 Open - Milk Factory Python Solution

### ISSUE THREAD

**Issue by TheScarletPhoenix** [cpinitiative/usaco-guide#3951]
Hello,

In the USACO Guide, the problem Milk Factory (Bronze 2019) is shown as only having two solutions in C++ and Java. It says that the solution is not available in your chosen language Python yet. But in the editor page with all the code, there is the Python section as well with all the relevant code and comments. Please check and make sure that the Python solution also shows up on the USACO Guide page. Thanks.

**Comment by bqi343** [comment]
The Python code shows up later on the page.
