### ISSUE TITLE
USACO Silver 2020 December - Rectangular Pasture Solution in Python

### ISSUE THREAD

**Issue by TheScarletPhoenix** [cpinitiative/usaco-guide#3952]
Hello,

Here is a solution in Python for the problem Rectangular Pasture (USACO Silver 2020 December):
* Please check the solution and add it to the USACO Guide page if the solution is correct, bug-free, and suitable for Silver Division.

def count_subsets(N, cows):
    x_values = set()
    y_values = set()
    for x, y in cows:
        x_values.add(x)
        y_values.add(y)

    x_values = sorted(list(x_values))
    y_values = sorted(list(y_values))

    x_to_idx = {x: idx for idx, x in enumerate(x_values)}
    y_to_idx = {y: idx for idx, y in enumerate(y_values)}

    num_x = len(x_values)
    num_y = len(y_values)

    cow_matrix = [[0] * num_y for _ in range(num_x)]

    for x, y in cows:
        cow_matrix[x_to_idx[x]][y_to_idx[y]] = 1

    dp = [[0] * (num_y + 1) for _ in range(num_x + 1)]

    for i in range(num_x - 1, -1, -1):
        for j in range(num_y - 1, -1, -1):
            dp[i][j] = cow_matrix[i][j] + dp[i + 1][j] + dp[i][j + 1] - dp[i + 1][j + 1]

    result = 0
    for i in range(num_x):
        for j in range(num_y):
            for k in range(i + 1, num_x + 1):
                for l in range(j + 1, num_y + 1):
                    if dp[i][j] + dp[k][l] - dp[i][l] - dp[k][j] == 0:
                        result += 1

    return result

# Input
N = int(input())
cows = [list(map(int, input().split())) for _ in range(N)]

# Calculate and print the result
result = count_subsets(N, cows)
print(result)

**Comment by bqi343** [comment]
If you would like to add your solution code to the guide, please open a pull request rather than an issue.

(FYI, it looks like the code you posted above doesn't pass the sample case.)

**Comment by TheScarletPhoenix** [comment]
Ohh okay 👍
