### ISSUE TITLE
USACO Bronze 2021 January - Uddered but not Herd Solution in C++

### ISSUE THREAD

**Issue by TheScarletPhoenix** [cpinitiative/usaco-guide#3953]
For the problem Uddered but not Herd (USACO Bronze 2021 January), there is no solution in C++ on the USACO Guide, but only in Java and Python (which is weird).
So here is a solution in C++ :
*Pls check if it's right, and if so, merge this and add the solution to the USACO Guide page.

#include <iostream>
#include <string>
#include <unordered_map>
using namespace std;

int main() {
    string cowphabet;
    cin >> cowphabet;
    string heard_string;
    cin >> heard_string;

    unordered_map<char, int> last_occurrence;
    int count = 1;
    int position = 0;

    for (char letter : heard_string) {
        if (cowphabet.find(letter) != string::npos) {
            int index = cowphabet.find(letter);
            if (index < position) {
                count++;
            }
            position = index;
        }
        last_occurrence[letter] = position;
    }

    cout << count << endl;
    return 0;
}

**Comment by bqi343** [comment]
See https://github.com/cpinitiative/usaco-guide/issues/3952#issuecomment-1722518092

**Comment by TheScarletPhoenix** [comment]
Well, there is no solution in C++ when I looked and it says not available yet. Same for the previous two issues I submitted. They are not appearing on the page. Pls check again in the USACO Guide.

**Comment by bqi343** [comment]
I meant the USACO analysis, not the USACO Guide solution.
