### ISSUE TITLE
Contact Form Submission - Suggestion (Silver - Two Pointers)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3959]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/two-pointers
**Module**: Silver - Two Pointers
**Topic**: Suggestion
**Message**: 
i require this for its imple:V https://codeforces.com/contest/1873/problem/F/

**Comment by SansPapyrus683** [comment]
@envyaims

**Comment by envyaims** [comment]
pretty bland problem. literally just template 2p with another condition
