### ISSUE TITLE
Contact Form Submission - Other (CPI Befinner Class)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3963]
Someone submitted the contact form!

**URL**: https://usaco.guide/groups/lfmUHQFuMnPi6O4E4llY/post/LAvYEWAQeIoakHlv73tr
**Module**: CPI Befinner Class
**Topic**: Other
**Message**: 
Hello - I am requesting a refund for my daughter who joined the CPI beginner class last week.  She was not able to attend the class on Sptember 23rd.  But I also realized that she needs to do more basic courses before she signs up for this class.  If you could please issue a refund that would be great!

**Comment by bqi343** [comment]
As described in the contact form:

> If you have any questions about [CPI classes](https://joincpi.org/classes), please email [classes@joincpi.org](mailto:classes@joincpi.org) rather than submitting this form.
