### ISSUE TITLE
Contact Form Submission - Unclear Explanation (Problem Solution - Why Did the Cow Cross the Road II (ID: usaco-712))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3964]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-712/user-solutions
**Module**: Problem Solution - Why Did the Cow Cross the Road II (ID: usaco-712)
**Topic**: Unclear Explanation
**Message**: 
Regarding Pavan Yeddanapudi's solution,
He gives no explanations  and his code is hard to read.

**Comment by bqi343** [comment]
This is expected of user solutions.
