### ISSUE TITLE
Mistake in the solution

### ISSUE THREAD

**Issue by Dayal-Kumar** [cpinitiative/usaco-guide#3966]
In this file https://usaco.guide/editor?filepath=solutions/gold/cses-1082.mdx, on line 34 there is the expression 
$$\sum_{d=1}^{n} \left\lfloor \frac{n}{d}\right\rfloor$$
But the correct one should be
$$\sum_{d=1}^{n} d\left\lfloor \frac{n}{d}\right\rfloor$$

**Comment by bqi343** [comment]
Feel free to open a PR to fix this.
