### ISSUE TITLE
Contact Form Submission - Other (Problem Solution - Race (ID: usaco-989))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3968]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-989/user-solutions
**Module**: Problem Solution - Race (ID: usaco-989)
**Topic**: Other
**Message**: 
The solution by Connor Fricke is incorrect

**Comment by bqi343** [comment]
marked as private
