### ISSUE TITLE
Contact Form Submission - Minor Mistake (Platinum - Sweep Line)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3973]
Someone submitted the contact form!

**URL**: https://usaco.guide/plat/sweep-line?lang=cpp#problem-kattis-closestpair2
**Module**: Platinum - Sweep Line
**Topic**: Minor Mistake
**Message**: 
Solution for Manhattan MST has mistakes:
Line 24 must be "i == 0"
Line 31 must be " < GRID_SZ"

**Comment by bqi343** [comment]
@SansPapyrus683 ?

Also, the time complexity seems wrong; I don't know how to show a bound better than $O(S^3\log S)$ for the provided solution ...

**Comment by SansPapyrus683** [comment]
brebnel did you test your code 💀

**Comment by brebenelmihnea** [comment]
<img width="1212" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/59292725/604b3db5-3fdb-4755-9871-1c54e94d6f74">
Bro I got AC with the code

**Comment by SansPapyrus683** [comment]
i think the time complexity issue still holds nvm

**Comment by FarisKarim** [comment]
yeah ill fix this; its not letting me add the new changes to my original pr, so ill make a new one

**Comment by FarisKarim** [comment]
ah that makes sense
