### ISSUE TITLE
Contact Form Submission - Suggestion (Problem Solution - Jury Marks (ID: cf-831C))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3975]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cf-831C/user-solutions
**Module**: Problem Solution - Jury Marks (ID: cf-831C)
**Topic**: Suggestion
**Message**: 
wai yip li Solution will give TLE he must use unordered_map

**Comment by bqi343** [comment]
marked as private. though as mentioned in the guide using unordered map without a custom hash function is a bad idea for CF
