### ISSUE TITLE
silver quizzes

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#3983]
all current modules w/o stuff:

- [x] [more on prefix sums](https://usaco.guide/silver/more-prefix-sums)
- [x] [graph traversal](https://usaco.guide/silver/graph-traversal)
- [x] [trees](https://usaco.guide/silver/intro-tree)
- [x] [func graphs](https://usaco.guide/silver/func-graphs)
- [x] [bitwise ops](https://usaco.guide/silver/intro-bitwise)

**Comment by ryanchou-dev** [comment]
W

**Comment by SansPapyrus683** [comment]
oh yeah forgor this was a thing
