### ISSUE TITLE
Contact Form Submission - Website Bug (Password Change)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3992]
Someone submitted the contact form!

**URL**: https://usaco.guide/settings#general
**Module**: Password Change
**Topic**: Website Bug
**Message**: 
Hi,

I registered with my google account. But when I try to solve a question the website tells me to login again. Since I registered with my google account I dont know my password. When I try to change it, I can not get an email. I dont know how to solve the problem. I would be glad if you could help me.

**Comment by SansPapyrus683** [comment]
so login with your google account?

**Comment by bqi343** [comment]
If this is in reference to usaco.org rather than the USACO Guide, you need to create a different account for that website. The USACO Guide is not affiliated with the USACO.
