### ISSUE TITLE
Contact Form Submission - Other (Problem Solution - Studentsko (ID: kattis-studentsko))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4010]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/kattis-studentsko/user-solutions
**Module**: Problem Solution - Studentsko (ID: kattis-studentsko)
**Topic**: Other
**Message**: 
solution doesn't work for the following case:

5 1
1 2 4 5 3

output: 1
answer: 2

**Comment by SansPapyrus683** [comment]
uh that's a user solution
idt we validate those lol

**Comment by bqi343** [comment]
> idt we validate those lol

Yes, we do; the user solution says to submit the contact form if any solutions are wrong.

Anyways, 1 is the correct output for this test case.

**Comment by SansPapyrus683** [comment]
i stand corrected
