### ISSUE TITLE
Contact Form Submission - Other (Problem Solution - Nezzar and Symmetric Array (ID: cf-1478C))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4011]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cf-1478C/user-solutions
**Module**: Problem Solution - Nezzar and Symmetric Array (ID: cf-1478C)
**Topic**: Other
**Message**: 
the solution from Long Doan is completely wrong, not only he forgot cin>>t; but also its output is wrong on certain cases such as
1
2
4 4 4 4

**Comment by bqi343** [comment]
marked as private

**Comment by SansPapyrus683** [comment]
<img width="282" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/55369003/4e451d32-f47c-4530-9141-eddc4b0d4fda">

ayo benq maybe you should remove this one as well

**Comment by bqi343** [comment]
we should remove all these at once (see https://github.com/cpinitiative/usaco-guide/issues/3222#issuecomment-1788673941)
