### ISSUE TITLE
How to create a pull request (first time on GitHub)

### ISSUE THREAD

**Issue by TheScarletPhoenix** [cpinitiative/usaco-guide#4015]
I would like to add solutions for a few problems in Python in the USACO Guide, but it's my first time on GitHub, and I don't know how to exactly create a pull request. Any steps to guide me?

**Comment by bqi343** [comment]
[See https://usaco.guide/general/contributing and the fo](https://github.com/cpinitiative/usaco-guide/blob/master/CONTRIBUTING.md)
