### ISSUE TITLE
Contact Form Submission - Other (Problem Solution - Old Berland Language (ID: cf-1083B))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4017]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cf-1083B/user-solutions
**Module**: Problem Solution - Old Berland Language (ID: cf-1083B)
**Topic**: Other
**Message**: 
Someone submitted a solution to a different problem.

**Comment by bqi343** [comment]
marked as private
