### ISSUE TITLE
https://usaco.guide/general/io https://usaco.guide/bronze/intro-ds java centric

### ISSUE THREAD

**Issue by frankieliu** [cpinitiative/usaco-guide#402]
The IO section is java centric, could you please add the corresponding optimizations for c++, since it is the suggested language of choice at harder levels.

The similar can be said of the data structures section, why give java so much time in this guide, just stick with c++, is there any advantage to writing this guide in anything else but c++, it makes it confusing for the reader.  Perhaps if you want to have java specific sections it would be good to just separate that in an appendix, one for java and another for python (if necessary).

**Comment by frankieliu** [comment]
Not an issue, settings dictates what content is seen.

**Comment by thecodingwizard** [comment]
yeah, it's not that obvious where language settings are right now :(
