### ISSUE TITLE
Contact Form Submission - Minor Mistake (Platinum - Binary Jumping)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4021]
Someone submitted the contact form!

**URL**: https://usaco.guide/plat/binary-jump?lang=cpp#lowest-common-ancestor
**Module**: Platinum - Binary Jumping
**Topic**: Minor Mistake
**Message**: 
In the c++ code for Solution (Distance Queries), the function is defined as LCA on line 279 and used as lca on line 313

**Comment by SansPapyrus683** [comment]
hey ben i think harry quit(?)
