### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Platinum - Square Root Decomposition)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4022]
Someone submitted the contact form!

**URL**: https://usaco.guide/plat/sqrt/#problem-joi-19-examination
**Module**: Platinum - Square Root Decomposition
**Topic**: Request - Missing Section or Solution
**Message**: 
https://usaco.guide/plat/sqrt/#problem-joi-19-examination
I'd really appreciate it if you could write an editorial for the square-root decomposition solution and the other solution that doesn't use square root decomposition. And thanks for all the effort you've put into making this guide!

**Comment by SansPapyrus683** [comment]
so you want 2 solutions?

**Comment by nehasane** [comment]
yes
