### ISSUE TITLE
Contact Form Submission - Suggestion (Platinum - Square Root Decomposition)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4043]
Someone submitted the contact form!

**URL**: https://usaco.guide/plat/sqrt
**Module**: Platinum - Square Root Decomposition
**Topic**: Suggestion
**Message**: 
the bitaro birthday problem has no sqrt decomp sol brother ://

**Comment by bqi343** [comment]
The model code uses sqrt decomp.
