### ISSUE TITLE
Contact Form Submission - Suggestion (Bronze - Simulation)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4052]
Someone submitted the contact form!

**URL**: https://usaco.guide/bronze/simulation
**Module**: Bronze - Simulation
**Topic**: Suggestion
**Message**: 
First I want to say that this site is awesome, so thank you. Anyway, I've been coding for around a year but just started thinking about trying USACO. When I got to the examples part, I went to the link it gave to try. However, I am confused on how you submit your solution to be checked. I know you upload the file to the analysis mode but what kind of file? So, I was wonder if a tutorial could be added to the website for beginners. Or, even better, if a built in code console that you type in and it checks (Like LeetCode). This would be much appreciated! Thank you so much!

**Comment by bqi343** [comment]
You submit a file containing your source code. I don't think the name / extension matters (except if you using Java, in which case the file should be named the same as your public class).

**Comment by bqi343** [comment]
I don't think it's necessary to explicitly mention this, though feel free to open a pull request if you want to add this somewhere in https://usaco.guide/general/input-output
