### ISSUE TITLE
Remove Inactive Contest Sites

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#4053]
https://usaco.guide/general/contests

Some of these should be removed (e.g., hackerrank)

**Comment by SansPapyrus683** [comment]
that site's inactive?

**Comment by SansPapyrus683** [comment]
![image](https://github.com/cpinitiative/usaco-guide/assets/55369003/4a144329-2900-4fa3-9463-a541f896c161)
isn't that stated here

**Comment by bqi343** [comment]
there aren't "Hack the Interview" contests anymore, maybe it should be removed altogether
