### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Silver Additional Practice)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4055]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: Silver Additional Practice
**Topic**: Request - Missing Section or Solution
**Message**: 
I would like to include an editorial for Circular Barn - The Game; I would also like to include another topic in the Silver section which is Ad Hoc. I notice a lot of ad hoc in Silver which USACO Guide Silver does not cover. If this were to be made, I can handle adding problems to the section along with editorials (I have completed over 90% of all silver problems). I am happy to do this for the Guide!

**Comment by SansPapyrus683** [comment]
sure! feel free to make a pr when you're ready!
