### ISSUE TITLE
Contact Form Submission - Other (Silver )

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4061]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/
**Module**: Silver 
**Topic**: Other
**Message**: 
Hi ,
 I am new to this . Can you please help to understand the contest flow ? Can I bypass First contest and appear on Second contest ?

Thanks,
Renju.

**Comment by bqi343** [comment]
https://usaco.guide/general/usaco-faq?lang=cpp#q-how-do-i-participate-in-a-usaco-contest
