### ISSUE TITLE
Contact Form Submission - Minor Mistake (Intro to Bitwise Operators)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4062]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: Intro to Bitwise Operators
**Topic**: Minor Mistake
**Message**: 
The problem Lights off requires DP when this is introduced in gold (the solution proposed uses DP) (Lights off is a problem that is presented in Intro to Bitwise Operators, that is a silver module)

**Comment by SansPapyrus683** [comment]
should we put this in uh
additional practice for gold then
