### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Gold - Minimum Spanning Trees)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4067]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/mst?lang=java
**Module**: Gold - Minimum Spanning Trees
**Topic**: Request - Missing Section or Solution
**Message**: 
I don't think there is a solution to the COCI 2017-Sirni problem. It said to use to "Contact Us" feature to request a solution.
Thanks!

**Comment by SansPapyrus683** [comment]
but uh while you're waiting i suggest you look at the user solutions
