### ISSUE TITLE
Contact Form Submission - Suggestion (Silver - Binary Search)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4070]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/binary-search?lang=cpp
**Module**: Silver - Binary Search
**Topic**: Suggestion
**Message**: 
Unusual use of notation in quiz question 1. Big O and Big Omega shouldn't be conflated with "worst-case" and "best-case", respectively. Describing the best-case runtime as Omega(1) is correct but doesn't mean much. It would be better to use theta or big O notation.

**Comment by bqi343** [comment]
it makes sense to say that the runtime of binary search is both O(log N) and Omega(1).

**Comment by evanbanks** [comment]
Yea I agree with that part, I think it's weird to answer "what's the best-case runtime?" with Omega notation here. Omega is a not-necessarily-tight lower bound, so it doesn't actually say how fast it'll run. Saying binary search is O(1) in the best-case is a much more useful statement as that says its not slower than constant time. It's a nitpick but I think it makes more sense to see these answers all written using big O or preferably theta notation.

**Comment by bqi343** [comment]
I interpret "what's the best-case runtime?" to mean "give the best lower bound on the time complexity of the algorithm," in which case Omega notation is appropriate. GFG agrees with me, though it's by no means a reliable source: https://www.geeksforgeeks.org/worst-average-and-best-case-analysis-of-algorithms/. (If you have a better source, please share.)

**Comment by evanbanks** [comment]
I guess it's a difference of interpretations. I interpret "what's the best-case runtime?" as asking for the order of growth of the runtime when the algorithm is invoked on ideal (best-case) input. That order of growth can then be characterized using O/Ω/ϴ notations. I did some `ctrl+F`ing through CLRS and they seem to support this notion:

> We can also correctly say that insertion sort’s best-case running time is O(n), Ω(n), and ϴ(n), again with
ϴ(n) the most precise and therefore the most preferred. 

I think with either interpretation it would be most appropriate to use ϴ-notation as it implies that the bounds are tight.

**Comment by bqi343** [comment]
Which page / edition of CLRS is this?

**Comment by evanbanks** [comment]
Page 57 of 4ed. I did a brief search for "best-case" and found that but there may be more concrete definitions or examples in chapter 2/3.

**Comment by bqi343** [comment]
Oh, I was looking at the third edition and couldn't find it. Feel free to submit a PR changing this.
