### ISSUE TITLE
Contact Form Submission - Suggestion (sqrt decomposition)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4081]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-793-cow-at-large/solution
**Module**: sqrt decomposition
**Topic**: Suggestion
**Message**: 
https://usaco.guide/problems/usaco-793-cow-at-large/solution
in here, perhaps you could remove the alternate (fake) solution, ig it was forgotten or smth, thanks.

**Comment by bqi343** [comment]
I think it's fine to keep - it's worth noting that USACO test data is occasionally weak enough for fakesolves to receive full credit.
