### ISSUE TITLE
Atom, a text editor on the C++ version of "Running Code locally", sunset a year ago.

### ISSUE THREAD

**Issue by IDON-TEXIST** [cpinitiative/usaco-guide#4093]
[Sunset announcement](https://github.blog/2022-06-08-sunsetting-atom/)

It's probably not a good idea to recommend an IDE that hasn't seen maintenance or security updates for a year. We could remove it, or we could add a warning that it's no longer maintained.

**Comment by bqi343** [comment]
can remove it
