### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Bronze - Simulation)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4103]
Someone submitted the contact form!

**URL**: https://usaco.guide/bronze/simulation
**Module**: Bronze - Simulation
**Topic**: Request - Missing Section or Solution
**Message**: 
Trying to log into usaco contest system but receiving no email

**Comment by bqi343** [comment]
https://github.com/cpinitiative/usaco-guide/issues/2854#issuecomment-1162802123
