### ISSUE TITLE
Activity Color Scale

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4104]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: None
**Topic**: Website Bug
**Message**: 
In the activity tab, color scale 3 is darker than color scale 2 (in dark mode)

**Comment by bqi343** [comment]
yeah, it's weird how the ranking of the colors in light mode doesn't appear to match those in dark mode.

<img width="69" alt="Screenshot 2023-12-24 at 8 47 23 PM" src="https://github.com/cpinitiative/usaco-guide/assets/21228024/74e5397e-f641-4b37-b6a2-f53c400145ab">

<img width="1273" alt="Screenshot 2023-12-24 at 8 49 36 PM" src="https://github.com/cpinitiative/usaco-guide/assets/21228024/76f1d6e5-a650-4fbb-add1-96199eb398f1">

@thecodingwizard any suggestions?

**Comment by thecodingwizard** [comment]
Heatmap colors for both light mode and dark mode are defined here: https://github.com/cpinitiative/usaco-guide/blob/a9538861583db0d9592e0c548410372d641cf298/src/components/Dashboard/heatmap-styles.css#L9

Maybe we can just copy the Github heatmap colors?

**Comment by bqi343** [comment]
sure

**Comment by thecodingwizard** [comment]
Oh wait for their color scheme to make sense, I think we also need to copy the color from `.color-empty`. @devo1ution do you want to do this?

**Comment by devo1ution** [comment]
Yeah sure 👍🏻
