### ISSUE TITLE
Contact Form Submission - Minor Mistake (Gold - Point Update Range Sum)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4105]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/PURS?lang=cpp#problem-cses-1651
**Module**: Gold - Point Update Range Sum
**Topic**: Minor Mistake
**Message**: 
The link about PBDS for CPH is of page 51 but it actually starts from page 54

**Comment by bqi343** [comment]
The link is intended to take you to the start of the numbered subsection (4.5 in this case).
