### ISSUE TITLE
Contact Form Submission - Other (Tell my score)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4107]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/usaco-faq?lang=cpp
**Module**: Tell my score
**Topic**: Other
**Message**: 
How can I find my score on the USACO website? Also, where can I find out whether I have been promoted to the next division or not? I understand what the cutoff score is, but I cannot find my own score.

**Comment by bqi343** [comment]
If you go to http://www.usaco.org/index.php?page=dec23results you should see your result next to the contest you took. Example:

<img width="543" alt="Screenshot 2023-12-24 at 2 17 03 PM" src="https://github.com/cpinitiative/usaco-guide/assets/21228024/c0e2ed57-8874-49a2-951a-dd0ef9f60983">

You can view your division in account settings: http://www.usaco.org/index.php?page=editaccount
