### ISSUE TITLE
Contact Form Submission - Suggestion (Centroid Decomposition)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4110]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cses-2081-fixed-length-paths-ii/solution
**Module**: Centroid Decomposition
**Topic**: Suggestion
**Message**: 
The internal solution for CSES - Fixed-Length Paths II (the centroid decomp one), TLEs on cses judge

**Comment by bqi343** [comment]
you're right. perhaps the judges have gotten slower or tests have been added to this problem. I would suggest removing the binary indexed tree from the solution to remove a log factor.

**Comment by enfuego27826** [comment]
how is that possible, can you please explain (if there is a solution other than small-to-large merging using cd)

**Comment by bqi343** [comment]
I'm not sure what you mean by small-to-large merging using cd. The centroid decomposition solution in the module doesn't use small to large merging.

**Comment by enfuego27826** [comment]
okay sure, thanks
