### ISSUE TITLE
Sketchy bronze graph problems

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#412]
https://usaco.guide/bronze/intro-graphs/

- http://www.usaco.org/index.php?page=viewproblem2&cpid=965
- http://www.usaco.org/index.php?page=viewproblem2&cpid=1013

Both really should not be graphs problems...?

**Comment by caoash** [comment]
Swappity swap is?

At least silver is, so I guess bronze can be viewed as graph too

**Comment by thecodingwizard** [comment]
wait even silver swappity swap is a bit of a stretch to be a graphs problem... it's like math / permutation cycles (?) but not graphs....

**Comment by thecodingwizard** [comment]
ok i just removed livestock lineup and unstarred swapity swap 97c0acdb84bbbc7f0f35d3fae3568be3fcf7a750

**Comment by caoash** [comment]
permutation -> functional graph!
