### ISSUE TITLE
typos in string searching module

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4120]
Someone submitted the contact form!

**URL**: https://usaco.guide/adv/string-search#knuth-morris-pratt-algorithm
**Module**: Advanced - String Searching
**Topic**: Minor Mistake
**Message**: 
meaning that a the suffix
->
meaning that the suffix

**Comment by bqi343** [comment]
If there are many problems with a module, I would suggest creating a pull request to fix all of them rather than creating a separate issue for each problem.
