### ISSUE TITLE
Contact Form Submission - Unclear Explanation (Ad hoc )

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4122]
Someone submitted the contact form!

**URL**: https://usaco.guide/
**Module**: Ad hoc 
**Topic**: Unclear Explanation
**Message**: 
Hi for the question sleepy cow herding I am confused as the sample input could be 4,8,9 or 5,6,9 but you don’t explain those scenarios. This is where there is 1 already consecutive pair.

**Comment by bqi343** [comment]
You are expected to figure out the correct outputs for those inputs on your own. In general, the sample input will not cover all possible scenarios.
