### ISSUE TITLE
livestock lineup graphs bronze

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#413]
https://github.com/cpinitiative/usaco-guide/blob/master/content/2_Bronze/Intro_Graphs.mdx

```
        new Problem(
            'Bronze',
            'Livestock Lineup',
            '965',
            'Hard',
            true,
            ['path'],
            ''
        ),
```

todo:

- unstar it (?)
- write internal solution to explain the graphs solution ig (for when n = 1e5 or smth)

**Comment by bqi343** [comment]
closed by 900e88d (unless someone wants to add to explanation)
