### ISSUE TITLE
Contact Form Submission - Minor Mistake (Counting Liars Sol)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4134]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-1228-counting-liars/solution
**Module**: Counting Liars Sol
**Topic**: Minor Mistake
**Message**: 
the solution code is wrong: https://forum.usaco.guide/t/potentially-wrong-solution-on-usaco-guide/5322

**Comment by SansPapyrus683** [comment]
ah piss

**Comment by envyaims** [comment]
what the balls

**Comment by SansPapyrus683** [comment]
no i'm fixing this, i touched the sols last

**Comment by envyaims** [comment]
its literally just changing the all the greater and less than signs to geq and leq
