### ISSUE TITLE
USACO Monthlies Page

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#4136]
Minor things:
  - Can `div_to_probs` be sorted by id?
    - The division tables (https://usaco.guide/general/usaco-monthlies?lang=cpp) were originally supposed to keep track only of problems since 2015. But now that pre-2015 problems have been added the problems are out of order, which is weird.
    - "All (2015 - 24)" should be changed to "All (2011 - 24)" for divisions below plat, if we're keeping the pre-2015 problems.
  - `contest_to_points` for Gold and Platinum should be updated at some point.

_Originally posted by @bqi343 in https://github.com/cpinitiative/usaco-guide/issues/4126#issuecomment-1870574848_

**Comment by devo1ution** [comment]
Is there any specific reason for no pre-2015 problems (compatibility, format, etc.)? I'm fine with either option, keeping them or not :)

**Comment by bqi343** [comment]
Platinum started in 2015. Also, 2011-12 problems aren't submittable through the website. Fine to include 2012 and later.

**Comment by devo1ution** [comment]
Oh oops, I think we should just keep >= 2015 then so we have data for all four divisions 😅
