### ISSUE TITLE
USACO Plat Problems not included correctly in search

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#4137]
for some reason, it seems that the plat problems only are being listed as not appearing in any module.

(Gold)

<img width="306" alt="Screenshot 2023-12-27 at 2 25 43 PM" src="https://github.com/cpinitiative/usaco-guide/assets/21228024/d8e4c2e5-c92f-4b2a-ad51-98d66ae7e772">

(Plat)

<img width="305" alt="Screenshot 2023-12-27 at 2 26 37 PM" src="https://github.com/cpinitiative/usaco-guide/assets/21228024/d5636857-3e73-4c0c-8792-fbf2340fdbfc">

_Originally posted by @bqi343 in https://github.com/cpinitiative/usaco-guide/issues/4027#issuecomment-1870570967_

**Comment by bqi343** [comment]
Not limited to the most recent Plat problems:

<img width="283" alt="Screenshot 2023-12-27 at 3 19 38 PM" src="https://github.com/cpinitiative/usaco-guide/assets/21228024/7fbc4ac7-e169-4fa5-bb71-80e221af2055">

**Comment by thecodingwizard** [comment]
I think it's because some problems are tagged `Plat` while others are tagged `Platinum`. Personally it seems to make more sense for all problems to be tagged `Platinum`?

**Comment by bqi343** [comment]
sure
