### ISSUE TITLE
Improve problems search dark mode?

### ISSUE THREAD

**Issue by danielzsh** [cpinitiative/usaco-guide#4152]
Tracked in #86

# Search Bar
## Light mode:
<img width="938" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/65467530/b6687e66-7ee3-40b1-b3ff-0d6c0ff96aa3">

## Dark mode:
<img width="1013" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/65467530/18db109d-5788-45a8-ab57-256321f7d93d">

(significant decrease in contrast)

# Bottom navigation 
## Light mode:
<img width="587" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/65467530/da8f6562-f246-450c-b016-3cf5cb3cf570">

## Dark mode:
<img width="591" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/65467530/3d6268af-a6e7-4c68-9900-a22067b391ba">

(should probably be different? esp since the current dark mode theme uses a different shade of blue as well; the hits per page dropdown should definitely be recolored in dark mode too)

Anyone else agree/have suggestions on how to recolor?

**Comment by SansPapyrus683** [comment]
idk man it looks fine to me lol
change it if you want ig

**Comment by thecodingwizard** [comment]
I agree a lot about the problems page (including dark mode / mobile support / etc) can be improved...

**Comment by thecodingwizard** [comment]
There's a long-standing issue here: https://github.com/cpinitiative/usaco-guide/issues/86 that describes a bunch of the issues / possible features we may want to implement. @devo1ution if you're interested, do you want me to assign you to that issue? (You can work on whatever you think makes sense -- don't feel compelled to follow our proposed plan exactly)

**Comment by devo1ution** [comment]
sure tysm 🙏🏻
