### ISSUE TITLE
Contact Form Submission - Other (Problem Solution - Flight Routes Check (ID: cses-1682))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4156]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cses-1682/user-solutions
**Module**: Problem Solution - Flight Routes Check (ID: cses-1682)
**Topic**: Other
**Message**: 
One of the java solutions happens to be in cpp, specifically the one by, Asad Khan.

**Comment by bqi343** [comment]
marked private
