### ISSUE TITLE
Improvement in Java Queue Example: Replace queue.add with queue.offer

### ISSUE THREAD

**Issue by Rian354** [cpinitiative/usaco-guide#4159]
#### Explanation:
The Java example should use queue.offer instead of queue.add. The Queue.add method throws an IllegalStateException, while queue.offer is specifically designed for queues, providing a more appropriate behavior by returning true or false without an exception.

Initial:

``` java
Queue<Integer> q = new LinkedList<Integer>();
q.add(1);                      // [1]
q.add(3);                      // [3, 1]
q.add(4);                      // [4, 3, 1]
q.poll();                      // [4, 3]
System.out.println(q.peek());  // 3
```

Modified:
``` java
Queue<Integer> q = new LinkedList<Integer>();
q.offer(1);                      // [1]
q.offer(3);                      // [3, 1]
q.offer(4);                      // [4, 3, 1]
q.poll();                      // [4, 3]
System.out.println(q.peek());  // 3
```

**Comment by bqi343** [comment]
> boolean offer([E](https://docs.oracle.com/javase/8/docs/api/java/util/Queue.html) e)
Inserts the specified element into this queue if it is possible to do so immediately without violating capacity restrictions. When using a capacity-restricted queue, this method is generally preferable to [add(E)](https://docs.oracle.com/javase/8/docs/api/java/util/Queue.html#add-E-), which can fail to insert an element only by throwing an exception.

But linked list isn't capacity-restricted, so it doesn't make a difference.

**Comment by Rian354** [comment]
Well in this context it doesn't make a difference due to the fact that it is a LinkedList implementation however for learners working with non-dynamic queue implementations, it's important to emphasize the contextual use of add and offer. Using offer over add works with other queue formats such as ArrayBlockingQueue or LinkedBlockingQueue. Given that usaco.guide is a "One Stop Shop" (https://usaco.guide/general/using-this-guide?lang=java#about-this-guide) for Bronze to Gold contestants, educating learners about good coding habits such as preferring offer over add can lead to a deeper understanding of good coding practices. This way learners are prepared to deal with the countless unique scenarios that they could deal with in competitive programming and real world software engineering/development.

**Comment by bqi343** [comment]
I can’t think of any time where the queues you mentioned would be useful in competitive programming.

**Comment by Rian354** [comment]
For comp there is Parallel Task processing and Concurrency control, they aren't commonly used though. And in the real world/software engineering there's task processing (e.g token-bucket algorithm), Event Handling, Job Scheduling for asynchronous tasks, Data transfer in between threads, thread pooling, and message passing. A good example of this in the real world would be Apache Kafka or RabbitMQ which use both Asynchronous message passing which is more or less involves the principals of blocking queues. These systems show the practical importance of blocking queues in real-world and scalable solutions. While blocking queues might not be popular in competitive programming, their significance is apparent when dealing with concurrent and distributed systems, making them valuable tools for a programmer. And in the end, they aren't too useful in comp however in the real world, after usaco, they are quite useful, because most likely, if you're doing competitive programming, you're looking to become a software engineer or study computer science in college. Even small habits like promoting the use of offer over add can go a long way.
