### ISSUE TITLE
CSES Flight Discount Alternative Sol

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#416]
https://usaco.guide/solutions/cses-1195

> there is also a dp solution, where dist[i][j] is min cost with j state, j is 0 if coupon not used yet, 1 if used.

**Comment by qpwoeirut** [comment]
I've written the described solution. Should I add it on to the existing solution file?

My solution is at https://cses.fi/paste/1c10d6f5f0a2634513cd15/. If you want, I can incorporate the template from the Code Conventions module for consistency.

**Comment by thecodingwizard** [comment]
please do, thanks!
