### ISSUE TITLE
Contact Form Submission - Mistake (Solution: CSES - Sum of Divisors)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4175]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cses-1082-sum-of-divisors/solution
**Module**: Solution: CSES - Sum of Divisors
**Topic**: Mistake
**Message**: 
> But calculating this with brute force yields an 
$\mathcal{O}(n \sqrt{n})$

This should be O(n) not O(n*sqrt(n))

**Comment by SansPapyrus683** [comment]
goddamit
