### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Gold - Digit DP)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4177]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/digit-dp?lang=cpp
**Module**: Gold - Digit DP
**Topic**: Request - Missing Section or Solution
**Message**: 
Could you make a tutorial for this problem (https://codeforces.com/gym/100886/problem/G)? There is no tutorial in CF, and I find this problem should be normal instead of easy.

**Comment by SansPapyrus683** [comment]
moved to the tasks page
