### ISSUE TITLE
Export editor changes to something

### ISSUE THREAD

**Issue by IDON-TEXIST** [cpinitiative/usaco-guide#4184]
It'd be nice if there was a more convenient way to make a PR from the USACO Guide editor. The easiest way to do this might be to generate a .patch file with `git format-patch`.

**Comment by thecodingwizard** [comment]
It's theoretically even possible to automatically open a PR on GitHub straight from the USACO editor page (using a nextjs serverless function or something). The `.patch` file is a neat idea!

**Comment by danielzsh** [comment]
I think I can try to work on this? I think we should be set if we can translate the ruby [here](https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-login-with-github-button-with-a-github-app#prerequisites) into javascript (not sure though, haven't looked too much into it yet)
