### ISSUE TITLE
Editor always warns "Draft 2020-12 schemas are not yet fully supported. (768)" in JSON files

### ISSUE THREAD

**Issue by IDON-TEXIST** [cpinitiative/usaco-guide#4200]
Go to [the editor](https://usaco.guide/editor) and open any module.problems.json. The warning will be on the first character.

**Comment by SansPapyrus683** [comment]
a part of me feels like that error's beyond our control, in some wack dependency, but it probably isn't

**Comment by IDON-TEXIST** [comment]
[It looks like the warning is correct at face value.](https://github.com/search?q=repo%3Acpinitiative%2Fusaco-guide+2020-12&type=code) I don't see any way to disable it, so you might be right, unless downgrading the JSON schema happens to just work.

**Comment by bqi343** [comment]
so if the warning is correct, is there a need to change anything?

**Comment by IDON-TEXIST** [comment]
No. It’s a minor annoyance. But carrying “the warning is correct” to “there’s no reason to remove it” isn’t really true because there’s nothing someone using the editor can do about it.

**Comment by SansPapyrus683** [comment]
what if we changed the schema to something earlier
idt our json uses any funny features

**Comment by IDON-TEXIST** [comment]
Let's try it and see what happens.

**Comment by thecodingwizard** [comment]
Possibly related: https://github.com/microsoft/monaco-editor/issues/3160

**Comment by SansPapyrus683** [comment]
idk man it's been months without any activity on that thing
