### ISSUE TITLE
Contact Form Submission - Mistake (Delegation-Platinum)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4203]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: Delegation-Platinum
**Topic**: Mistake
**Message**: 
incorrect output for this input case:
4
1 2
1 3
1 4

**Comment by envyaims** [comment]
doomed

**Comment by envyaims** [comment]
nice edge case on root, ben
