### ISSUE TITLE
Contact Form Submission - Mistake (Solution: USACO Platinum 2020 February - Delegation)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4205]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/plat-delegation/solution
**Module**: Solution: USACO Platinum 2020 February - Delegation
**Topic**: Mistake
**Message**: 
testing contact form labels

**Comment by bqi343** [comment]
hm the labels aren't being added. will try redeploying

**Comment by bqi343** [comment]
@thecodingwizard Are you able to redeploy the contact form function? I tried following the instructions at https://github.com/cpinitiative/usaco-guide/tree/master/src/functions but I got some error about node v12 being out of date, even though `node --version` shows `v20.6.1`.

**Comment by thecodingwizard** [comment]
I think a recent PR broke deployment of functions. I made a PR that fixes this and updates to use node 18 here: https://github.com/cpinitiative/usaco-guide/pull/4225

It may be a good idea to set your local node version to 18 before deploying firebase (if you use nvm or n or some other node version manager, you can switch between node versions more easily).

**Comment by thecodingwizard** [comment]
#4226 -- seems like it works now!
