### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Solution: USACO Bronze 2018 January - Blocked Billboard II)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4208]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-783-blocked-billboard-ii/solution#case-6
**Module**: Solution: USACO Bronze 2018 January - Blocked Billboard II
**Topic**: Request - Missing Section or Solution
**Message**: 
Hello, I don't now where my own solution has gone wrong, it passed all test cases expect for #4, can I get some help?"

#include <bits/stdc++.h>
using namespace std;
int main()
{
    ios::sync_with_stdio(0);
    cin.tie(0);
    int ax1, ay1, ax2, ay2;
    int bx1, by1, bx2, by2;
    cin >> ax1 >> ay1 >> ax2 >> ay2;
    cin >> bx1 >> by1 >> bx2 >> by2;

    int width_a, length_a;
    int width_b, length_b;
    width_a = ax2 - ax1;
    width_b = bx2 - bx1;
    length_a = ay2 - ay1;
    length_b = ay2 - ay1;
    int area_a = width_a*length_a;
    
    int width_inter = max(0, min(ax2,bx2)-max(ax1, bx1));
    int length_inter = max(0, min(ay2, by2)-max(ay1, by1));
    int area_inter = width_inter*length_inter;
    if(width_inter == width_a||length_inter == length_a)
        cout<<area_a-area_inter;
    else
        cout<<area_a;

    return 0;
}

**Comment by bqi343** [comment]
https://usaco.guide/general/usaco-faq#q-whats-wrong-with-my-code
