### ISSUE TITLE
Contact Form Submission - Mistake (Solution: USACO Bronze 2018 January - Blocked Billboard II)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4245]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-783-blocked-billboard-ii/solution
**Module**: Solution: USACO Bronze 2018 January - Blocked Billboard II
**Topic**: Mistake
**Message**: 
The code for solution 1 is incorrect and produces the wrong results.

**Comment by SansPapyrus683** [comment]
unable to repoduce
