### ISSUE TITLE
Contact Form Submission - Mistake (Solution: COCI 2016 - Burza)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4249]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/coci-2016burza/solution
**Module**: Solution: COCI 2016 - Burza
**Topic**: Mistake
**Message**: 
K<=20 rather than N<=20

**Comment by SansPapyrus683** [comment]
i'm p sure that's intended

**Comment by bqi343** [comment]
no, it should be K<20

**Comment by SansPapyrus683** [comment]
fixed in next pr

**Comment by bqi343** [comment]
can you link the PR so that this issue is closed once the PR is merged?
