### ISSUE TITLE
Contact Form Submission - Other (USACO 2016 February Contest, Bronze Problem 3. Load Balancing)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4253]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: USACO 2016 February Contest, Bronze Problem 3. Load Balancing
**Topic**: Other
**Message**: 
Hi, so my code has passed all test cases except for test case 7, on which I got "Runtime error or memory limit exceeded". But when I went to look at the test cases, #8, 9 and 10 were all bigger than #7, but my code passed on all 3. Is there a reason why this is happening?

**Comment by SansPapyrus683** [comment]
perhaps this is a question for https://forum.usaco.guide/
