### ISSUE TITLE
Contact Form Submission - Unclear Explanation (Solution: CSES - Police Chase)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4278]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cses-1695-police-chase/solution
**Module**: Solution: CSES - Police Chase
**Topic**: Unclear Explanation
**Message**: 
Please, tell me idea of this task and why this idea works...

**Comment by bqi343** [comment]
Yeah, an explanation should be added. In short, it's the Min-Cut Max-Flow Theorem.

**Comment by Ani10-prog** [comment]
> Yeah, an explanation should be added. In short, it's the Min-Cut Max-Flow Theorem.

can you explain min-cut max-flow theorem? 
why this idea works?

**Comment by bqi343** [comment]
The solution is in CPH: https://usaco.guide/CPH.pdf

**Comment by Ani10-prog** [comment]
> The solution is in CPH: https://usaco.guide/CPH.pdf

please tell me, why and how 
this idea works

**Comment by SansPapyrus683** [comment]
my guy it's in the book

**Comment by Ani10-prog** [comment]
> my guy it's in the book

can you tell me in brief why min-cut and max-flow is equal?

**Comment by SansPapyrus683** [comment]
[google it](https://en.wikipedia.org/wiki/Max-flow_min-cut_theorem)

**Comment by SansPapyrus683** [comment]
moved to #4165
