### ISSUE TITLE
Contact Form Submission - Mistake (wrong class)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4282]
Someone submitted the contact form!

**URL**: https://usaco.guide/groups/9HIFp2pBRARWrbD4rSJB/post/0VEKpgdhPSuvirE66Uxe
**Module**: wrong class
**Topic**: Mistake
**Message**: 
Hello, i joined Spring 2024 USACO class, but by mistake i has choosen bronze class, i need to join silver one, please can we solve it?

**Comment by bqi343** [comment]
https://github.com/cpinitiative/usaco-guide/issues/4280#issuecomment-1925480897
