### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by dongliu0426** [cpinitiative/usaco-guide#429]
![Screen Shot 2020-11-16 at 6 18 09 PM](https://user-images.githubusercontent.com/59348162/99337937-25a85300-2838-11eb-9407-168965b74390.png)

**Comment by MrinallU** [comment]
@dongliu0426 Oh, I haven't coded that up yet, as I have been busy developing some other features for the site so I'll be sure to work on that after I finish the other tasks. Seems to be a trivial task so I'll get to it as fast I can!
