### ISSUE TITLE
Logo in dark mode forum

### ISSUE THREAD

**Issue by dongliu0426** [cpinitiative/usaco-guide#430]
![Screen Shot 2020-11-16 at 8 04 51 PM](https://user-images.githubusercontent.com/59348162/99345396-0d8c0000-2847-11eb-9803-c34172b50008.png)

**Comment by bqi343** [comment]
@thecodingwizard ?

https://meta.discourse.org/t/automatic-dark-mode-color-scheme-switching/161593

**Comment by thecodingwizard** [comment]
yep this is supported by Discourse. We just need a dark mode logo XD

**Comment by thecodingwizard** [comment]
![image](https://user-images.githubusercontent.com/7865976/100395671-9f89ca80-2ff6-11eb-99d4-da04d46f33f8.png)

aight I made one real quick
