### ISSUE TITLE
Contact Form Submission - Suggestion (General - Using This Guide)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4305]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/using-this-guide?lang=py
**Module**: General - Using This Guide
**Topic**: Suggestion
**Message**: 
Hello. I have never coded before but believe I would be good at it. To begin learning coding, what resources would you guys recommend that could 100% allow me to enroll in the competition next year? Thank you.

**Comment by bqi343** [comment]
See the Getting Started section.
