### ISSUE TITLE
Contact Form Submission - Website Bug (Solution: USACO Silver 2019 January - Grass Planting)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4309]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-894-grass-planting/solution
**Module**: Solution: USACO Silver 2019 January - Grass Planting
**Topic**: Website Bug
**Message**: 
When I click to view problem statement, it says "To view the content of this site, please visit it using a hostname (e.g., google.com) rather than just an IP address."

**Comment by bqi343** [comment]
The USACO website is being updated, please wait. Will closed once resolved.
