### ISSUE TITLE
Prompt users for problem feedback

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#431]
When someone marks a problem as solved, we should prompt them to give feedback:

- How difficult they found the problem
- Their solution code
- Solution notes
- Tags (?)
- How good was the problem

(Also, option to suggest a problem)

**Comment by MrinallU** [comment]
@thecodingwizard So essentially have a feedback modal which then sends to whatever email that you guys use for feedback correct?

**Comment by thecodingwizard** [comment]
hmm. ideally it should hook up to firebase or github issues or something...

**Comment by MrinallU** [comment]
Ohhh, that makes things a bit harder to be honest here.

**Comment by MrinallU** [comment]
Unless, there is some kind of feedback field in firebase for each problem.

**Comment by thecodingwizard** [comment]
there isn't. we'll have to think about how to structure it in firebase....

**Comment by thecodingwizard** [comment]
maybe implement the problem suggestion first? that can be hooked up to github issue API which should be easier.

**Comment by MrinallU** [comment]
Yeah sure I'll get to it as soon as I can.

**Comment by MrinallU** [comment]
@thecodingwizard It might take a little longer because I'm probably going to do much more CP training to make it to usaco gold for the next month or so 😅.

**Comment by thecodingwizard** [comment]
no worries. good luck!! :)

**Comment by MrinallU** [comment]
@thecodingwizard Thanks, by the way have you guys ever thought about making lectures or walkthroughs with a youtube channel? I'm fairly sure it will boost your popularity and spread the word about all of the resources CPI provides.

**Comment by thecodingwizard** [comment]
no, it seems too hard to grow a youtube channel, and video lectures already exist for a lot of CP topics...

**Comment by MrinallU** [comment]
@thecodingwizard That's does seem to be the case, plus many other people are creating some nice CP content on youtube so we probably are better off focusing on the live classes.

**Comment by Hanaffi** [comment]
@thecodingwizard Can you assign it to me?

**Comment by MrinallU** [comment]
I'm working on this but if you can get it done faster then go at it!

**Comment by thecodingwizard** [comment]
Sorry @Hanaffi, I think @MrinallU is working on it. Feel free to pick another feature to work on though. Thanks! :)

**Comment by MrinallU** [comment]
@thecodingwizard So I have the modal implemented 🥳 but now we need to figure out what happens when you submit the feedback.

**Comment by MrinallU** [comment]
@thecodingwizard Also when submitted I don't have access to firebase so you may need to do that, also if we hooked it up to github issues we would have way too many issues just because the magnitude of problems and users is far too great.

**Comment by thecodingwizard** [comment]
@MrinallU just connect the project to your own firebase project and lmk which settings / rules you need me to configure?

**Comment by MrinallU** [comment]
@thecodingwizard So like when submitting the form like where would I put the feedback? Like with each user's data with a collection called problem feedback.

**Comment by thecodingwizard** [comment]
no -- perhaps make a new root-level collection called problem_feedback or something, where each document within the collection will store info such as which user submitted it, etc. (and then somehow build an admin interface to view the suggested problems)

**Comment by MrinallU** [comment]
@thecodingwizard This may take a few weeks to be honest.

**Comment by MrinallU** [comment]
@thecodingwizard For the admin interface https://retool.com/use-case/firestore-admin-interface would this work?

**Comment by thecodingwizard** [comment]
It's probably better to just build one out ourselves? It would only need to support viewing the list of problem feedbacks and marking problem feedbacks as "done" for now.

**Comment by MrinallU** [comment]
Alright, I will probably have to make a seperate app for the admin interface though, so they can search through the problems and filter by done.

**Comment by MrinallU** [comment]
@thecodingwizard The Ui for the admin problem feedback doesn't need to be fancy right?

**Comment by thecodingwizard** [comment]
Yeah as long as it works (for now) :P

Styling can be relatively easily added later anyway

**Comment by MrinallU** [comment]
@thecodingwizard So I have everything ready.

**Comment by MrinallU** [comment]
The only thing you need to do on your end  is make a problemFeedback (It needs to have this as it is in the code) collection, and make it in the rules so users can write to that collection in the database.

**Comment by MrinallU** [comment]
@thecodingwizard From there you should be able to see the modal  submission values show up in the database.

**Comment by MrinallU** [comment]
@thecodingwizard Right now I have it so it is connected to my database, after you add the new problemFeedback collection you  should test it with the official guide database (change it back in the firebase context file). Please let me know if there are any problems with the feedback system.

**Comment by MrinallU** [comment]
@thecodingwizard I'll make a PR.

**Comment by bqi343** [comment]
- toggle private / public setting for solution code

**Comment by MrinallU** [comment]
@bqi343 I think this should be a different issue.

**Comment by thecodingwizard** [comment]
closed by #515
