### ISSUE TITLE
Contact Form Submission - Other (CPI Beginner Class)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4311]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard
**Module**: CPI Beginner Class
**Topic**: Other
**Message**: 
I enrolled my son Vyom Aggarwal for the CPI Beginner Class. However when he clicked on the link at the time of the class, it showed him the error message ""Error: The given key is no longer valid. "His email ID is aggarw.vyom@gmail.comBecause of this he missed his class. Can you please fix this for him so that he can attend the classes. Also is there a way for him to attend a make up class?
Thanks and Regards
Kajal Aggarwal424 422 5421

**Comment by bqi343** [comment]
> If you have any questions about [CPI classes](https://joincpi.org/classes), please email [classes@joincpi.org](mailto:classes@joincpi.org) rather than submitting this form.
