### ISSUE TITLE
Contact Form Submission - Website Bug (Solution: USACO Bronze 2016 February - Milk Pails)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4312]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-615-milk-pails/solution
**Module**: Solution: USACO Bronze 2016 February - Milk Pails
**Topic**: Website Bug
**Message**: 
problem link not working it is telling To view the content of this site, please visit it using a hostname (e.g., google.com) rather than just an IP address.

**Comment by SansPapyrus683** [comment]
uh can i have steps to reproduce

**Comment by bqi343** [comment]
https://usaco.org/ should be working now
