### ISSUE TITLE
Contact Form Submission - Other (Silver Class Spring 2024)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4318]
Someone submitted the contact form!

**URL**: https://usaco.guide/groups/SblK1O4syWZOIbNBQ09m/leaderboard
**Module**: Silver Class Spring 2024
**Topic**: Other
**Message**: 
The link to the recorded video is wrong. It was from 2022 class. Could you correct it so we can see the past two Zoom recordings? Thanks.

**Comment by bqi343** [comment]
> If you have any questions about [CPI classes](https://joincpi.org/classes), please email [classes@joincpi.org](mailto:classes@joincpi.org) rather than submitting this form.
