### ISSUE TITLE
Contact Form Submission - Other (General - Resources: Learning to Code)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4319]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/resources-learning-to-code?lang=cpp
**Module**: General - Resources: Learning to Code
**Topic**: Other
**Message**: 
Hello, 

I have a question about learning the syntax for CPP. I tried last year, but realized I didn't have enough time, so I want to do it again this year. Last year, I purchased the subscription for Codecademy which was pretty expensive and I'm not sure if it is really even better than the other options. Would completing CPP and LCPP be sufficient to make it to USACO silver? This is  a subjective question, but roughly how long in hours will it take to complete these 2?

Thanks!

**Comment by SansPapyrus683** [comment]
Not sure what you mean by LCPP, but given the state of powercreep these days, I don't think just learning the syntax and basic algorithms is enough; you would have to do a fair bit of practice as well.
