### ISSUE TITLE
Inaccurate Documentation On: More On Prefix Sums?

### ISSUE THREAD

**Issue by Jasgeet** [cpinitiative/usaco-guide#4342]
Hello Everyone,
I feel that the formulas mentioned in [Solution - Max Subarray Sum](https://usaco.guide/silver/more-prefix-sums?lang=cpp#solution---max-subarray-sum) are inaccurate.

1. $a_i \dots a_{j-1}$, where $i\leq j$
***Should be:*** $a_i \dots a_{j-1}$, where $i\leq j - 1$
***Reason:*** for a single element subarray $a_i$, $i\leq j$ doesn't make sense 

2. $0 \leq i \leq j \leq N$
***Should be:*** $1 \leq i +1\leq j \leq N$
***Reason:*** $0 \leq i < N$ and  $0 \leq j - 1 < N$
*Array is 0-indexed and prefix array is 1-indexed, hence range of array is (0, N - 1) and range of prefix array is (0, N)*

3. $$p[j]-\min_{i\leq j}{p[i]}$$
***Should be:*** $$p[j]-\min_{0\leq i\leq j - 1}{p[i]}$$
***Reason:*** $i$ is always lower than $j$ in prefix array.

Apologies if my explanation is confusing, but I definitely feel that this section needs some updates.

Thanks

**Comment by envyaims** [comment]
1. why doesn't a single element subarray make sense?
2. doesnt really matter imo. if i = j then the subarray is from the range of [i+1, i] which is invalid, so the sum is defaultly 0.
3. ^^

**Comment by bqi343** [comment]
>  but imo it doesn't really matter,

It does matter for the problem that's linked since it explicitly asks about *nonempty* subarrays

**Comment by bqi343** [comment]
simply changing $i\le j$ to $i<j$ should fix all the issues
