### ISSUE TITLE
Contact Form Submission - Mistake (Problem Solution - Censoring (ID: usaco-526))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4346]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-526/user-solutions
**Module**: Problem Solution - Censoring (ID: usaco-526)
**Topic**: Mistake
**Message**: 
Pasha Khoshkebari's code is incorrect

**Comment by SansPapyrus683** [comment]
:skull: who here has access to the db?

**Comment by envyaims** [comment]
looks pretty right to me 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄

**Comment by SansPapyrus683** [comment]
envy idk what you're on bc it literally doesn't even do the io correctly

**Comment by bqi343** [comment]
marked as private
