### ISSUE TITLE
update tailwind css to 2.0

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#435]
tailwind css 2.0 is pretty neat :heart:

Unfortunately it breaks like half of our website :/

**Comment by MrinallU** [comment]
@thecodingwizard Just curious how does it break the site, like are the components not compatible with some other stuff?

**Comment by thecodingwizard** [comment]
yeah, some classes changed + twin.macro isn't supported (but we should get rid of that) + some colors changed + some text sizes changed...

**Comment by thecodingwizard** [comment]
also, thanks @Laphatize for helping! :)

**Comment by thecodingwizard** [comment]
twin.macro should support tw2 now (but hopefully we migrate away from it at some point)
