### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Problem Solution - Hot & Cold (ID: bts-hotcold))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4351]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/bts-hotcold/user-solutions
**Module**: Problem Solution - Hot & Cold (ID: bts-hotcold)
**Topic**: Request - Missing Section or Solution
**Message**: 
In the site (https://dmoj.ca/problem/bts17p7/editorial), there isn't any detailed editorial or model code. So can anyone share his/her model code and editorial.

**Comment by SansPapyrus683** [comment]
i mean that comment seems good enough but i suppose i'll add it

**Comment by MisterReaper2008** [comment]
When will you add?

**Comment by SansPapyrus683** [comment]
it's being tracked in #4165, trust me we'll add it soon:tm:
