### ISSUE TITLE
Recommended problem on Silver Prefix Sums is in wrong category?

### ISSUE THREAD

**Issue by andreionoie** [cpinitiative/usaco-guide#4352]
The CodeForces problem "Nusret Gokce" recommended on Silver page [More on Prefix Sums](https://usaco.guide/silver/more-prefix-sums#problem-cf-104114N) has a greedy solution, or one with a priority queue. These seem unrelated to the topic at hand, unless there is actually a solution for this problem using pfx sums? If there is one, then maybe we need an Internal Solution since the official editorial doesn't mention it.

**Comment by SansPapyrus683** [comment]
*runs git blame*

@envyaims this is your problem

**Comment by envyaims** [comment]
Hi,

do you have a priority queue solution? My solution does not use any fancy algorithms / ds. I think the solution is pretty reminiscent to max subarray sums problem, which is why I put it there.

My solution:
```c++
int main(){
	cin.tie(0) -> sync_with_stdio(0);
	ll n, m; cin >> n >> m;
	vector<ll> a(n);
	for(ll& i: a) cin >> i;
	vector<ll> mn(n+1);
	for(int i = n-1; i >= 0; i--){
		mn[i] = max(a[i], mn[i+1]-m);
	}
	vector<ll> ans(n);
	ans[0] = mn[0];
	for(int i = 1; i < n; i++){
		ans[i] = max(ans[i-1]-m, mn[i]);
	}
	for(ll i: ans) cout << i << " ";
}
```

**Comment by andreionoie** [comment]
I see, though personally when I was reading the editorial it didn't click with me that it's a form of prefix max, as the solution implied updating a[i] inline so it seemed more like a greedy solution. So skill issue on my part I guess, though I found the problems on the previous page "Introduction to Prefix Sums" easier to approach than this one.
