### ISSUE TITLE
Warning EVERYWHERE

### ISSUE THREAD

**Issue by Pramad712** [cpinitiative/usaco-guide#4363]
Why does every module have a warning in it? Even stranger is that the additional practice modules don't ...

**Comment by SansPapyrus683** [comment]
care to elaborate on what you mean by that?

**Comment by Pramad712** [comment]
<img width="293" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/77818951/7a6900ed-d3d1-4731-9346-837220bbff6b">
<img width="232" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/77818951/cb04e0eb-6c76-4223-93ed-138733f5fecf">
<img width="156" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/77818951/3f838109-fa20-4ff9-8ffb-df9dc5b25907">
<img width="161" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/77818951/00eaff9d-4fa2-45b2-8b86-045863abe110">
Only some modules in advanced though:
<img width="143" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/77818951/31b92284-56c9-4011-a47e-e28a70cf773d">

**Comment by bqi343** [comment]
@danielzsh looks like this was caused by #4325, can you take a look?
