### ISSUE TITLE
Contact Form Submission - Mistake (Platinum - Geometry Primitives)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4366]
Someone submitted the contact form!

**URL**: https://usaco.guide/plat/geo-pri?lang=cpp
**Module**: Platinum - Geometry Primitives
**Topic**: Mistake
**Message**: 
The implementation of the Point's location relative to polygon is wrong, it gives WA on CSES. The mistake is in the checking the point to be boundary.

**Comment by SansPapyrus683** [comment]
@brebenelmihnea

**Comment by bqi343** [comment]
@brebenelmihnea any update on this?

also, this code looks somewhat longer than it needs to be (e.g., compare with https://github.com/bqi343/cp-notebook/blob/08e3d0d722584442bd38280251d5e65f7ac61612/Implementations/content/geometry%20(13)/Polygons/InPolygon.h#L5)

**Comment by brebenelmihnea** [comment]
@bqi343  the polygon is not convex

**Comment by brebenelmihnea** [comment]
https://cses.fi/problemset/result/9602931/

<img width="504" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/59292725/df1f5444-5d12-4cd1-8e18-ba0f66d9be2e">
