### ISSUE TITLE
MooBuzz BinSearch Sol

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#437]
https://usaco.guide/silver/binary-search-ans

> + Internal binary search solution for moobuzz

tbh I'm not sure why anyone would do this with binary search

**Comment by thecodingwizard** [comment]
should we write an internal sol, or should we just remove this problem (given that we have so many other binary search problems)?

**Comment by bqi343** [comment]
Removed in 97b5316.
