### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Advanced - Offline Deletion)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4383]
Someone submitted the contact form!

**URL**: https://usaco.guide/adv/offline-del
**Module**: Advanced - Offline Deletion
**Topic**: Request - Missing Section or Solution
**Message**: 
Add this problem, which is a Time Series Tree on knapsack instead of DSU.

https://codeforces.com/contest/601/problem/E

**Comment by SansPapyrus683** [comment]
moved to https://github.com/cpinitiative/usaco-guide/discussions/3046#discussioncomment-8792299
