### ISSUE TITLE
Contact Form Submission - Mistake (Solution: CSES - Maximum Building I)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4384]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cses-1147-maximum-building-i/solution
**Module**: Solution: CSES - Maximum Building I
**Topic**: Mistake
**Message**: 
https://usaco.guide/problems/lc-max-histogram-area/solution this link is not working

**Comment by bqi343** [comment]
why was this closed? it needs to be fixed

**Comment by SansPapyrus683** [comment]
oops lmao
