### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Problem Solution - Stamp Painting (ID: usaco-791))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4390]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-791/user-solutions
**Module**: Problem Solution - Stamp Painting (ID: usaco-791)
**Topic**: Request - Missing Section or Solution
**Message**: 
Actually, the problem can be solved using deque (instead of Segment Tree which isn't a Gold-DS though). It would be nice if you present this method of deque in the solution page, as Segment Tree would be kind-of over-kill and bit-lot heavy. 

Like, in the deque, we keep the values of last (k-1) dp values (as that's what we need) along with their sum. When we move to (j+1) position from j position, we add dp[j] to the front of the deque, and remove the last-most element of the deque (and of-course, we update the sum also). 

Here is the code (C++):

#include <iostream>
#include <vector>
#include <queue>
#include <cstring>
#include <map>
#include <climits>
#include <cmath>
#include <algorithm>
#include <stack>
using namespace std;

#define speedup ios_base::sync_with_stdio(false); cin.tie(nullptr); cout.tie(nullptr);
#define ll long long

const ll MOD = 1e9+7;

void setIO(string s){
    freopen((s+".in").c_str(), "r", stdin);
    freopen((s+".out").c_str(), "w", stdout);
}

template <typename T>
T modpow(T base, T exp, T modulus) {
    base %= modulus;
    T result = 1;
    while (exp > 0) {
        if (exp & 1) result = (result * base) % modulus;
        base = (base * base) % modulus;
        exp >>= 1;
    }
    return result;
}

int main() {
    speedup
    setIO("spainting");
    int n, m, k; cin >> n >> m >> k;
    vector<ll> dp(n);
    deque<ll> dq;
    ll cur = 0;
    for (int i = 0; i < k-1; i++){
        dp[i] = modpow((ll)m, (ll)(i+1), (ll)MOD);
        dq.push_front(dp[i]);
        cur = (cur+dp[i])%MOD;
    }
    for (int i = k-1; i < n; i++){
        dp[i] = ((m-1)*cur)%MOD;
        dq.push_front(dp[i]);
        cur -= dq.back(); dq.pop_back();
        cur += MOD; cur %= MOD;
        cur += dp[i]; cur %= MOD;
    }
    cout << (MOD+modpow((ll)m, (ll)n, (ll)MOD)-dp[n-1])%MOD << endl;
    return 0;
}

**Comment by bqi343** [comment]
this is similar to the official analysis
