### ISSUE TITLE
Contact Form Submission - Mistake (Platinum - Centroid Decomposition)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4398]
Someone submitted the contact form!

**URL**: https://usaco.guide/plat/centroid
**Module**: Platinum - Centroid Decomposition
**Topic**: Mistake
**Message**: 
typo: "{ continue } ;" fix: "{ continue; }" in get_subtree_size(...)

**Comment by bqi343** [comment]
the incorrect semicolons are due to #3775
