### ISSUE TITLE
Additional Problem Dropdown Options?

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#440]
> I love that you created markers to track progress in modules and problems. I would appreciate it if in a problem, there are markers for "Reading Solution" and "Had difficulty". Just like on the home page, there is a section for "active problems", it would be helpful to put a section for "difficult problems". Whatever we mark as "Had difficulty" would go into this box.

> That way, it will help users like me remember which problems to come back to and which modules they were part of. The "Reading sol" would also tell someone that reviewing the solution is still pending, though they might have completely solved the problem.

At the very least, there should be a way to mark a problem and have it show up on the dashboard in a section distinct from active problems.

**Comment by MrinallU** [comment]
@bqi343 Would you mean like a mark as favourite option?

**Comment by bqi343** [comment]
Not sure. I guess something like starring and unstarring (if there weren't any starred problems initially ...)

**Comment by MrinallU** [comment]
@bqi343 So basically each problem should have an option to be starred, excluding the ones that were starred by the authors? And then in the dashboard there should be an additional section that displays a list of the problems starred by the user and each problem must be a link to it's corresponding place in the guide, correct?

**Comment by bqi343** [comment]
Sure. Though maybe should use an icon other than star :P @thecodingwizard thoughts?

**Comment by thecodingwizard** [comment]
Don't we already have functionality for this? "Skipped" problems would essentially be the "Hard Difficulty" problems to come back to at a later time; they are distinguished in the active problems section by the skipped tag. Also, I'm not too sure how useful making a distinction between "Solving" and "Reading Solution" is...

**Comment by thecodingwizard** [comment]
Should we close this issue then?
