### ISSUE TITLE
Contact Form Submission - Suggestion (Problem Solution - Milk Measurement (ID: usaco-763))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4416]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-763/user-solutions
**Module**: Problem Solution - Milk Measurement (ID: usaco-763)
**Topic**: Suggestion
**Message**: 
in the internal solution you initialize the map milk prod with {g,n} which is not the case as n is the number of days not the number of cows so i think it must be {g,number of cows} if i am wrong please illustrate why is it done this way

**Comment by SansPapyrus683** [comment]
i believe n just serves as an upper bound on the number of cows
