### ISSUE TITLE
Contact Form Submission - Mistake (Solution: APIO 2014 - Sequence)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4424]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/apio-2014split-the-sequence/solution
**Module**: Solution: APIO 2014 - Sequence
**Topic**: Mistake
**Message**: 
The memory complexity should be O(n) instead of O(nk).

**Comment by ADTmux** [comment]
Hey, can I work on this issue?

**Comment by SansPapyrus683** [comment]
yeah go for it
