### ISSUE TITLE
Contact Form Submission - Mistake (Problem Solution - Watermelon (ID: cf-4A))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4450]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cf-4A/user-solutions
**Module**: Problem Solution - Watermelon (ID: cf-4A)
**Topic**: Mistake
**Message**: 
wrong code, also in the internal solution, given solution as well code is wrong. Seems like the author misunderstood the problem

**Comment by bqi343** [comment]
That's embarrassing... #4428 @SansPapyrus683 @ryanchou-dev

**Comment by SansPapyrus683** [comment]
OOP HAHA SHOULD'VE ASKED FOR AC SS MY BAD
