### ISSUE TITLE
Hint 2 is: "If we reverse an odd number of cows, does anything effectively change?", but you can only reverse "even length prefixes"

### ISSUE THREAD

**Issue by boasbakker** [cpinitiative/usaco-guide#4466]
https://github.com/cpinitiative/usaco-guide/blob/master/solutions/bronze/usaco-1227.mdx
In the Bronze, Introduction to Greedy Algorithms section

**Comment by bqi343** [comment]
@SansPapyrus683 what was the intent for this hint?

**Comment by SansPapyrus683** [comment]
great question
