### ISSUE TITLE
Problem "SumDiv" of "Divisibility" requires theory of modular arithmetic so a better module for the problem would be "Modular Arithmetic"

### ISSUE THREAD

**Issue by boasbakker** [cpinitiative/usaco-guide#4467]
Theory of modular arithmetic like the modular inverse and Fermat's little theorem

**Comment by SansPapyrus683** [comment]
I would argue that the problem has much more to do with divisibility than with modular arithmetic, but others might have different opinions.
@ryanchou-dev what do you think?

**Comment by SansPapyrus683** [comment]
WAIT LOL I JUST REALIZED THIS ISN'T ABOUT THE CSES PROBLEM HAHA
in that case yeah i agree

**Comment by boasbakker** [comment]
Yeah I meant the Kilonova problem. Also, I think it isn't available in English?
