### ISSUE TITLE
Contact Form Submission - Mistake (Gold - Modular Arithmetic)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4468]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/modular
**Module**: Gold - Modular Arithmetic
**Topic**: Mistake
**Message**: 
first resource link seems broken

**Comment by bqi343** [comment]
@Aryansh-S do you have an updated link?

**Comment by vr-varad** [comment]
could use 

https://github.com/mochow13/competitive-programming-library/blob/master/Notes/Advanced%20Modular%20Arithmetic.pdf

https://cc-mnnit.github.io/2020-21-Classes/Freshers/First_Year_Competitive_Programming/07_02_2021_Class_1/Modular%20Arithmetic.pdf

**Comment by vr-varad** [comment]
@bqi343 Could I work on this?

**Comment by bqi343** [comment]
@vr-varad There are already many resources linked, no need to add more unless they differ significantly from all the existing ones.

**Comment by vr-varad** [comment]
The link associated is broken bcoz the pdf might has been deleted or name has been  changed and I searched but could not find the pdf resource.
So  what could be done is either delete that resource or add another.
@bqi343 what are ur thoughts?

**Comment by bqi343** [comment]
Can use this:

https://web.archive.org/web/20230324003836/https://aryansh-s.github.io/The_Art_of_Modular_Arithmetic.pdf

or remove it
