### ISSUE TITLE
Contact Form Submission - Suggestion (Advanced - Eulerian Tours)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4500]
Someone submitted the contact form!

**URL**: https://usaco.guide/adv/eulerian-tours
**Module**: Advanced - Eulerian Tours
**Topic**: Suggestion
**Message**: 
Problem on topic Eulerian Tours - https://codeforces.com/contest/1981/problem/D?locale=en

**Comment by SansPapyrus683** [comment]
@envyaims @brebenelmihnea

**Comment by brebenelmihnea** [comment]
Good problem
