### ISSUE TITLE
Grayed out module title on TOC

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#451]
@thecodingwizard want to take a look?

Intro DS, Intro to Graphs

<img width="764" alt="Screen Shot 2020-11-29 at 6 44 22 PM" src="https://user-images.githubusercontent.com/21228024/100556815-eab01180-3272-11eb-921d-efb506c438dc.png">
<img width="289" alt="Screen Shot 2020-11-29 at 6 43 07 PM" src="https://user-images.githubusercontent.com/21228024/100556802-d10eca00-3272-11eb-9866-d126ad8404f7.png">

**Comment by thecodingwizard** [comment]
shouldn't be a bug -- did you mark those as ignored?

**Comment by bqi343** [comment]
Ah.
