### ISSUE TITLE
Contact Form Submission - Other (CPI Bronze 2024 Summer class)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4511]
Someone submitted the contact form!

**URL**: https://usaco.guide/groups/IGSb8xCR9ZI737oAPto2
**Module**: CPI Bronze 2024 Summer class
**Topic**: Other
**Message**: 
The period of a regular zoom sessions (5-7 PM PT) converting to Kyiv time is 3-5 AM. I will try to join them, but this is mostly past my bedtime. Would there be a possibility of video recordings? 

Thanks in advance
Pavlo

**Comment by SansPapyrus683** [comment]
i was told this was already responded to in email so
