### ISSUE TITLE
Rewrite Simulation Example Code

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#453]
https://usaco.guide/bronze/simulation

Input & Output should be consistent with IO module (https://usaco.guide/general/io)

 - C++ - IO module doesn't mention use of `FILE*`, either mention it in IO module or change in this module.
 - Java - cleaner with `Kattio`
 - Python - redirect `sys.stdin` and `sys.stdout`

**Comment by bqi343** [comment]
> It would be nice if there are comments in code explaining each line of code

**Comment by frodakcin** [comment]
> * Python - redirect `sys.stdin` and `sys.stdout`

Currently, I'm using Method 1 in the IO section, except without the `with ...  as ...:` operator. Is redirecting stdin & stdout better?

**Comment by bqi343** [comment]
Yes.

**Comment by frodakcin** [comment]
Ok I'll change it

**Comment by frodakcin** [comment]
Out of curiosity, why is it better?

Is it because it's the easiest to convert between standard io and file io?

**Comment by bqi343** [comment]
> Can you try to make the array names for the examples a bit more specific. It will be a little bit more convenient.

**Comment by frodakcin** [comment]
Both problems?

For mixmilk, I think `c[]` for capacity and `m[]` for milk is understandable.

**Comment by frodakcin** [comment]
For shell game, I think `cnt[]` for counter is fine. For the other array, which tracks which shell is at which position, I called it `ord[]`, but I'm not sure what to change it to... Possibly `shell[]` or `pos[]`?

**Comment by bqi343** [comment]
>  For the other array, which tracks which shell is at which position, I called it `ord[]`, but I'm not sure what to change it to... 

Maybe `shell_at_position[]`?

**Comment by frodakcin** [comment]
Ok, wordy but clear. Might as well un-abbreviate the others too.

**Comment by frodakcin** [comment]
https://github.com/cpinitiative/usaco-guide/pull/509
