### ISSUE TITLE
Contact Form Submission - Mistake (Platinum - Binary Jumping)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4538]
Someone submitted the contact form!

**URL**: https://usaco.guide/plat/binary-jump?lang=cpp
**Module**: Platinum - Binary Jumping
**Topic**: Mistake
**Message**: 
The animation video has a mistake
"Jumping 4 from 10 to 1" should be the correct statement

**Comment by bqi343** [comment]
@SansPapyrus683

**Comment by SansPapyrus683** [comment]
oops uh that's mihnea's video uuuuhh
