### ISSUE TITLE
Contact Form Submission - Mistake (Problem Solution - The Bucket List (ID: usaco-856))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4546]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-856/user-solutions
**Module**: Problem Solution - The Bucket List (ID: usaco-856)
**Topic**: Mistake
**Message**: 
Implementation 2 - Sweep，LINE 25，change[end] -= amt;
I think change[end + 1] -= amt; is right.

**Comment by bqi343** [comment]
if the implementation is wrong, can you provide an example test case?

looks fine to me since all s_i, t_i are guaranteed to be distinct
