### ISSUE TITLE
Contact Form Submission - Suggestion (Silver - Introduction to Functional Graphs)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4556]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/func-graphs?lang=cpp
**Module**: Silver - Introduction to Functional Graphs
**Topic**: Suggestion
**Message**: 
Some harder problem on functional graphs - https://oj.uz/problem/view/IOI11_garden.
Editorial - https://ioinformatics.org/page/ioi-2011/37

**Comment by TheScarletPhoenix** [comment]
this issue should be closed after merging pr #4563
