### ISSUE TITLE
Contact Form Submission - Mistake (Solution: USACO Silver 2022 February - Redistributing Gifts)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4581]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-1206-redistributing-gifts/solution
**Module**: Solution: USACO Silver 2022 February - Redistributing Gifts
**Topic**: Mistake
**Message**: 
SCC time complexity should be N^2 log N

**Comment by bqi343** [comment]
@envyaims

**Comment by bqi343** [comment]
also, it would be good to remove the log factor

**Comment by envyaims** [comment]
https://github.com/cpinitiative/usaco-guide/pull/4583
