### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Problem Solution - Spanning Tree Fraction (ID: hr-SpanningTreeFraction))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4593]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/hr-SpanningTreeFraction/user-solutions
**Module**: Problem Solution - Spanning Tree Fraction (ID: hr-SpanningTreeFraction)
**Topic**: Request - Missing Section or Solution
**Message**: 
HackerRank solutions are not available anymore, unles you pay for them. It might make sense to try to add them internally.

**Comment by bqi343** [comment]
I can view the editorial for this problem without any issue, can you post a screenshot?

<img width="891" alt="Screenshot 2024-07-08 at 7 39 50 PM" src="https://github.com/cpinitiative/usaco-guide/assets/21228024/6905ebf9-665e-4622-a276-b50f0ae67c25">

**Comment by bqi343** [comment]
as far as I can tell, this hackerrank sol is available, so closing unless there's evidence to the contrary
