### ISSUE TITLE
Contact Form Submission - Mistake (Solution: CF - Maximum Product)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4596]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cf-maximum-product/solution
**Module**: Solution: CF - Maximum Product
**Topic**: Mistake
**Message**: 
The solution to this question is flawed even though it passes all the official test cases. If you take the inputs a = 789 and b = 1234, the answer should be 999, but the current code outputs 999.

**Comment by owennaonao** [comment]
Whoops I meant that the current code outputs 1199 while the correct answer is 999.

**Comment by SansPapyrus683** [comment]
@danielzsh 💀
