### ISSUE TITLE
Contact Form Submission - Unclear Explanation (Silver - Intro to Bitwise Operators)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4607]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/intro-bitwise
**Module**: Silver - Intro to Bitwise Operators
**Topic**: Unclear Explanation
**Message**: 
For XOR Pyramids, how do you get from the formula for pascal's triangle to using prefix sums?

**Comment by SansPapyrus683** [comment]
@brebenelmihnea i think you wrote this

**Comment by bqi343** [comment]
Combinations haven't been introduced yet. I think this problem would be better suited for this module: https://usaco.guide/gold/combo?lang=cpp

**Comment by SansPapyrus683** [comment]
yeah to whoever submitted this issue
here's your chance to ask about his explanation
