### ISSUE TITLE
Digit DP - Devu and Locks misplaced

### ISSUE THREAD

**Issue by Oz121** [cpinitiative/usaco-guide#4609]
In the Digit DP module, the problem Devu and Locks seems to be too hard/requires advanced topics. The official editorial here: https://discuss.codechef.com/t/devlock-editorial/9727 uses FFT and Matrix Exponentiation. There are also no user solutions posted on usaco guide, so others probably found it too complex. 

I believe this has been mentioned before: https://forum.usaco.guide/t/devu-and-locks/5195, which probably explains the issue a lot better than I can.

**Comment by bqi343** [comment]
Agreed. Feel free to submit a fix (removing this problem, adjusting difficulties of other problems as necessary).

**Comment by SansPapyrus683** [comment]
@jessechoe10 you made this module...

**Comment by bqi343** [comment]
He wasn't the one who added the problem.

**Comment by bqi343** [comment]
Since it's long overdue, I created a PR to address this. But in the future please feel free to do it on your own if you want this resolved quickly.
