### ISSUE TITLE
Contact Form Submission - Mistake (Gold - MITM - Proportional Cake)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4624]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard/
**Module**: Gold - MITM - Proportional Cake
**Topic**: Mistake
**Message**: 
https://usaco.guide/gold/meet-in-the-middle#problem-prepbytes-PROCAK

broken link

**Comment by bqi343** [comment]
@envyaims you're the one who added this problem

**Comment by envyaims** [comment]
uhh just remove it, seems like the website shut down lol
