### ISSUE TITLE
Contact Form Submission - Mistake (Problem Solution - BFS-DFS (ID: csa-bfsdfs))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4637]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/csa-bfsdfs/user-solutions
**Module**: Problem Solution - BFS-DFS (ID: csa-bfsdfs)
**Topic**: Mistake
**Message**: 
in Users Solution for BFS-DFS, if there isn't a check on the n=1 case, the code can be hacked with data 1 \n 1 \n 1, however CS Academy doesn't have a testcase like that

**Comment by Victor-X-Li** [comment]
nevermind I checked again and all of the codes are correct, my bad
