### ISSUE TITLE
Contact Form Submission - Suggestion (General - Contests)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4644]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/contests?lang=cpp
**Module**: General - Contests
**Topic**: Suggestion
**Message**: 
Hi! I was hoping for a button which would help me mark a module like a bookmark feature. Like the contests and Olympiads page I want to mark it so I could  see it regularly but currently I have to mark it either solving or reading in order to differenciate from other modules

**Comment by bqi343** [comment]
Marking as reading is intended for this purpose. Or just bookmarking the page in your browser.
