### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (USACO Monthlies)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4653]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/
**Module**: USACO Monthlies
**Topic**: Request - Missing Section or Solution
**Message**: 
Hi I noted that in the USACO Monthlies section the Tag for most questions in the last two seasons (i.e. 2023/24 and 2022/23) are missing. Could you guys either add those on the website or maybe send me a list through email separately?  It'd help my son practice knowing what algorithm is being tested for each question.  Thank you for help!

**Comment by bqi343** [comment]
I added tags for the problems I thought fit neatly into a few categories (though this does not apply to many recent Bronze problems ...). Feel free to add tags yourself if something was missed (to https://github.com/cpinitiative/usaco-guide/blob/master/content/extraProblems.json).
