### ISSUE TITLE
Two Pointers Editorial for the Books Problem from CF

### ISSUE THREAD

**Issue by tachithanhdanh** [cpinitiative/usaco-guide#466]
https://usaco.guide/silver/2P
The Codeforces Editorial for the Books Problem (https://codeforces.com/blog/entry/6864) is full of Russian so I cannot understand what it was saying. Would you mind adding some code or some hints to help me understand the way of solving the problem?

**Comment by bqi343** [comment]
Google translate works well enough. Anyways, added.
