### ISSUE TITLE
Contact Form Submission - Suggestion (Internal Solution - Mountain Time (ID: csa-MountainTime))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4663]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/csa-MountainTime/user-solutions
**Module**: Internal Solution - Mountain Time (ID: csa-MountainTime)
**Topic**: Suggestion
**Message**: 
The solution is awsome, though I think there can be a small improvement in the code part.

```
for (int &i : comp[x]) {
				ans[i] = intermediate > grid[i] ? 0 : grid[i] - intermediate;
			}
```

Here, since we sorted the heights from big to small, there's no need to check whether "intermediate" is greater than "grid[i]" or not, because it never will! We can simply subtract "intermediate" from "grid[i]", it's not an error but I think fixing it can make it clearer to other readers.

**Comment by bqi343** [comment]
What solution are you talking about?

**Comment by SansPapyrus683** [comment]
no yeah i can't find this in the user solutions or the official sol lol

**Comment by Victor-X-Li** [comment]
It's in the ofiical sol, folded using a code snippet.

**Comment by Victor-X-Li** [comment]
fail enough, thank you for your contribution

**Comment by bqi343** [comment]
> It's in the ofiical sol, folded using a code snippet.

I see, then I think this should be changed (and the code snippet removed - usually the code snippet is included only if the code inside is directly copy-pasted from the module, or something like that). 

> ok like i think the principle here is for the implementation inside the data structure to not trust any assumptions not specified by the types given to it

if the types given to it are wrong then the output will be wrong regardless of whether you add the ternary if or not. So I don't see what the point of the ternary if is.

**Comment by bqi343** [comment]
(side note: it would be good to rewrite the solution to remove the log factor - you can replace vector with list)

**Comment by SansPapyrus683** [comment]
> if the types given to it are wrong then the output will be wrong regardless of whether you add the ternary if or not. So I don't see what the point of adding the ternary if is.

if the types are wrong the code won't even compile...

**Comment by SansPapyrus683** [comment]
> I see, then I think this should be changed (and the code snippet removed - usually the code snippet is included only if the code inside is directly copy-pasted from the module, or something like that).

@ryanchou-dev do you remember why the extra params were needed lol

**Comment by SansPapyrus683** [comment]
no yeah i agree which is why now i'm curious why we had to have an adjusted dsu

**Comment by ryanchou-dev** [comment]
yep, you're right that the ternary check is not needed.

> @ryanchou-dev do you remember why the extra params were needed lol

iirc the problem involved splitting up the grid into sections & finding the answer for each component, so the dsu needed to store the indices of each component instead of just the sizes. to process merges, we needed to get the value at a point on the grid & setting answers for a component was easier in the unite function.

> (side note: it would be good to rewrite the solution to remove the log factor - you can replace vector with list)

is this with std::splice? you would still have a log factor from sorting though 👀

---

i can make a pr soon for removing that ternary check + code snippet & the splice for merges 👍

**Comment by bqi343** [comment]
> you would still have a log factor from sorting though 👀

True, though since the maximum height is not large that could technically be sped up.
