### ISSUE TITLE
Contact Form Submission - Mistake (Problem Solution - Garland (ID: cf-814C))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4664]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cf-814C/user-solutions
**Module**: Problem Solution - Garland (ID: cf-814C)
**Topic**: Mistake
**Message**: 
I think there is a typo? CF 814C should be problem "An impassioned circulation of affection" instead of "Garland"

**Comment by bqi343** [comment]
the original name is too long lol
