### ISSUE TITLE
Contact Form Submission - Suggestion (Platinum - Binary Jumping)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4674]
Someone submitted the contact form!

**URL**: https://usaco.guide/plat/binary-jump
**Module**: Platinum - Binary Jumping
**Topic**: Suggestion
**Message**: 
It would be nice if you could clarify that it's not the log of the number of nodes, example is Planet Queries 1.

**Comment by bqi343** [comment]
what's not the log of the number of nodes?

**Comment by bqi343** [comment]
if it is a tree then it has to be. if it's not, then you'll need to make adjustments.
