### ISSUE TITLE
Contact Form Submission - Suggestion (Platinum - Small-To-Large Merging)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4675]
Someone submitted the contact form!

**URL**: https://usaco.guide/plat/merging?lang=cpp#merging-data-structures
**Module**: Platinum - Small-To-Large Merging
**Topic**: Suggestion
**Message**: 
Instead of doing (i < n ? " " : "\n") it would be more concise to do " \n"[i == n]
Both ways work, but the second one is more concise.

**Comment by bqi343** [comment]
alternatively just output " " since the newline isn't checked

IMO this doesn't matter but you can submit a PR if you want
