### ISSUE TITLE
Contact Form Submission - Website Bug (PURS)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4677]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-532/user-solutions
**Module**: PURS
**Topic**: Website Bug
**Message**: 
I checked several times and I believe there are only 15 problems in this module, so where is the 16-th problem?

**Comment by Victor-X-Li** [comment]
The number 15/16 is showed on the top of the page, next to the frequency of the module.

**Comment by bqi343** [comment]
good catch, the solution to this problem is mentioned in the module, but the problem itself is not. it should be added.

https://github.com/cpinitiative/usaco-guide/blob/master/content/4_Gold/PURS.problems.json#L3

**Comment by Victor-X-Li** [comment]
I see, thanks you!

**Comment by SansPapyrus683** [comment]
pretty sure all 3 module problems are added now?
