### ISSUE TITLE
"key" should be "val" in Treaps.mdx

### ISSUE THREAD

**Issue by ndjapic** [cpinitiative/usaco-guide#4679]
There is a typo in the section "[Implicit Treaps](https://usaco.guide/adv/treaps#implicit-treaps)" of the document "[Treaps.mdx](https://usaco.guide/adv/treaps)". In the cpp code of the split function both `key` and `val` are used. They should be the same, like in the next code of the same function that follow it.

**Comment by bqi343** [comment]
can you link to the relevant lines in the Github file?

**Comment by freakin23** [comment]
> can you link to the relevant lines in the Github file?

line 215 and 219. both use an undeclared variable "key", it should be "val"
