### ISSUE TITLE
Broken Link in `Resources_CP.mdx`

### ISSUE THREAD

**Issue by devishraq** [cpinitiative/usaco-guide#4688]
**File Location**
The broken link is located in the `./content/1_General/Resources_CP.mdx` file in the USACO Guide repository.

**Broken Link**
The link [IOI community site](https://www.commonlounge.com/community/e4aac00a033a40ec96657906c6e1b43c/main) at `Other Resources` is not working.

**Details**
<img width="929" alt="image" src="https://github.com/user-attachments/assets/65c16d59-3920-4917-b21d-81ca5f89e58c">

**Suggestions**
It would be great if this link could be updated to the correct resource or removed if it's no longer relevant. I would be happy if I got a chance to correct this!!! 

**_I think it would be better to remove this link!_**

**Comment by bqi343** [comment]
feel free to remove

**Comment by devishraq** [comment]
@bqi343 ! Can u assign me this?
