### ISSUE TITLE
Exercise

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#469]
<img width="900" alt="Screen Shot 2020-12-07 at 7 01 04 PM" src="https://user-images.githubusercontent.com/21228024/101419714-96cea980-38be-11eb-8741-a343ca80c8cc.png">

Should show up as part of Knapsack DP rather than DP_NT.

**Comment by thecodingwizard** [comment]
uh oh....

**Comment by thecodingwizard** [comment]
should be fixed now. There's actually a bigger bug (feature? 😉) here... problem modules don't automatically update.
