### ISSUE TITLE
Contact Form Submission - Mistake (Advanced - Game Theory)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4700]
Someone submitted the contact form!

**URL**: https://usaco.guide/adv/game-theory
**Module**: Advanced - Game Theory
**Topic**: Mistake
**Message**: 
The problem name is "Chessboard Game, Again!", and the source should be Hackerrank.

**Comment by bqi343** [comment]
@brebenelmihnea
