### ISSUE TITLE
Contact Form Submission - Suggestion (Gold - Digit DP)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4704]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/digit-dp?lang=cpp
**Module**: Gold - Digit DP
**Topic**: Suggestion
**Message**: 
Devu and Locks - 1. USACO Guide says the solution is on the codechef website, but that is behind a paywall 2. The only solution I could find requires FFT which IMO is too hard for a normal digit DP problem (and also FFT is a more advanced topic than Digit DP so the problem should not be in this module at all).

**Comment by bqi343** [comment]
#4609
