### ISSUE TITLE
Contact Form Submission - Other (Solution: CSES - Coding Company)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4705]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cses-1665-coding-company/solution
**Module**: Solution: CSES - Coding Company
**Topic**: Other
**Message**: 
Hello, I was reading the solution and was just wondering how would one reach it, as in what's the intuition behind it, maybe because I'm not particularly good with dp but it seems like such a random idea I can't imagine myself even conceiving of it.
And thank you in advance.

**Comment by SansPapyrus683** [comment]
i ain't gon lie this seems like a better question for the forums

**Comment by TheGamingMousse** [comment]
answer: just read it on a random cf blog LOL
