### ISSUE TITLE
Contact Form Submission - Suggestion (Any)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4737]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/tree-euler
**Module**: Any
**Topic**: Suggestion
**Message**: 
Write the idea name next to problems in problem set. Like finding diameter of a graph, or finding farthest distance for each vertex of a tree, or ...

**Comment by bqi343** [comment]
All the problems in a module are supposed to be at least tangentially related to one of the focus problems in the module, doesn't that already reveal the idea?
