### ISSUE TITLE
Contact Form Submission - Request - Missing Section or Solution (Silver - Introduction to Prefix Sums)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4747]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/prefix-sums?lang=cpp
**Module**: Silver - Introduction to Prefix Sums
**Topic**: Request - Missing Section or Solution
**Message**: 
Problem * Haybale Stacking * is not submitable.

Introduction to Prefix Sums > Practice Problems

**Comment by bqi343** [comment]
See the note after the table.

(Probably this should be moved before the table, feel free to change.)
