### ISSUE TITLE
SOS DP appears twice

### ISSUE THREAD

**Issue by dolphingarlic** [cpinitiative/usaco-guide#476]
SOS DP appears in both /adv/dp-more and /adv/dp-sos. Which should we keep? /adv/dp-sos seems more complete right now

**Comment by thecodingwizard** [comment]
let's keep /adv/dp-sos? @bqi343 @frodakcin

**Comment by bqi343** [comment]
sure

**Comment by bqi343** [comment]
closed by 5cc9a49
