### ISSUE TITLE
WA on Test 4 for Mixing Water

### ISSUE THREAD

**Issue by freakin23** [cpinitiative/usaco-guide#4772]
Problem Link: https://codeforces.com/problemset/problem/1359/C
Provided Solution: https://usaco.guide/problems/cf-mixing-water/solution

The provided solution is Wrong for Test Case 4. Especially for 

TC:
1
999977 17 499998

User's Output:
499979

Expected: 
499981

**Comment by SansPapyrus683** [comment]
:skull:

**Comment by SansPapyrus683** [comment]
seems to be due to floating point error

**Comment by bqi343** [comment]
https://codeforces.com/contest/1359/submission/280670589

Apparently it passes only in C++17. Anyway, it's best to avoid using floating point numbers if you can.

**Comment by SansPapyrus683** [comment]
i suppose we just add a warning?

**Comment by bqi343** [comment]
Should fix the solution so that it works regardless of C++ version.

**Comment by freakin23** [comment]
ig it is clear that no matter how we write binary search we can not overcome the floating point error in C++ 20

**Comment by SansPapyrus683** [comment]
i mean i think if we use fractions instead it'll work out better

**Comment by freakin23** [comment]
exactly how?

**Comment by freakin23** [comment]
Do you intend to use quotient and remainder separately?

**Comment by SansPapyrus683** [comment]
uh numerator and denominator, but yeah

**Comment by bqi343** [comment]
> ig it is clear that no matter how we write binary search we can not overcome the floating point error in C++ 20

actually, on the provided test case, the error is not due to the binary search. Instead, it's due to the code inside the else statement.

**Comment by freakin23** [comment]
> > ig it is clear that no matter how we write binary search we can not overcome the floating point error in C++ 20
> 
> actually, on the provided test case, the error is not due to the binary search. Instead, it's due to the code inside the else statement.

![Screenshot from 2024-09-21 20-33-55](https://github.com/user-attachments/assets/45653a09-23c7-4967-8a67-6a33f091d890)
Little diff approach but still wrong output on the mentioned tc.

**Comment by TheGamingMousse** [comment]
> ok now now i wouldn't call it a "bs" solution also the constant time one is literally given a mention in the editorial

BS = binary search in this context, lol

**Comment by SansPapyrus683** [comment]
oops haha
