### ISSUE TITLE
Sliding Window 

### ISSUE THREAD

**Issue by freakin23** [cpinitiative/usaco-guide#4787]
In the sliding window module under the subtopic "Sliding Window Minimum", instead of using the sliding window maximum question as a focus problem which was already used above why not use this question from CSES (Question link: https://cses.fi/boi24/task/3221). I think it would be much better for the module.

**Comment by bqi343** [comment]
aren't the problems the same?

can replace Leetcode with CSES since the latter source is preferred, but doesn't matter much

**Comment by freakin23** [comment]
> aren't the problems the same?
> 
> can replace Leetcode with CSES since the latter source is preferred, but doesn't matter much

I was just wondering if the subtopic is about "minimum" then why now include a problem related to that instead of "maximum"

**Comment by bqi343** [comment]
oh, the subtopic name should be fixed.

anyway, if you want, you can replace the existing problem with the one you suggested (and rewrite the sols accordingly). no point in including both problems

**Comment by TheGamingMousse** [comment]
maybe sliding window RMQ would be a more suitable name? because RMQ = max or min :trust:
