### ISSUE TITLE
Contact Form Submission - Other (How to become a USACO coaching?)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4799]
Someone submitted the contact form!

**URL**: https://usaco.guide/
**Module**: How to become a USACO coaching?
**Topic**: Other
**Message**: 
Hi, I am a parent and would like to build up a computer science club for my kid's middle school. How can I become a USACO coaching instructor? Are there training materials to become a USACO coach? Also, do you mind if I pay $100 by myself and sign up your classes as a parent? I am new to the USACO, but I would like to create a fun learning environment for my kid's school. Thanks.

**Comment by bqi343** [comment]
> Are there training materials to become a USACO coach?

There are slides for clubs but they align pretty closely with the guide: https://joincpi.org/clubs

> Also, do you mind if I pay $100 by myself and sign up your classes as a parent? 

As per the contact form:

> If you have any questions about [CPI classes](https://joincpi.org/classes), please email [classes@joincpi.org](mailto:classes@joincpi.org) rather than submitting this form.
