### ISSUE TITLE
Contact Form Submission - Suggestion (General - Contests)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4800]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/contests?lang=cpp
**Module**: General - Contests
**Topic**: Suggestion
**Message**: 
I would like to suggest adding Coder Bloom to this list (https://coderbloom.org/). We host monthly programming competitions for Hispanic women, with problems provided in Spanish. Participants can use C++, Python, or Java to solve the challenges, which are divided into two categories: beginners and advanced.

**Comment by bqi343** [comment]
this page is only for contests in English
