### ISSUE TITLE
Contact Form Submission - Other (Solution: DMOJ - Phidias)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4832]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/ioi-phidias/solution
**Module**: Solution: DMOJ - Phidias
**Topic**: Other
**Message**: 
Why O(W⋅H⋅(W+H)) is working ? 
if w = h = 6000, then its equal to 4.32e8, which is 4 times greater then 1e8 ( I learned that c++ can do 1e8 operations per second ) ( none of sumbissions takes more time tan 0.1 second in judge !)

**Comment by bqi343** [comment]
actually you can do a lot more operations than that:

- https://codeforces.com/blog/entry/17799?#comment-226627

e.g., you can sum 1 ... 10^9 in half a second on CF.
