### ISSUE TITLE
Contact Form Submission - Other (Bronze - Introduction to Greedy Algorithms (USACO 2017 January Problem 3 Cow Tipping))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4837]
Someone submitted the contact form!

**URL**: https://usaco.guide/bronze/intro-greedy
**Module**: Bronze - Introduction to Greedy Algorithms (USACO 2017 January Problem 3 Cow Tipping)
**Topic**: Other
**Message**: 
Instead of using a matrix like other solutions, I just opted for using the extend function. Is this why my code fails on some cases? And can I do this in the future? Here's the code:

f = open('cowtip.in', 'r')
n = int(f.readline())
cows = []
for _ in range(n):
    cows.extend(list(map(int, f.readline()[:-1])))
t = 0
while 1 in cows:
    farthest_cow = n**2 - list(reversed(cows)).index(1)
    for i in range(farthest_cow):
        if cows[i] == 0:
            cows[i] = 1
        else:
            cows[i] = 0
    t += 1
f = open('cowtip.out', 'w')
f.write(str(t))

**Comment by SansPapyrus683** [comment]
ain't gon lie chief this seems like a question for the usaco guide forums: https://forum.usaco.guide/
