### ISSUE TITLE
Sign In with Goolge/Github

### ISSUE THREAD

**Issue by artahaam** [cpinitiative/usaco-guide#4845]
I get "Error: auth/network-request-failed" when trying to Sign In with both Google and Github.
I tried Chrome and Firefox, but got the same error.

**Comment by bqi343** [comment]
@thecodingwizard any suggestions?

**Comment by thecodingwizard** [comment]
I'm not really sure...

- Are you using a VPN?
- Which country are you located in?
- What do you see in the developer console?
- Which OS are you on?
- Can you sign in to Google / Github normally through their websites?
- Can you open the developer console networking tab, try logging in again, and capture the network calls that are made?

**Comment by artahaam** [comment]
- I tried with and without VPN
- Iran
- Where is that?
- Windows
- Yes I can, there is no problem, I even did sign up in https://forum.usaco.guide/ via Google Account
- ![image](https://github.com/user-attachments/assets/55b5f8d7-861e-45ee-9abd-5edbeb0a3e51)
- No I don't

**Comment by thecodingwizard** [comment]
https://stackoverflow.com/questions/37373532/why-is-firebase-based-app-not-working-in-iran :( it's possible Firebase does not work with Iran. Does it still not work if you use a VPN into the United States?

**Comment by artahaam** [comment]
It actually worked with United States IP. Thanks

**Comment by SansPapyrus683** [comment]
ok seems fixed
