### ISSUE TITLE
Contact Form Submission - Suggestion (Problem Solution - Range Update Queries (ID: cses-1651))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4848]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/cses-1651/user-solutions
**Module**: Problem Solution - Range Update Queries (ID: cses-1651)
**Topic**: Suggestion
**Message**: 
There is another solution.
Lets solve this problem for -1e9<=u<=1e9.
if we can handle [1, r] queries, then [a, b] += u is equal to [1, b] += u and [1, a-1] -= u.
And for handle [1, r] query, We can add u to value of r and for get value of a[i] we can print suffix sum of bit[i] + bit[i+1] + ... + bit[n].
which we can do it using fenwick tree.
My code: https://cses.fi/paste/a3f5fa95c7e7e8dca64db3/

**Comment by bqi343** [comment]
Nearly the same as the current internal sol.
