### ISSUE TITLE
Contact Form Submission - Other (USACO lost ID and Password)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4883]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/usaco-faq?lang=cpp
**Module**: USACO lost ID and Password
**Topic**: Other
**Message**: 
Hello USACO team,

I created my account with email "ssongjinseob@gmail.com", but I forgot both my ID and password for USACO website. Could you guys send a reset-password or ID of my email so that I login?

Thanks

**Comment by bqi343** [comment]
> The USACO Guide is not affiliated with the USACO. If you encounter any issues with [usaco.org](http://usaco.org/) (e.g., trouble [registering for an account](https://github.com/cpinitiative/usaco-guide/issues/2854)), contact the USACO contest director ([Brian Dean](mailto:bcdean@clemson.edu)) rather than submitting this form.
