### ISSUE TITLE
Contact Form Submission - Website Bug (General - USACO FAQ)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4902]
Someone submitted the contact form!

**URL**: https://usaco.guide/general/usaco-faq?lang=cpp
**Module**: General - USACO FAQ
**Topic**: Website Bug
**Message**: 
Good morning
I have a problem with my usaco.org account. I've been trying to create an account on usaco.org for an hour now, but I'm not getting an email with the password or the password reset. 
With respect,
Oliwier Wisniewski

**Comment by SansPapyrus683** [comment]
email brian dean about that not us
