### ISSUE TITLE
Contact Form Submission - Website Bug (Bronze - Simulation)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4934]
Someone submitted the contact form!

**URL**: https://usaco.guide/bronze/simulation#problems
**Module**: Bronze - Simulation
**Topic**: Website Bug
**Message**: 
I am using this block to output a file 
`

ios::sync_with_stdio(false);
    if (fropen("filename.in")) {
		freopen("filename.in", "r", stdin);
		freopen("filename.out", "w", stdout);
    }

`
and for some reason when I submit my solution file to usaco.org it always gives me  "Your output file speeding.out:
[File missing!]" no matter what and this is the first time this behavior occurs

**Comment by bqi343** [comment]
Please see the user solutions for this problem for examples of using file I/O correctly.

**Comment by SansPapyrus683** [comment]
what's the issue

**Comment by bqi343** [comment]
for some time, all submissions would give the error mentioned in the contact form. I think this is resolved now
