### ISSUE TITLE
Contact Form Submission - Mistake (Problem Solution - Blocked Billboard II (ID: usaco-783))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4938]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-783/user-solutions
**Module**: Problem Solution - Blocked Billboard II (ID: usaco-783)
**Topic**: Mistake
**Message**: 
Hello
Maybe i am wrong but as i believe the solution provided for  
https://usaco.guide/problems/usaco-783/ has a mistake 
while when you try this case
it give you zero
while it should be 10
i tried other codes been accepted and re-read the problem and as i believe it should be 10
Thank you for amazing guide
Kind regards,
Aibak

**Comment by bqi343** [comment]
Can you specify which solution you are referring to?

**Comment by SansPapyrus683** [comment]
ok closing until op responds
