### ISSUE TITLE
Sharing URL + Language

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#495]
Ex. say I want to share a URL that refers to a section that is only present in the java version of some module.

**Comment by thecodingwizard** [comment]
I'm assuming if you click this URL, then your default language will be changed? (otherwise it'll be out of sync)

**Comment by MrinallU** [comment]
@bqi343 So is the copy to clipboard feature still needed?

**Comment by bqi343** [comment]
No (unless you want to?)
