### ISSUE TITLE
Contact Form Submission - Website Bug (Silver - Introduction to Prefix Sums)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4968]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/prefix-sums
**Module**: Silver - Introduction to Prefix Sums
**Topic**: Website Bug
**Message**: 
It seems at the start of each category (bronze, silver, etc.), and only at the start, is the top visible, showing e.g. "prev" and "next".

**Comment by bqi343** [comment]
Can you provide a screenshot?

**Comment by Sosuke23** [comment]
![Screenshot from 2024-12-11 11-54-48](https://github.com/user-attachments/assets/6c4e90f7-e950-4673-afee-070321e2f1c6)
![Screenshot from 2024-12-11 11-54-57](https://github.com/user-attachments/assets/ea4c9cea-b48e-4592-bb61-b4bfb46b4e8f)

**Comment by Sosuke23** [comment]
He was right about this issue

**Comment by bqi343** [comment]
Are you saying that the issue is the prev / next buttons not appearing?

This behavior was changed by #4228, @danielzsh can you take a look?

**Comment by Sosuke23** [comment]
> Are you saying that the issue is the prev / next buttons not appearing on the Intro to Prefix Sums page?

Yes, and in fact on the first modules of all sections.
