### ISSUE TITLE
Latex is not rendered properly in the table of contents

### ISSUE THREAD

**Issue by izhang05** [cpinitiative/usaco-guide#497]
Latex is not rendered properly in the table of contents for modules.
![image](https://user-images.githubusercontent.com/29922692/102677744-bba20700-4171-11eb-811e-99799e0569da.png)

This came from https://usaco.guide/gold/lis.

**Comment by thecodingwizard** [comment]
![image](https://user-images.githubusercontent.com/7865976/105571177-dc2a2780-5d02-11eb-8c0d-6e0b8648307b.png)


:heart:
