### ISSUE TITLE
Topological Sort has an incorrect DFS solution

### ISSUE THREAD

**Issue by arnavwinner** [cpinitiative/usaco-guide#4977]
Due to recent hacks, the cses solution now requires checking whether the given graph is a DAG or not. The [preliminary solution](https://usaco.guide/gold/toposort?lang=cpp#dfs) assumes that the given graph is a DAG.

**Comment by bqi343** [comment]
The code you linked is not the code from the module, I don't see how it's relevant.

**Comment by bqi343** [comment]
This code (from the module) gets AC. https://cses.fi/paste/e4ec414fb531e05dae1c6e/

**Comment by arnavwinner** [comment]
Okay sorry @bqi343! Yes my code is exactly the same except line 50!

`(ind[j] <= ind[i])` is the right one
while I did `(ind[j] < ind[i])`

I don't know what makes it different but anyway the code in the module is perfect!

Sorry I am new to GitHub, I don't know how to close an issue!
