### ISSUE TITLE
Contact Form Submission - Other (Need help)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4984]
Someone submitted the contact form!

**URL**: https://usaco.guide/
**Module**: Need help
**Topic**: Other
**Message**: 
The code for the first problem in the USACO Bronze division runs fine with the sample cases in the blocks IDE, but why does it keep failing the sample tests when submitted to the USACO official website? (I successfully submitted and passed the test cases for the second and third problems first, but when I worked on the first problem, the software encountered an error, and after restarting it, this issue appeared.) I'm a primary school student using a Mac computer with a virtual machine, and after trying for a long time, I still can't find the reason. Could you please help me with this? Thank you.

**Comment by bqi343** [comment]
some potential reasons are in this module: https://usaco.guide/general/debugging-checklist#wrong-answer-or-runtime-error
