### ISSUE TITLE
Disable TOC?

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#499]
<img width="472" alt="Screen Shot 2020-12-19 at 1 00 02 PM" src="https://user-images.githubusercontent.com/21228024/102696144-2139d600-41fa-11eb-9459-5be04d3319dd.png">

Seems silly for the TOC to take up so much space when there are no sections. (This would probably apply to most solution pages.)

**Comment by MrinallU** [comment]
Can the user have the option to do this as well, like have a button that closes and reopens the TOC on click .

**Comment by MrinallU** [comment]
Another option is to have the TOC act as a hamburger menu
