### ISSUE TITLE
Contact Form Submission - Mistake (Solution: USACO Silver 2016 January - Build Gates)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#5000]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-596-build-gates/solution
**Module**: Solution: USACO Silver 2016 January - Build Gates
**Topic**: Mistake
**Message**: 
this must be added as a warning because I wasted 5 hours  debugging and getting RTE on the judge so please add this   : The maximum allowed stack size on the judge is around 2000x2000. The test cases are designed to pass if you declare a 2005x2005 farm. Exceeding the stack capacity  by doing 4000x4000 might result in unexpected behavior from your compiler.

To avoid this issue, you can also implement an iterative flood-fill approach.

**Comment by bqi343** [comment]
I think you're just exceeding the memory limit?

**Comment by mowafkmha** [comment]
> I think you're just exceeding the memory limit?

yes I just noticed that in my flood fill my base case is (x<0) and it should be (x<minx)  but still need to place the warning of exceeding the stack size so one need to really make sure that his flood fill is only doing what is inside the defined boundary 
because it was a debugging nightmare

**Comment by bqi343** [comment]
It's already mentioned in the module: https://usaco.guide/silver/flood-fill#example---counting-rooms
