### ISSUE TITLE
Contact Form Submission - Mistake (Incorrect USACO Placement)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#5006]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard
**Module**: Incorrect USACO Placement
**Topic**: Mistake
**Message**: 
please email me

**Comment by bqi343** [comment]
> If you encounter any issues with [usaco.org](http://usaco.org/) (e.g., trouble [registering for an account](https://github.com/cpinitiative/usaco-guide/issues/2854)), contact the USACO contest director ([Brian Dean](mailto:bcdean@clemson.edu)) rather than submitting this form.
