### ISSUE TITLE
Contact Form Submission - Mistake (Problem Solution - Haybale Stacking (ID: usaco-104))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#5012]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-104/user-solutions
**Module**: Problem Solution - Haybale Stacking (ID: usaco-104)
**Topic**: Mistake
**Message**: 
Hello, the problem doesn't allow submissions. Is there another site to submit solutions?

**Comment by bqi343** [comment]
https://github.com/cpinitiative/usaco-guide/issues/4964
