### ISSUE TITLE
Contact Form Submission - Mistake (Problem Solution - Barn Tree (ID: usaco-1254))

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#5013]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/usaco-1254/user-solutions
**Module**: Problem Solution - Barn Tree (ID: usaco-1254)
**Topic**: Mistake
**Message**: 
Both of the python solutions for this problem are incorrect. I just tested them.

**Comment by bqi343** [comment]
marked as private
