### ISSUE TITLE
Contact Form Submission - Mistake (Two Pointers)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#5015]
Someone submitted the contact form!

**URL**: https://usaco.guide/dashboard
**Module**: Two Pointers
**Topic**: Mistake
**Message**: 
In the problems section of the Two Pointers module in USACO Silver, one of the problems is Codeforces "Cellular Network". However, upon clicking on the problem, the problem name is "Cellular Communications". Very minor mistake.

**Comment by bqi343** [comment]
Huh? I don't see a problem named "Cellular Communications" ...

<img width="906" alt="Screenshot 2024-12-30 at 12 43 58 PM" src="https://github.com/user-attachments/assets/2f6105d8-9967-490b-a4a3-cd1975c9d1d7" />
