### ISSUE TITLE
Contributing Solutions

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#512]
(Apologies if this isn't the place to ask questions such as this- I can close this issue if the maintainers tell me to)

Is there a list of the solutions that haven't been made already? I'd like to contribute some solution, but I can't seem to find a list of the "open" problems that don't have an internal solution yet.

**Comment by bqi343** [comment]
Not sure what you mean, the guide will display an internal solution in the "solution" column if one exists.

<img width="803" alt="Screen Shot 2020-12-22 at 8 02 13 PM" src="https://user-images.githubusercontent.com/21228024/102947140-9a525b00-4490-11eb-87c9-edff19e86ddc.png">

**Comment by SansPapyrus683** [comment]
Ah, I see. Thanks!
When submitting a PR for solutions, do I just have to include the `.mdx` files with my written solutions (named appropriately, of course)? I don't know that much frontend css/js, so I won't be able to integrate the written solutions into the actual links.

**Comment by bqi343** [comment]
You should be fine as long as you follow the instructions [here](https://usaco.guide/general/contributing#adding-a-solution).
