### ISSUE TITLE
saving / sharing code associated with a problem

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#513]
> Maybe we add a column to the table that's like "View Solutions," and then it lists a whole bunch of (public) user submissions and people can browse them or something. Not sure

Also should be possible to edit code / associate more than one solution with the same problem.

_Originally posted by @bqi343 in https://github.com/cpinitiative/usaco-guide/issues/431#issuecomment-747153400_

**Comment by MrinallU** [comment]
@bqi343 The problem feedback thing is about done so this should be possible pretty soon, plus each submission in the database is identified by its problem name so it should be trivial for the most part.

**Comment by MrinallU** [comment]
@bqi343 We should also show the verified solutions first in the public solves section like somebody should make sure a few of them are correct by running them and then the website will show the ones that are verified first and then all of the other solutions .

**Comment by MrinallU** [comment]
@bqi343 what would be the purpose of editing the code in the solution library?

**Comment by bqi343** [comment]
Say the user who created it wants to add additional comments.

**Comment by thecodingwizard** [comment]
Does this need to be decoupled from problem feedback then?

**Comment by bqi343** [comment]
@thecodingwizard Up to you.

**Comment by thecodingwizard** [comment]
Does anyone have ideas for how the UI for this is going to work? The problem table is getting awfully cramped; seems difficult to add another column.

Maybe we should replace the "Solution" column with a "More Details" column? And then clicking the "More Details" link would open a popup modal with all the information related to the problem, including:

- external solution links
- internal solution links
- other users' codes
- option to give problem feedback

**Comment by MrinallU** [comment]
@thecodingwizard With all this stuff I feel like it should not be cramped into one modal and instead it should be a separate page for each solution, possibly a new route or page for the more info page?
