### ISSUE TITLE
Get rid of templates?

### ISSUE THREAD

**Issue by dolphingarlic** [cpinitiative/usaco-guide#517]
So a few feedback emails have been complaining about templates being hard to read. Should we try to convert all the code with templates to code without? There are a few thousand LOC with templates, so I'm not sure whether it's worth it

**Comment by bqi343** [comment]
Should be resolved by #513? People can submit their own code and the official solution can be replaced if the submitted code more readable.

**Comment by thecodingwizard** [comment]
Yeah. Even removing macros seems a little nontrivial (though perhaps doable); templates is like impossible to automate.

I honestly don't think we (as in guide authors) should spend our time removing macros -- anybody can do it and submit a PR (it makes a good first issue to contribute with anyway), and if we do have extra time we should really fill in incomplete sections / incomplete solutions.

(Plus it's not like code is unreadable with templates...)
