### ISSUE TITLE
Issue with Test Cases 3 and 8 in speeding.out file

### ISSUE THREAD

**Issue by theRealBird** [cpinitiative/usaco-guide#529]
Can someone please verify whether the test cases 3 and 8 for the problem **Speeding-USACO Bronze December 2015** contain the correct output? I think they have some weird character in them instead of an integer.
Here's the image for reference.
![image](https://user-images.githubusercontent.com/75845929/103140673-7f414e80-470f-11eb-843e-bdf06db38481.png)

**Comment by thecodingwizard** [comment]
They do for me -- They are 0 for both 3.out and 8.out.

(In the future, it may be better to use the [USACO Forum](https://forum.usaco.guide/) for these types of questions :)

**Comment by theRealBird** [comment]
Whoops! I must have made some error. Thanks for your help, I will head to the forums.  Apologies for causing inconvenience.
