### ISSUE TITLE
Make the settings modal dark in dark mode

### ISSUE THREAD

**Issue by dolphingarlic** [cpinitiative/usaco-guide#530]
It's quite jarring to see a light-mode settings modal when everything else is dark mode

**Comment by dolphingarlic** [comment]
Also the sections dropdown thing

**Comment by bqi343** [comment]
similar to #325

**Comment by NikolaSiplakova** [comment]
Hi, I'd like to work on this issue. Could you assign it to me? :)

**Comment by thecodingwizard** [comment]
oh i fixed this recently :heart:
