### ISSUE TITLE
Ability to Import User Data

### ISSUE THREAD

**Issue by coderinblack08** [cpinitiative/usaco-guide#531]
Since I have been working without an account, whenever I log in, my work done previously is not uploaded to the account. You have an export user data button so could you also add an import user data button? I could help write a PR :D

**Comment by thecodingwizard** [comment]
If you submit a PR, we'll definitely take a look :).

Also, why not just make a user account?

**Comment by coderinblack08** [comment]
I think I created one before when it was newer, and didn't use it again and now that I login in, my data gets wiped from local storage:C

**Comment by thecodingwizard** [comment]
oh yeah oops, syncing local data and server data is insanely annoying. We should really figure out a better way to do that (maybe a popup that asks you to choose between local data or server data)

**Comment by coderinblack08** [comment]
yep, I think that would be nice
