### ISSUE TITLE
@firebase/firestore could not reach cloud firestore backend

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#534]
If Firebase detects a bad internet connection, it will switch to offline mode, which may result in user data synchronization issues.

The biggest issue I have identified so far is with initial account creation; if it switches to offline mode, then it will erroneously prompt the user to override server data with local data, which may lead to permanent loss of data for the user.

![image](https://user-images.githubusercontent.com/7865976/103256284-818aef00-4941-11eb-8450-a8c48b362b84.png)

This can probably (?) be fixed by either disabling offline mode or handling offline mode when prompting user to upload local data.

**Comment by thecodingwizard** [comment]
I successfully reproduced this issue one time on my machine (very unreliably).

1. Log out of account
2. Throttle to 3G
3. Log in with Google
4. throttle to offline (timing of this is weird -- you need to let the google sign in go through but not the firebase data loading)
5. you should see override server data prompt -- select yes
6. disable throttling
7. data is lost!

**Comment by mjh316** [comment]
Troubleshooting:
1. Try different browsers (Edge, Firefox, Chrome)
2. Try incognito
3. Try different networks - wifi, phone hotspot from cellular data
4. Turn off Windows Firewall, Anti-virus
5. Turn off any extensions (or just use incognito with them all off).

6. Find [this](https://github.com/firebase/firebase-js-sdk/issues/1674)
7. Try forcing experimental long polling option?

**Comment by mjh316** [comment]
Just pushed a fix in #3594. Is this closable @thecodingwizard?

**Comment by thecodingwizard** [comment]
yes, thanks!
