### ISSUE TITLE
"Solved" popup

### ISSUE THREAD

**Issue by nwatx** [cpinitiative/usaco-guide#553]
![image](https://user-images.githubusercontent.com/43394822/103423878-f8f19600-4b6e-11eb-9e64-60603179af4b.png)
Maybe we could have this popup come up randomly (30% maybe) or volunteer feedback, as it currently comes up every time a solution is marked (a little annoying xd).

**Comment by bqi343** [comment]
Should add an option to disable popups.

**Comment by MrinallU** [comment]
@thecodingwizard I'll work on this then.

**Comment by thecodingwizard** [comment]
https://github.com/cpinitiative/usaco-guide/issues/513#issuecomment-750548424 this might be relevant...

**Comment by MrinallU** [comment]
@thecodingwizard I'll probably use the dark mode toggle a reference for this one.

**Comment by dolphingarlic** [comment]
Should we close this issue, since the popup is gone now?

**Comment by nwatx** [comment]
sure
