### ISSUE TITLE
Ugly wrapping for long code lines

### ISSUE THREAD

**Issue by SansPapyrus683** [cpinitiative/usaco-guide#560]
While looking at one of the solutions for a problem, I noticed that the way the website handles long lines of code is rather ugly (at least in my opinion):
![image](https://user-images.githubusercontent.com/55369003/103432510-cd81a200-4b94-11eb-8fdd-ed3f3dac929d.png)
It'd be nice if instead of just hard wrapping it like that, there was a sort of horizontal scrollbar so the longer lines look better. 
Or is this not possible as the format used is MDX?

**Comment by thecodingwizard** [comment]
It was a deliberate decision to have it wrap (mostly for mobile, though maybe this was the wrong decision?). On desktop no code wrapping should occur -- the code we wrote there should probably be split into multiple lines :P

**Comment by bqi343** [comment]
Just reformat the specific file in question so that there aren't so many characters on a single line.
