### ISSUE TITLE
display date of last commit on module

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#592]
mb on syllabus page too?

**Comment by bqi343** [comment]
> https://stackoverflow.com/questions/50194241/get-when-the-file-was-last-updated-from-a-github-repository

> https://mohamedsahbi.com/2019/12/24/fix-a-gap-in-github-api-v4/

**Comment by thecodingwizard** [comment]
@bqi343 was it intentional that the last commit is only on the syllabus page, and that it only shows if it's within two weeks or so?

**Comment by bqi343** [comment]
yeah, do you want it on the module pages as well? seems to be enough stuff in the module header already

**Comment by bqi343** [comment]
closed by #596

**Comment by MrinallU** [comment]
@thecodingwizard What about having monthly update notes, like new/updated sections so people can come back and visit the pages, especially while the guide is still in it's "prerelease" stages.

**Comment by thecodingwizard** [comment]
It's technically possible to automate that with conventional commits ;)
