### ISSUE TITLE
More cow photos

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#594]
(email request)

**Comment by bqi343** [comment]
For ppl with insane streaks??

**Comment by HarryWangATX** [comment]
I think just in general lol. we need more cows

**Comment by HarryWangATX** [comment]
maybe web scrape for cow pics if possible???

**Comment by nwatx** [comment]
> 
> 
> maybe web scrape for cow pics if possible???

well that ig could lead to copyright? maybe pixabay and creative commons places. Ik pixabay has some.

**Comment by thecodingwizard** [comment]
> For ppl with insane streaks??

I had a 130-day streak until I sacrificed it to test the cow photo bug :c


> maybe web scrape for cow pics if possible???

sure, though someone will still have to look through the scraped cow photos. So it's probably fine to just ask for PR's and hope somebody who's bored will take on the job :P

**Comment by bqi343** [comment]
#597 should be sufficient?
