### ISSUE TITLE
Dead USACO problems

### ISSUE THREAD

**Issue by wengh** [cpinitiative/usaco-guide#606]
USACO Problems earlier than 2012 US Open seem to no longer accept Analysis Mode submissions.
[Some of these problems are used in USACO Guide](https://usaco.guide/plat/hld#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=102).

We should probably link to a mirror site such as [Luogu](https://www.luogu.com.cn/problem/P3038) or contact USACO staff.

**Comment by SamZhang3** [comment]
The issue with Luogu is that it is a Chinese website, and not a lot of USACO Guide users speak the language. Even if one uses, say, Google Translate to understand the site, there are still other issues (for example, as Gmail is blocked in China, I suspect that it is not possible to create an account on Luogu with a Gmail address; and an account is necessary to make submissions.)

I am not even certain whether what Luogu is doing (mirroring the statements and test data of USACO problems) complies with copyright law or USACO policy.

I hope that USACO will deal with the problem and allow solutions to be submitted there.

**Comment by dongliu0426** [comment]
https://usaco.guide/general/oly?lang=cpp#usaco

**Comment by thecodingwizard** [comment]
https://usaco.guide/general/oly#usaco There's a Korean website apparently
