### ISSUE TITLE
Spelling issue?

### ISSUE THREAD

**Issue by ochen1** [cpinitiative/usaco-guide#633]
![iff](https://user-images.githubusercontent.com/59662605/104953889-86f9b900-5984-11eb-8754-2817f054c823.png)
*"if" with two f's. Is this a bug or a feature?*

Link: https://usaco.guide/silver/intro-tree

**Comment by andrewwangva** [comment]
Nope! iff stands for if and [if and only if](https://en.wikipedia.org/wiki/If_and_only_if) I'm pretty sure.

**Comment by ochen1** [comment]
> Answer: Feature.

I see :eyes:! Thank you! :smile:
