### ISSUE TITLE
Add Binary Search on Array implementation for Java

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#652]
I think we should add a binary search implementation for Java that doesn't rely on library implementation: https://usaco.guide/silver/binary-search-sorted?lang=java (maybe other languages too?)

None of the resources seem to have a Java implementation.

**Comment by HarryWangATX** [comment]
sure i can do that

**Comment by HarryWangATX** [comment]
@thecodingwizard how do you want that section to be formatted with that addition? do i just add the impl to all the langs?

**Comment by thecodingwizard** [comment]
oops just kidding -- I completely forgot that Binary Search on Answer exists. I think it's fine that bin search on array only uses library function calls in this case (unless someone feels otherwise?)
