### ISSUE TITLE
Request for a section with a randomly sorted problemset

### ISSUE THREAD

**Issue by frodakcin** [cpinitiative/usaco-guide#702]
Putting every problem into categorized sections removes the novelty of seeing a new problem in a contest. Create a section (probably for each division) with randomly sorted problems to practice w/o hints.

(initially brought up by izhang)

**Comment by bqi343** [comment]
Why not just do random probs from here?

https://usaco.guide/general/usaco-monthlies?lang=cpp

**Comment by frodakcin** [comment]
Oh I didn't know that was a thing. I guess this resolves the issue.
