### ISSUE TITLE
Basic Complete Search code should directly solve focus problem

### ISSUE THREAD

**Issue by frodakcin** [cpinitiative/usaco-guide#720]
https://usaco.guide/bronze/intro-complete?lang=cpp

**Comment by HarryWangATX** [comment]
like completing the code, not just the main code block?

**Comment by frodakcin** [comment]
yea. It might help some people who aren't getting it yet.
https://codeforces.com/gym/102951/standings
Also we should mention `max(sqrt())` = `sqrt(max()))`

**Comment by frodakcin** [comment]
to avoid float point

**Comment by HarryWangATX** [comment]
wait why should be mention max(sqrt())=sqrt(max())? im not seeing it at all in the section

**Comment by frodakcin** [comment]
some people are implementing it by computing max of all distances, and then printing the square of the result.
