### ISSUE TITLE
Add https://usaco.guide/silver/greedy?lang=cpp#example-studying-algorithms to codeforces gym?

### ISSUE THREAD

**Issue by dongliu0426** [cpinitiative/usaco-guide#721]

**Comment by frodakcin** [comment]
https://codeforces.com/gym/102951/problem/B

Test if this works?

**Comment by dongliu0426** [comment]
nice, it works!

**Comment by dongliu0426** [comment]
oops we still need to link the problem to the module

**Comment by dongliu0426** [comment]
https://codeforces.com/gym/102951/submission/106936123 oof LOL

**Comment by frodakcin** [comment]
fixed it & rejudged. we good now :)
