### ISSUE TITLE
System dark mode

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#725]
Dark mode should be System / Light / Dark (defaulting to System)

https://forum.usaco.guide/t/request-use-system-theme-for-dark-mode/752

**Comment by jeffreymeng** [comment]
I think a prerequisite is an overhaul of the settings modal.
It’s kinda clunky right now.

Best,
Jeffrey Meng

--
Jeffrey Meng | jeffkmeng@gmail.com | jeffkmeng.com
