### ISSUE TITLE
Flood Fill - Unnecessary Code

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#728]
It's not necessary to have both the "Implementation" and the solution to Counting Roads. The two should be merged.

**Comment by bqi343** [comment]
Also:

> Essentially, it’s DFS, but on a grid, and we want to find the connected component of all the connected cells with the same number.

Why "but"? Also, it doesn't necessarily have to be DFS ([Wikipedia](https://en.wikipedia.org/wiki/Flood_fill) mentions both stack and queue implementations).

**Comment by thecodingwizard** [comment]
> It's not necessary to have both the "Implementation" and the solution to Counting Roads. The two should be merged.

they're slightly different though right? the "implementation" is more generic than the solution (colors + currentSize variable + comments)

**Comment by bqi343** [comment]
Yeah, I guess that's fine. I made a few other changes in #737.
