### ISSUE TITLE
Separate Style from Templates

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#733]
https://usaco.guide/general/code-con

Should separate coding style from making templates. Also mention

https://py.mit.edu/fall20/notes/style

**Comment by thecodingwizard** [comment]
> Should separate coding style from making templates.

Do you mean making a separate module for templates? (Is that actually necessary? code conv is so short already)

**Comment by bqi343** [comment]
I think we can just remove the template part entirely and maybe mention style in "Contributing."

**Comment by thecodingwizard** [comment]
where would we put the template part though? (I think it's still somewhat useful?)

**Comment by bqi343** [comment]
closed by #738
