### ISSUE TITLE
Adding a new free book to the NT module in Gold

### ISSUE THREAD

**Issue by pavanscoding** [cpinitiative/usaco-guide#750]
So I found this free NT book that covers everything AoPS: Intro to NT does and more. I think in the module you should say that you only need to do Chapter 1 and 2 along with Section 9.2 based on what is currently in the module. However, don't quote me on that because I am only in silver.

Here is the link to the book:
https://drive.google.com/file/d/1BcJTLjQaelZ4w_70oHKyImC2I8zLfyrt/view 

Here is the link to the forum from where it originates from:
https://artofproblemsolving.com/community/c6h2344755

**Comment by bqi343** [comment]
Please make a PR as described [here](https://usaco.guide/general/contributing).

**Comment by pavanscoding** [comment]
I created a PR for it.
