### ISSUE TITLE
Combine Sets with Custom Comparators with Sets

### ISSUE THREAD

**Issue by jessechoe10** [cpinitiative/usaco-guide#761]
Since sets with custom comparators doesn't have any unique problems, it'd be better to combine the sets module with sets with CC.

**Comment by thecodingwizard** [comment]
I think it's fine as is (though maybe including a focus problem would be good if)

**Comment by jessechoe10** [comment]
> I think it's fine as is (though maybe including a focus problem would be good ig?)

Are there any good problems you know of rn?
