### ISSUE TITLE
Code blocks should not collapse if they are the sole element inside a spoiler

### ISSUE THREAD

**Issue by jeffreymeng** [cpinitiative/usaco-guide#789]
If a code block is the only thing inside a spoiler tag, then the code block should not be collapsed or collapsable. For example, see solution 2 of [this page](https://usaco.guide/gold/dp-trees?lang=java). When expanding the solution, there's no need to have to spend another click to expand the code block.

(how to solve)
Inside spoiler blocks, iterate through its children. If the only child is a code block, then pass a prop `expandable={false}` to the code block.
Inside the code block component, accept the prop mentioned above and render the entire code block, without any collapsing functionality.

**Comment by MrinallU** [comment]
@jeffreymeng I'll do this.

**Comment by MrinallU** [comment]
Closed by #1008

**Comment by thecodingwizard** [comment]
I'm reopening until the PR is merged (and it should auto-close when it's merged anyway)
