### ISSUE TITLE
Adding a resource to Binary Search

### ISSUE THREAD

**Issue by subra9minion** [cpinitiative/usaco-guide#794]
I'm Rahul. I recently started going through the USACO Guide (Silver section) and I find this a very useful way for me to learn and get better at problem solving. 
While I was practicing problems on Leetcode, I came across this [article on Binary Search](https://leetcode.com/discuss/general-discussion/786126/python-powerful-ultimate-binary-search-template-solved-many-problems), which contains lots of insights and patterns, along with problems and how to approach them. 
I would love to see this on the Binary Search module so future learners who come across the Binary Search module can benefit from this. I am willing to learn and make the contribution of adding this to the module, but before I start I would like to know if it is a good idea, and if a team member thinks the resource mentioned above would add value.

**Comment by bqi343** [comment]
https://github.com/cpinitiative/usaco-guide/pull/795

Though most of it is already contained within the module / associated problems, and I don't like how it spoils so many of them. T.T

**Comment by subra9minion** [comment]
I understand. Thank you for the response! I'll be around looking for ways to help/contribute and make the guide better.

**Comment by subra9minion** [comment]
Thank you so much for adding it!
