### ISSUE TITLE
Change logo font

### ISSUE THREAD

**Issue by Shad0wSeven** [cpinitiative/usaco-guide#799]
Most likely will get ignored, but the conflicting typefaces between almost all the elements, and the logo looks pretty unprofessional. 

![image](https://user-images.githubusercontent.com/19739712/108318671-11485f00-7175-11eb-8adf-98b853941b73.png)

I use macOS so GitHub, and USACO Guide seem to use my System font, San Fransisco

**With a revised interface the UI could look more like this, without conflict sans serif fonts**

![image](https://user-images.githubusercontent.com/19739712/108319970-0b537d80-7177-11eb-9c1c-c913189b0da8.png)

I know for different OS' this might be a problem, so maybe have the logo be system text rather than an image?

I don't know, this just seems to bug me a lot. 

USACO forum seems to already do this so just wondering why its not cohesive?

You don't have to change the entire logo scheme, mostly just the lettering on homepage and other places to system font, the actual logo and typesetting for that can be the same, like it is on diff websites

**Comment by Shad0wSeven** [comment]
USACO forumn seems to already do this so just wondering why its not cohesive?

**Comment by bqi343** [comment]
@thecodingwizard ?

**Comment by thecodingwizard** [comment]
yeah, I should fix this at some point :/

(on an unrelated note, if people have better ideas for website logos, please let me know...)

**Comment by bqi343** [comment]
When?? D:

**Comment by thecodingwizard** [comment]
Er maybe this coming Sunday LMAO (unless there's good reason to get it done sooner?)
