### ISSUE TITLE
Code folding for boilerplate

### ISSUE THREAD

**Issue by mizlan** [cpinitiative/usaco-guide#800]
This could help solve many of the problems experienced by templating and boilerplate. For example, fast I/O for Java such as discussed in #788. Code folding should probably be manual, not syntax or indentation reliant. Leaving this here for discussion, not sure how hard it would be to extend our codeblocks to support folding.

**Comment by thecodingwizard** [comment]
> not sure how hard it would be to extend our codeblocks to support folding

This is doable, though perhaps rather annoying to implement.

**Comment by frodakcin** [comment]
Potential improvements:
 - add to documentation
 - make `renderTokens` less wordy
 - handle processing codeblock children better (right now trim() and split() are called multiple times for the same string)
 - visuals (icon, code snip replacement text style, etc)

**Comment by mizlan** [comment]
I have an alternative, easier-to-write and easier-to-read interface for code snippets in mind. We create a global reference file/directory for snippets (maybe at `usaco-guide/snippets/` and then inserting snippets would be as follows:

```cpp
    some_cpp_code();
    cin >> x;
    // CodeSnippet{benq-template}
    proceed_with_cpp_code();
```

```java
public class Solution {
    // CodeSnippet{kattio}
    public static void main(String[] args) {
        ...
    }
}
```

where `CodeSnippet{benq-template}` would point to `usaco-guide/snippets/benq-template.txt` or something along those lines.

This is easier to parse (making source code more readable), less error-prone, and much less cognitively tasking for people working on writing their own solutions (since most often the snippets are shared across multiple editorials). It is also _much_ better for organizing our project.

If @frodakcin has already implemented code folding for actual UI, hopefully I'd be able to refer to his implementation. Let me know what you think.

**Comment by thecodingwizard** [comment]
I'm fine with the above approach, but I also don't think it's necessary. I think there will only be two (maybe three) snippets that are shared across editorials: Benq's long template, Kattio, and (maybe) C++ short template, but C++ short is probably fine without being a snippet. These snippets also shouldn't change very often.

As long as there's only two to three "shared" snippets, it's probably not too difficult for editorial authors to figure it out. Snippets are [documented](https://github.com/cpinitiative/usaco-guide/blob/master/docs/Content%20Documentation.md#code-blocks-and-code-snippets) too. If we ever do need a large number of shared snippets, then I would agree that the above approach is necessary.

(Also, liveupdate page should really have an embedded documentation or something, but that's a separate issue)

**Comment by mizlan** [comment]
In addition to those templates, I think things like segtree implementations could work a lot nicer if they were unified since it makes reading multiple editorials involving segtree a lot easier to just jump in. That would, however, require some change from the editorial writers to stick to that guideline.
