### ISSUE TITLE
Stop using Kattio for Java

### ISSUE THREAD

**Issue by skittles1412** [cpinitiative/usaco-guide#802]
This was discussed around [here](https://github.com/cpinitiative/usaco-guide/pull/788#issuecomment-781080676). Right now USACO Guide and its editorials use `Kattio` which is basically a `FastScanner` that subclasses `PrintWriter`

Advantages:
* Merges input and output class (this is really personal preference). I don't see any difference between `io.nextInt()` and `in.nextInt()` as well as `io.println()` and `pw.println()`. If you're looking for methods which can initialize IO classes you can make them global and write the corresponding method.

Disadvantages:
* Requires knowledge of OOP. It was mentioned that perhaps the guide should assume knowledge of APCSA, but I think that the bar should be set as low as possible, especially when it's not even required. Also, I doubt most people that use the guide have taken APCSA, and I know people who have attempted to learn OOP simply because `Kattio` used it.
* More importantly it's much harder to write than a simple input class. Considering that templates are now banned in USACO, the shorter the input class the better. This causes a simple input class to be preferred over a confusing subclass that is quite counterintuitive.

**Comment by bqi343** [comment]
> I know people who have attempted to learn OOP simply because Kattio used it.

Isn't this a *good* thing? Can add some notes about what it's doing if it's not clear ...

> it's much harder to write than a simple input class.

Removing the `PrintWriter` would reduce the length by two lines, so I don't see where this is coming from.

> I don't see any difference between io.nextInt() and in.nextInt() as well as io.println() and pw.println(). I

ok, since there isn't any difference let's leave it as is :P 

>  If you're looking for methods which can initialize IO classes you can make them global and write the corresponding method.

elaborate? not sure what you mean

Also, regarding your comment about `cio >>` vs `cio << `, I think this would be fine as long as the difference between the two was more visually obvious.

**Comment by mizlan** [comment]
I would like to emphasize the point that templates are already banned. In addition, my belief is that USACO Guide solutions don't need to aim to be as fast as possible, they should aim to be as readable and simple as possible while maintaining the correct overall algorithm. Further tinkering for speed boosts would be left to the reader.

**Comment by skittles1412** [comment]
> Isn't it a good thing that people want to learn about OOP? :o Can add some notes about what it's doing if it's not clear ...

You're just adding unnecessary barriers for beginners who want to begin competitive programming. Sure, they can learn OOP if they want but it shouldn't be because USACO guide input class **forced** them to

> Removing the PrintWriter would reduce the length by two (three?) lines, so I don't see where this is coming from.

To be able to successfully reproduce it, you'll need to understand OOP (or you memorize it by brute force but that's more prone to errors), which goes back to my first point.

> ok, since there isn't any difference let's leave it as is :P

I mentioned some clear advantages of using `FastScanner`. I mentioned this because of "I think it's more convenient to have all I/O managed through the same class"

> elaborate? not sure what you mean

Something like
```java
...
FastScanner in;
PrintWriter pw;
public void initIO() {
    in = new FastScanner(System.in);
    pw = new PrintWriter(System.out);
}
public void initIO(String name) {
    ...
}
```

**Comment by mizlan** [comment]
Would a PR for #800 address some of your concerns @skittles1412?

**Comment by skittles1412** [comment]
> I would like to emphasize the point that templates are already banned. In addition, my belief is that USACO Guide solutions don't need to aim to be as fast as possible, they should aim to be as readable and simple as possible while maintaining the correct overall algorithm. Further tinkering for speed boosts would be left to the reader.

`Scanner` should be avoided. It is simply too slow. I don't see how readability applies to a input class. If you choose to use Java unfortunately it will be part of your code. In addition, it should be encouraged imo as it's much easier and much more readable than simulating it with `BufferedReader` and `StringTokenizer`, and the syntax is virtually the same as `Scanner`.

**Comment by skittles1412** [comment]
> Would a PR for #800 address some of your concerns @skittles1412?

It would definitely be an improvement for Java solutions, and I think the ability to hide/show the input class template would be great, but I'm more concerned about replacing `Kattio` with a better, more readable, easier to write, and easier to understand alternative.

**Comment by skittles1412** [comment]
@HarryWangATX I would like to move the discussion of Kattio here. How is combining the two classes easier? Specifically what's the difference?

Also googling isn't very sufficient. OOP is somewhat confusing at first and 
> You're just adding unnecessary barriers for beginners who want to begin competitive programming. Sure, they can learn OOP if they want but it shouldn't be because USACO guide input class **forced** them to

Finally this is more of a minor issue but OOP isn't meant to merge two unrelated classes which is what Kattio is doing. Perhaps more apt uses of it would be more beneficial to those learning it and less confusing to those who know it.

**Comment by HarryWangATX** [comment]
> @HarryWangATX I would like to move the discussion of Kattio here. How is combining the two classes easier? Specifically what's the difference?

For me, the difference is that kattio has i/o merged and organized into one class. I don't have to instantiate a bufferedreader and then a printwriter. Also for beginners, having the ability to work with a scanner syntaxed input is better than having them look at a bunch of Integer.parseInt()s and the use of stringtokenizer.

> Finally this is more of a minor issue but OOP isn't meant to merge two unrelated classes which is what Kattio is doing. Perhaps more apt uses of it would be more beneficial to those learning it and less confusing to those who know it.

I do agree that OOP shouldn't merge two unrelated classes, but by what you may say "abusing" OOP, kattio effectively merges the classes imo. I personally do not think it confuses the people who knows OOP. Extending something not related to itself will not confuse someone. It might be bad practice, but in essence its still just extending another class. For beginners, I think this will prompt them to learn OOP, which I think is a good thing.

**Comment by skittles1412** [comment]
I'm not sure if you have read through this thread yet. I mentioned replacing it with a `FastScanner` for scanner syntaxed input and [here](https://github.com/cpinitiative/usaco-guide/issues/802#issuecomment-781493034) is an example of not having to instantiate two classes. Really though the two are the same since Kattio is doing it in the constructor while this is doing it as a method.

> For beginners, I think this will prompt them to learn OOP, which I think is a good thing.

For the third time
> You're just adding unnecessary barriers for beginners who want to begin competitive programming. Sure, they can learn OOP if they want but it shouldn't be because USACO guide input class **forced** them to

Also, if you want to teach them OOP why are you beginning their journey through a misuse of it?

**Comment by bqi343** [comment]
> I would like to emphasize the point that templates are already banned. 

As the module notes, you are free to refer to basic I/O code (w/o copy-pasting it).

> In addition, my belief is that USACO Guide solutions don't need to aim to be as fast as possible, they should aim to be as readable and simple as possible while maintaining the correct overall algorithm. 

It is readable/simple.

> Further tinkering for speed boosts would be left to the reader.

It isn't optimized for speed.

> You're just adding unnecessary barriers for beginners who want to begin competitive programming. Sure, they can learn OOP if they want but it shouldn't be because USACO guide input class forced them to

All beginners need to take away from this is that `io` is inheriting `PrintWriter` methods. If they don't want to learn additional OOP then they don't have to?

> Finally this is more of a minor issue but OOP isn't meant to merge two unrelated classes which is what Kattio is doing. 

> Also, if you want to teach them OOP why are you beginning their journey through a misuse of it?

Why isn't this a valid use of OOP to add additional functionality to a `PrintWriter`? I wouldn't call input and output "unrelated."

**Comment by skittles1412** [comment]
My main point is that I don't see any advantages to Kattio but it:
1. adds unnecessary confusion and forces beginners to learn syntax not really used in CP
2. is harder to write in contest

**Comment by thecodingwizard** [comment]
> adds unnecessary confusion and forces beginners to learn syntax not really used in CP
To me, Kattio is helpful because it allows beginners to blackbox input/output code, and focus on the important things instead (like writing algorithms). I personally do not expect anyone to read through and understand the Kattio class.

> is harder to write in contest
- I don't really see how splitting up Kattio into `FastScanner` and `PrintWriter` will reduce the amount of boilerplate code needed. 
- Kattio is related to i/o, and can definitely be referenced during contest.
- I think the intent of banning templates, etc was to prevent copy pasting of entire algorithms like HLD or DSU, not to prohibit bronze or silver contestants from using an efficient input/output class.

**Comment by frodakcin** [comment]
> I personally do not expect anyone to read through and understand the Kattio class.
Side note: This also isn't very difficult

**Comment by skittles1412** [comment]
> To me, Kattio is helpful because it allows beginners to blackbox input/output code, and focus on the important things instead (like writing algorithms). I personally do not expect anyone to read through and understand the Kattio class.

A `FastScanner` also blackboxes io similarly, but is easier to understand if you choose to do so.

> I don't really see how splitting up Kattio into FastScanner and PrintWriter will reduce the amount of boilerplate code needed.

The reason it's easier to remember is because you don't need an understanding of OOP. The amount of code is around the same for both ways.

> Kattio is related to i/o, and can definitely be referenced during contest.

Perhaps this should be clarified then. The current rules only allow for "syntax or library functions"

> Side note: This also isn't very difficult

The main difference between the two is that Kattio requires you to at least understand how `extends` works which is unnecessary imo.

**Comment by thecodingwizard** [comment]
> The main difference between the two is that Kattio requires you to at least understand how extends works which is unnecessary imo.

I don't think that's too difficult...

---

I think I'm going to close this issue for now (though feel free to keep discussing) since it seems like the majority of content authors / core members seem to prefer sticking with Kattio...
