### ISSUE TITLE
Add editorial code requirements

### ISSUE THREAD

**Issue by skittles1412** [cpinitiative/usaco-guide#803]
This applies to USACO editorials as well, really all editorials.

The point of editorial code is to provide a reference for an implementation of the ideas mentioned in the editorial, not for beginners to have to ask what it's doing on a discord server, and not for readers to have to split screen so they can view the macros on one side and the code on the other. Editorial code should be **as readable as possible**, which means at least no macros, templating to a minimum, and preferably comments. IMO **hard requirements should be set to improve the quality of editorials**. Editorial code readability shouldn't be compromised but rather be a required part of any editorial. This means that **you should spend the 10 extra minutes improving the readability of your code**, rather than give that responsibility to the hundreds of readers which will spend a lot more wasted time trying to understand your editorial code that should've been clear in the first place.

**Comment by dolphingarlic** [comment]
What requirements do you propose?

**Comment by skittles1412** [comment]
No 200 line templates. Macros should be avoided; maybe `using ll = long long;` but other stuff like loop macros and the shortening of 50 different combination of primitives, vectors, and pairs should be removed. Don't use separate methods for initializing IO; just use three lines at the beginning of main. Really, just use this as your template and don't add other stuff.
```cpp
#include <bits/stdc++.h>

using namespace std;

int main() {
    cin.tie(0) -> sync_with_stdio(0);
    //maybe freopen here
}
```

Try your best to make your code readable. Use meaningful variable names and function names (meaning that they may get long) and try your best to add comments to any code you think readers might find confusing. Comment what a variable/loop/function is doing and add implementation notes.

Commenting and readability is obviously subjective, but I think a hard requirement should be little to zero macros and no templates.

**Comment by dolphingarlic** [comment]
I agree with you about the templates (after all, they're against USACO rules now :P). However, I don't think that comments are necessary unless the problem a) involves casework or b) uses "complicated" maths (since the written solution above the code almost always already has the variable definitions, I think)

What do you guys think about requirements for spacing in code? (i.e. `for(int i=0i<n;i++)` vs `for (int i = 0; i < n; i++)`) Are they also necessary?

**Comment by skittles1412** [comment]
Comments are subjective. I think just add it for any code that you think readers might find confusing or use it as implementation notes that aren't mentioned in the editorial. I think I'll open a separate issue about formatting.

**Comment by bqi343** [comment]
I agree that a lot of code needs to be replaced.

> No 200 line templates. 

:eyes:

**Comment by frodakcin** [comment]
Yea, agree with this, especially since guide is designed for beginners. In plat/cf div 1 editorials though, I don't think this matters at all.

**Comment by skittles1412** [comment]
Why not? Regardless of problem difficulty editorial code should still be as readable as possible.

**Comment by bqi343** [comment]
>  Regardless of problem difficulty editorial code should still be as readable as possible.

I agree. For many of the plat / advanced internal solutions, I pasted my code without much concern for readability, but these aren't meant to serve as editorials. They're meant to be example solutions for platforms where submissions are not publicly viewable.

> What do you guys think about requirements for spacing in code? (i.e. for(int i=0i<n;i++) vs for (int i = 0; i < n; i++)) Are they also necessary?

Doesn't matter to me as long as it's consistent as mentioned [here](https://usaco.guide/general/contributing?lang=java) (although I prefer `for (int i = 0; i < n; ++i)`).

**Comment by thecodingwizard** [comment]
I think Gold+ (Platinum+?) should be more lenient with some macros though...

Also, Ben's Github implementations all require a lot of macros...

I agree that we should standardize code style though.

**Comment by bqi343** [comment]
> Also, Ben's Github implementations all require a lot of macros...

Just refer to [KACTL](https://github.com/kth-competitive-programming/kactl/tree/master/content) instead whenever possible?

**Comment by SansPapyrus683** [comment]
It'd probably take a lot of time, but I believe that we should just remove all the macros (save for `#include`s) except for things like `using ll = long long` or minor things like that.

There probably is a script out there that replaces macros with their defined things.

**Comment by skittles1412** [comment]
> I think Gold+ (Platinum+?) should be more lenient with some macros though...

Sure, but I feel like macros should be solely used for abbreviating types. Specifically I dislike loop macros, and while maybe `F0R` is fine there's a lot of variants of it that are not very readable imo.

Macros can be removed by first commenting out all the includes and then running `g++ -E` on the file. The result is spitted to stdout.

**Comment by thecodingwizard** [comment]
```cpp
#include <bits/stdc++.h>
using namespace std;

using ll = long long;
using vi = vector<int>;
using pi = pair<int,int>;

#define sz(x) (int)(x).size()
#define pb push_back
#define all(x) begin(x), end(x)
#define f first
#define s second

int main() {
    cin.tie(0)->sync_with_stdio(0); 
    // freopen("name.in", "r", stdin); 
    // freopen("name.out", "w", stdout);

}
```

Perhaps we can just stick to this template for Bronze - Gold?

**Comment by SansPapyrus683** [comment]
To be honest, I don't think all those `#define`s are necessary. But the rest seems good enough to be readable.

**Comment by frodakcin** [comment]
I guess it's more like: use defines if you want, but no more than those listed. It's obviously not necessary to add macros that aren't necessary.

**Comment by HarryWangATX** [comment]
> ```cpp
> 
> #include <bits/stdc++.h>
> 
> using namespace std;
> 
> 
> 
> using ll = long long;
> 
> using vi = vector<int>;
> 
> using pi = pair<int,int>;
> 
> 
> 
> #define sz(x) (int)(x).size()
> 
> #define pb push_back
> 
> #define all(x) begin(x), end(x)
> 
> #define f first
> 
> #define s second
> 
> 
> 
> int main() {
> 
>     cin.tie(0)->sync_with_stdio(0); 
> 
>     // freopen("name.in", "r", stdin); 
> 
>     // freopen("name.out", "w", stdout);
> 
> 
> 
> }
> 
> ```
> 
> 
> 
> Perhaps we can just stick to this template for Bronze - Gold?

FOR F0R ROF??

**Comment by HarryWangATX** [comment]
also should we go fix our previous sols?

**Comment by skittles1412** [comment]
> ```c++
> #include <bits/stdc++.h>
> using namespace std;
> 
> using ll = long long;
> using vi = vector<int>;
> using pi = pair<int,int>;
> 
> #define sz(x) (int)(x).size()
> #define pb push_back
> #define all(x) begin(x), end(x)
> #define f first
> #define s second
> 
> int main() {
>     cin.tie(0)->sync_with_stdio(0); 
>     // freopen("name.in", "r", stdin); 
>     // freopen("name.out", "w", stdout);
> 
> }
> ```
> 
> Perhaps we can just stick to this template for Bronze - Gold?

This looks good to me.

> FOR F0R ROF??

I'd rather not have loop macros.

**Comment by HarryWangATX** [comment]
> I'd rather not have loop macros.

😩😩 i think loop macros are fine tho

**Comment by skittles1412** [comment]
A lot of people (especially beginners) would like to disagree.

**Comment by SansPapyrus683** [comment]
> also should we go fix our previous sols?

Definitely. Otherwise, this issue loses half its purpose if it's only supposed to apply to new solutions.

**Comment by thecodingwizard** [comment]
See #806 -- seems like we've reached a consensus here! 🎉
