### ISSUE TITLE
Formatting code

### ISSUE THREAD

**Issue by skittles1412** [cpinitiative/usaco-guide#804]
It was mentioned in #803 that perhaps we should add a code format style that authors should follow, or even add a code formatter which can be run against solutions. I think a style like [this](https://codeforces.com/blog/entry/64218) would be fine.

**Comment by SansPapyrus683** [comment]
Well, this only applies to C++. PEP 8 can probably be used for Python solutions.

Do you propose any style guide for Java?

**Comment by mizlan** [comment]
We could also possibly integrate [EditorConfig](https://editorconfig.org/) to provide a general formatting guide that integrates with editors/IDEs.

**Comment by skittles1412** [comment]
For Python PEP 8 probably should be used. This style guide still applies to Java, and you can easily translate the points mentioned in it to Java.

**Comment by thecodingwizard** [comment]
Are there any specific recommendations we should include in #805 that don't relate to templates/macros (which is being discussed in other issues)?

**Comment by thecodingwizard** [comment]
closing unless people have ideas... general code styles are mentioned in the contributing module anyway.
