### ISSUE TITLE
Improve C++ Template Usage

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#806]
For C++ code, especially for Bronze through Gold, we should use (at most) the following template:

```cpp
#include <bits/stdc++.h> // see /general/running-code-locally
using namespace std;

using ll = long long;

using vi = vector<int>;
#define pb push_back
#define all(x) begin(x), end(x)
#define sz(x) (int)(x).size()

using pi = pair<int,int>;
#define f first
#define s second
#define mp make_pair

void setIO(string name = "") {
	cin.tie(0)->sync_with_stdio(0); // see /general/fast-io
	if (sz(name)) {
		freopen((name+".in").c_str(), "r", stdin); // see /general/io
		freopen((name+".out").c_str(), "w", stdout);
	}
}

int main() {
	setIO();
	
}
```

Code can use fewer macros than above, but shouldn't use additional macros (in particular, for loop macros are highly discouraged in Bronze through Gold).

Any help removing macros/templates would be greatly appreciated! You can help by:

- submitting a PR (better)
- commenting which modules / solutions need to have templates removed

Please note that when removing templates, you *shouldn't change any logic* -- the code should be identical except with templates removed (and possibly with comments added as necessary).

**Comment by SansPapyrus683** [comment]
Perhaps we should mention this in the contributing module. Right now all it mentions is this:
![image](https://user-images.githubusercontent.com/55369003/108447303-7dc66b00-7214-11eb-98f6-0f392fd93807.png)

**Comment by thecodingwizard** [comment]
this will be mentioned in the contributing module (at some point in the near future).

**Comment by tachithanhdanh** [comment]
https://github.com/bqi343/USACO/blob/master/Implementations/content/contest/TemplateVeryShort.cpp
maybe we can seperate the macros like this for readability (just ignore the setIO function).

**Comment by bqi343** [comment]
> https://github.com/bqi343/USACO/blob/master/Implementations/content/contest/TemplateVeryShort.cpp
> maybe we can seperate the macros like this for readability (just ignore the setIO function).

oops ig we can just use this template then (though I don't think anyone else uses `rsz`?)

```cpp
#include <bits/stdc++.h> // see C++ Tips & Tricks
using namespace std;

using ll = long long;

using vi = vector<int>;
#define pb push_back
#define all(x) begin(x), end(x)
#define sz(x) (int)(x).size()

using pi = pair<int,int>;
#define f first
#define s second
#define mp make_pair

void setIO(string name = "") { // name is nonempty for USACO file I/O
	cin.tie(0)->sync_with_stdio(0); // see Fast Input & Output
	if (sz(name)) {
		freopen((name+".in").c_str(), "r", stdin); // see Input & Output
		freopen((name+".out").c_str(), "w", stdout);
	}
}

int main() {
	setIO();
	
}
```

**Comment by Shad0wSeven** [comment]
```c++
void setIO(string name = "") {
	cin.tie(0)->sync_with_stdio(0); // see /general/fast-io
	if (sz(name)) {
		freopen((name+".in").c_str(), "r", stdin); // see /general/io
		freopen((name+".out").c_str(), "w", stdout);
	}
}
```
is also probably not needed, as `ifstream`/`ofstream` is good enough for bronze and silver, and it would make templates more verbose, you could just add a comment like "`//fastio possible` or whatever

**Comment by fishy15** [comment]
I think that it is a good idea to keep it, maybe move it directly into the main method instead of having it as a separate function. Having fast IO is something that should be in each program anyway.

**Comment by TanishT** [comment]
I just went through the bronze section and some of the silver section (up to custom comparators) and made a list of the solutions that use too many macros. I found a bunch so I just wanted to share them so that more people can submit PRs to fix them which would everything go quicker. 

Let me know if I made any mistakes. 

Bronze 
  - https://usaco.guide/solutions/usaco-665?lang=cpp
  - https://usaco.guide/solutions/usaco-568?lang=cpp
  - https://usaco.guide/solutions/usaco-831?lang=cpp (benq)
  - https://usaco.guide/solutions/usaco-619?lang=cpp (benq)
  - https://usaco.guide/solutions/usaco-857?lang=cpp (benq)
  - https://usaco.guide/solutions/usaco-831?lang=cpp (benq)
  - https://usaco.guide/solutions/usaco-687?lang=cpp (benq)
  - https://usaco.guide/solutions/usaco-667?lang=cpp (benq)
  - https://usaco.guide/solutions/usaco-940?lang=cpp 
  - https://usaco.guide/solutions/usaco-965?lang=cpp (benq)
  - https://usaco.guide/solutions/usaco-1013?lang=cpp (benq)

- Silver 
  - https://usaco.guide/solutions/cses-1661?lang=cpp (benq)
  - https://usaco.guide/solutions/cses-1662?lang=cpp (benq)
  - https://usaco.guide/solutions/cses-1619?lang=cpp (extra macros in Implementation 2)

**Comment by tachithanhdanh** [comment]
> I just went through the bronze section and some of the silver section (up to custom comparators) and made a list of the solutions that use too many macros. I found a bunch so I just wanted to share them so that more people can submit PRs to fix them which would everything go quicker. 

I think I can fix some of them by removing the macros and replacing with clean code. (Maybe when I have some free time)

**Comment by Mastermind497** [comment]
Are there any more files that still need to be de-templated?

**Comment by SansPapyrus683** [comment]
not that i know of, but there probably is.

**Comment by thecodingwizard** [comment]
If we've managed to de-template everything then I'll close this issue?

**Comment by SansPapyrus683** [comment]
the ones in plat + advanced probably are still pretty template-heavy

**Comment by HarryWangATX** [comment]
we agreed that plat sols can have templates

**Comment by thecodingwizard** [comment]
Yeah. As long as General - Gold are mostly template less I think we're good :)

Thanks everyone for their help here! If you see something Gold or below that has a template please open a new issue

**Comment by SansPapyrus683** [comment]
> we agreed that plat sols can have templates

dear god i guess i'll do it myself then
