### ISSUE TITLE
Hashing a tree

### ISSUE THREAD

**Issue by dolphingarlic** [cpinitiative/usaco-guide#813]
Hashing a tree is a somewhat-useful technique (though it's very uncommon), and I think it would be nice to add to the guide. Here's a nice blog post about it: http://rng-58.blogspot.com/2017/02/hashing-and-probability-of-collision.html

Where would this technique fall under though? It doesn't feel right to be put under string hashing

**Comment by bqi343** [comment]
wow this blog is really popular

**Comment by bqi343** [comment]
if you want to put it in an optional block along after some explanation about the collision probability for strings, that's fine w/ me?
