### ISSUE TITLE
Internal solutions for USACO problems?

### ISSUE THREAD

**Issue by dolphingarlic** [cpinitiative/usaco-guide#821]
So USACO problems all have editorials already, but I recently got this feedback on Discord:
> pleasepleaseplease add like really nice editorials for superhard silver problems, Im really dying on these and the normal editorials really suck please :pray:

(And when asked about specific problems):
> well rn i really dont understand meetings moop and clock tree

How should we approach this? Do we write internal solutions for these problems, or can USACO update their editorials somehow?

**Comment by SansPapyrus683** [comment]
Uh... is there anything wrong with writing an internal solution for these problems?

**Comment by thecodingwizard** [comment]
I think internal sol > update existing USACO editorial. We can copy paste and modify the official editorial if we want (and then just include a citation or something)

**Comment by dolphingarlic** [comment]
> Uh... is there anything wrong with writing an internal solution for these problems?

I just think unnecessary internal solutions are a bit wasteful, but I guess it's fine if the official editorial is actually bad

**Comment by fishy15** [comment]
I do agree that having unnecessary internal solutions is wasteful, and the official editorials could simply be linked to. However, there are certainly problems that should have rewritten solutions (notably cowland comes to mind, I am not too familiar with silver editorials however).

An advantage with having internal solutions is that we can update them based on user feedback on what editorials they are finding confusing.

**Comment by bqi343** [comment]
> Im really dying on these and the normal editorials really suck please 🙏

> well rn i really dont understand meetings moop and clock tree

wow I wonder who wrote these??

(but srsly, please be more specific?)

**Comment by Shad0wSeven** [comment]
![image](https://user-images.githubusercontent.com/19739712/108612177-db84bf80-739a-11eb-97e4-9d10b3155257.png)
hey that was me :thonk:

**Comment by SansPapyrus683** [comment]
Of course, I 100% agree that some of the editorials are hard to understand. I feel like in the internal solutions, we could add on to the explanations by providing some sort of example.

For example, in Meetings, we could use the sample input and say "Consider the first cow. Notice that [insert explanation here]". I feel like that would be a great improvement.

**Comment by skittles1412** [comment]
On a similar note I think the editorial for [circular barn gold](http://usaco.org/index.php?page=viewproblem2&cpid=621) could be improved. It uses one incorrect, confusing, and ambiguous sentence to explain the core part of the solution (where to find the starting point). Although more explanations, examples, and maybe even pictures could be added on USACO Guide, I feel like incorrect solutions like this one should be changed on the USACO website.

**Comment by SansPapyrus683** [comment]
Yeah, and there's a bunch of other solutions that could use further explanation. Perhaps something like a "request internal solution" button along with a form asking for a reason would help alot.

**Comment by bqi343** [comment]
There's already a contact us form where you can request an editorial.

**Comment by thecodingwizard** [comment]
I think walking through a sample input like you mentioned would be most effective in a video solution. I personally think the text editorial is fine as is and does not warrant such changes, though I agree it would be nice if someone were to make a video solution that did contain an example.

**Comment by SansPapyrus683** [comment]
Well, if no one can do a video solution walking through the sample input, the second best thing would be to just do a text walkthrough.

**Comment by thecodingwizard** [comment]
unless people have specific requests to revise certain internal solutions, I'll just close this :P
