### ISSUE TITLE
potentially misleading description of `char` data type

### ISSUE THREAD

**Issue by huynhtrankhanh** [cpinitiative/usaco-guide#832]
[This reference to 'Unicode characters' is potentially misleading.](https://usaco.guide/general/data-types?lang=cpp)
> Character variables represent a single Unicode character. They are returned when you access the character at a certain index within a string. Characters are represented using the ASCII standard, which assigns each character to a corresponding integer. 

'Character' isn't a well defined concept in Unicode. Also the `char` data type in C++ can't represent a lot of Unicode 'characters'.
> Characters are represented using the ASCII standard

From what I've gathered a lot of character encodings try to mimic ASCII when possible so I'm not really sure if this is accurate or not but it sounds fishy :joy:

I hope someone knowledgeable could chime in because I'm not too familiar with Unicode and text encoding.

**Comment by bqi343** [comment]
You're right.

Java: 16 bits

[Docs](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html):

> Unicode code unit is used for 16-bit char values that are code units of the UTF-16 encoding

CPP: 8 bits

[Source 1](https://www.learncpp.com/cpp-tutorial/chars/), [Source 2](https://www.cplusplus.com/doc/ascii/)

ASCII = 0-127, printing 128-255 just result in `?` for me

**Comment by bqi343** [comment]
(closed by bfaa0ae)
