### ISSUE TITLE
Show C++ code if Java/Python code isn't available?

### ISSUE THREAD

**Issue by dolphingarlic** [cpinitiative/usaco-guide#834]
From feedback on Discord:
> i feel like you should be able to choose multiple languages instead of just 1
> because if i prefer to see sols in java, but a solution is not available in java, i have to go and change my language to c++, then afterwards change in back

This might be a problem if people don't expect the code not to be in Java/Python though (e.g. if they want to copy and paste), so how do you guys think we should approach this?

**Comment by dolphingarlic** [comment]
Actually, selecting multiple languages and then showing the code in one of those languages if available is probably smarter.

E.g. if someone chooses Java and Python but only C++ code is available, then nothing is shown

**Comment by mizlan** [comment]
Can you have an option on the page similar to this: "no Java solution found; display C++ solution?"
