### ISSUE TITLE
Add submittable problem: LCS on Permutations

### ISSUE THREAD

**Issue by frodakcin** [cpinitiative/usaco-guide#839]
https://github.com/cpinitiative/usaco-guide/pull/791

Is https://www.luogu.com.cn/problem/P1439 good enough or should we create new problem on polygon?

**Comment by HarryWangATX** [comment]
isn't that chinese?

**Comment by frodakcin** [comment]
It is

**Comment by HarryWangATX** [comment]
let's do polygon imo

**Comment by frodakcin** [comment]
sure

**Comment by frodakcin** [comment]
ok i shared the problem wit hyou on polygon

**Comment by frodakcin** [comment]
if nothing's extremely wrong ill add it to gym

**Comment by frodakcin** [comment]
https://codeforces.com/gym/102951/problem/C

**Comment by HarryWangATX** [comment]
looks 👍
