### ISSUE TITLE
USACO Solutions file names

### ISSUE THREAD

**Issue by dongliu0426** [cpinitiative/usaco-guide#844]
- `USACO {contest} {name}.mdx` (e.g. `USACO dec16-cow-checklist.mdx`)
- `USACO {contest} {problemslug}.mdx` (e.g. `USACO dec19-milkvisits.mdx`)

opinions?

**Comment by bqi343** [comment]
slug is better (but recent problems don't have :/)

**Comment by SansPapyrus683** [comment]
NGL, spaces in filenames make me kind of uneasy (I think I read somewhere that they have plenty of problems associated with them), but I think that the second one would make solutions more easily searchable within the repo.
