### ISSUE TITLE
Binary Jumping

### ISSUE THREAD

**Issue by darren-yao** [cpinitiative/usaco-guide#862]
https://usaco.guide/plat/bin-jump?lang=cpp

Binary jumping LCA should be learned before O(1) Euler Tour +RMQ LCA, and furthermore, Binary Jumping LCA should be located in the Gold Trees section.

**Comment by bqi343** [comment]
> furthermore, Binary Jumping LCA should be located in the Gold Trees section.

but all of the practice problems are plat :eyes:
