### ISSUE TITLE
Coordinate Compression 

### ISSUE THREAD

**Issue by darren-yao** [cpinitiative/usaco-guide#865]
For silver, some explanation on coordinate compression would be useful, as it has shown up a few times in the past
I don't think it should be an entirely separate module, but some explanation within any of the present modules would be nice

-why#0726

**Comment by SansPapyrus683** [comment]
What present module should it be categorized under?

**Comment by dolphingarlic** [comment]
Probably intro-sorting or something because it's about relative order

**Comment by thecodingwizard** [comment]
I think Coord compression in bronze is sketchy though idk ://

@bqi343 any particular preference on where this should go?

**Comment by bqi343** [comment]
no

**Comment by HarryWangATX** [comment]
can assign to me if needed

**Comment by thecodingwizard** [comment]
Sure, unless @nchn27 already started

**Comment by nchn27** [comment]
Sorry, I'm worked on it... creating a PR rn. But I would gladly appreciate your review @HarryWangATX

**Comment by thecodingwizard** [comment]
Oops mb, I reassigned 😅
