### ISSUE TITLE
Functional Graphs

### ISSUE THREAD

**Issue by darren-yao** [cpinitiative/usaco-guide#866]
Also, I don't think functional graphs are really optional? They've shown up 3 times so far, and 2 times in the past year, which is actually more frequent than 2D prefix sums I think, and that has a dedicated, nonoptional module -why#0726

I believe @caoash has talked about this in the past.

**Comment by bqi343** [comment]
> 2 times in the past year

Are you counting dance mooves twice?

**Comment by bqi343** [comment]
See #882
