### ISSUE TITLE
Update USACO Langs

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#874]
Change mention of C++11 here:

https://github.com/cpinitiative/usaco-guide/blob/369f46701fca844483d6ce28aed27caa842afadf/content/1_General/Cpp_Command.mdx

Also

https://github.com/cpinitiative/usaco-guide/pull/409#issuecomment-786747792

**Comment by thecodingwizard** [comment]
Closed with #928 (I think)
