### ISSUE TITLE
Remove Instances of cout.tie(0)

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#875]
`cout.tie(0)` does nothing (see https://usaco.guide/general/fast-io?lang=cpp#method-2---cintie0)

Appears in prefix sums module & some solutions

**Comment by HarryWangATX** [comment]
@bqi343 im not seeing any issues in psums module anymore is that the 2 sols u fixed?

**Comment by bqi343** [comment]
https://usaco.guide/silver/prefix-sums-2?lang=cpp#solution---forest-queries

**Comment by thecodingwizard** [comment]
![image](https://user-images.githubusercontent.com/7865976/110580938-77922300-811e-11eb-9b92-bcdc6a21f659.png)

these are all the instances of `cout.tie(0)`

**Comment by thecodingwizard** [comment]
actually it's probably faster if I just do it :P
