### ISSUE TITLE
Todo: Remove Dance Mooves, Swapity Swapity Swap from Func Graph

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#882]
https://usaco.guide/silver/func-graphs?lang=cpp

Material discussed in the module isn't relevant for these problems.

**Comment by bqi343** [comment]
Also - should this still be in silver?

**Comment by frodakcin** [comment]
Should we have a separate permutations module?

**Comment by bqi343** [comment]
If you have other problems that would go in such a module? I can't think of anything else rn, I think it's fine for them to just not be in a module.

**Comment by frodakcin** [comment]
> I think it's fine for them to just not be in a module.

ok sure
