### ISSUE TITLE
Making Notes

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#89]
save custom text for future reference (as part of user account?)

https://codeforces.com/blog/entry/80438?#comment-666863

**Comment by MrinallU** [comment]
Would you leave noted for the module or each problem?

**Comment by bqi343** [comment]
each problem

**Comment by MrinallU** [comment]
So then when you click on the notes link of something would we have a popup where the user can make and save the notes

**Comment by thecodingwizard** [comment]
wait would people actually use this feature? :O (what notes would they take?)

**Comment by MrinallU** [comment]
@thecodingwizard I think it is better to have general module notes so they can set reminders to themselves (ie what problems they want to do) or other stuff, for example many textbooks have the note taking functionality that I use constantly to have a quick summary to comeback to if I need a quick refresher on the topic. Imo it's a nice little feature to have in the guide to make it a little bit more like a interactive.

**Comment by bqi343** [comment]
> wait would people actually use this feature? :O (what notes would they take?)

place to paste code for a problem (and share it)? :o

**Comment by thecodingwizard** [comment]
wouldn't this be more like "when you're done with a problem, we prompt you to leave feedback on difficulty, paste your code, and write an editorial"?

(And then we let other people view code/editorial, sort of like oj.uz)

**Comment by bqi343** [comment]
sure

**Comment by thecodingwizard** [comment]
in that case can we close this for #431 ?

**Comment by bqi343** [comment]
> @thecodingwizard I think it is better to have general module notes so they can set reminders to themselves (ie what problems they want to do) or other stuff, for example many textbooks have the note taking functionality that I use constantly to have a quick summary to comeback to if I need a quick refresher on the topic. Imo it's a nice little feature to have in the guide to make it a little bit more like a interactive.

I guess this would be separate (but still useful)?

**Comment by MrinallU** [comment]
@thecodingwizard So like would we make a new issue of making some kind of solutions page which gets solution code from the problem feedback collection?

**Comment by thecodingwizard** [comment]
do people actually need to take notes on modules though? ~~oops I never take notes on anything~~ (and if they do, couldn't they just take notes on like google keep or something?)

**Comment by MrinallU** [comment]
@thecodingwizard I mean we would also need to verify each solution since there is no way to do it automatically.

**Comment by MrinallU** [comment]
> do people actually need to take notes on modules though? ~oops I never take notes on anything~ (and if they do, couldn't they just take notes on like google keep or something?)

I mean it depends on preference lol but I think it would be nice to have the notes in one place but I mean if you think our time is better spend on  other things then I guess it's fine for now.

**Comment by thecodingwizard** [comment]
> @thecodingwizard So like would we make a new issue of making some kind of solutions page which gets solution code from the problem feedback collection?

erm I haven't thought too much about how exactly this functionality would work oops, but something like that?

Maybe we add a column to the table that's like "View Solutions," and then it lists a whole bunch of user submissions and people can browse them or something. Not sure

> I mean it depends on preference lol but I think it would be nice to have the notes in one place but I mean if you think our time is better spend on other things then I guess it's fine for now.

I just don't know how many people would actually use such a feature to justify making + maintaining it...?

**Comment by MrinallU** [comment]
@thecodingwizard let me know what you come up with and what  you need me to implement!

**Comment by bqi343** [comment]
> Closing this for #431
