### ISSUE TITLE
Lex Min TopoSort

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#890]
https://usaco.guide/gold/toposort?lang=cpp#bfs

Clarify that this code doesn't actually extract the lexicographically minimum topological sort ...

**Comment by mizlan** [comment]
Git blame time! Maybe we would've been able to inspect [what happened there](https://github.com/cpinitiative/usaco-guide/blame/master/content/4_Gold/TopoSort.mdx#L375) if we had better commit messages...

**Comment by bqi343** [comment]
Not sure what you mean. The module isn't incorrect per se (the code was never intended to extract it).

**Comment by dolphingarlic** [comment]
Should we just move the lexographically minimum paragraph to an "optional" block to avoid the confusion?
