### ISSUE TITLE
Default solution links for OI problems

### ISSUE THREAD

**Issue by dolphingarlic** [cpinitiative/usaco-guide#904]
Some OIs (besides the IOI) have (somewhat) centralized pages with editorials/code solutions. It'd be nice if the solutions linked there by default.

- CEOI: http://ceoi.inf.elte.hu/tasks-archive/
- Baltic OI: https://boi.cses.fi/tasks.php (mostly code in a zip file)
- COCI: https://hsin.hr/coci/
- COI: https://hsin.hr/hio2020/ (replace 2020 with the desired year)

**Comment by thecodingwizard** [comment]
This should probably be done after #930 is resolved...

**Comment by SansPapyrus683** [comment]
oh wait crap forgot this pr wasn't really

**Comment by bqi343** [comment]
it should be straightforward to do this if we want to (just modify https://github.com/cpinitiative/usaco-guide/blob/master/src/models/problem.ts#L323)
