### ISSUE TITLE
missing editorial

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#916]
Problem [IOI 2013 - Game] 
The external solution link provided doesn't contain solution.

https://usaco.guide/plat/2DRQ?lang=cpp

(From email)

**Comment by bqi343** [comment]
That's weird ... I remember reading the solution before but I can't find it anymore.

**Comment by thecodingwizard** [comment]
@bqi343 is this sufficient as an editorial? http://blog.brucemerry.org.za/2013/07/ioi-2013-day-2-analysis.html

**Comment by bqi343** [comment]
for now, maybe
