### ISSUE TITLE
Should Not Have Extra Blank Line After Code Snippets

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#924]
ex. https://usaco.guide/general/cpp-command?lang=cpp#on-mac

(also, why does adding `bash` after the backticks cause the code snippet to display differently? though remember this happening previously)

**Comment by bqi343** [comment]
Code blocks should also have top margin by default (this doesn't look great):

<img width="835" alt="Screen Shot 2021-03-08 at 9 22 05 AM" src="https://user-images.githubusercontent.com/21228024/110333612-c68d6a80-7fef-11eb-93d4-21c1d923699b.png">

**Comment by thecodingwizard** [comment]
fixed in https://github.com/cpinitiative/usaco-guide/pull/925 I think

**Comment by thecodingwizard** [comment]
still need to fix bash language
