### ISSUE TITLE
Problem Suggestion: Add "USACO January 2013 Gold Problem 2 - Island Travels" to Platinum - Dynamic Programming on Bitmasks

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#934]
*Kepha Sher* (UID EcPWekxtRCegZEHRXaoN6U2v1JI2) suggested adding the problem [USACO January 2013 Gold Problem 2 - Island Travels](http://www.usaco.org/index.php?page=viewproblem2&cpid=230) to the module [Platinum - Dynamic Programming on Bitmasks](https://usaco.guide/plat/dp-bitmasks#problem-https://atcoder.jp/contests/dp/tasks/dp_o?lang=en).

**Difficulty**: Easy
**Tags**: bitmask DP, flood fill, bfs
**Additional Notes**:None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by nchn27** [comment]
Good for mixed problemset
