### ISSUE TITLE
Problem Suggestion: Add "USACO 2014 February Gold Problem 3 - Cow Decathlon" to Platinum - Dynamic Programming on Ranges

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#935]
*Kepha Sher* (UID EcPWekxtRCegZEHRXaoN6U2v1JI2) suggested adding the problem [USACO 2014 February Gold Problem 3 - Cow Decathlon](http://www.usaco.org/index.php?page=viewproblem2&cpid=401) to the module [Platinum - Dynamic Programming on Ranges](https://usaco.guide/plat/dp-ranges#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=647).

**Difficulty**: Easy
**Tags**: Bitmask DP
**Additional Notes**:None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by nchn27** [comment]
Was this meant to be put with bitmask DP?
Regardless, good for mixed problemset
