### ISSUE TITLE
Problem Suggestion: Add "USACO March 2013 Gold Problem 1 - The Cow Run" to Platinum - Dynamic Programming on Ranges

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#936]
*Kepha Sher* (UID EcPWekxtRCegZEHRXaoN6U2v1JI2) suggested adding the problem [USACO March 2013 Gold Problem 1 - The Cow Run](http://www.usaco.org/index.php?page=viewproblem2&cpid=265) to the module [Platinum - Dynamic Programming on Ranges](https://usaco.guide/plat/dp-ranges#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=647).

**Difficulty**: Easy
**Tags**: range DP
**Additional Notes**:None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by nchn27** [comment]
good for mixed problmset
