### ISSUE TITLE
Problem Suggestion: Add "CEOI 2012 - Job scheduling" to Silver - Binary Search

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#939]
*ignacio cantarella* (UID u5tnOwwl9vRItES9RAuv7i6CTwu2) suggested adding the problem [CEOI 2012 - Job scheduling](https://oj.uz/problem/view/CEOI12_jobs) to the module [Silver - Binary Search](https://usaco.guide/silver/binary-search#problem-https://codeforces.com/contest/702/problem/C).

**Difficulty**: Normal
**Tags**: Binary Search
**Additional Notes**:None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by andrewwangva** [comment]
Yea I think this is a pretty good prototypical bin-search problem.
