### ISSUE TITLE
Problem Suggestion: Add "USACO January 2013 Silver - Square Overlap" to Platinum - Sweep Line

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#942]
*Rohit Raman* (UID Ax2gBJ9sU4g6UJn71XqDjti0LNq2) suggested adding the problem [USACO January 2013 Silver - Square Overlap](http://usaco.org/index.php?page=viewproblem2&cpid=227) to the module [Platinum - Sweep Line](https://usaco.guide/plat/sweep-line#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=266).

**Difficulty**: Easy
**Tags**: Sweep
**Additional Notes**:None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by andrewwangva** [comment]
Yea I think this is a pretty good basic sweep line problem
