### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by HarryWangATX** [cpinitiative/usaco-guide#948]
![image](https://user-images.githubusercontent.com/47877587/110692531-09943d00-81ac-11eb-83f5-09239bf9f902.png)

??

**Comment by thecodingwizard** [comment]
What page?

**Comment by HarryWangATX** [comment]
> What page?

i'm guessing it was the psums wodget causing this

**Comment by thecodingwizard** [comment]
The 2D prefix sums page has some latex that overflows the page. However:

- The user should be able to scroll to the left
- The initial scroll position should be on the very left

So unless there's a bug one of these things isn't true, I think it's fine as is...
