### ISSUE TITLE
Problem Suggestion: Add "USACO December 2014 - Piggyback" to Gold - Breadth First Search (BFS)

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#949]
*Ritvik Teegavarapu* (UID 1RGePX8bH2PCnWGmtveiig5u4Fg1) suggested adding the problem [USACO December 2014 - Piggyback](http://www.usaco.org/index.php?page=viewproblem2&cpid=491) to the module [Gold - Breadth First Search (BFS)](https://usaco.guide/gold/bfs#problem-https://cses.fi/problemset/task/1193).

**Difficulty**: Normal
**Tags**: BFS
**Additional Notes**:None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by caoash** [comment]
Accepted.
