### ISSUE TITLE
Problem Suggestion: Add "Boring Business" to Bronze - Simulation

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#951]
*Johnston Liu* (UID eflYBQR7lfdoQU64AypFEXpjfKo1) suggested adding the problem [Boring Business](https://dmoj.ca/problem/ccc11j4) to the module [Bronze - Simulation](https://usaco.guide/bronze/simulation#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=665).

**Difficulty**: Easy
**Tags**: Simulation
**Additional Notes**:None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by caoash** [comment]
Will add.
