### ISSUE TITLE
Problem Suggestion: Add "Karen and Coffee" to Silver - Introduction to Prefix Sums

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#954]
*Tauhid Hassan Farian* (UID VM5OehAyh5eDXwbZhJhZuxQ87U62) suggested adding the problem [Karen and Coffee](https://codeforces.com/contest/816/problem/B) to the module [Silver - Introduction to Prefix Sums](https://usaco.guide/silver/prefix-sums#problem-https://leetcode.com/problems/find-pivot-index).

**Difficulty**: Normal
**Tags**: Prefix sums
**Additional Notes**:None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by andrewwangva** [comment]
I feel like this is too easy.

**Comment by SansPapyrus683** [comment]
What's easy for one person might be really hard for another. I feel this is a perfect fit for the module.
