### ISSUE TITLE
Problem Suggestion: Add "JOI Spring Camp 2019 Day 4 - Cake 3" to Platinum - Divide & Conquer - DP

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#955]
*Jsoft Programs* (UID ATTuQmdY3bRJYbAT4SUTbCjArFk2) suggested adding the problem [JOI Spring Camp 2019 Day 4 - Cake 3](https://oj.uz/problem/view/JOI19_cake3) to the module [Platinum - Divide & Conquer - DP](https://usaco.guide/plat/DC-DP#problem-https://szkopul.edu.pl/problemset/problem/ovRIpLFK3IhyFPjnVXeZtGxH/site/?key=statement).

**Difficulty**: Hard
**Tags**: 
**Additional Notes**:None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by nchn27** [comment]
Good for mixed problemset
