### ISSUE TITLE
Problem Suggestion: Add "USACO January 2016 Gold - Angry Cows" to Gold - Introduction to DP

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#957]
*Alan Zhong* (UID 4pEJNhhWr6V7gIkn3htE8yOzpAQ2) suggested adding the problem [USACO January 2016 Gold - Angry Cows](http://www.usaco.org/index.php?page=viewproblem2&cpid=597) to the module [Gold - Introduction to DP](https://usaco.guide/gold/intro-dp#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=694).

**Difficulty**: Normal
**Tags**: DP, Two Pointers, Binary Search
**Additional Notes**:None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by caoash** [comment]
Accepted.
