### ISSUE TITLE
Problem Suggestions - Auto Assign to Relevant Codeowners

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#958]
@jeffkmeng is this possible?

https://github.com/cpinitiative/usaco-guide/blob/master/CODEOWNERS

**Comment by thecodingwizard** [comment]
@jeffreymeng 

(it is)

(also it's theoretically possible to auto-make a PR but that's harder0

**Comment by jeffreymeng** [comment]
Yeah it is.
I'll implement.
