### ISSUE TITLE
Problem Suggestion: Add "USACO March 2014 Old Gold - Sabotage" to Silver - Binary Search

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#964]
*Dong Liu* (UID ~~GEbBrhoYRxQfFujkBbghKUew3UY2~~) suggested adding the problem [USACO March 2014 Old Gold - Sabotage](http://usaco.org/index.php?page=viewproblem2&cpid=419) to the module [Silver - Binary Search](https://usaco.guide/silver/binary-search#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=690).

**Difficulty**: Normal
**Tags**: Binary Search
**Additional Notes**:
:) @dongliu0426

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by dongliu0426** [comment]
:c my user id exposed
