### ISSUE TITLE
Problem Suggestion: Add "CSES - Bit Inversions" to Platinum - More Applications of Segment Tree

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#969]
*Benjamin Qi* (UID CdRpIRR4jeYtAnzeP89Q7fAWeJp1) suggested adding the problem [CSES - Bit Inversions](https://cses.fi/problemset/task/1188/) to the module [Platinum - More Applications of Segment Tree](https://usaco.guide/plat/seg-ext#problem-https://cses.fi/problemset/task/2206).

**Difficulty**: Easy
**Tags**: SegTree
**Additional Notes**:None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by nchn27** [comment]
Pretty classical problem (CSES), I'd say it's better to add to the module
