### ISSUE TITLE
Problem Suggestion: Add "CF beta round #42A Football" to Bronze - Introduction to Sets & Maps

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#979]
*C. Jeffrey* (UID jgp6mvMSRuMYx26njGKAWGHPyAi2) suggested adding the problem [CF beta round #42A Football](https://codeforces.com/contest/43/problem/A) to the module [Bronze - Introduction to Sets & Maps](https://usaco.guide/bronze/intro-sets/#problem-https://cses.fi/problemset/task/1640).

**Difficulty**: Easy
**Tags**: Sets
**Additional Notes**:
:) thanks for creating this website; I need help on IOI so feel free to contact me at jeffprivate0313@gmail.com

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by caoash** [comment]
While you can solve this with sets & maps, it's not intended and constraints don't suggest it. Also I don't think it adds anything interesting that isn't already covered by other problems (store how many times each string appears).
