### ISSUE TITLE
Problem search for Telephone shows wrong module

### ISSUE THREAD

**Issue by maggie-j-liu** [cpinitiative/usaco-guide#984]
It says the problem appears in Greedy Algorithms with Sorting, but it actually doesn't.
![image](https://user-images.githubusercontent.com/63619830/111357775-d7b92580-8646-11eb-8235-ee1c235cf58a.png)
Just a guess at what is happening - there is a CSES problem with the same ID number (1090) in that module and the search is using that...?

**Comment by thecodingwizard** [comment]
the module might have been moved. our search implementation doesn't update modules automatically yet oops

**Comment by maggie-j-liu** [comment]
Oh. I don't think that problem would have been categorized as greedy with sorting, though... Is there no issue with two problems having the same ID?
