### ISSUE TITLE
Problem Suggestion: Add "boi cat in a tree" to Platinum - Centroid Decomposition

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#985]
*Ray Tang* (UID jjkJgktEM3brQnXtcoJaqtkjnYg1) suggested adding the problem [boi cat in a tree](https://cses.fi/203/list/) to the module [Platinum - Centroid Decomposition](https://usaco.guide/plat/centroid#problem-https://cses.fi/problemset/task/2079).

**Difficulty**: Normal
**Tags**: 
**Additional Notes**:
not sure if this is centroid

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by dolphingarlic** [comment]
It isn't centroid lol (and it's already in the guide)
