### ISSUE TITLE
Problem Suggestion: Add "Double Tree" to Platinum - Binary Jumping

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#989]
*Ray Tang* (UID jjkJgktEM3brQnXtcoJaqtkjnYg1) suggested adding the problem [Double Tree](https://codeforces.com/contest/1140/problem/G) to the module [Platinum - Binary Jumping](https://usaco.guide/plat/bin-jump#problem-https://codeforces.com/gym/102694/problem/C).

**Difficulty**: Normal
**Tags**: 
**Additional Notes**:
same problem from centroid section

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by nchn27** [comment]
So put it in both sections?
