### ISSUE TITLE
Problem Suggestion: Add "USACO 2021 February Contest - Just Green Enough" to Silver - More on Prefix Sums

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#992]
*Jad Isaac* (UID VXiyaNcxkDhuiqc54YpwVb2BLap2) suggested adding the problem [USACO 2021 February Contest - Just Green Enough](http://usaco.org/index.php?page=viewproblem2&cpid=1112) to the module [Silver - More on Prefix Sums](https://usaco.guide/silver/prefix-sums-2#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=919).

**Difficulty**: Hard
**Tags**: 2D Prefix Sums
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by bqi343** [comment]
As analysis notes, doing this w/o prefix sums is not hard.
