### ISSUE TITLE
Problem Suggestion: Add "USACO December 2013 Bronze - Wormholes" to Bronze - Introduction to Greedy Algorithms

### ISSUE THREAD

**Issue by jeffkmeng** [cpinitiative/usaco-guide#997]
*Pearl Yu* (UID WacLjPHFTOZJcasba2jKETwPcH43) suggested adding the problem [USACO December 2013 Bronze - Wormholes](http://www.usaco.org/index.php?page=viewproblem2&cpid=360) to the module [Bronze - Introduction to Greedy Algorithms](https://usaco.guide/bronze/intro-greedy#problem-http://www.usaco.org/index.php?page=viewproblem2&cpid=689).

**Difficulty**: Very Hard
**Tags**: greedy
**Additional Notes**: None

*This report was automatically generated from a user submitted problem suggestion on the USACO guide.*

**Comment by bqi343** [comment]
how is this greedy?
